### ISSUE TITLE
Wi-fi activation fails 

### ISSUE THREAD

**Issue by ghaspias** [maxnet/berryboot#1]
Hi,

Congratulations for your great work!
I have struggled for some time to get wi-fi working on the installer and by default on any distribution, but even if the modules and firmware seem to be present in (berryboot)/shared, and a known good wpa-supplicant.conf is in (mmcblk0p1)/, wi-fi doesn't start. As it seems (thank you for the console access in installer!) the firmware loading fails (my Belkin usb has a ralink chip that requires rt73.bin)... in fact, the /lib/firmware isn't present, because only "/mnt/shared/lib/modules" is symlinked to "/lib/modules", in installer->LoadDrivers.
Still, even after creating manually that symlink, and running "/usr/sbin/wpa_supplicant -Dwext -iwlan0 -c/boot/wpa_supplicant.conf -B" as the installer would, I still get errors in dmesg (phy3 -> rt2x00lib_request_firmware: Error - Failed to request Firmware.) and wpa-supplicant fails saying that device wlan0 doesn't exist.

**Comment by maxnet** [comment]
Thanks for your report.
Seems that the firmware blob of my own Realtek test device is embedded in the kernel module itself instead of in a separate file, so didn't notice the symlink missing.

Not sure why it still fails though.
Plan to release a Berryboot beta based on Linux 3.6 next week. You might want to wait for that, to see if that works better.

**Comment by ghaspias** [comment]
Hi,

Thanks for the quick fix.
I have compiled everything from source, with the fix for firmware symlink, but it still fails to activate wi-fi. The same device works fine after booting (with berryboot) Raspbian, Sugar, Puppy, and OpenElec.

**Comment by maxnet** [comment]
Maybe Berryboot needs to read in and pass the firmware file data to the kernel. A task probaby done by udev or one of its friends under normal distros.

When you open a shell in Berryboot, and do "ls /sys/class/firmware" does it show any entries?
And if so do any of them indicate what the exact name of the firmware file it wants is?

**Comment by ghaspias** [comment]
Hello,

Only tonight I managed to check this again.
There is only one file on /sys/class/firmware, it's named timeout.
The symlink for firmware is in place, berryboot gui now does immediately complain that it couldn't bring up wifi, instead of having to wait 60 seconds as it did before. Also there are no messages in dmesg about firmware.
I have set up my wpa_supplicant.conf exactly as the installer would (by looking at the code).
My device as present by lsusb in ubuntu:
Bus 002 Device 006: ID 050d:705a Belkin Components F5D7050 Wireless G Adapter v3000 [Ralink RT2571W]

when plugged in my ubuntu laptop, on /var/log/syslog I get:
Dec  5 03:39:24 cdrsp-laptop-miguel kernel: [75528.673778] usb 2-1.3: new high-speed USB device number 6 using ehci_hcd
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.392553] usb 2-1.3: reset high-speed USB device number 6 using ehci_hcd
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.814906] cfg80211: Updating information on frequency 2412 MHz for a 20 MHz width channel with regulatory rule:
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.814917] cfg80211: 2402000 KHz - 2472000 KHz @ 40000 KHz), (300 mBi, 2000 mBm)
...
...
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.815087] cfg80211: 2474000 KHz - 2494000 KHz @ 20000 KHz), (300 mBi, 2000 mBm)
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.815364] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.817624] Registered led device: rt73usb-phy1::radio
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.817688] Registered led device: rt73usb-phy1::assoc
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.817746] Registered led device: rt73usb-phy1::quality
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75529.818286] usbcore: registered new interface driver rt73usb
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75530.208530] ADDRCONF(NETDEV_UP): wlan1: link is not ready
Dec  5 03:39:25 cdrsp-laptop-miguel kernel: [75530.210149] ADDRCONF(NETDEV_UP): wlan1: link is not ready
Dec  5 03:39:29 cdrsp-laptop-miguel kernel: [75533.568220] wlan1: authenticate with 00:05:ca:8d:53:88 (try 1)
Dec  5 03:39:29 cdrsp-laptop-miguel kernel: [75533.569729] wlan1: authenticated
Dec  5 03:39:29 cdrsp-laptop-miguel kernel: [75533.626273] wlan1: associate with 00:05:ca:8d:53:88 (try 1)
Dec  5 03:39:29 cdrsp-laptop-miguel kernel: [75533.824597] wlan1: associate with 00:05:ca:8d:53:88 (try 2)
Dec  5 03:39:29 cdrsp-laptop-miguel kernel: [75534.024258] wlan1: associate with 00:05:ca:8d:53:88 (try 3)
Dec  5 03:39:30 cdrsp-laptop-miguel kernel: [75534.223901] wlan1: association with 00:05:ca:8d:53:88 timed out
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.599573] wlan1: direct probe to 00:05:ca:8d:53:88 (try 1/3)
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.603213] wlan1: direct probe responded
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.624828] wlan1: authenticate with 00:05:ca:8d:53:88 (try 1)
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.626452] wlan1: authenticated
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.626869] wlan1: associate with 00:05:ca:8d:53:88 (try 1)
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.629161] wlan1: RX AssocResp from 00:05:ca:8d:53:88 (capab=0x431 status=0 aid=4)
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.629168] wlan1: associated
Dec  5 03:39:36 cdrsp-laptop-miguel kernel: [75540.643677] ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
Dec  5 03:39:48 cdrsp-laptop-miguel kernel: [75552.252652] wlan1: no IPv6 routers present

In Ubuntu there's no reference to firmware in syslog or dmesg.

miguel@cdrsp-laptop-miguel:~$ lsmod|grep rt
rt73usb                31735  0 
crc_itu_t              12707  1 rt73usb
rt2x00usb              20762  1 rt73usb
rt2x00lib              55279  2 rt73usb,rt2x00usb
parport_pc             32866  0 
mac80211              506816  3 rt2x00usb,rt2x00lib,ath9k
cfg80211              205544  4 rt2x00lib,ath9k,mac80211,ath

In Raspbian wheezy, booted via last released berryboot, I end up with the same modules loaded, no references to firmware in dmesg, node wlan0 is present, associated with my AP. But, altough I'm pretty sure I had a working connection before on raspbian, now it doesn't get an ip, even if ifconfig shows packets received and sent. Also, it gets stuck early in boot, right after succesfull association, showing some peridic activity (the adapter lights blink), but with no progress in boot until I remove the adapter. If I afterwards reconnect it, there is no complain. In the meanwhile I have upgraded berryboot to the new gui version. On another sd card, booting directly raspbian, wifi works like a charm (but I can't remember how I have tweaked that install).
I will keep investigating, whenever I have time.

**Comment by maxnet** [comment]
Can you try if the following files work better: http://get.berryboot.com/tmp/berryboot-36beta-20121207.zip  ?
Has a /sbin/hotplug helper script that tries to feed the file the kernel module asks for.

**Comment by maxnet** [comment]
Found any time to try the 36beta out yet?

I hate open bug reports :-)

**Comment by ghaspias** [comment]
Hello, maxnet

I apologize for the long absence, but I really didn't have the time to fiddle with the raspi recently.
I tried the beta today, with the following results:
on a blank sd card, with only the extracted files from the package berryboot-36beta-20121207.zip, after the dialog for the networking/display/keyboard, having selected wi-fi, a dialog appears saying 'loading drivers' for a brief moment, then it takes a few minutes while displaying 'starting wpa-supplicant'; after that, a dialog for selecting the access point appears, with no access point in the list. I canceled, and also canceled the next dialog (usb or network scsi), and the os selection, until I got to the main os setup dialog; I started a console, and grabbed /var/log/debug and the output from lsusb and lsmod, which are in the attached zip. I forgot to copy dmesg, but I believe the last lines where similar to the next one (failed to request firmware).
Then I edited wpa-supplicant.conf, and restarted. This time, as it started, it stayed a few minutes with only the background image and cursor, seemingly frozen, until it presented a message 'check your wpa-supplicant.conf'. The procedure from that point on was identical.
![debug_beta_wifi tar gz](https://f.cloud.github.com/assets/262618/35621/5d2fec6e-5232-11e2-8129-cf82e777be2d.png)

(please save the 'image' above and change the extension to tar.gz)

I also tried the last official release of berryboot (updated from berryboot itself), but still complains 'check your wpa-supplicant.conf' after a few minutes. Curious is that the delay was gone in the version I compiled.

The contents of /sys/class/firmware is the same as before.

Thanks for trying to fix this. I'm sorry I spoiled your clean bug record... 

and I wish you a happy new bug-squeezing year!

**Comment by maxnet** [comment]
Can you try if this one works better? 
http://dl.berryboot.com/berryboot-20121230.zip

/sbin/hotplug had #!/bin/bash while it should be #!/bin/sh

**Comment by maxnet** [comment]
Re-open if problem still applies.

**Comment by caveman-dick** [comment]
Hi I think I am getting a similar issue to this. 

I am using the released version off the website berryboot-20121230.zip and unfortunately I cannot connect when either by using the gui or if I supply a pre-generated wpa_supplicant.conf. When it tries to connect the wifi-dongle starts flashing but just pops up with the "check your settings" message. On a previous version before the wifi gui was released I did manage to get this working via the wpa_supplicant file and the wifi works with OpenElec fine.

I notice on of the above messages something about a timeout, is it possible that this is too short and it is timing out before the connection is made? If so can it be extended without building a new package?

Thanks

**Comment by maxnet** [comment]
Not possible without recompile.
Retrying several times would involve removing the "-n" at the following places:

https://github.com/maxnet/berryboot/blob/berryboot2.0/BerrybootGUI2.0/wifidialog.cpp#L173
https://github.com/maxnet/berryboot/blob/berryboot2.0/BerrybootGUI2.0/installer.cpp#L482

**Comment by glebovitz** [comment]
Don't know why this is closed, it still isn't working.

**Comment by maxnet** [comment]
> Don't know why this is closed, it still isn't working.

Was closed because I did not receive a reply to the question if 20121230 worked better.
Assumed it was either fixed or the topic starter had given up on it.

Do you have a Ralink RT73 based device as well like the topic starter, or does it concern a different wifi device you are having issues with?

**Comment by glebovitz** [comment]
I have an RT73 device using the 20130213 release. I think I have the same device (Belkin FSD7050,) It works with Ubuntu-weezy, but not berryboot. What would you like me to try?

**Comment by maxnet** [comment]
> I have an RT73 device using the 20130213 release. I think I have the same device (Belkin FSD7050,) It works with 
> Ubuntu-weezy, but not berryboot. What would you like me to try?

Try starting a Berryboot installation, and select that you want to use wifi,
I assume you get an empty access point list there?

Press "ctrl+alt+f2" to get a console and enter "dmesg"
Do the last lines of "dmesg" show "rt2x00lib_request_firmware: Error - Failed to request Firmware" like the original poster got?

**Comment by glebovitz** [comment]
Hi, I am traveling this week. I won't be able to try this until I return on Monday.

Gregg

**Comment by glebovitz** [comment]
phy0 -> rt2x00lib_request_firmware: Error - Failed to request firmware

**Comment by maxnet** [comment]
Thanks for the feedback.
Think I may have a clue why it is not loading firmware, please give this one a try: http://dl.berryboot.com/tmp/berryboot-20130327.zip

**Comment by glebovitz** [comment]
Yes, that fixed the problem. The driver loaded and I was able to select the access point from the scanned list, connect, and acquire an IP Address. I am going to do a hard disk install, so I will let you now if I run into any issues.

**Comment by maxnet** [comment]
Fixed in 20130311

**Comment by Danny4096** [comment]
The link for the working version is not available anymore, throws an error 404. can the file be rehosted please as the one i download from the berryboot site still has the WiFi connection issue

**Comment by maxnet** [comment]
The 2013 fix has been incorporated into normal Berryboot.
If you are still having problems it is likely an unrelated problem.
