### ISSUE TITLE
Updating BerryBoot

### ISSUE THREAD

**Issue by tyilo** [maxnet/berryboot#10]
Is it possible to update BerryBoot on an Raspberry Pi, without removing the installed OS'es?

How do you do that?

**Comment by tyilo** [comment]
Nevermind, the images are stored on another partition.
I just couldn't see the partition on OSX, because it is an ext2 partition.

**Comment by maxnet** [comment]
No need to mess with partitions manually.
Just click "add OS" and accept the update there, if there is one.
