### ISSUE TITLE
Pty interfaces for SSH

### ISSUE THREAD

**Issue by Treebro** [maxnet/berryboot#103]
Trying to add the dropbear ssh to berryboot.  I can add the package fine and the service starts fine, though it seems there are no pty interfaces to use.  I am having trouble finding information related to buildroot as to why this is happening and for fixes.  Would this have been intentionally done specific to berryboot?  If so, what would I need to change to fix it?

**Comment by maxnet** [comment]
Try mounting devpts before starting dropbear (but after mounting /dev):

```
mkdir /dev/pts
mount -t devpts /dev/pts /dev/pts
```

**Comment by Treebro** [comment]
I have no clue what just happened with those commands but I like the results...  Thank you very very much.
