### ISSUE TITLE
After deleting last OS, the buttons for edit, recover, delete, and set default are still available.

### ISSUE THREAD

**Issue by Treebro** [maxnet/berryboot#106]
If these buttons are clicked it crashes and enters an emergency shell

**Comment by Treebro** [comment]
Err this is nitpicky but the backup button now becomes greyed out after removing the last OS.   The backup button is generally left available to backup sd card to usb, with the other options greyed out.

**Comment by maxnet** [comment]
edit: oops, misread your comment.
yeah, that one shouldn't be greyed out.
