### ISSUE TITLE
Parsing of cmdline.txt does not allow for multiple ssh authorized keys.

### ISSUE THREAD

**Issue by Treebro** [maxnet/berryboot#107]
Combined with the no password option leaves the only option of having 1 keypair being able to access the devices ssh.

Would having the authorized keys option with a delimeter that is replaced by \n not be a good option? 

Also this is an off topic, but you have the dropbear save it's public/private key on the mmcblk0p1 partition...  If it failed to mount that partition it would then proceed to generate the random keys as normal to the devtmpfs and continue with normal operation?

**Comment by maxnet** [comment]
> Combined with the no password option leaves the only option of having 1 keypair being able to access 
> the devices ssh.

Would personally just create a single dedicated key pair, and distribute that to anyone that needs access.

> Would having the authorized keys option with a delimeter that is replaced by \n not be a good option?

Think there is a length limit on cmdline.txt, although you would need to test that.

> Also this is an off topic, but you have the dropbear save it's public/private key on the mmcblk0p1 partition... 
> If it failed to mount that partition it would then proceed to generate the random keys as normal to the 
> devtmpfs and continue with normal operation?

If you are able to click away the "error mounting system partition" message through VNC, yes.
Otherwise no.
Not sure how common the scenario where the FAT partition is considered good enough to the Videocore to boot from, but not good enough for Linux is.

**Comment by Treebro** [comment]
> Would personally just create a dedicated key pair, and distribute that to anyone that needs access.

Not good for places where varieties of keypairs have been already implemented.  It is looking like I'll set it to use password login.

> Think there is a length limit on cmdline.txt, although you would need to test that.

Having trouble finding documentation on this...  Though I can confirm that it seems to not boot with 2 ssh public keys....

> If you are able to click away the "error mounting system partition" message through VNC, yes.
> Otherwise no.
> Not sure how common the scenario where the FAT partition is considered good enough to the Videocore to boot from, but not good enough for Linux is.

Sadly this is a very common reality here.  Hoping that the kernel fix solves the majority of corruption issues, although I want to be prepared for the unfortunate even that something else is still wrong.  There is a very high ratio of pis that I "can vnc into with partition issues" vs "cannot vnc at all".  Our pis are situated in not very friendly atmospheric environments, or it was just the kernel, or the sd cards are shoddy, we don't really know why it's happening, but we seem to have a much higher occurance of corruption than anyone using them for home situations. (opinion)

**Comment by maxnet** [comment]
> Not good for places where varieties of keypairs have been already implemented. It is looking like I'll set it to use password login.

Yes, if you are doing your own buildroot build, you can just specify a hardcoded password there and enable password authentication in dropbear.
That is not a solution I can include in the main Berryboot branch though. 

> There is a very high ratio of pis that I "can vnc into with partition issues" vs "cannot vnc at all".

Might indeed be something specific to your setup/SD card brand.
Only had problems with the FAT partition after writing to it (which normally only happens on updates), not out of the blue.

**Comment by Treebro** [comment]
It seems as though it is being corrupted during normal operation and then upon reboot, it attempts to load into berryboot.  Good news, it seems durable in the fact that it can read the cmdline.txt upon initial boot. Proof: Corrupted pis reboot with vnc running and correct ip address.  Also that it can access the rootfs on device. Proof: Through a couple tweaks was able to access usb loader and see the directories. Fake.img file I added was also accessible.

**Comment by Treebro** [comment]
Offtopic now. Possibly could add authorized keys file to mmcblk0p1 that is copied to the /root/.ssh/authorized_keys rather than inputting it from cmdline.

If this is against design, this should be closed.

**Comment by maxnet** [comment]
Problem is that if you use a separate file on the FAT partition, and Linux is unable to mount the FAT partition, SSH will not work.

(cmdline.txt is read by the Pi's bootloader on boot and passed to the Linux kernel. Berryboot retrieves its contents by reading /proc/cmdline instead of mounting the partition. so that will still work as long as the videocore managed to read it)

**Comment by Treebro** [comment]
I'm enabling the password way anyways. Chances are someone somewhere will want multiple keys and will not be experiencing corruption issues like these.  Could also set your rebuild-berryboot.sh ask the user for a password on the root/alternate user. then uses the mkpasswd command and exports it to the buildroot-2012.05/output/target/etc/shadow file.  Which would fit with your design i believe. (assumes removal of key only access)

**Comment by Treebro** [comment]
> Think there is a length limit on cmdline.txt, although you would need to test that.
> Having trouble finding documentation on this... Though I can confirm that it seems to not boot with 2 ssh public keys....

I don't think this fix will work because I am still seeing the above.

**Comment by maxnet** [comment]
Verified with "cat /root/.ssh/authorized_keys" that it actually ends up truncated?

**Comment by Treebro** [comment]
Err, The pi I have here won't boot when 2 ssh publics are entered... this is the line i'm using:

smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=80 vncinstall ipv4=192.168.20.30/255.255.255.0/192.168.20.1 ssh_authorized_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvdUCWeq54fnVqQ9O3lxUoyz5V1NcS0Jrf42OjBVStS1/BmiGx5E2fdO2SxnuINXSjel+PGb0nK8DYR2ToqfmxIU4WX7SkheBNjj5yU9552obKeK513qU27+Qi9SkExdpA2HIsDrqZwjKmDnuIQ6odlOFIEnHedf0UApChZb4AxoQKUkoy9XbQWmQhGUwXvGVaLUHNxDr796QbwMr85l0rui4WyzyLx3+Gag0EKBLrTx5KerpQ2hHiOHCB5QfjfJCyWUmpkQmm/dMldZM6MUMGmdmr10pdqfmox/CFgsPk5Axh5w/z14xclQpvOBPbgKdjV+N7dRXwOyHKL0mqq7gJ Null\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvdUCWeq54fnVqx9O3lxUoyz5V1NcS0Jrf42OjBVStS1/BmiGx5E2fdO2SxnuINXSjel+PGb0nK8DYR2ToqfmxIU4WX7SkheBNjj5yU9552obKeK513qU27+Qi9SkExdpA2HIsDrqZwjKmDnuIQ6odlOFIEnHedf0UApChZb4AxoQKUkoy9XbQWmQhGUwXvGVaLUHNxDr796QbwMr85l0rui4WyzyLx3+Gag0EKBLrTx5KerpQ2hHiOHCB5QfjfJCyWUmpkQmm/dMldZM6MUMGmdmr10pdqfmox/CFgsPk5Axh5w/z14xclQpvOBPbgKdjV+N7dRXwOyHKL0mqq7gJ Null" datadev=mmcblk0p2

**Comment by maxnet** [comment]
Yeah, with the extra parameters the bootloader inserts it is probably hitting the bootloader's 1024 character limit

http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=19334&start=125

**Comment by Treebro** [comment]
I can see that.  post on that forum page was 2012... dang.  
My votes for the mmcblk0p1 file with keys and give a root password option for redundancy.
