### ISSUE TITLE
Unable to get sound working over HDMI

### ISSUE THREAD

**Issue by mattie47** [maxnet/berryboot#109]
Device: Model B RaspberryPi

I can't for the life of me get sound working over HDMI in 3 different images (OpenELEC version 4.0.6 and 4.0.7, and RetroPie) I've tried that boot from Berryboot. 2014-06-26.

Installing OpenELEC 4.0.6 .or 4.0.7 on another SD card works perfectly fine with HDMI sound. 

Tried the Pi on 2 different model Samsung TVs, and multiple HDMI cables with no success. 

I will add that sound did work from the 3.5mm Audio jack (if selecting it instead of HDMI in OpenELEC). 

Things not attempted: 
- An earlier version of Berryboot. I've set up my SD card images perfectly with how I wanted them (as I initially spent several hours configuring both images on a computer screen without audio, assuming it would work) but at this point I haven't found anything on how to upgrade or downgrade the version of Berryboot without touching the images. 

A week ago I did try a few audio commands in an OpenELEC shell, and from memory I don't think I could see the HDMI audio as an option. I'll investigate this later, but wanted to raise this to see if anyone else was having this problem. 

Again as I said with the HDMI-CEC issue, any suggestions for things I could try, or debug I could provide? 

Thanks,

Matt

**Comment by maxnet** [comment]
Again, this is something that is not reproducible on my Samsung TV.

> I've tried that boot from Berryboot. 2014-06-26.

Newest version is 2014-08-14, but if you go to "add OS" with an older version, it will prompt to update.

Only differences I can see between standalone OpenELEC and Berryboot:
- The standalone version of OpenELEC might run a different Raspberry firmware version. Try if it does work if you copy the firmware files (start*.elf fixup* and bootcode.bin) from the OpenELEC card to the Berryboot card.
- OpenELEC has in config.txt "hdmi_ignore_cec_init=1", try putting that in Berryboot's config.txt as well to see if it makes a difference.

**Comment by mattie47** [comment]
Will have a go at that tomorrow. Cheers.

**Comment by mattie47** [comment]
> Newest version is 2014-08-14, but if you go to "add OS" with an older version, it will prompt to update.

Wow I didn't realise this was how you got Berryboot updates. Have done this, and now my sound is working! Thanks! I didn't have to try the other things you mentioned. Now just waiting for Berryboot CEC support issue :)
