### ISSUE TITLE
Buid from sources fails

### ISSUE THREAD

**Issue by ddeletic** [maxnet/berryboot#11]
I downloaded the latest set of sources (05-Feb-2013), checked I have all pre-requisites installed, extracted sources and started rebuild-berryboot.sh. It went on for a long while displaying lots and lots of text (none looked like errors) until eventually it stopped with: 

> > > rpi-userland next Downloading
> > > Cloning into bare repository rpi-userland-next...
> > > github.com[0: 207.97.227.239]: errno=Connection timed out
> > > fatal: unable to connect a socket (Connection timed out)
> > > --2013-02-05 15:42:30--  http://sources.buildroot.net//rpi-userland-next.tar.gz
> > > Resolving sources.buildroot.net... 176.9.16.109
> > > Connecting to sources.buildroot.net|176.9.16.109|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2013-02-05 15:42:31 ERROR 404: Not Found.

I then tried with the set of sources dated 30-Dec-2012, and got the exact same error. Unsurprisingly, http://sources.buildroot.net//rpi-userland-next.tar.gz is a bad URL. 

Any ideas on how to proceed with building? 

As a side note, your build (dated 30-Dec-2012) runs on my Pi flawlessly.

**Comment by maxnet** [comment]
Do you happen to have firewall rules that block the git port?

**Comment by ddeletic** [comment]
Yep, that was it. Thanks.
