### ISSUE TITLE
Enhancement request: Primary and secondary boot partitions

### ISSUE THREAD

**Issue by Treebro** [maxnet/berryboot#111]
if datadev1 in cmdline.txt use datadev1=$PrimaryBootDevice datadev2=$SecondaryBootDevice and so on. attempt to mount those partitions as datadev in that order.  If datadev1 cannot mount, move onto datadev2.  If mount successful, use it as datadev.  If all mounts fail and there is no more datadev#, move onto default search pattern.

if datadev=$BootPartition in cmdline, do not use aforementioned process. 

Thoughts?

**Comment by maxnet** [comment]
It currently already searches all possible partitions for one with a file system label of BERRYBOOT if it cannot find its data partition at datadev.

**Comment by Treebro** [comment]
hmm, I've been having issues with it set to datadev=mmcblk0p2 while mmcblk0p2 has the berryboot label.  When it corrupts, it should be ok because i have sda1 with label=berryboot set up as well.  Though the way it ends up executing is can't mount mmcblk0p2 right on boot, so it searches with findfs. Findfs returns a single line of "/dev/mmcblk0p2" because, even though it is unmountable, it can read the label.  Then after attempting to mount this it gives up.  sda1 is not returned by findfs and goes ignored.

Also if it's of any benefit, blkid command with grep may be a viable alternative

**Comment by maxnet** [comment]
Just relabel mmcblk0p2 to something else than Berryboot then.
It always tries to mount datadev first, regardless of label that has. Only tests if it can mount it, and if it has an /images folder.

**Comment by Treebro** [comment]
That is the workaround i've currently implemented.  In the process if it fails to mount the datadev, relabel that dev to 'n'. I also have it set to relabel all other partitions to 'n' on format. 

The method of search on every boot for every berryboot labelled partition and then have priorities on which drive to use seems to make a lot of sense to me, like how most pc bootloaders have drive priorities.

**Comment by maxnet** [comment]
> if it fails to mount the datadev, relabel that dev to 'n'.

Can give it another label beforehand.
Like I said, Berryboot always tries datadev regardless of what it is labelled.

> The method of search on every boot for every berryboot labelled partition and then have priorities on which 
> drive to use seems to make a lot of sense to me, like how most pc bootloaders have drive priorities.

Not something I plan to implement.
Feel free to submit a patch though.

**Comment by Treebro** [comment]
Sadly I don't think I'll be submitting a patch.  If the fixes I've put in place start to fail, maybe I'll have time to fix something up properly then.
