### ISSUE TITLE
can't find valid F2FS filesystem on OS selection

### ISSUE THREAD

**Issue by VirtualEB** [maxnet/berryboot#113]
I'm attempting to use Berryboot 2.0 with a class 10 Samsung 32GB microSDHC UHS-1 card on a B+.  Berryboot boots just fine and I'm able to add Raspbian and Pidora images from cifs (torrent downloads from raspberrypi.org).  However, when I select either OS two errors are reported that it can't find a valid F2FS filesystem at superblock x, followed by can't mount /sqaushfs.

I would like to rule out that I'm dealing with an incompatible card on the PI, but I am able to load Raspbian and NOOBS 1.3.9 with Raspbian/Pidora on the same card and all OSes boot without issue.  Hoping someone here can give me some direction on a solution.

**Comment by maxnet** [comment]
> torrent downloads from raspberrypi.org

Images found there are not directly compatible with Berryboot and need to be converted to SquashFS format first.

http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

Already converted images can be found at:

http://sourceforge.net/projects/berryboot/files/os_images/
