### ISSUE TITLE
BerrybootUI freezes using iSCSI if dhcp server is down

### ISSUE THREAD

**Issue by Spindletop** [maxnet/berryboot#115]
When there is no DHCP server on the network, the network dialog is opened/closed and in the following dialog trying to connect to the network storage, the GUI hangs. Only a power cycle will resolve this situation.

Steps to reproduce:
- Make sure iSCSI is configured
- Disable DHCP on the network
- Reboot

But I have a question regarding this, is it possible to use a static ip address with Berryboot? Editing /etc/network/Interfaces from Berryboot does not work as the change is not persistent and on reboot it is defaulted to dhcp. Any ideas?

**Comment by maxnet** [comment]
> But I have a question regarding this, is it possible to use a static ip address with Berryboot?

Yes.
The option is a bit hidden though.

![berryboot-static-net](https://cloud.githubusercontent.com/assets/1123701/4125986/da128502-32e6-11e4-8b7c-b6c1836193b0.png)

Go to "Add OS" -> "Network settings"
Probably should move it to a more prominent place.

**Comment by Treebro** [comment]
Also to add to max, you can edit the cmdline.txt on the boot partition to get the same effect by appending ipv4=$ip/$mask/$gateway 

Ex. ipv4=192.168.0.2/255.255.255.0/192.168.0.1
