### ISSUE TITLE
Network Boot & Installation

### ISSUE THREAD

**Issue by systmkor** [maxnet/berryboot#116]
I am trying to build a recovery partition for Raspberry Pi that is able to install new operating systems or do network booting. For network installation I have gathered it is possible to do it with NFS but is not possible with HTTP(S), TFTP, FTP(S), rsync, or scp. I also have not found any way to do network booting such as PXE with BerryBoot.

Let me know if I am missing critical information, there is a better solution, or if what I can do to add these features into BerryBoot.

Thank you for your time.

**Comment by maxnet** [comment]
True network boot is not supported.
We cannot execute a kernel other than our own, as kexec() is broken on the Pi last time I checked.

We do support storing the rootfs on network storage: http://www.berryterminal.com/doku.php/storing_your_files_on_a_synology_nas_using_iscsi

**Comment by systmkor** [comment]
For the rootFS network storage is that only synology nas or does that apply to an open source implementation? Also I take it then TFTP, FTP, HTTP or SCP, NFS are not supported.

**Comment by maxnet** [comment]
Any device that speaks the iSCSI protocol.
If you want to use any other protocol you will need to create a helper script for that yourself, that fetches your rootfs, extracts it, and calls switch_root

**Comment by systmkor** [comment]
@maxnet is this the location that needs modification to make kexec work ? berryboot / buildroot-2012.05 / package / kexec

**Comment by maxnet** [comment]
If you do "cd buildroot-2012.05 ; make menuconfig" you can enable compilation of the kexec userspace utilities, which reside in that package.
However last time I tried, executing kexec hanged the system.
Think the modifications to fix that need to be done in the Linux kernel and possibly in the Broadcom firmware.

**Comment by systmkor** [comment]
Where would I place the helper script? I tried looking around to find a iSCSI script but couldn't find anything that exactly matched what you mentioned. Would I add necessary packages to berryboot/ buildroot-2012.05/package/ for TFTP etc and then do some magic image stuff before berryboot/buildroot-2012.05/package/berrybootgui2 /init is launched?

**Comment by maxnet** [comment]
Create a Squashfs image Boot_my_operating_system_from_the_network.img containing a single file named "berryboot-init" and put whatever shell commands are necessary to download and boot your operating system.

Add Boot_my_operating_system_from_the_network.img to Berryboot like any other distribution.
http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

**Comment by systmkor** [comment]
Okay I have looked through all of "make menuconfig" and can't find kexec. I may have missed it. Thanks for your time. Thanks for the reply on custom os from other than a iSCSI. Not entirely sure where the shell commands that are necessary to donload and boot OS are supposed to go.

**Comment by maxnet** [comment]
Suggest you read the manual of all the tools you want to use first.
Like which keyboard shortcut you can use to search for packages in the "make menuconfig" screen...

**Comment by systmkor** [comment]
I know how to utilize the tools I am needing. Though that doesn't give me guidance on where they need to be ran in the berryboot/berryboot gui process to download and package to your current format.  Also I  found kexec. I skimmed passed it in Packages for target -> Debugging, profiling, and benchmark
