### ISSUE TITLE
enabling network interface 

### ISSUE THREAD

**Issue by jtdc12** [maxnet/berryboot#118]
I have been trying to download berry boot on my raspberry pi b+ and when i set it up everything works fine until i try to add operating systems and it comes up as enabling network interface for hours and won't go away i am using a eathernet i tried at least 5 times redownloading it resetting up the micro sd still won't work help me!!! 
thanks 
JTDC12

**Comment by maxnet** [comment]
What kind of Ethernet switch is the Pi connected to?

A simple one like most people have at home, or a fancy managed one with (web)interface and all?
If the latter, make sure STP is either disabled completely, or set to the portfast/RSTP variant.

**Comment by jtdc12** [comment]
A semi fancy i gess because my router is all the other way on the other side of my house so on my mac there is a way to make the ethernet input a output if u use wifi with your mac 
thanks

**Comment by maxnet** [comment]
> on my mac there is a way to make the ethernet input a output if u use wifi with your mac

And you checked that actually works properly with another computer/device than the Pi connected to your mac?

**Comment by jtdc12** [comment]
yes it does i tested it with Noobs retro pie and raspben

**Comment by maxnet** [comment]
Does Noobs Lite manage to download an OS off the Internet?
Only difference between that and Berryboot is essentially that Berryboot does 3 attempts to get a DHCP lease, while I believe NOOBS tries 6 times.

**Comment by jtdc12** [comment]
Yes noobs downloades it off the internet

**Comment by maxnet** [comment]
If in the "add OS" window you go to "network settings" and press "ok" does it work?
That should try it 3 more times.

**Comment by jtdc12** [comment]
no and i tried it about 5 times

**Comment by maxnet** [comment]
If you go to ctrl+alt+f2 login as root, and execute "/sbin/ifup -a" manually a second time, it doesn't give you an IP either?

**Comment by jtdc12** [comment]
it did not load an ip

**Comment by jtdc12** [comment]
is there a command to manually start the network

**Comment by jtdc12** [comment]
i fixed it

**Comment by johnsonra** [comment]
I seem to be experiencing a similar problem. What did you do to fix it?
