### ISSUE TITLE
OpenELEC on Berryboot outdated.

### ISSUE THREAD

**Issue by d10si** [maxnet/berryboot#12]
Hi,is there any chance you will update the image of OpenELEC available under Add OS option? The current version is 2.99.2 and Berryboot still has 2.95.6.
I was trying to add it on my own as a custom distro but for some reason I have failed even though I followed your tuto step by step.

Best Regards

**Comment by maxnet** [comment]
Might update it soonish.

What steps did you take to add it though?
OpenELEC is already in the right file format, just need to rename the SYSTEM file to OpenELEC.img128 and add it to Berryboot.

**Comment by d10si** [comment]
Wow,did not know that :) I took all those steps :

$ sudo kpartx -av image_you_want_to_convert.img 
add map loop0p1 (252:5): 0 117187 linear /dev/loop0 1
add map loop0p2 (252:6): 0 3493888 linear /dev/loop0 118784
$ sudo mount /dev/mapper/loop0p2 /mnt
$ sudo mksquashfs /mnt converted_image.img -comp lzo -e lib/modules
$ sudo umount /mnt 
$ sudo kpartx -d image_you_want_to_convert.img 

BTW. you are so fast mate thanks.

**Comment by maxnet** [comment]
Added 2.99.2 to the main download list
