### ISSUE TITLE
Network broadcast address set to 0.0.0.0 when using "vncinstall ipv4=" (Raspbian)

### ISSUE THREAD

**Issue by jwarnier** [maxnet/berryboot#122]
When using e.g. "vncinstall ipv4=192.168.1.11/255.255.255.0/192.168.1.1" on the command-line, it works as expected.
When installing Raspbian, though, the /etc/network/interfaces then looks like this:

```
# Static network configuration handled by Berryboot
iface eth0 inet manual

auto lo
iface lo inet loopback
```

and the actual configuration of eth0 looks like this:

```
eth0      Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx  
          inet addr:192.168.1.11  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1198319 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1374687 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:923553056 (880.7 MiB)  TX bytes:1531378815 (1.4 GiB)
```

As you can see, the _Bcast_ adress is 0.0.0.0, which is just wrong.
Note that I didn't try to fix this myself so far, but would like to avoid having to hardcode anything.

Thanks

**Comment by maxnet** [comment]
Recall Linux just uses the default broadcast address (last IP of subnet) if you do not specify one explicitly.
Do you need a non-standard broadcast address?

**Comment by jwarnier** [comment]
The problem is that the address appears wrongly in ifconfig here.
If the configuration of that same interface on Wheezy in /etc/network/interfaces was e.g.:
iface eth0 inet static
    address 192.168.1.11
    netmask 255.255.255.0
    network 192.168.1.0
    gateway 192.168.1.1

The broadcast address would be correct, i.e. 192.168.1.255, and certainly not 0.0.0.0.
Do you want me to run any diagnostic (such as some form of ping -b) to prove my point?

**Comment by maxnet** [comment]
> The broadcast address would be correct, i.e. 192.168.1.255, and certainly not 0.0.0.0.

Think Debian's ifup calculates the broadcast address itself, and sets it explicity.
While busybox's equivalent does not bother.

> Do you want me to run any diagnostic (such as some form of ping -b) to prove my point?

Think ARP requests are send to the broadcast address as well. And if broadcasts didn't work, you would not have any useful network connectivity.

**Comment by jwarnier** [comment]
OK, that's the explanation, then.
It is something related to busybox.
So I guess there is just no easy way to fix this, as Debian's ifupdown does it automatically, and this is not something that deserves being simulated on top of busybox.

Thanks

**Comment by maxnet** [comment]
> So I guess there is just no easy way to fix this, as Debian's ifupdown does it automatically, and this is 
> not something that deserves being simulated on top of busybox.

You could add code to Berryboot to calculate the broadcast address yourself given ip and netmask and set the broadcast address explicity.
But I am not going to bother, unless the current situation really breaks applications.

**Comment by jwarnier** [comment]
I have no such evidence.
Forget about this ones.
