### ISSUE TITLE
Unable to enter luks password over ttyS0

### ISSUE THREAD

**Issue by jeraymond** [maxnet/berryboot#125]
When booting with an encrypted file system, I'm unable to enter the luks password over the serial interface ttyS0 (on a Banana Pi). Seems like it might be because in installer.cpp Installer::switchConsole() is hard coded to use tty0

https://github.com/maxnet/berryboot/blob/bdd54331639ea0c7a25eba98c1c63dd59898e2a5/BerrybootGUI2.0/installer.cpp#L769

Maybe we could specify the tty value to use via cmdline.txt or some other mechanism? Would doing so fix this issue?

**Comment by maxnet** [comment]
No, you cannot switch the virtual terminal of a serial link, as the serial link does not have virtual terminals.
Try creating a normal login prompt with getty instead.
