### ISSUE TITLE
mksquashfs: invalid option

### ISSUE THREAD

**Issue by Superman1001** [maxnet/berryboot#127]
i want to convert an img for berryboot, i follow the guide in this page: http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions
but the mksquashfs command is wrong, this is the result (http://pastebin.com/NfJ0zEUR):

$ sudo mksquashfs /mnt converted_image_for_berryboot.img -comp lzo -e lib/modules
mksquashfs: invalid option

SYNTAX:mksquashfs source1 source2 ...  dest [options] [-e list of exclude
dirs/files]

Options are
-version        print version, licence and copyright message
-recover <name>         recover filesystem data using recovery file <name>
-no-recovery            don't generate a recovery file
-info           print files written to filesystem
-no-exports             don't make the filesystem exportable via NFS
-no-progress            don't display the progress bar
-no-sparse              don't detect sparse files
-b <block_size>         set data block to <block_size>.  Default 131072 bytes
-processors <number>    Use <number> processors.  By default will use number of
                processors available
-read-queue <size>      Set input queue to <size> Mbytes.  Default 64 Mbytes
-write-queue <size>     Set output queue to <size> Mbytes.  Default 512 Mbytes
-fragment-queue <size>  Set fagment queue to <size> Mbytes.  Default 64 Mbytes
-noI            do not compress inode table
-noD            do not compress data blocks
-noF            do not compress fragment blocks
-no-fragments           do not use fragments
-always-use-fragments   use fragment blocks for files larger than block size
-no-duplicates          do not perform duplicate checking
-noappend               do not append to existing filesystem
-keep-as-directory      if one source directory is specified, create a root
                directory containing that directory, rather than the
                contents of the directory
-root-becomes <name>    when appending source files/directories, make the
                original root become a subdirectory in the new root
                called <name>, rather than adding the new source items
                to the original root
-all-root               make all files owned by root
-force-uid uid          set all file uids to uid
-force-gid gid          set all file gids to gid
-nopad          do not pad filesystem to a multiple of 4K
-root-owned             alternative name for -all-root
-noInodeCompression     alternative name for -noI
-noDataCompression      alternative name for -noD
-noFragmentCompression  alternative name for -noF
-sort <sort_file>       sort files according to priorities in <sort_file>.  One
                file or dir with priority per line.  Priority -32768 to
                32767, default priority 0
-ef <exclude_file>      list of exclude dirs/files.  One per line
-wildcards              Allow extended shell wildcards (globbing) to be used in
                exclude dirs/files
-regex          Allow POSIX regular expressions to be used in exclude
                dirs/files
-p <pseudo-definition>  Add pseudo file definition
-pf <pseudo-file>       Add list of pseudo file definitions

**Comment by klinnex** [comment]
Did you do that in root ?

**Comment by maxnet** [comment]
> i follow the guide in this page: http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

From that page:

```
Some older versions of mksquashfs do not support the ”-comp lzo” option.
You can leave it out to let it use gzip compression instead. 
```

Tried without the "-comp lzo"?
