### ISSUE TITLE
automount luks encrypted sdcard

### ISSUE THREAD

**Issue by tristan-k** [maxnet/berryboot#128]
Is there a way to automount the luks encrypted sdcard without entering the password manually and without exposing the password?

Thanks!

**Comment by maxnet** [comment]
Duplicate issue

**Comment by tristan-k** [comment]
How is this is a duplicate and if so, which one?

**Comment by maxnet** [comment]
It is a variant of #28 
The lock on your door while leaving the key in.

**Comment by tristan-k** [comment]
I want to colocate my Raspberry Pi in a professional data center. Since the motivation for doing that is primarly build arround privacy and security reasons (see https://github.com/nylira/prism-break/issues/1052 for further information), I need a way to unlock the encrypted container automatically without exposing the password. I dont have physically access to the pi anymore as soon as it is send to the data center.
