### ISSUE TITLE
berryboot iscsi reboot issue

### ISSUE THREAD

**Issue by sebastienvg** [maxnet/berryboot#129]
I installed raspbian on a iscsi target everything works smoothly beside reboot, it hangs after releasing the IP (and therefor drops the connection to the NAS). Is there any work-around this?

**Comment by maxnet** [comment]
Try setting a static ip in Beryboot, under "add os" button -> "network settings"

**Comment by lgb-this** [comment]
I use a static ip and my PI does not connect with the iSCSI server after a reboot. I have to power off and on the PI to boot with the iSCSI successfuly.

**Comment by Ikyrz** [comment]
hello
an issue ? i've the same problem

**Comment by Ikyrz** [comment]
i think it's the network config
