### ISSUE TITLE
Img for berryboot

### ISSUE THREAD

**Issue by reeeky2001** [maxnet/berryboot#13]
I've a quick question on img files for BerryBoot. I understand that system partitions have to be in the SquashFs format and how to get them there.

If I us the following command on the Pi to make an image of the SD card:
`dd bs=1M if=/dev/mmcblk0   of=/media/USB_Drive/backup.img`
Then mount the resulting img file on another PC, use mksquashfs of the mounted img file and respective partition, will the resulting img file be able to be used in BerryBoot?

**Comment by maxnet** [comment]
Yes.
Although you might need to comment out the entries in /etc/fstab
