### ISSUE TITLE
Removing an image from BB to boot independently

### ISSUE THREAD

**Issue by SeanGeb** [maxnet/berryboot#130]
Hi,
Due to some changes in the hardware I now have available, I am trying to move an image that includes changes (Raspbian) from BB to a separate microSD (I'm using a B+), so that I can plug in the other microSD and go straight to Raspbian. I made a backup of the Raspbian install from BB and then used Win32 Disk Imager to burn it onto the microSD. When I plug it into the Pi and power it up, the ACT light stays on and the rainbow image does not appear - it doesn't recognise/boot from it. This card and Pi are known to work perfectly. So is there a way to make this work? I'm guessing its something to do with BB managing some of the boot files.
Thanks!

**Comment by maxnet** [comment]
Were you using a B+ previously with the old card?
Older firmware does not support the B+
Might need to update Berryboot first by going to "add OS" in the Berryboot menu editor.
Can also backup your SD card from there, if you have a USB stick or USB card reader. No need to mess with win32 disk imager.

**Comment by SeanGeb** [comment]
The card I'm using has only ever been used in my B+. It worked fine.
I think I need to clarify what I did:
1) I stuck in a memory stick of mine (known good) and backed up the Raspbian image to it, from BB.
2) I took the image to my computer.
3) I formatted a microSD (known good).
4) I used Win32 Disk Imager to put the Raspbian image on to the microSD on its own, without BB.
5) I put the newly-formatted and imaged microSD into the B+, powered it on, and... nothing. The ACT light stays on, in the same manner as if there wasn't actually a microSD card inserted.

The aim of this was to take the Raspbian image, with the changes I had made, and put it on to this microSD, but without BB needing to be on the microSD.

The distro was fully up-to-date, firmware, distro and software all included.
The BB image was the newest too.

Sorry if my first post was unclear :) I do go on a bit!

I get the feeling its due to how BB manages the low-level files like start.elf and the config files.

Thanks for the fast reply, and BB itself, it's a brilliant little tool!

**Comment by maxnet** [comment]
> 1) I stuck in a memory stick of mine (known good) and backed up the Raspbian image to it, from BB.
> 4) I used Win32 Disk Imager to put the Raspbian image on to the microSD on its own, without BB.

Berryboot backups are meant to be imported in Berryboot (by holding down your mouse cursor over the "add OS" button and selecting "from USB stick" in the dropdown)

Not going to work with Win32 disk imager, or anything else that runs under Windows.

If you want a standalone image, you'll need to use Linux, create 2 partitions, one FAT, one ext4.
On the first partition: put the Raspberry Pi firmware files from: https://github.com/raspberrypi/firmware/tree/master/boot
On the second partition: unsquashfs your Berryboot backup file.

**Comment by SeanGeb** [comment]
That... was exactly what I wanted to hear! Thank you very much - I'll close this once I am sure it works. This sort of 'customer support' is what makes us mere users happy!
Keep working on BB, it's a brilliant tool.

So I should be able to just download the zip of the firmware, stick it on the FAT partition (which version of FAT? Just a standard FAT partition?) and use my Ubuntu VM to sort out the ext4. I'm guessing that the Pi handles the updates and config, so all I'll need to do is use the firmware as-is.
Thanks again.

**Comment by maxnet** [comment]
> So I should be able to just download the zip of the firmware, stick it on the FAT partition (which version of >FAT? Just a standard FAT partition?)

Standard FAT16/FAT32. Not exFAT
Only copy the contents of the "boot" folder to the root folder of the FAT partition.
If you download a .zip of the firmware github repository, you get other files like a toolchain as well.

**Comment by SeanGeb** [comment]
Cool... but I have no idea what a toolchain is... I feel like a scrub now :(
At least I can boast of modifying the very heart of a linux distro if I add a comment, right? XD
Just trying it at the moment, once my Ubuntu VM sorts itself out, I'll be sticking on the Raspbian files on the ext4, but I've managed to use Windows utils up until now. Might make a tutorial for others that want to do this.

Thanks again.

**Comment by SeanGeb** [comment]
Right, finished it (finally, found it was super easy using Ubuntu running off my memory stick, it didn't like VirtualBox), but when it starts, a kernal panic ensues.

[Anything in "" is exactly what Ubuntu says]
"Partitioning: Master Boot Record" for the whole card.#

1) I copied the boot part of the firmware to a FAT32 (Ubuntu says it's a "W95 FAT32 (LBA)", with "Contents: FAT (16-bit version)") partition. Set the size to 128MB (Ubuntu now says it's 129MB).

2) The Raspbian image went in the rest in an ext4 partition, size was about 15GB ("Contents: Unknown (squashfs 1024.0)").

3) Ejected the microSD.

4) Put it in B+, boots with the RPi symbol in the top of the console, loads of kernal messages flash past, which all seem good, then I get a kernal panic (yikes!). Message is:
PANIC: VFS: Unable to mount root fs on unknown-block(179,2) 
I'll stick an image of the console up in a sec.
The main line beforehand is it listing avaliable filesystems - it finds both the microSD's partitions fine, but immedietly after says:
No filesystem could mount root, tried: ext4.

Possibly it not recognising the FAT32 partition somehow? Am checking, any suggestions (as always!) welcome.

Thanks.

**Comment by maxnet** [comment]
The FAT partition is fine, or it wouldn't have booted at all.
Has problems with the ext4 partition instead.

Did the tool you used to create the partitions created the ext4 as second primary partition, or as logical partition?
If the last, you need to create a cmdline.txt file on the FAT partition that has:

```
root=/dev/mmcblk0p5 rootwait
```

The default cmdline of the Raspberry Pi kernel uses root=/dev/mmcblk0p2, which is ok if the ext4 data partition is the second primary partition.

**Comment by SeanGeb** [comment]
Wow, that reply was BLISTERINGLY fast. I would give you a medal for that.
I'll give it a try a little later, my brain is overloaded and practically smoking right now.

Got the images fortunately:
![image](https://cloud.githubusercontent.com/assets/10674942/5888086/efcdbdc6-a3e8-11e4-8255-29e97d48c2c4.png)
![image](https://cloud.githubusercontent.com/assets/10674942/5888089/fbb65972-a3e8-11e4-8da0-709fb048fa0b.png)

Sorry for the bad quality, I blame Apple.

**Comment by maxnet** [comment]
You do have mmcblk0p2 there, so it is a primary partition, which is good.

> 2) The Raspbian image went in the rest in an ext4 partition, size was about 15GB ("Contents: Unknown (squashfs 1024.0)").

That doesn't sound like an ext4 file system though. And unlike the Berryboot kernel, the stock Raspberry kernel doesn't understand the Squashfs filesystem format without additional modules.

Using your Ubuntu cd, create an ext4 file system instead:

```
sudo mkfs.ext4 /dev/sdX2
```

Where sdX2 is the second partition device of your SD card. Make sure you don't get this wrong, and it is not your hard disk. :-)
Or use a GUI tool like `gparted` instead

Mount it somewhere:

```
sudo mkdir /mnt/mymountpoint
sudo mount /dev/sdX2 /mnt/mymountpoint
```

Unsquashfs your backup file there, and unmount again. Using commands along the lines of this (untested):

```
sudo unsquashfs -d /mnt/mymountpoint your-berryboot-backup-file.img
sudo umount /mnt/mymountpoint
```

If unsquahsfs is not a recognized command, you might need to do `sudo apt-get update && sudo apt-get install squashfs-tools` first, don't know if it is installed by default on your rescue cd.

**Comment by SeanGeb** [comment]
Hi again

While unsquashfs'ing, it came up with three messages (not errors):

create_inode: socket [Extraction Directory]/tmp/.lxterminal-socket:0.0-root ignored
create_inode: socket [Extraction Directory]/tmp/.pcmanfm-socket--0-pi ignored
create_inode: socket [Extraction Directory]/tmp/.pcmanfm-socket--0-root ignored

I'm guessing that's fine?

Copying now, lets see how this will do!

It errors copying 'lost+found' ("Failed to remove target: It is a directory"), but I guess that's fine, I never had to use it luckily. Turns out it was hidden, and the command took care of it anyway (good ol' sudo!)
I just wish mv had a progress bar.

**Comment by SeanGeb** [comment]
Dammit,
PANIC: No working unit found. Try passing init= option to kernel. See
Linux Documentation/init.txt for guidance.

I'm really sorry this has taken so long! Don't worry, I'll repay it by
creating a tutorial for people! Thanks for all the help so far.

**Comment by maxnet** [comment]
> I just wish mv had a progress bar.

Why are you using mv?
unsquashfs to the mount point where you mounted the second partition of your SD card directly.

**Comment by SeanGeb** [comment]
Nah, for some reason that didn't work, something about an error?

Will just try some other stuff in the meantime, bear with!

Thanks for all the help so far, its been very useful.

**Comment by maxnet** [comment]
> Nah, for some reason that didn't work, something about an error? 

Might need to prepend the options with "-f" to force it to do as told, if it complains about the folder already existing.

**Comment by SeanGeb** [comment]
Hah, something finally worked XD
So  I started over on formatting the microSD, and it worked perfectly. I named the partitions according to what I'd (thought) I'd seen (so the FAT as "boot", the ext4 as "data"). It booted up fine (though quite slowly, especially on the preliminary keymap), but got to the login prompt.
Then I tried to log in. Details were fine, but in the no warrenty message, it said:
"Unable to cd to '/home/pi'"
Even though that directory exists! :)
Then the login prompt reappears, and even though the details are correct, it never lets you log in :(
Some things from the boot sequence that may help:
- 'libkmod' cannot load, has an error
- console font and keymap takes a while
- preliminary keymap takes a while
- could not host some ssh host keys
- 'VFS: mounted root (ext4 filesystem) readonly on device 179:2.'

**Comment by maxnet** [comment]
> "Unable to cd to '/home/pi'"
> Even though that directory exists! :)

Did you unsquashfs directly to the moint point like I suggested?

If you used other commands to copy the information, and did not use the right flags, you likely lost file ownership information (uid/gid)...
If /home/pi is suddenly owned by user root instead, user pi cannot access it.

Might also need to uncomment the lines in /etc/fstab

**Comment by Rand0mUsers** [comment]
Yeah, I did everything directly, so I'll check the ownership of the directory

**Comment by Rand0mUsers** [comment]
Right, so when I try to chown the /home/pi directory, it won't accept the username pi because it doesn't exist here, so what can I do?

**Comment by SeanGeb** [comment]
Checked ownership of /home/pi, it was root, so I copied the fs again.

Can confirm it's using the correct permissions now, no idea why it lost them in the first place.

Don't know why I'd need fstab, it looked fine (in a confusing manner). What would uncommenting the lines do?

**Comment by maxnet** [comment]
> Don't know why I'd need fstab, it looked fine (in a confusing manner). What would uncommenting the lines do?

Remount the root file system read-write (in case you specified "ro" to be used at boot in cmdline.txt)
Mount any other filesystems. E.g. /dev/mmcblk0p1 on /boot, allowing tools like rpi-update to access the FAT partition, if they want to update that.

**Comment by SeanGeb** [comment]
Yeah, I understood absolutely none of that XD
It works fine now, just a few errors in the boot log, will chuck them here when it finishes updating

Thanks for everything!

**Comment by scargill** [comment]
Did you everdo that tutorial - there has to be an easy way for non-Linux people to do what I need.

I have a brand-spanking new JESSIE installation on a Pi2 with loads of installations in it.. I made the mistake of NOT using Berryboot. I need to convert that installation so that it can be imported into Berryboot and ran (and the only reason to do that is Berryboot's back and restore facility which is almost child-proof).

Is there a script around to make life easy - I have the installation on a 16GB uSD... I'd like to put it on a USB stick, put a 16GB uSD with Berryboot into the Pi2 and import that image...   there are instructions on the Berryboot site but they make too many assumptions about Linux knowledge.

**Comment by scargill** [comment]
I got your email Maxnet but I don't have a Linux PC, I do have another PI but that does not have the software needed and I didn't understand the references and locations of the different files..

**Comment by mimi89999** [comment]
@maxnet If I understood, the steps are (to move to Raspbian):
1. Download the Raspbian image from the website.
2. Put the first partition on the SD card
3. Backup the OS from Berryboot menu
4. Put the backup on the second partition of the SD card
5. Correct the fstab file

Is this correct?

**Comment by maxnet** [comment]
Yes.
Or if you know how to partition and format yourself, for step 1, just download the boot.tar.xz from: http://downloads.raspberrypi.org/raspbian/boot.tar.xz instead of the entire image.
