### ISSUE TITLE
Berryboot on RPi2

### ISSUE THREAD

**Issue by foznoth** [maxnet/berryboot#131]
Now the 2nd gen board has been released.  Any chance of Berryboot being compiled for that?

Steve

**Comment by lennvilardi** [comment]
It will be nice to have this update ...

**Comment by maxnet** [comment]
http://downloads.sourceforge.net/project/berryboot/berryboot-20150206-pi2-only.zip

**Comment by peter0123** [comment]
.. Buggy.. No iscsi support

**Comment by lennvilardi** [comment]
I cannot connect myself to my iSCSI volume, got an error : Error connecting to target. Check settings.
I change the initiator iqn and tried to create an another iSCI volume on my nas still not working.
