### ISSUE TITLE
Adding your own custom operating systems to the menu

### ISSUE THREAD

**Issue by jibtga** [maxnet/berryboot#133]
Hi

I follow the tutorial of web page to add other image to berryboot, but it can't get work to openelec. Could you explain  some How to, for this special system.

Thanks

**Comment by maxnet** [comment]
OpenELEC's SYSTEM file is already in the right file format.
Just rename it to OpenELEC.img128 and import it to Berryboot.

**Comment by panfri787** [comment]
Maxnet, Are you refer about img file or tar file from openelec website?

Thank you.

**Comment by maxnet** [comment]
The file named SYSTEM inside the tar.

**Comment by panfri787** [comment]
Well, that works thanks by faster response.

Good job!

**Comment by jibtga** [comment]
Thanks for answering. Great software
