### ISSUE TITLE
How get BerryBoot to load latest versions of Raspbian and OpenELEC?

### ISSUE THREAD

**Issue by DennyW41** [maxnet/berryboot#134]
MaxNet, I really like what you have done to create BerryBoot.  Great user interface, fast and easy download and install, wonderfully automatic.
Only problem is, it's not loading the lastest Raspberry Pi organisation software nor the new version of OpenELEC.  The version of Raspbian doesn't incorporate the new startx GUI and underlying features, which is much cleaned up from their older versions.  
Any timetable for implementing those?  Is there a workaround to get them loaded?  (sudo apt-get doesn't "get it.")
Again, thanks for your great work...
Regards, DennyW41

**Comment by maxnet** [comment]
Do have OpenELEC 5.0.1 for Pi 2. Haven't had time to test it on a Pi 1 yet.
Plan to update Raspbian and the various ARMv7 images (Ubuntu, Fedora, Sugar, Android) eventually, but cannot make any promise to a schedule.

**Comment by were55** [comment]
Maxnet,

I see that you updated berryboot for RPi-2, happy to tested in one week (when arrived). One question, how can I load OSMC? I tried several ways and not find how to do it work.

Thanks and congrats for you nice work

**Comment by roel8032** [comment]
Not working on Rapsberry PI 2 B. 32GB SD card. Working: Install Openelec 5.01. Second start of Openelec not working. Errors.

**Comment by roel8032** [comment]
Both not working. feb. 6 and feb 11 version.

**Comment by roel8032** [comment]
It works on a 16 GB sd card. What is the maximum card size? Will it work on a sd card of 32GB after resize the partition before installing BerryBoot?

**Comment by maxnet** [comment]
Got a photo of the errors?

**Comment by roel8032** [comment]
I already deleted the card.
Have to reinstall.
Come back to you soon with a photo.
Yours,

Roel

Van: maxnet [mailto:notifications@github.com] 
Verzonden: woensdag 11 februari 2015 11:04
Aan: maxnet/berryboot
CC: roel8032
Onderwerp: Re: [berryboot] How get BerryBoot to load latest versions of Raspbian and OpenELEC? (#134)

Got a photo of the errors?

**Comment by roel8032** [comment]
I can not recreate the errors, because the openelec is no longer on the download folder: 

Yours

Roel 

Van: maxnet [mailto:notifications@github.com] 
Verzonden: woensdag 11 februari 2015 11:04
Aan: maxnet/berryboot
CC: roel8032
Onderwerp: Re: [berryboot] How get BerryBoot to load latest versions of Raspbian and OpenELEC? (#134)

Got a photo of the errors?

**Comment by Chickenmarkus** [comment]
OpenELEC's images (v5.0.3) distinguish between ARM11 of Pi and ARMv7 of Pi 2: http://openelec.tv/get-openelec
Is BerryBoot's image "OpenELEC_5.0.1.img128" really for both?

**Comment by maxnet** [comment]
It's ARMv6 (ARM11) so the image should run on both as far as architecture goes.
However I am not sure if the kernel we ship with Berryboot for the Pi 1 is not too old.
Like I said, I haven't tested it on a Pi 1 yet.

**Comment by roel8032** [comment]
There is no img for Pi 1 and Pi 2. See: http://openelec.tv/get-openelec 
The version is already to 5.03.

**Comment by maxnet** [comment]
> There is no img for Pi 1 and Pi 2.

Again: their image for Pi 1 does run on a Pi 2 with our Pi 2 kernel.
It only has the downside that it may be slower in theory than their ARMv7 Pi 2 image, but does work.

Just not sure if their Pi 1 image, works on a Pi 1 with our Pi 1 kernel, as our Pi 1 kernel is old.
Haven't tested that yet.

**Comment by maxnet** [comment]
Works on a Pi 1 with our old kernel as well.

Upgraded Raspbian and OpenELEC to 5.0.3
