### ISSUE TITLE
problem with update OpenElec version 

### ISSUE THREAD

**Issue by sealexcz** [maxnet/berryboot#135]
My setup:  RaspBerry Pi 2 B,  OpenElec 5.01,  Kingston 16GB Class 10
Cannot update version of OpenElec ( actual version 5.03).
After automatic download of new version it goes to restart and nothing change.
On standalone installation of OpenElec I have no problem.

I like berryboot so much, so fix this please.

**Comment by maxnet** [comment]
Duplicate of #126

Berryboot doesn't support updating operating systems automatically.
You can do so manually.
