### ISSUE TITLE
BerryBoot 2.0+openelec 5.0.3+youtube glitch?

### ISSUE THREAD

**Issue by Haris1977** [maxnet/berryboot#138]
Greetings. I set up berryboot to work with latest openelec image (5.0.3) in my rasp pi model b.

While it works very good i have a specific "glitch" with some youtube videos. With default youtube settings many videos play with only audio and not video. 

If i change youtube seetings (video quality to 144p - lowest video quality settings) those videos play with audio+video !! But in low quality...

If i change yt settings (video quality other than 144p, eg 360p 480p 720p 1080p) those videos wont play !! (only sound)

Is it a known bug??

**Comment by Haris1977** [comment]
Is it only me to have this issue?

If you want to test it. Go into youtube (openelec 5.03 in bb). Search channels: makeleio2012. Open a random video. No video only audio!!

**Comment by maxnet** [comment]
Does work for me.

![screenshot000](https://cloud.githubusercontent.com/assets/1123701/6328972/c5b97e30-bb6c-11e4-9359-c576b3f991c6.png)

If you press "O" on your keyboard, does it show you are being fed a different video format than h264?

**Comment by Haris1977** [comment]
I have uninstalled my bb image and i cannot test it. If there is no h264 video format how can i change it?

**Comment by maxnet** [comment]
h264 should be the default if you did not specify any special settings anywhere.
Try not associating OpenELEC with your Youtube account -if any- to be sure no settings come from there.

**Comment by Haris1977** [comment]
Thanks.I will test and report back

**Comment by maxnet** [comment]
Also, were you using a packaged Berryboot version (like berryboot-20140814.zip) or did you compile from source?

If the last, you may have newer firmware, with issues.
https://github.com/raspberrypi/firmware/issues/365

**Comment by Haris1977** [comment]
I used a packaged bb image. I also used a usb flash drive to write the image to. Then installed youtube. Will have to check it again though..

**Comment by Haris1977** [comment]
Checked it. No problem. The problem was when "specifying" special settings on youtube plugin.
