### ISSUE TITLE
berryboot, custom os to harddrive problem

### ISSUE THREAD

**Issue by Kmhamel** [maxnet/berryboot#139]
raspberry pi model 2
installing a custom os to harddrive using berryboot.
get:
[warn] mount point '/squashfs' does not exist. skipping mount

at the end:
df: '/squashfs' : no such file or directory

This has happened to three other os's that others have used. They on the other hand put them on SD cards and not a harddrive.

When using a OS from the repository there is no problem.
making the squashed os was done using the instructions supplied by berryboot.

**Comment by maxnet** [comment]
Can simply ignore that warning.
