### ISSUE TITLE
Upgrade not working for me

### ISSUE THREAD

**Issue by chapas** [maxnet/berryboot#14]
I'm having a issue when entering the menu:

1 - berryboot detects a new update/recent version
2 - it downloads it form the web
3 - seems to be installing/upgrading
4 - reboot
5 - back to step 1 like nothing happened and so on unless i don't accept the upgrade

Thanks,
chapas

**Comment by maxnet** [comment]
Are you using Berryboot on a Raspberry Pi or another device?
If a Pi, can you post the contents of your config.txt file?

**Comment by chapas** [comment]
Berryboot on raspi Mod. B 512MB.

Forget to mention that current version on pi is 1.2

Lines from config.txt:
disable_overscan=1
kernel=kernel_berryboot.img

**Comment by maxnet** [comment]
Seems it was unable to update config.txt

Double check that you have files named kernel_rpi_aufs.img and berryboot.img on your SD card.
And if so, edit config.txt manually to this:

`
disable_overscan=1
kernel=kernel_rpi_aufs.img
initramfs berryboot.img
`

**Comment by chapas** [comment]
Checked that they existed.
Edited
It hangs up now, just like on the image
![20130214_230851](https://f.cloud.github.com/assets/682276/158964/75bcea18-76fc-11e2-86ae-a29eca17bdad.jpg)

**Comment by maxnet** [comment]
Double check there is no typo in "initramfs berryboot.img"

**Comment by maxnet** [comment]
Alternatively, try copying the config.txt from the new .zip.
This ensures that there isn't a problem with your text editor (e.g. some Windows text editors insert MS-DOS style  line-ends)

http://downloads.sourceforge.net/project/berryboot/berryboot-20130213.zip

**Comment by chapas** [comment]
You are right, "initramfs berryboot.img" was not ok.
Fixed now and its starting up.
The upgrade does not update config.txt
Thanks for the help (no longer an issue for me)
