### ISSUE TITLE
Issue using berryboot-20150211-pi2-only.zip and headless configuration

### ISSUE THREAD

**Issue by markhm** [maxnet/berryboot#141]
The following combination did not work for me:

```
http://downloads.sourceforge.net/project/berryboot/berryboot-20150211-pi2-only.zip
http://www.berryterminal.com/doku.php/berryboot/headless_installation
```

I was able to configure both eth0 and wlan0, which both worked, but could not access via VNC. Apart from that, everything did look normal. I could format a partition, select and download an OS, etc. 

However, as an undesired side-effect, BerryBoot did not finalise the install of the OS, or perhaps better said, writing the option to load it to the boot partition. So a reboot after the installation brought me back to the install menu, time after time.

When using a clean, unmodified berryboot-20150211-pi2-only.zip archive, I was able to successfully configure and install. 

I modified cmdline.txt on OS-X using TextWrangler as Unix (LF) and UTF-8, so I doubt that was the problem.

**Comment by VTTR** [comment]
same Problem here!!

using the PI2 with the berryboot-20150211-pi2-only on my transcend micro sdhc card (TS16GUSDC10)
also using a hdmi-cable to my samsung tv and a wifi-stick (edimax)

berryboot is connected to wifi and able to download some os but there is no way to connect through vnc.
also after setting one os as default and clicking on exit - the berryboot is still starting in the initialization-mode.

**Comment by maxnet** [comment]
Same issue as #154
VNC via wifi should work in the latest version.
