### ISSUE TITLE
BerryBoot-2015/02/11-pi2-only.zip and Raspberry PI 2 - Other Distro's (Not Raspbian)

### ISSUE THREAD

**Issue by adamrharding** [maxnet/berryboot#143]
Openelec, sugar and all other distributed OS's don't work on the Berryboot setup selection.  Openelec errors at sourceforge and sugar somewhere else,, Raspbian is the only one that works.  Can anyone help, please?

**Comment by paansamari** [comment]
Openelec 5.0.3 works on my setup. At boot "Failed to start Load Kernel modules" appears. Openelec functions well though, but can't be updated to 5.0.5. Fedora 21 Mate works well.

**Comment by maxnet** [comment]
> Openelec, sugar and all other distributed OS's don't work on the Berryboot setup selection. Openelec 
> errors at sourceforge and sugar somewhere else,, Raspbian is the only one that works. 

Sounds more like you had some temporary problems with your Internet connection.
Assuming they have been solved by now, and closing this.

> At boot "Failed to start Load Kernel modules" appears.

That's more or less normal.
Always happens unless you configure LIRC with an overlay.
