### ISSUE TITLE
filesystem.armv7hl 0:3.2-28.fc21

### ISSUE THREAD

**Issue by nolteg** [maxnet/berryboot#145]
Hi All, does anyone know why the update from filesystem. armv7hl 0:3.2-27.fc21 to filesystem.armv7hl 0:3.2-28.fc21 fails because of version filesystem.armv7hl 0:3.2-27.fc21not being removed?

**Comment by maxnet** [comment]
Does not sound like a Berryboot related question.

fc = Fedora?
