### ISSUE TITLE
Berryboot 2.0 on Raspberry Pi 2 - Backup problem

### ISSUE THREAD

**Issue by postacik** [maxnet/berryboot#149]
I'm using Berryboot 2.0 and Raspberry Pi 2..

I am trying to backup an OS using the image + data option but I get "Msquashfs does not have enough memory" error.

Is there a way to fix this error?

**Comment by postacik** [comment]
Can this problem occur because of the following -read-queue, -write-queue and -fragment-queue parameters? (mainwindow.cpp)

args << "/aufs" << destfileName << "-comp" << "lzo" << "-noF" << "-noD" << "-no-progress" << "-read-queue" << "16" << "-write-queue" << "16" << "-fragment-queue" << "16";

**Comment by f15radar** [comment]
I'm having the same problem.  I desperately need to do a backup.  Is there either a fix or a workaround available?

**Comment by maxnet** [comment]
Not sure what is up with that. Would expect the Pi 2 to have sufficient memory.
Is there anything special about the file system you are trying to backup? E.g. an extraordinary large number of files?

> Can this problem occur because of the following -read-queue, -write-queue and -fragment-queue 
> parameters? 

The parameters REDUCE the memory consumption of the queues to 16 MB each.
They are normally larger by default (read 64 MB, write 512 MB, fragment 64 MB)

**Comment by postacik** [comment]
I have two OSs installed (Raspbian and OpenElec).

When I try to backup any of those with image + data option, I get that error.

You can try yourself if you have a Pi 2.

**Comment by f15radar** [comment]
I know I am not trying to back up a huge amount of files.

**Comment by MOhlmann** [comment]
Hallo,
ich habe das gleiche Problem. Raspbian kann ich kein Backup erstellen. Bei dem OpenElec geht es aber.

**Comment by peter0123** [comment]
@MOhlmann 
Ich habe es gerade getestet und es klappt. hast du die originalen Einstellungen? Wenn nicht, stell mal die config auf die default werte.
Lauft bei dir alles auf einer SD?

@postacik i have no problem, but i work with iscsi. have you test the default/original settings?

**Comment by MOhlmann** [comment]
@peter0123 
Ja, die Einstellungen sind die Originalen. Und es ist alles auf einer 16GB SD-Karte drauf. Backup Image+Daten geht nicht. Weder mit OpenELEC noch mit der RetroPie Installation. Es kommt bei beiden der gleiche Fehler.

![wp_20150531_11_04_52_pro](https://cloud.githubusercontent.com/assets/11851134/7901389/1772c312-0785-11e5-8127-430adec20a30.jpg)

**Comment by peter0123** [comment]
Schick mir mal die wichtigsten config Dateien von bootberry, ich teste es
für dich. Benutzte Kingston und pny SD Cards 8gb, sollte aber egal sein,
mit welchen wir testen.

Und ein Tipp am Rande, ich hatte auch mal sehr unerklärliche Probleme die
mich Stunden gekostet haben, am Ende lag es am download oder am entpacken
von den Bootberry Dateien, aber ich hab da auch gleich die SD Karte neu
formatiert und dann ging alles. Verwende 7-zip zum entpacken. Lg
Am 31.05.2015 11:06 schrieb "MOhlmann" notifications@github.com:

**Comment by MOhlmann** [comment]
Hallo, hier mal config. Ich denke es liegt aber an der Daten-Partition. Ein Backup des Original-Images geht ja. Nur nicht wenn ich Image und Daten auswähle.

[config.txt]
disable_overscan=1
overscan_scale=0
start_x=1
#gpu_mem=128
gpu_mem_256=128
gpu_mem_512=256
gpu_mem_1024=384

# Berryboot settings, do not change

initramfs berryboot.img

[pi2]
kernel=kernel_rpi2_aufs.img

[pi1]
kernel=kernel_rpi_aufs.img
cma_lwm=16
cma_hwm=32
cma_offline_start=16

[cmdline.txt]
smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=10 datadev=mmcblk0p2 qmap=de

**Comment by peter0123** [comment]
Aber heute wird es sich nicht mehr ausgehen, also warte nicht auf das
Ergebnis, vielleicht Nachts. Schraube gerade eine neue Workstation zusammen.
Am 31.05.2015 12:01 schrieb "MOhlmann" notifications@github.com:

**Comment by g1t-dlanor** [comment]
I too have the same problem as stated in the original post of this issue, in that all attempts to make image backups including modifications lead to an error message about Mksquashfs requiring more RAM (which is absurd on an RPi2 with its 1GB of RAM available).

This problem has also been involved in other issues raised recently, such as #169 and #183, possibly because the people starting those issues were not able to follow this thread due to the switch of recent posters here to the German language.
