### ISSUE TITLE
Add this great server solution on berryboot

### ISSUE THREAD

**Issue by miguipda** [maxnet/berryboot#15]
Hi,

here is for me the better small server I found.
Superb Mini Server. It has so many needed fetures : http://sms.it-ccs.com/features.html
that I am sure it could become the perfect server to deliver trhoough berryboot.

As somebody already made a slackware based distribution for Raspberry Pi :
http://rpi.fatdog.eu/
it means you could add this Superb Mini Server (SMS) on the berryboot :
http://sms.it-ccs.com/downloads.html

With pleasure to discover soon a new berryboot version with this Superb Mini Server.

Have a nice day,

Miguipda ;-)

**Comment by maxnet** [comment]
Sorry, no plans for that.
However if someone else would like to create an ARM port of the SMS distribution and creates a Squashfs image, I would happily add it to Berryboot.
