### ISSUE TITLE
Disable for Berryboot Icon in Display Corner

### ISSUE THREAD

**Issue by infinityab** [maxnet/berryboot#150]
Could you explain how to disable the multi-coloured Berryboot icon displayed in display right corner using Kodi - it's burning my screen! Great utility BTW!

**Comment by smileybob** [comment]
Hi,
I also experienced this multicoloured icon on my raspberry pi 2.
The appearance of this icon is not s berryboot problem but is something that happens on pi 2 systems to show you visually that they are not getting enough power.
It could be a low quality usb cable you are using or you will need to use another more powerful power supply.
Hope this helps :)

**Comment by infinityab** [comment]
Changed the PS for a 2amp job but no change, tried using my Samsung Tab cable which is chunkier and Voila! No more icon - thanks.

**Comment by smileybob** [comment]
Glad I could help, I've had to buy a better USB lead myself recently since overclocking my pi2.
It was working ok but would randomly reboot or freeze, changed to a better quality USB and problem solved ;)
