### ISSUE TITLE
network config openelec

### ISSUE THREAD

**Issue by buzzbo** [maxnet/berryboot#153]
I have been trying to get OpenElec network config and it has not been successful with either wlan0 and eth0. I tried with 3 different OpenElec images on sourceforge with no luck on network. On a separate microsd card, I have noobs with OpenElec 4.0.5 and network works fine.

I was also running Puppy alpha4 and it was having some strange network issues, so it got me wondering if it might be the berryboot auto network configuration.

I edited the cmdline.txt file, commenting out the network as such:

```
smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=10 datadev=mmcblk0p2 sound=hdmi
#ipv4=192.168.0.232/255.255.255.0/192.168.0.1/wlan0piersol2tb2:/shares/Public#
```

Then I booted OpenElec 4.0.6 and got the network up using wlan0. Is this a standard way to do this, or am I missing something?

**Comment by maxnet** [comment]
You will need to configure OpenELEC's network settings separately from Berryboot.
We only pre-configure the settings for operating systems that store their network settings in /etc/network/interfaces (Debian and friends).
