### ISSUE TITLE
iSCSI Connection - boot from iSCSI, connected with WLAN, not LAN

### ISSUE THREAD

**Issue by chiabudini** [maxnet/berryboot#154]
Hi,
My berryboot system works great, My image lies on iSCSI, hosted by QNAP NAS.
But now, I'll like to go a step further and try to connect to my iSCSI Image not with LAN but with WLAN.
Unfortunately loads the driver for my WLAN card not before the attempt to connect the iSCSI device.
The driver loads correctly for the setup-phase of BERRYBOOT, so I think its not a question of the correct driver but rather a question of the moment when the WLAN initialisation starts.
(Every time  I open the Berry-Boot menu, the WLAN card was initialized too.)

So, my question is:
How could I connect the iSCSI storage with WLAN to boot from iSCSI with the WLAN connection therefore to get a bit more location-independent.

**Comment by seiger30** [comment]
Hi,
confirm for me the same problem unfortunately.

**Comment by maxnet** [comment]
Can you try if the following version works better?

http://downloads.sourceforge.net/project/berryboot/berryboot-20150916-pi2-only.zip

Outsources driver loading to udev
That should deal better with USB devices that are not ready (enumerated) at boot yet, but detected a second later.

**Comment by maxnet** [comment]
Closing as no response from submitter

**Comment by chiabudini** [comment]
Sorry, same issue.

WLAN was not initialized to connect to iSCSI.

LAN works fine.

Von: maxnet [mailto:notifications@github.com]
Gesendet: Montag, 12. Oktober 2015 21:23
An: maxnet/berryboot berryboot@noreply.github.com
Cc: chiabudini chia@hoypoint.de
Betreff: Re: [berryboot] iSCSI Connection - boot from iSCSI, connected with WLAN, not LAN (#154)

Closed #154https://github.com/maxnet/berryboot/issues/154.

**Comment by chiabudini** [comment]
Hwinfo from booted image for my wlan card:

  Hardware Class: network interface
  Model: "WLAN network interface"
  Driver: "rtl8192cu"
  Driver Modules: "8192cu"
  Device File: wlan0

Von: maxnet [mailto:notifications@github.com]
Gesendet: Montag, 12. Oktober 2015 21:23
An: maxnet/berryboot berryboot@noreply.github.com
Cc: chiabudini chia@hoypoint.de
Betreff: Re: [berryboot] iSCSI Connection - boot from iSCSI, connected with WLAN, not LAN (#154)

Closed #154https://github.com/maxnet/berryboot/issues/154.

**Comment by Doev** [comment]
Same Problem here. Berryboot successfully setup the wlan connection, but booting over wlan is not possible.
