### ISSUE TITLE
Error installing to SD card

### ISSUE THREAD

**Issue by BeetleHook** [maxnet/berryboot#155]
Latest build of BerryBoot berryboot-20150211-pi2-only 
copy berryboot files to card, boot successfuly, try to add OS, get error
"sd card contains extra files that do not belong to berryboot" on selecting SD card and hitting format.

Appears to be no way of getting past other than to use a USB stick. Happens with three different SD cards of different sizes and manufacturers.

**Comment by maxnet** [comment]
Means there is more than 63 MB worth of files stored on the SD card.

Double check you did not copy the unextracted .zip file itself to the SD card, and only extracted the files inside the zip file to the SD card.

**Comment by BeetleHook** [comment]
Have now identified the issue. 

Original attempt involved format/erase of SD on a mac, then unzip on mac then file copy to SD on a mac. This fails with the message stated.

By doing the whole process (erase/format, unzip, copy) under Windows all works.

Clearly there is something (at this point I don't know what) on the card when the entire prep is carried out in the Mac environment. 

Maybe the extraneous data coukd be identified and berryboot amended to allow for it?

(Just for info, the Windows operations were carried out on the mac using windows run under Parallels so it's not h/w)

Cheers, Beetlehook

**Comment by bitboy13** [comment]
I just ran into same problem on my Mac.  Open a terminal window and list the files on the SD.  You'll find several "hidden" files (starting with a dot) that need to be deleted.  Some are directories, so they'll require a little extra work.  Once they're gone (except "." and ".."), and only the BerryBoot files remain, things will work fine.

**Comment by n1iic** [comment]
I found an empty 4MB partition in front of the Fat32 partition that initially existed on the card. Nuke it all and make one Fat32 partition.

**Comment by al116** [comment]
> I just ran into same problem on my Mac. Open a terminal window and list the files on the SD. You'll find several "hidden" files (starting with a dot) that need to be deleted. Some are directories, so they'll require a little extra work. Once they're gone (except "." and ".."), and only the BerryBoot files remain, things will work fine.

Running 'rm -rf .*' from the SSD directory worked for me without having to look into them further.
