### ISSUE TITLE
Problems with HDMI-CEC on Raspberry pi 2

### ISSUE THREAD

**Issue by panfri787** [maxnet/berryboot#156]
I had a berryboot system in my old Raspberry pi Model B, without problems. 

But now i have a Raspberry pi 2 and I installed berryboot to make dual boot (Openelec + Retropie) but when i try to choose the system wich i want to boot with my Samsung TV remote it doesn't works.

If I select the system with one mouse or keyboard works perfectly but not with TV remote. Any idea?

Thanks

**Comment by maxnet** [comment]
Fixed in 20150401
Forgot to modify the code to detect it is a Pi and CEC should be enabled for the Pi 2.

**Comment by panfri787** [comment]
Works perfectly, thanks for quick support!
