### ISSUE TITLE
berryboot and overlays

### ISSUE THREAD

**Issue by divinours** [maxnet/berryboot#157]
Hi,
Can Berryboot be made to load drivers as overlays using "dtoverlay=..." in the config.txt file, like in Raspbian? I would need it to get my Hifiberry-compatible DAC to work in Raspbian/Berryboot (it works fine in single-boot Raspbian)...
Thanks :)

**Comment by maxnet** [comment]
Yes.
Just put the overlays in the FAT partition of the SD card, and adjust config.txt

**Comment by Chateaudur** [comment]
Hi,
Just tried that, the card is detected but I got no sound in Raspbian or OpenElec. Any instructions? Thanks! :)

**Comment by maxnet** [comment]
> Just tried that, the card is detected 

Then I guess the dtoverlay=... part works.

> but I got no sound in Raspbian or OpenElec. Any instructions? 

Suggest you ask the place you got the card from for instructions.
Do not have any of those myself.

**Comment by Chateaudur** [comment]
Thanks for your answer. Actually, my bad, the card is detected in Raspbian, but not in OpenElec which does not allow any configuration, shouldn't it appear automatically in the list of audio devices?

**Comment by maxnet** [comment]
Like I mentioned, I do not own such a card.
So am not the right person to ask if it is supposed to show up automatically there.
