### ISSUE TITLE
Make my own OpenElec image for BerryBoot

### ISSUE THREAD

**Issue by stefano-px** [maxnet/berryboot#161]
Hello. I read carefully your "how to to add your own OS". I set up my linux desktop with kpartx et cetera. The guide does not work with OpeneElec image, at least do not with 5.0.8 for Raspberry pi2. When mount loop*, there is no filesystem tree, there'is justa another big SYSTEM file (img, compressed filesistem?). Please, can you upgrade your guide for Openelec image? Thanks.

**Comment by maxnet** [comment]
Just rename SYSTEM to OpenELEC.img128
It is already in our format :-)

**Comment by stefano-px** [comment]
That's great! Thank you for info and thanks again for BerryBoot!
