### ISSUE TITLE
Question - play sound during startup berryboot

### ISSUE THREAD

**Issue by roblad** [maxnet/berryboot#163]
Hi,

Is it possible to add startup sound in berryboot ?
I add madplay package and modify init script and put mp3 file in source of system in /root dir

like:
# Show GUI, it will write the OS choosen to /tmp/answer

/usr/bin/BerrybootGUI -qws 2>/tmp/debug
# Clear screen

clear
/usr/bin/madplay /root/startup.mp3 >/dev/null

And without success - is it possible to get sound playing during start up ?

**Comment by maxnet** [comment]
If you are using a Pi: you probably need to load the sound kernel module first.

**Comment by roblad** [comment]
Hmm,

haw to do it ? somewhere in init ? do you have any idea for that ?

Thanks,

**Comment by maxnet** [comment]
Modules are normally not available until after Berryboot mounted its storage partition.
So if you want to have sound before that, you will have to remodel Berryboot yourself, or build sound support statically into the kernel instead of as module.

**Comment by roblad** [comment]
Hi,

I means that it is not possible for me, I can start it just after erryboot mounted its storage partition, it could be there , but it is to difficult for me remodeling berryboot. I can add to the kernel build sound support statically - through make menuconfig.

But, if you have maybe some plans for new things in berryboot the play sound will be nice during boot.
