### ISSUE TITLE
BerryTerminal not running on Raspberry Pi 2 

### ISSUE THREAD

**Issue by umutcansu** [maxnet/berryboot#165]
hello,
Does it work on the berryterminal raspberry pi 2? I could not run.
http://www.berryterminal.com/doku.php/berryboot
I follow the procedure on the page, but throw exception LTSP server not found.
thanks

**Comment by maxnet** [comment]
> LTSP server not found

You do have a LTSP server running?

http://www.berryterminal.com/doku.php/setting_up_edubuntu_as_ltsp_server
