### ISSUE TITLE
berryboot traversing from pi1 to pi2

### ISSUE THREAD

**Issue by imrepentek** [maxnet/berryboot#166]
Hi, not really a bug report, but if you could add a doc to your wiki detailinig how can I traverse from pi1 to pi2 (when using berryboot) that would be appreciated. On my old flash card I have a cmdline.txt and a config.txt wich are different from the new files, and on my old one I have an uEnv.txt which isn't present in the pi2 zip. I'm not exactly sure if I can just copy these three files to make my pi2 work with my old raspbian. Thank you in advance.

Imre

**Comment by maxnet** [comment]
Originally I planned to provide an update through Berryboot itself that would include the Pi 2 files, so you could use your card in both the Pi 1 and 2.
However there are some practical issues with that.
Currently CMA which we are using on the Pi 1 is broken in newer Raspberry Pi firmware updates. And the Pi 2 does not run with the older firmware.
Also I'm not sure if both the Pi 1 and Pi 2 files fit inside the smallish FAT partition created by early Berryboot versions.

As for manual upgrade:
Use the _cmdline.txt_ from your old SD card, and delete/replace all other files on the FAT partition with the Pi 2 files.
uEnv.txt is for Allwinner devices (e.g. Cubieboard), you do not need it for the Pi 1 nor 2.

**Comment by imrepentek** [comment]
Ok, is there any other way to communicate between us, it seems like my HDD loses power for a moment when berryboot starts to boot, there are chances that this is a berryboot related issue

**Comment by alec801** [comment]
Sorry to post on a closed thread, but @maxnet, I was wondering if there was any progress on making a version with both pi1 and pi2 files.

**Comment by maxnet** [comment]
You can make such version yourself when compiling from source.
This thread is about an upgrade path however, and that is complicated if an older version of Berryboot was used that does not have sufficient space in FAT partition.
