### ISSUE TITLE
iSCSI partition recycling

### ISSUE THREAD

**Issue by Htaborda** [maxnet/berryboot#168]
I managed to put a lot of OSes on a iSCSI target, as expected, and everything works fine.

But when the card fails, or if I lose it, how do I reinstall Berryboot to recognize the iSCSI target without formatting it, and starting all over?

**Comment by maxnet** [comment]
Simply backup the contents of your SD card after installation. In particular iscsi.sh and cmdline.txt.
All Berryboot settings are on the FAT partition of the SD card, so the files can be simply copy and pasted in Windows explorer.

**Comment by Htaborda** [comment]
The question is the opposite...if I don't have a backup of the SD card, how do I regenerate the necessary files for the RPi to recognize the data on the iSCSI target?

**Comment by maxnet** [comment]
Let Berryboot connect to another iSCSI target, and modify iscsi.sh to your old connection details.
