### ISSUE TITLE
Remove LUKS

### ISSUE THREAD

**Issue by locutus007** [maxnet/berryboot#170]
Hello!

I am using BerryBoot since what seems for me forever, and i really like it.
But now, the tasks for my RaspBerry have changed, and I need to remove the LUKS encryption on my SD.
How can I do that without reinstalling or loosing my data?

Thanks,
Jack

**Comment by maxnet** [comment]
You will need to copy the contents of the filesystem over to a new SD card using a normal Linux desktop computer.

**Comment by locutus007** [comment]
Thanks for the fast reply.
So the steps are:
- mount the sd card
- backup the files on the encrypted partition
- delete this partition, create a new on(which format, ext2?)
- restore the files
  and it should work just fine?

Thanks,
jack

**Comment by maxnet** [comment]
Berryboot defaults to ext4, although ext2 should also work.
You might also need to remove "luks" from cmdline.txt so Berryboot knows it no longer needs to prompt for password.

Suggest you use tar to archive the files, and extract the files later, so permissions are kept.

**Comment by locutus007** [comment]
i just can't mount the partition on my desktop machine. Which keyboard layout does BerryBoot use?

**Comment by maxnet** [comment]
The one you specified when you installed Berryboot. Defaults to one determined by geoip based on your IP.

**Comment by locutus007** [comment]
well, can i get berryboot to print out the password? I am using a German keyboard, but when i try to mount it on my linux(openSuse) machine, it says that the password is incorrect.

**Comment by maxnet** [comment]
What does cmdline.txt say for qmap=xx ?
If not present it is "us" layout.

**Comment by maxnet** [comment]
Thinking of it, I think it is using "us" layout always, as password is entered in text console instead of GUI.

**Comment by locutus007** [comment]
Its a german keyboard, but even if I use exactly the same keyboard(a wireless Trust-Keyboard), it tells me that i have entered it incorrectly...
Is there some way that BerryBoot can echo my password when i am entering it in?

**Comment by maxnet** [comment]
Berryboot doesn't know your password.

Might be able to open up a console in the Berryboot editor (">>" -> "console" -> "ctrl+alt+f2") and see what characters appear on the screen if you re-enter your password there though.

**Comment by locutus007** [comment]
Well, I know that BerryBoot does not know my password, but this solution has done the job anyway, thanks. Maybe you could add this to the wiki, or even implement a function to unencrypted the drive.
The keyboard layout was kinda messed up, I think that partially, my keyboard is cause of this problem :-(
Thanks
