### ISSUE TITLE
Multiple OSes, same MicroSD card?

### ISSUE THREAD

**Issue by seaders** [maxnet/berryboot#172]
In a perfect World, I'm looking to have all of OSMC, Windows 10 IoT, Android and RetroGaming booting from the one MicroSD card.

First off, I'm asking is this possible?  I got myself a 64GB card a while ago, and can/will partition it however Berry needs it, obviously, but I'm not exactly sure exactly how to go about setting this up.

I've already gone through installing images from Berryboot's main menu (Debian and Android KitKat), I've gone about making an img file from another install (OSMC), and I have the img file for Windows 10 IoT ready to go too.

So, if it's possible, I think I have all the ingredients to do this, so what I'm asking is if I'll be able to do this, but if it's not possible, I'm asking if there's a way to make it possible?

**Comment by maxnet** [comment]
Berryboot requires operating systems to be able to share a Linux ext4 partition nicely with the others.
That rules out Windows 10. Besides that the Windows license does not allow redistribution, which would prevent us from putting any image based on that on our site.

**Comment by seaders** [comment]
In terms of hosting, I'm able to install locally, amn't I?  So any advice on that would be great.

If I can't have it on one SD card, I'd be able to install Windows on another drive, or something along those lines.  And even in the _worst_ case scenario, when Windows is just ruled out altogether, I'd love a little bit of advice on how to set up the rest of them.

I did read your docs, but unfortunately wasn't able to get my head around setting multiple OSes up that weren't in the list on startup.  Overall, would just like a bit more info about how to play with Berryboot, as after initial install, I just wasn't 100% about how to get my custom setup running.

**Comment by maxnet** [comment]
Adding Linux OSes: http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions
