### ISSUE TITLE
rpi-update not working on RPI2

### ISSUE THREAD

**Issue by HellStorm666** [maxnet/berryboot#178]
Running official raspbian, installed from the selector menu in BerryBoot V2.
When running Sudo rpi-update, or sudo BRANCH=next rpi-update the Pi runs all nice.
Then it finshes without problems.
Reboots
And then the version in still the same as in the beginning.

The updates gets 3.18.16-v7+
But after the restart the version is 3.18.10v7-aufs again.

How to update/upgrade RPI2?

**Comment by maxnet** [comment]
Firmware updates are delivered through Berryboot's update system.
No need to use rpi-update.

**Comment by HellStorm666** [comment]
Why is it still version 3.18.10v7-aufs instead of 3.18.16-v7+?
I need 3.18.16-v7+ for drivers.

**Comment by maxnet** [comment]
Then you will need to compile your own kernel.

We will eventually upgrade to the 4.0 branch.
Just waiting for some other issues to get fixed first (like the SD card corruption issue in firmware repo) before releasing any Berryboot update.

**Comment by HellStorm666** [comment]
Any info (step-by-step) on how to do that?
New to this all.

**Comment by maxnet** [comment]
Requires that you have Linux on your normal desktop computer.

1) Install standard development software such as a compiler.

```
sudo apt-get install build-essential libncurses-dev rsync
```

2) Download and compile Berryboot, which will build the kernel as well.

```
git clone https://github.com/maxnet/berryboot.git
cd berryboot
./build-berryboot.sh device_pi2
```

3) get a lot of coffee. Takes a while to build.

**Comment by HellStorm666** [comment]
hmm... don't have a linux desktop.
Would you be so kind to build it and upload it somewhere so I can get it?

**Comment by maxnet** [comment]
Nope.
In that case you will have to wait until the next Berryboot update.

**Comment by HellStorm666** [comment]
lol... Webserver where I work runs Ubuntu14.
Making it now.
Can I upload it somewhere, when its done, so that others can use it to?
