### ISSUE TITLE
Compile a kernel module 

### ISSUE THREAD

**Issue by stefano-px** [maxnet/berryboot#180]
Hello. 

Is it possible to compile a kernel module to work with Berryboot 2 running Raspian? I have a cheap WIFI dongle and the driver source. I'm able to compile a module under a standard linux system, but I'm in trouble with BerryBoot and Raspian.  
Current kernel is 3.18.10v7-aufs

Thanks.

Regards,

Stefano

**Comment by maxnet** [comment]
The driver is not part of the upstream Linux tree at all?
Not even in newer kernel branches like 4.0?

**Comment by stefano-px** [comment]
I don't know about the 4.0 tree. The driver is mt7601Usta.ko for wifi dongle 

 148f:7601 Ralink Technology, Corp. 

On Raspbery forum a user proveded a compiled driver, but it obviously is built against Rasbian kernel. 

All discussion is here:

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=49864

It's something I can live without, but I'd like to know if there is a way to compile the driver.

Thanks

**Comment by maxnet** [comment]
If the driver was not accepted into the main kernel, it means the hardware is either very new (which I doubt, given your 2013 thread), or the code was rejected because it is bad quality.

You can rebuild Berryboot from source, and patch the kernel source in buildroot/output/build/linux-3.18 manually to include the driver.
But I think spending $ 5 on a better wifi dongle might be a better option...

**Comment by peter0123** [comment]
@maxnet - yes, i looked. two, three times on google and your sites.

**Comment by maxnet** [comment]
Yes Peter, this is the wrong place to ask.
My e-mail address is not that hard to find, looked at the front page?

**Comment by stefano-px** [comment]
Hello. Sorry to bother you. Is it possible to download the Module.symvers file of Berryboot Pi2 3.18.10v7-auf kernel. 

Thanks.

**Comment by maxnet** [comment]
Nope, do not keep those, and no longer have a 3.18 build on my disk.

**Comment by stefano-px** [comment]
Uhm.. what about to keep next BerryBoot kernel  Module.symvers on github (for weird request such as mine) ?

**Comment by stefano-px** [comment]
Info: it seems it will be supported in 4.2.

 https://github.com/kuba-moo/mt7601u/issues/9
