### ISSUE TITLE
Add a duplicate/backup OS option 

### ISSUE THREAD

**Issue by C-Fu** [maxnet/berryboot#184]
Good day,

 With any fresh SD card, I would normally do this
1. Install Berryboot
2. Install Raspbian
3. Update
4. Customize to my 1st usage, reboot
5. Rename Raspbian in BerryBoot
6. Install (another) Raspbian
7. Update
8. Customize to my 2nd usage, reboot
9. Repeat for the 3rd time

If there's a way to replace step 4 with duplicate updated OS, that'd help tremendously. Or better yet, an option to "backup" the OS into .img192 or something.

Cheers and thanks for the great software!

**Comment by g1t-dlanor** [comment]
A backup feature does exist, but unfortunately the variant that includes modifications made since original install is bugged. It gives an error message stating that mksquashfs needs more RAM, even when running on an RPi2 unit with a full GigaByte available.
