### ISSUE TITLE
Digi+ board made by HifiBerry is not recognised by the RPi2

### ISSUE THREAD

**Issue by RRajnai** [maxnet/berryboot#185]
Hi,
I have successfully configured my new Raspberry Pi2 using Berryboot and OpenELEC 5.0.8. In order to use my home-cinema system I have bought the Digi+ board for Raspberry from Hifiberry. My problem is that the system does not recognize the board. 
After logging into my running Openelec system via ssh and issuing: aplay -l - I receive:
aplay: device_list:268: no soundcards found...  
I have complained about this to Hifiberry, but they gave this message as a reply:
"it looks like people often have problems with Berryboot and putting the configuration files in the right place. We don’t have any experiences with it. The Berryboot developers might help here. Otherwise I recommend to use a plain OpenElec, we have a guide for this."
According to the guide they are referring to, the user should modify the flash directory as:
mount -o remount,rw /flash
The system however rejects this command by:
mount: can't find /flash in /proc/mounts.
My feeling is they expect the config file to reside in Openelec's flash directory - as it is in the standalone system. My question is, whether there is a way to resolve this issue - or is there someone in the forum who has successfully managed to install a Hifiberry system and booting by Berryboot?
Thanks,
Robert

**Comment by maxnet** [comment]
It should not be necessary to modify anything if your hardware extension complies to the HAT spec: https://www.raspberrypi.org/blog/introducing-raspberry-pi-hats/

For legacy hardware: you can use the Berryboot's built-in config editor to edit config.txt.
http://www.berryterminal.com/doku.php/berryboot bottom of page under the "advanced options" heading.
It may also be necessary to copy the overlay files needed for your hardware to the FAT partition manually.

**Comment by RRajnai** [comment]
Thank you for your answer to my problem.
First I would like to mention, that the board I have bought has advertised itself as fully HAT compliant.
In the mean time I have done was to get an empty MicroSD card and have installed a "stand alone" OpenElec (with the sw version matching the one installed by Berryboot). After boot-up the Digi+ board was recognized in the audio configuration and everything was working fine. (The config.txt file included the modifications necessary for the board in both of the test cases.)
Next I tried to figure out whether there is a difference in the file structure of both of my installations and have found out that there is some. (The way I did was that I have mounted the SD cards - one after the other - to a Linux (Ubuntu) system running in a VirtualBox on a MacBook.)
During my trial attempts I have managed to create a flash directory in the berryboot system and have created a second config.txt file - but still had no success. (In the berryboot/data/OpenELEC_5.0.8.img128/flash directory.) During my search in the internet I have come across the unofficial Raspberry Pi configuration add-on for OpenELEC and after installing it I have found that this add-on indeed has modified the config.txt file I have created for my berryboot installation and the changes are presented on the OpenELEC configuration screen. I have created log files for both of my installations and the problem seems to be, that the Digi+ board is not listed among the Enumerated PI devices. Also when the system boots, on the TV screen the lirc_rpi writes: gpio chip not found. I have copied manually the hifiberry-digi-overlay.dtb file to the FAT partition of my memory card - and also the "overlays" directory with its content, which I have found in my standalone installation.
My conclusion is, that berryboot is causing the problem as it somehow does not pass the necessary information (concerning gpio devices) to the OpenElec or other running systems. Can you help me with further information how I could solve this problem?
Thanks for your time,
Robert
