### ISSUE TITLE
Error downloading file from Internet: file corrupt (sha1 does not match)

### ISSUE THREAD

**Issue by Zedosix** [maxnet/berryboot#186]
Hello everyone, 

I've a problem with my Raspberry Pi 2 and with Berryboot. I cannot download any OS in the menu editor, i've always an error : "Error downloading file from Internet: file corrupt (sha1 does not match)".
I don't understand where is the problem. A network problem ? I have a RJ45 wired connection. 

Thnak you in advance for your help. :)

(PS : I'm sorry for my bad english)

**Comment by maxnet** [comment]
Seems Sourceforge that hosts the OS files is having its maintenance.

```
The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service.
```

Try again later.

**Comment by Zedosix** [comment]
Thanks for that clarification ! It's a good news for me so, because i believed the problème was on my installation. :)
