### ISSUE TITLE
Proper procedure to update OS

### ISSUE THREAD

**Issue by zanie420** [maxnet/berryboot#188]
First off, fantastic software!

So I have been hunting around and I cannot seem to figure out the proper way to update an OS, like OpenElec or Retropie, after initial install. Doing an automatic update from the distributor in the distro does not seem to work. Especially in both of the aforementioned OS's. What additional steps need to be done after an update to make BerryBoot correctly recognize the change? This has cause me some major frustrations :(

I am trying to avoid using NOOBS since it does not allow you to add subsequent OS's, or add them to a USB stick either. With NOOBS is seems like you are stuck with what you first choose.

**Comment by g1t-dlanor** [comment]
Whether internal update methods of an OS will work or not depends entirely on how that OS does it.
I have successfully done it with some RasPlex versions, but even when it works it leads to inefficiency, as BerryBoot stores modifications separately from the original image.

For something like OpenELEC it is probably best to scrap the old install and start a new one for the new OpenELEC release. (A lot of work with configs and add-ons, I know, but the result is better.)

For a console emulator system I'm not sure what's best, but if possible I'd store all ISOs and gamesaves outside the berryboot system (like on external USB drives), to minimize reinstall needs and avoid loss of gameplay states.

**Comment by smileybob** [comment]
The first thing to remember when using berryboot is that it uses the squashfs images to load the OS. the image never gets written to and so therefore any changes are recorded seperately.
 With this in mind what you need to achieve is to simply replace the OS squash image with a newer version whilst keeping its original name you have given to it and thus still leaving the saved changed files working from the new image.

So with openelec in mind, I do the following to update the OS:

On a windows pc Download a program called winscp. https://winscp.net/eng/download.php. choose either the installation package or the Portable, its up to you.

goto openelec website http://openelec.tv/get-openelec and download the openelec not maked as the disk image, (when you select it the file will end with tar).

open the downloaded file using winrar or another similar compression tool and extract the file named "system" (this is the squashfs openelec file!) from the target directory (remember the location you extract this).

On the raspberry Pi load into the berryboot os selection screen, select "edit menu", then select your Openelec image and click on clone image, select to copy the changed data and give it a relevant name such as "test" or "cloned openelec".

Next reboot and select the new Openelec you just created and then load.

Now goto your PC and load winscp and connect to openelec usind the IP address its been given on your network along with the username (root) and password (openelec).

Winscp will load a split directory list, the left side is your pc, the right is your raspberry pi.

At the top of winscp, select options-preferences then select panels, make sure that "show hidden files" is ticked. then click ok.

In the right panel (your openelec instance) click on the .. to go up a level and then you should be now located in the directory.

Next go into var-media-berryboot-images. This is where your image files are loaded in berryboot
 .
 Still in the right panel you need to then change the name of your original openelec image file by adding .bak to it (this is the one you`ve been using and want to update).

on the left screen locate the system file you extracted earlier. drag this file over to the right panel and then select copy, next rename this file to the original openelec file but without the bak, this has now replaced the old openelc with the new one which will be loaded when you reboot and keep all of your original setting!!!

I will try this method soon with retropie

This looks long winded but once you understand what you have just done, you will be able to do this with ease next time :)

I Hope this helps, any problems let me know :)
