### ISSUE TITLE
Android_KitKat_[unaccel].img128

### ISSUE THREAD

**Issue by zsmvpn01** [maxnet/berryboot#189]
hello maxnet,

i've downloaded Android_KitKat_[unaccel].img128 form sourceforge.net, and booted successful use berryboot.
I want customize a kitkat image for my rpi2. I found Android_KitKat_[unaccel].img128 build form Linaro Android 4.4.4_r1, but I found hardware/libhardware/modules/gralloc/framebuffer.cpp is different from Linaro's framebuffer.cpp. I think framebuffer.cpp is modified.
could you send a copy of framebuffer.cpp to me? my email is zsmvpn01@126.com.

thanks.

**Comment by maxnet** [comment]
Modified it to wait for vsync in fb_post() as quick hack lacking a better solution.

```
max@lynx:/mnt/nfs/linaro-android/android/hardware/libhardware$ git diff
diff --git a/modules/gralloc/framebuffer.cpp b/modules/gralloc/framebuffer.cpp
index 08c0a71..90daaac 100644
--- a/modules/gralloc/framebuffer.cpp
+++ b/modules/gralloc/framebuffer.cpp
@@ -102,6 +102,10 @@ static int fb_post(struct framebuffer_device_t* dev, buffer_handle_t buffer)
             m->base.unlock(&m->base, buffer); 
             return -errno;
         }
+        
+        // Max edit
+        ioctl(m->framebuffer->fd, FBIO_WAITFORVSYNC, 0);
+        
         m->currentBuffer = buffer;

     } else {
```
