### ISSUE TITLE
Keyboard navigation in Berryboot menu editor

### ISSUE THREAD

**Issue by anauta** [maxnet/berryboot#19]
Hello. I can use tab and arrows navigation in the initial Berryboot menu (and the "Access restricted!" password prompt, if activated), but in the second "main" window (Berryboot menu editor), I can't use either tab or arrows to move through the options, except for going up and down the OSs list (where pressing "Enter" opens the"Image properties" sub-window for the selected OS). 

ln all the sub-windows, tab/shift and arrows navigation works again as expected, but I just can acess them by mouse click, I checked:  
- Add OS > Network settings
- Edit > Image properties
- Clone > Clone image
- Backup > Export
- Delete > Confirm deletion
- Advanced configuration > Config editor
- Set password > Berryboot settings
- Repair file system > Confirm

I'm using spanish keyboard (qmap=es)

Thank you and congratulations for your great work and support.

**Comment by maxnet** [comment]
It is indeed not possible to access toolbar buttons with the arrows, but the most common operations do have a shortcut key.

Add OS:  CTRL+A  (or "red" button on TV remote)
Edit: Enter
Delete: Del
Exit: Esc

**Comment by anauta** [comment]
Thank you.

I asked because I still don't have a working USB hub and once or twice I've unplugged the mouse to use a wifi dongle or a USB memory stick (and also because, lately, I'm trying to use the mouse less overall...). One of those keyboard-only days I noticed I couldn't edit config.txt without the mouse (I still didn't try the VNC server either yet).

I thought it could be a bug since I could navigate with the keyboard in the main window and all the subwindows.

Would you mind, then, considering full keyboard navigation in Berryboot GUI a -humble- feature request?

(thanks on the remote control tip: unfortunately, the one I'm using doesn't seem to work at all with the raspi, but it's nice to know Berryboot would work straight from the r/c in other TVs!)

so... slightly off-topic: Is there something I could do about this seemingly non-CEC-enabled TV?

My HDMI manual config.txt settings are: 
    hdmi_force_hotplug=1
    hdmi_drive=2
    hdmi_group=1
    hdmi_mode=4
    config_hdmi_boost=4

Well, this has been my first report/request ever (not just here), please excuse me if it was a bit buggy itself...

IMO you're doing a great job, Berryboot is certainly helpful for those of us willing to try and learn within a tight budget/schedule and with not-that-many skills (what could a bunch of skilled rich idle people do with it... is certainly beyond my puréed brains). Kudos.

**Comment by maxnet** [comment]
> Would you mind, then, considering full keyboard navigation in Berryboot GUI a -humble- feature request?

Maybe in a future version.
Problem is we use a standard components library for the GUI, and the QToolbar component does not support keyboard navigation as far as I am aware.
Technically it could be added (Qt is open source), but might be a bit of work.

> so... slightly off-topic: Is there something I could do about this seemingly non-CEC-enabled TV?

I am afraid not.
If it doesn't "just work" out-of-the-box, I don't think there is any setting that can make it work.

The Cubieboard (unlike the Pi) does have an IR sensor that could in theory be used with normal TV remotes, even when the TV does not support CEC.
However this requires configuration and extra software to be installed, which kinda defeats the purpose. (if you need to connect a mouse/keyboard to configure which brand remote you have, you might as well use the keyboard  instead of the remote)

**Comment by anauta** [comment]
> Maybe in a future version.

Let it be a "future" request then... Thanks again for your clear answers!

I googled (and subsequently "stackoverflowed") "keyboard navigation in QToolbar" and read this: http://stackoverflow.com/questions/1377679/problem-with-event-handling-on-qtoolbutton-in-linux

What led me to the QT docs:

> keyPressEvent() is called whenever a key is pressed, and again when a key has been held down long enough for it to auto-repeat. The Tab and Shift+Tab keys are only passed to the widget if they are not used by the focus-change mechanisms. To force those keys to be processed by your widget, you must reimplement QWidget::event().

Not that I can do anything about it (I still read these programming things as if they were different mad sci-fi hallucinations, and what always amazes me is that, hey, you're not actually making it all up!!!), but it's nice to know the why-whys... Gracias chavales, have a nice day!
