### ISSUE TITLE
this looked like abandonware

### ISSUE THREAD

**Issue by bill-hudacek** [maxnet/berryboot#190]
at this page (http://www.berryterminal.com/doku.php/start), you have this text: "Latest beta version is 20131225".

I found out about this software from a mailing list  - where someone mentioned in '14 that it looked like abandonware. 

I'm the curious type so I grabbed the URL, stripped off the file name, and landed on your sourceforge page, where I could see an april 2015 software version. 

You've probably lost potential users because of that page - I saw a mention in another mailing list that this looked like abandonware based on that page.

**Comment by maxnet** [comment]
> at this page (http://www.berryterminal.com/doku.php/start), you have this text: "Latest beta version is 
> 20131225".

Berryterminal has indeed not been updated after 2013.
Didn't make any public release after that as I'm having issues with sound on the Pi, which I do not know how to fix.

Issue about that is here: https://github.com/raspberrypi/linux/issues/688

> I'm the curious type so I grabbed the URL, stripped off the file name, and landed on your sourceforge 
> page, where I could see an april 2015 software version.

That's Berryboot's latest version.

Berryboot != Berryterminal

**Comment by bill-hudacek** [comment]
Thanks for the quick reply.

/Bill
