### ISSUE TITLE
Problem upgrading BerryBoot itself: All installed OS lose keyboard access

### ISSUE THREAD

**Issue by g1t-dlanor** [maxnet/berryboot#191]
I have for some time used the BerryBoot version downloaded as "berryboot-20150211-pi2-only.zip", and it has worked fairly well for me, but I want to be able to update my setup to newer versions without losing my existing installed OS.

I have tested using new BerryBoot content for the SD card boot partition, downloaded as "berryboot-20150401-pi2-only.zip" and simply editing its cmdfile.txt to indicate the correct OS partition (whether on that SD card or external), and it does work in many respects. Every one of my installed OS can be booted from the BerryBoot boot menu, but once they have booted correctly and reached the point where they wait for user input (eg: In main menu of Kodi or RasPlex, or the login screen of Linuxes) then I no longer have keyboard access (though it worked in the BerryBoot menu).

I suspect this has something to do with changed kernel usage in the new version, somehow making it incompatible with keyboard input as used by my old installed OS images.

Is this a known issue ?
And is there some fix or workaround for it ?

**Comment by maxnet** [comment]
Extract the contents of shared.tgz to /shared on the ext4 partition of the SD card.
It contains the kernel modules shared with all OSes.

**Comment by g1t-dlanor** [comment]
OK, I'll try doing that, but should I really extract it to the existing folder without removing its old content  first ?
I do have a backup of that folder (as mentioned in a recent post of another issue), so I can revert if anything goes wrong. But I'd like to know what you consider the proper method.

**Comment by maxnet** [comment]
> OK, I'll try doing that, but should I really extract it to the existing folder without removing its old content first ?

Wouldn't worry about that.

New modules will end up in /shared/lib/modules/3.18.10v7-aufs
Old modules will have a different kernel version, and thus separate folder.

> But I'd like to know what you consider the proper method.

Well, the proper method would be to use Berryboot's built-in self update functionality.
However I haven't made any recent versions available though that, as I am afraid the update may cause trouble for existing Berryboot users.
CMA -which we were using previously, and thus is still in the config.txt of many- is broken in recent firmware.
And newer Berryboot releases may not fit in the FAT partition created by early Berryboot versions.

**Comment by g1t-dlanor** [comment]
OK then. I'm now going to try updating that /shared folder as you suggested above, and will add my results here later on.

**Comment by g1t-dlanor** [comment]
I've now unpacked the shared.tgz file from the newer BerryBoot release into the /shared folder in the "berryboot" partition of my 'WD PiDrive', and it seems to have worked as intended. I can now boot with either the old or the new SD card setup and successfully launch the OS stored in that HDD partition with working keyboard after complete boot. So that problem is fixed.

The only remaining issue is that when I boot into Fedora_21_MATE and have logged in, an error message box is displayed in the top right corner of the screen, saying that a kernel problem has been detected, but without any more details than that. I am then offered the option to "Ignore forever", which makes me conclude that it can't have been any serious system-fatal problem that was detected. My hope is that Fedora simply responds this way because it found something kernel-related that differs from the original install conditions.

Btw: I noticed that it's only the "modules" subfolder of the "lib" folder that uses a subfolder with version-dependent name, while tons of other stuff duplicates file and folder names that already existed. So to cope with that I used the following command to unpack the .tgz file with terminal inside the /shared folder:

sudo tar --overwrite -xhzvf /home/ronald/RA_BUP/shared.tgz

I'm not sure if that's the best way to do it, so I'd welcome improvements/corrections for future use.

**Comment by maxnet** [comment]
> sudo tar --overwrite -xhzvf /home/ronald/RA_BUP/shared.tgz

That's the concept.
If you where doing it from within Berryboot, by going to the menu editor, pressing ">>" and the console button, the line would be:

`gzip -dc /boot/shared.tgz | tar x -C /mnt/shared`

busybox's tar doesn't have the "z" option by default, so you would have to pipe from gzip to tar in that case.

**Comment by g1t-dlanor** [comment]
Thanks for that info, which I've copied to a text file for future use (I don't trust my memory when it comes to detailed parameters of new commandline usage).
Since my immediate problems with this are solved now I guess you can close the issue, though it might be a good idea to leave it 'visible' to guide others with similar problems.
