### ISSUE TITLE
No wifi driver for Edimax EW-7811UN in berryboot-20150808-pi2-only.zip

### ISSUE THREAD

**Issue by lbalogh** [maxnet/berryboot#192]
Hi,

I want to do a full clean reinstall of my pi. But when I first boot with berryboot, my wifi dongle (Edimax EW-7811UN) is not detected.

Was working great in the previous version. Is it possible to add the driver for this device ?

Thanks

**Comment by maxnet** [comment]
Do you happen to know which kernel module your dongle uses?
Try typing "lsmod" on a Linux distribution where the card does work.

**Comment by lbalogh** [comment]
Well, I just reformatted my card :/ I'll reinstall raspbian to check and let you know

**Comment by lbalogh** [comment]
Here is the result of lsmod :

```
cfg80211              386508  0 
rfkill                 16651  1 cfg80211
snd_bcm2835            18649  4 
snd_pcm                73475  1 snd_bcm2835
snd_seq                53078  0 
snd_seq_device          5628  1 snd_seq
snd_timer              17784  2 snd_pcm,snd_seq
snd                    51038  13 snd_bcm2835,snd_timer,snd_pcm,snd_seq,snd_seq_device
joydev                  8879  0 
8192cu                528365  0 
evdev                   9950  6 
uio_pdrv_genirq         2958  0 
uio                     8119  1 uio_pdrv_genirq
```

I believe the module is "8192cu"

**Comment by maxnet** [comment]
The new Berryboot version ships with a newer kernel than before.
It does have that driver though:

`
4.1.4v7-aufs/kernel/drivers/net/wireless/rtl8192cu/8192cu.ko
`

Not sure why it doesn't actually work.

**Comment by lbalogh** [comment]
Ok the problem is that "/lib/modules" does not exists. When I try to manually load the module ("lsmod 8192cu"), I get: 

*can't change directory to '/lib/modules' : No such file or directory.

Then I created a link:

```
ln -n /mnt/shared/lib/modules /lib/module
```

And now the module load correctly. Is there any way to relaunch the wifi selection dialog ?

**Comment by maxnet** [comment]
> Ok the problem is that "/lib/modules" does not exists.

/lib/modules is normally not available, because you do not need modules for wired operation.
But when you select during installation that you want to use wifi, shared.tgz gets extracted, so that /lib/modules does is available.

> Is there any way to relaunch the wifi selection dialog ?

Negative
You do can copy a previously created wpa_supplicant.conf to the FAT partition of the SD card though.

**Comment by lbalogh** [comment]
I assure you that I chose to use wifi during the installation (did it 3 times !). I'll try to create a wpa_supplicant.conf file, as I don't have a previous file.

Thanks

**Comment by maxnet** [comment]
continue in #193

**Comment by jp438** [comment]
I just wanted to point out that I am having the same problem with the same dongle, so this problem still exists. This dongle works fine on Openelec and Retropie.

**Comment by Ikyrz** [comment]
hi
same problem same dongle, last update :'(
