### ISSUE TITLE
Wifi Issue with Kernal 4.1 On Berryboot

### ISSUE THREAD

**Issue by ghost** [maxnet/berryboot#193]
When I start Berryboot's setup, I choose Wifi and then it doesn't find any networks. I also found that there is no light on my dongle. It works on Raspbian. It uses a Realtek RTL8188CUS driver!

Any Help Will Be Greatly Appreciated!!!

**Comment by lbalogh** [comment]
Hi,

I started a similar thread earlier this day (https://github.com/maxnet/berryboot/issues/192), I think there's an issue with modules when "wifi" is selected. I'll let maxnet respond ;)

**Comment by ghost** [comment]
You said it worked in the previous versions of Berryboot, do you think I could possibly try installing a previous version? @Ibalogh

**Comment by lbalogh** [comment]
Well, you can try. You can download it here : http://sourceforge.net/projects/berryboot/files/

Then we'll have a confirmation that something is wrong with the latest build ;)

**Comment by ghost** [comment]
Yep I can confirm that berryboot-20150808-pi2-only.zip has an issue with Wifi Dongles' Drivers.
I used berryboot-20150401-pi2-only.zip just now and my wifi dongle can connect to my network! @lbalogh 
Hope it helps others! :-) 

So there is a problem in the latest build :(

**Comment by maxnet** [comment]
Does work for me, with the official Raspberry wifi dongle.
So problem might be limited to Realtek modules.

If after wifi fails, you press ctrl+alt+f2, login as root (no password), and type "dmesg", do you get any error message in the last couple lines?

**Comment by maxnet** [comment]
Seems Realtek on Raspberry was already a problem in 4.0 branch as well (we are using 4.1).
https://github.com/raspberrypi/linux/issues/1095

**Comment by lbalogh** [comment]
For whatever reason, when I do CTRL+ALT+F2 to switch to the second tty, I only get a blinking cursor (no prompt)...

**Comment by maxnet** [comment]
> For whatever reason, when I do CTRL+ALT+F2 to switch to the second tty, I only get a blinking cursor (no prompt)...

Then you are not doing a fresh Berryboot installation.
Console is only automatically activated during installation.

Again, it only makes sense to check during installation after wifi fails, on the screen you normally see the wifi access points. That's the point where an attempt is made to load wifi drivers.
They are not loaded automatically on startup, if there is no wifi config.

**Comment by lbalogh** [comment]
I understand. Unfortunatelly I have only one sd card and I already have reinstalled the OS's (I did it manually by following you guide : http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions).

I'll let you know if I have something new. Note that my wifi is working correctly in Rasplex 0.7 (kernel  4.0.7 according to the changelog) and in Raspbian with kernel 4.1.

**Comment by ghost** [comment]
Yep mine works in raspbian with the new 4.1 kernel.

But I'm just gonna stay with previous version of BerryBoot for now and wait for a patch to come out for kernal 4.1.

**Comment by ghost** [comment]
Does the Previous version of berryboot use Kernal 4.0

**Comment by maxnet** [comment]
> Does the Previous version of berryboot use Kernal 4.0

No. Previous version used the 3.18 branch.

**Comment by ghost** [comment]
OK so maybe an issue with the 4's

**Comment by elektrotiko** [comment]
Hi guys. I can confirm the wifi no connection issue also with 300Mbps Wireless N USB Adapter
TL-WN821N. Previous version of Berryboot (from may, 2015), however, works excellent.
No Wifi connection at all with the most recent version of berryboot.

**Comment by ghost** [comment]
Yeah, definitely kernel issue gonna recommend staying with the old version or using an Ethernet cable

**Comment by Fireprufe15** [comment]
Has anyone found a solution to this particular problem? Some of the OSs I want to run on BerryBoot work perfectly in 20150808, but not so much in the previous version.  But then my WiFi dongle doesn't work in 20150808 and that's my only networking option at the moment.  I seem to be pretty much stuck fumbling around with multiple SD cards until this is fixed.

**Comment by maxnet** [comment]
Can you try if the following version works better with your wifi?

http://downloads.sourceforge.net/project/berryboot/berryboot-20150916-pi2-only.zip

**Comment by maxnet** [comment]
Closing as no reply from submitter

**Comment by jayp76** [comment]
I have a 8192 wifi dongle, that is working with an old build with kernel 3.18.
When updating (overwriting files) the wifi module will not be loaded.
With a fresh install it is working. Gotta figure out how to transfer my os'ses.

**Comment by maxnet** [comment]
> When updating (overwriting files) the wifi module will not be loaded.

Overwriting files on the FAT partition is not the right way to update, as that will not extract shared.tgz to the shared folder on the ext4 partition.

Easiest way to update is pressing "add OS", and accepting the update there.

**Comment by jayp76** [comment]
I tried also updating over the gui, with the same problem not loading the wifi module.

**Comment by maxnet** [comment]
> I tried also updating over the gui, with the same problem not loading the wifi module.

Before or after you manually updated files?
If it's after it is indeed too late. Update will not see the shared.tgz as new anymore.
Will need to manually extract shared.tgz to the /shared folder on ext4 then.

**Comment by jayp76** [comment]
sorry. it did't explain it in detail. it was not working some months a go updating over gui.
i tried now with my working image and the latest update over gui and it is working.
i took some time to connect to the wifi. i checked over the terminal, the wifi module was loaded.
all fine with latest update. thanks for your tips maxnet.
