### ISSUE TITLE
Berryboot + openelec 5.0.8 problem

### ISSUE THREAD

**Issue by Haris1977** [maxnet/berryboot#199]
I can replicate it all of the times, whatever skin i use:

When i play a movie from my nas (or local file) and - lets say - i stop it 20 minutes after, when i re-play the movie the window screen appears: resume from 20 or play from the beginning. When i hit resume, the movie starts and immediately pauses (as if i pressed pause). I thing this is a bug..

**Comment by maxnet** [comment]
Closing this as not Berryboot specific.
Can install a newer OpenELEC version through "add OS"
