### ISSUE TITLE
password in Fedora

### ISSUE THREAD

**Issue by cproad** [maxnet/berryboot#20]
I downloaded the img for Fedora_18_ARMv7,and installed it in my cubieboard.
what is password for user root?
tanks

**Comment by anauta** [comment]
I think it's "fedora".

Ref: http://fedoraproject.org/wiki/Architectures/ARM/Fedora_18_Alpha/Trimslice

cproad notifications@github.com escribió:

> I downloaded the img for Fedora_18_ARMv7,and installed it in my
> cubieboard.
> what is password for user root?
> tanks
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maxnet/berryboot/issues/20

## 

Desde un teléfono.

**Comment by maxnet** [comment]
Root password should indeed be "fedora"
During first run you also get presented with a screen to create a normal user.
If you ticked the box there that the user should be part of the admin group, you should also be able to do "sudo bash" to gain root.

**Comment by cproad** [comment]
thanks a lot!
