### ISSUE TITLE
GPIO button support

### ISSUE THREAD

**Issue by Vitorbnc** [maxnet/berryboot#203]
Is it possible to add support for OS selection using a physical GPIO button?

**Comment by maxnet** [comment]
Currently no plans for that.
The average end-user does not have any extra hardware on his Pi.

**Comment by Vitorbnc** [comment]
Could you provide some info on how could I do that?

**Comment by maxnet** [comment]
We have code that reads the name of an image to boot from a file called runonce here: https://github.com/maxnet/berryboot/blob/c15db5c52dbfb2f9c47025462f659de087d414e3/BerrybootGUI2.0/bootmenudialog.cpp#L197

You could modify that code to check your gpio or other condition and boot a specific named image.

**Comment by Vitorbnc** [comment]
Thanks! But can I use some library, like WiringPi?

**Comment by maxnet** [comment]
Theoretically yes.
But most libraries are more work, than doing it in plain C++

**Comment by Vitorbnc** [comment]
I'll try doing that later and see if it works.
