### ISSUE TITLE
Cannot compile kernel, rpi-update, and update berryboot

### ISSUE THREAD

**Issue by magarto** [maxnet/berryboot#204]
Hi!

I'm trying to update kernel to be able to use selinux/apparmor and I have the following problems...

1) When compiling, I have errors with AUFS but I have read here that aufs is not continued any longer (but I can check that 4.1 was updated some days ago). How can we compile and copy a kernel for raspbian and berryboot? and how can we choose this new kernel in the next boot?

2) rpi-update update kernel and gpu but it does not work with berryboot... I guess that it is because berryboot needs also squashfs, aufs and other commitments.

3) When updating berryboot and rebooting, I have some errors on /lib/modules files... I guess that it is because I updated kernel using rpi-update and modules are not compatible.
How can I update berryboot (and kernel also) without having to reinstall the OS?

Thanks in advance

**Comment by maxnet** [comment]
> 1) When compiling, I have errors with AUFS but I have read here that aufs is not continued any longer (but I >can check that 4.1 was updated some days ago). How can we compile and copy a kernel for raspbian and >berryboot? 

That some folks like overlayfs better, does not mean aufs is dead.
Just make sure you select an AUFS branch matching your kernel version.

https://github.com/maxnet/berryboot/blob/berryboot2015/configs/device_pi2#L9

> and how can we choose this new kernel in the next boot?

Just overwrite the old one.

> 3) When updating berryboot and rebooting, I have some errors on /lib/modules files... 

If you updated the kernel manually, put your modules in /shared/lib/modules on the ext4 partition.

> I guess that it is because I updated kernel using rpi-update and modules are not compatible.

Think you updated the kernel manually instead.
rpi-update will not overwrite our kernel, because we gave it a different file name to prevent people bricking their system.

**Comment by magarto** [comment]
Thanks for this great and quick answer.

Would it be possible to give us a "howto" for compiling raspbian kernel for berryboot? Thanks in advance!!!

**Comment by maxnet** [comment]
> Would it be possible to give us a "howto" for compiling raspbian kernel for berryboot?

When you use Berryboot all Linux distributions run under the same kernel.
There is no such thing as a "Raspbian kernel"

**Comment by magarto** [comment]
Ok, so a tutorial for compiling a kernel the way you did for the last 4.1 update?

**Comment by maxnet** [comment]
Build Berryboot using instructions on front page, and you get a kernel as free bonus.
That was not the way you were trying to compile, at step 1 above?

**Comment by magarto** [comment]
xD

Thanks, found! But after making a "make menuconfig" it shows a few options of the ones I can find in a linux kernel compilation from the official git. For example. I cannot find any option to implement selinux or apparmor.

One more question, if in a future we want to do the same but using the last Linux kernel? Is it "easy" to implement?

Thanks for all, mate

**Comment by maxnet** [comment]
Create a file in the `configs` folder with your custom kernel options:

```
CONFIG_MY_KERNEL_OPTION=y
```

Add that file to the kernel configuration fragment list `BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES`  in the device file: https://github.com/maxnet/berryboot/blob/berryboot2015/configs/device_pi2

**Comment by magarto** [comment]
Thanks!!!!!!!!!!!!!!!!!!!
