### ISSUE TITLE
HDMI CEC not working on Philips TV and how to Update OS?

### ISSUE THREAD

**Issue by Vitorbnc** [maxnet/berryboot#205]
Good evening,
I've enabled cec on my TV and it works fine with OpenELEC, but when I press any button on BerryBoot, it doesn't do anything. Could you fix that please?
I also have another question: how to install the latest version of any OS? Will I lose all my changes?

**Comment by sal666** [comment]
I'm afraid that CEC is not working properly:
https://github.com/maxnet/berryboot/issues/97

**Comment by maxnet** [comment]
How well CEC works differs by TV model.
Does work on my Samsung TV, but I know there are issues with others.
Closing this as there is already another issue for it.

> also have another question: how to install the latest version of any OS?  Will I lose all my changes?

How to update an existing installation differs by OS.
E.g. for Debian/Ubuntu run:

```
sudo apt-get update
sudo apt-get dist-upgrade
```
