### ISSUE TITLE
Berryboot wifi setup

### ISSUE THREAD

**Issue by ColtSta** [maxnet/berryboot#206]
I am attempting to set up berryboot with a wireless connection. The network shows on the list of possible networks, however, when I put in the password it gives me the error, "unable to connect or obtain IP address." I have tried logging in as root and manually trying to connect to a network but after 3 tries is says "lease, failing."  Any help or suggestions would be appreciated!

**Comment by maxnet** [comment]
Try a different wifi dongle if you have one.
Not all models work that well on Linux in practice.
