### ISSUE TITLE
RetroPie on Berryboot

### ISSUE THREAD

**Issue by joolswills** [maxnet/berryboot#208]
Hi,

Sorry if this is already detailed elsewhere, but I am interested in getting RetroPie onto the list of network installable Berryboot images. I see there is an old 2.3 available, but with the upcoming RetroPie 3.1 I will release some Berryboot images too. Do you maintain this list - and also do you host the files yourself or reference them wherever they may be hosted.

Thanks.

**Comment by maxnet** [comment]
Yes, do maintain the list.

If you have a direct download URL and sha1 for me, I can add it.
Can also mirror the image on sourceforge if you have a traffic limit.

**Comment by joolswills** [comment]
A mirror would be great for now - sourceforge is fine when they are not hacked and when it's up - im hoping they will be more reliable in future. mirroring would be good for now as our bandwidth is somewhat saturated!

but for now here's some urls

http://downloads.petrockblock.com/images/retropie-v3.1-rpi1-berryboot.img256
sha1: e4579fe7591bf6a8095474d5298d1c8af8533ab8

http://downloads.petrockblock.com/images/retropie-v3.1-rpi2-berryboot.img256
sha1: e304c8fd139dd0a6349cba5bbcbb610ed4fd11c0

tagging @petrockblog and @herbfargus so they are in on this,

**Comment by joolswills** [comment]
@petrockblog

**Comment by joolswills** [comment]
Where are my manners! I also mean - thanks very much :D I think it will be great to give users an easy install route via Berryboot! :)

**Comment by maxnet** [comment]
Added sourceforge as primary download location, and will fallback to your site if it is down, or something went wrong downloading and sha1 mismatches.

Be aware that the download counter on the sf site only shows people downloading the file with a web browser through the main sf site, and does not count direct downloads through Berryboot. 
(So don't be disappointed if number seems low for your image)

**Comment by petrockblog** [comment]
Thanks!

**Comment by joolswills** [comment]
yeh - Cheers!
