### ISSUE TITLE
NAT problem in Linaro_Ubuntu_ALIP_2012.11.img

### ISSUE THREAD

**Issue by cproad** [maxnet/berryboot#21]
my cubieboard have a etho and a wlan0
I plan to set up NAT service in it.
this is my config for NIC:

root@linaro-alip:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 66:cf:91:51:86:9d  
          inet addr:192.168.100.1  Bcast:192.168.100.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:55 Base address:0xb000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:480 (480.0 B)  TX bytes:480 (480.0 B)

wlan0     Link encap:Ethernet  HWaddr 48:02:2a:67:38:dd  
          inet addr:192.168.0.20  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:181 errors:0 dropped:467 overruns:0 frame:0
          TX packets:109 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:32938 (32.9 KB)  TX bytes:16682 (16.6 KB)

and I also modified the /proc/sys/net/ipv4/ip_forward

when i set up the iptables,i got a error message
root@linaro-alip:~# iptables -P INPUT ACCEPT 
root@linaro-alip:~# iptables -P FORWARD ACCEPT 
root@linaro-alip:~# iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
iptables v1.4.12: can't initialize iptables table `nat': No chain/target/match by that name
Perhaps iptables or your kernel needs to be upgraded.

then I try to load the modules:
root@linaro-alip:~# modprobe ip_tables
root@linaro-alip:~# modprobe ip_conntrack
FATAL: Module ip_conntrack not found.
root@linaro-alip:~# modprobe iptable_filter
root@linaro-alip:~# modprobe ipt_state
FATAL: Module ipt_state not found.

so,I need to recompile the kernel with these modules

question is How to recompile the kernel?

**Comment by maxnet** [comment]
See rebuild-berryboot-a10.sh
Add "make menuconfig ARCH=arm" after make sun4i_aufs_defconfig if you want to set custom options.
