### ISSUE TITLE
"Fall back" if iSCSI is not reachable

### ISSUE THREAD

**Issue by Hanzzz** [maxnet/berryboot#211]
Hello everybody,
first of all: berryboot is great!! Thank you for maintaining the project!!
I am really not familiar with linux at all. But would it be possible to have some kind of fall back (or parallel installed to iSCSI) to images on SD or USB, in case iSCSI cannot be connect? I am using the pi mainly at home so the iSCSI is available. But if I take the pi with me anywhere else it will not start as it is waiting for the iSCSI. In this case it would be realiy nice to have a distro that is located on the SD card or USB.
Is there a way ro realize something like this?
Thank you very much for your help!

**Comment by maxnet** [comment]
No plans for that.
Recommend you use a second SD card for that.

Determining whether iSCSI/the network is really unreachable is problematic.
In corporate networks with Ethernet switches that have STP enabled, it can take 45 seconds until the Pi has network connectivity, so would have to wait at least that.
