### ISSUE TITLE
Will works anyday update from Internet OPenelec?

### ISSUE THREAD

**Issue by druidamix** [maxnet/berryboot#213]
Hi, 
Berryboot is a grate multiboot project. Better than noobs.

However, it doesn't know how to update openelec (doesn't know other distros) automatically.

I know, One can update openelec by replacing system by berryboot/images/*.img. It worked.
However is tedious and resets the system every time.

Isn't possible to adapt the code to do the thing??

Thanks.

PD. Noobs lets update. But doesn't support cec.....

**Comment by maxnet** [comment]
The Berryboot version for the Pi 2 does let you upgrade.

**Comment by druidamix** [comment]
I have pi 2, trying to update from openelec 5.08(default berryblue) to 5.9.95

To update openelec, there are two options:
One is over net, Not working.
The other, (I used several times) is putting a tar inside a update folder. After reboot Openelec automatically should update.

What I do, I put the tar in the update folder.
Choose openelec in berryboot menu, some lines are shown "like linux" (one load module fails). Openelec doesn't update.

In another issue, someone says

> > 1.clone your openelec within berryboot.
> > 
> > 2.boot into the cloned openelec.
> > 
> > 3.download the new openelec system file.
> > 
> > 4.replace the system.img in your original openelec.
> > Done, that's the basics and it takes 5 mins to do and you don't need to redo your settings.
> > Just try my guide, it's quite sime really.**

That works. But not practical.

Any way to debug, logs?

**Comment by druidamix** [comment]
What it occurs .

Berryblue uses squashfs (read only) per distro. Every time one select a distro, i mounts the image squashfs, kernel and essentials files. Personal files should be saved in a writable partition.
So, I added the system  of openelec in distros folders. It booted correctly, found update, updated  and reboot.
Seconds after boot.
You can see on the photo:
![Squashfs crash](http://s10.postimg.org/l0otxgyd5/20151015_175956_HDR.jpg)

Trying to update the update on Squash.
i Think I'll use two sd ti interchange.

**Comment by maxnet** [comment]
`/mnt` is where the ext4 data partition is mounted, and that one is NOT supposed to be read-only.
Try pressing ">>" "Repair file system" in the Berryboot menu editor.
May be corrupt beyond repair though. Always make sure you power off system before removing card.

**Comment by druidamix** [comment]
I'll try 
Thanks.
