### ISSUE TITLE
LUKS encryption via berryboot AFTER Installation in regular mode?

### ISSUE THREAD

**Issue by hellyberry** [maxnet/berryboot#221]
The help and Manual pages do not give details about that, how can LUKS encryption via berryboot be enabled AFTER installation in regular mode? Thus a berryboot-SD without encryption, including latest Raspbian and 4 other OS.

Is there some procedure via a ramdisk and cloning/converting a second (micro)SD Card via a cardreader?

This would make it even more universally useful, since MOST distributions still do not support "full encryption", except /boot, resp. initrd. This would be helpful for many users and their privacy, as the RasPi is easy to take with you, some can and will get lost or some times even stolen. Data-at-Rest is then properly secured and no data leakage is possible. So the loss is reduced to hardware costs.

**Comment by maxnet** [comment]
1) Backup the individual images to USB stick using the "backup" button
2) Reinstall Berryboot on your SD card, and enable encryption this time
3) Hold mouse over "Add OS" button -> "from USB" and add your images from USB stick again
4) Destroy USB stick with hammer (or other weapon of choice)

**Comment by hellyberry** [comment]
Thank you! This procedure works fine. For  wiping there are ''wipe" and "shred' Linux tools.
