### ISSUE TITLE
Adding own customer OS

### ISSUE THREAD

**Issue by horozlu** [maxnet/berryboot#222]
There is a quiet good help regarding adding customer OS with images that only have two partitions
(one fat, and the second one ext4 partition). The second one must be converted to a squashfs format first. What do I have to do, if there are more than two partitions? For example recalboxOS has a third partition.

**Comment by maxnet** [comment]
We do not support extra partitions.
Copy the files from the third partition over to the main partition, at the folder the third partition is normally mounted.
