### ISSUE TITLE
Piface Digitial 2 and spi_bcm2708 no such device - Unique to Berryboot

### ISSUE THREAD

**Issue by Senapsys** [maxnet/berryboot#223]
Hi there
I have a Raspberry Pi 2 running the Jessie release of the OS.  I have successfully installed and used the Piface Digital 2 IO controller with it without any problems.

When I tried using Berryboot, the Piface Digital 2 IO controller doesn't work.  All of the related software installs fine, but the issue that I am seeing is that when I try and enable SPI, I get an error message "ERROR: could not insert 'spi_bcm2708': No such device".
I have double checked the config.txt within the Berryboot config.txt file and it includes dtparam=spi=on.

Given that everything works fine when Berryboot is not installed, it suggests to me that Berryboot is the cause.  If anyone is able to provide some advice on how I might get this working it would be appreciated.
Thanks
Richard

**Comment by maxnet** [comment]
Can you paste your full config.txt?

In particular make sure the line you added is not under the `[pi1]` section, as in that case it will only be active when you are using a Pi 1....

**Comment by Senapsys** [comment]
Thanks for the super fast reply.
Your response answered the question.  The dtparam=spi=on was in fact below the [pi1] section.
Adding it to the [pi2] section resolved the issues that I was having.
