### ISSUE TITLE
Pi Zero

### ISSUE THREAD

**Issue by scargill** [maxnet/berryboot#227]
Anyone any joy with the Pi Zero? I've tried both the code for the original Pi and the Pi2 (out of desperation) - the first yields nothing - the second at least puts the green light on - I used the additions with a Wi-Pi hardwired to the board (no shorts) following the Berryboot instructions to get it running with VNC (as I don't have a video lead) and I cannot get any activity at all other than aforementioned green light.

**Comment by scargill** [comment]
Not too popular then. That's a shame...

**Comment by maxnet** [comment]
Should work if you update the firmware files.
Not sure if there is demand enough to release a new Berryboot version for it, given the zero does not have any network connectivity by default, and Berryboot does kinda need that.

**Comment by scargill** [comment]
I was assuming that with a certified WIFI card (WiPi) that Berryboot would pick up on this – the example given showed a file to be added with the WIFI details?  That’s what I did but I didn’t get as far as the start screen.

**Comment by scargill** [comment]
Given that the Zero has sold out absolutely everywhere – and that Berryboot is one of the few easy to use solutions that includes easy backup I would have thought Berryboot ideal for this. The Zero is an original Pi, not the Pi2 but with that Berryboot software you don’t even get the startup coloured background (you do with the Pi2 files – but no further).

Pete.

**Comment by maxnet** [comment]
Again, should work if you install the new firmware files.
As in, copy files from: https://github.com/raspberrypi/firmware/tree/master/boot to SD card.

> I was assuming that with a certified WIFI card (WiPi)

Certified by who?

**Comment by scargill** [comment]
Trying that now.. thanks

**Comment by scargill** [comment]
Further but..

First line – not syning VFS – unable to mount root FS on unknown block (0,0) – I tried 2 different branded SDs…

Here is the cmdline.txt

smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=10 vncinstall ipv4=192.168.0.24/255.255.255.0/192.168.0.1/wlan0

and here the wpa.supplicant.conf – both of which I added to your repository files on the SD, formatted with SDFormatter as normal.

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev

ap_scan=1

network={

```
ssid="hollyprivate"

psk="mypassword"
```

}

Any ideas?

**Comment by scargill** [comment]
For reference it didn’t work. Got a few lines in and stopped.  Grabbed NOOBS and that is working fine so it isn’t the Pi Zero.

**Comment by profundiscom** [comment]
Berryboot is a no go for me as well, would love to get it working. Peter, can you tell me what hardware you are using for WiFi or LAN as I am having trouble with getting NOOBS to see my network with what I'm using. I won't hijack this thread, I swear.. just wondering.

**Comment by scargill** [comment]
Well Profundiscom - I've put this on hold as I'm getting no-where with Pi Zero and BerryBoot. It works a treat on a normal Pi2.

**Comment by thejsa** [comment]
This needs to happen - just got a PiZero today and don't feel like wiping out my phone's microSD (while I try and find my other one)

**Comment by profundiscom** [comment]
I will likely give this a shot getting a working version in order shortly after the new year and once I solve the network issue, which should not take long. I will keep you posted. Note to maxnet, thanks for the awesome software! If I get there quickly according to your instructions, I'll make sure to fork it appropriately - seems like it should work. I would bet that regardless of the out of box connectivity, a great deal of Pi Zero people will be hankering for Berryboot running on their tiny Pi. I've been squashing OS'es and loving Berryboot for some time.

**Comment by scargill** [comment]
Oh Excellent. I’m just about to order a new cheap WIFI usb unit for it.

**Comment by maxnet** [comment]
> If I get there quickly according to your instructions, I'll make sure to fork it appropriately - seems like it 
> should work.

There shouldn't be any changes needed, so no need to fork.
Works fine on a zero for me with newer firmware + kernel, which you get automatically if you compile from source.
Just haven't had time to make a new release.

**Comment by scargill** [comment]
Are you planning a new release soon? I’ll order up a WIFI dongle (last one was useless) and give it a go – I really do think that Berryboot is the way to go…. Of course you only get one USB on the Zero so clearly, setting up the WIFI credentials in the initial files would be needed so you could then SCP into the unit from a PC….

**Comment by maxnet** [comment]
> Are you planning a new release soon?

Do not plan to make a new official release soon, as it is time consuming (especially testing if upgrading from previous versions works).

But if you want to play with a fresh installation: [berryboot-20151229-pi1.zip](http://5.9.48.238/dl/berryboot-20151229-pi1.zip)

Be aware that not all USB hubs work equally well with the Pi zero.
Have a cheap Chinese micro-USB hub that is good enough to connect a keyboard and mouse to, but inserting a wifi stick into it doesn't work.
Doesn't recognize it at all.

**Comment by profundiscom** [comment]
Thanks maxnet. Worked like a charm. You are also right about the hub. The cheapie is still giving me grief with my Inland USB to LAN. Will start again tomorrow with my WiPi. I appreciate your extra effort, and thanks again for the help.

**Comment by symbios24** [comment]
Hi,is the berryboot-20151229-pi1.zip working on Pi Zero?

**Comment by profundiscom** [comment]
It certainly is. Please be sure to use a Berryboot approved WiFi or LAN dongle with a suitable USB hub (see above) so you can take advantage of the multiple OS installs. Kudos go  to maxnet for the recompile.

**Comment by symbios24** [comment]
So far what operating systems are working on PiZero with berryboot?

**Comment by macmpi** [comment]
berryboot-20151229-pi1.zip is a good start. Wished it had Realtek r8152 driver like Raspbian, so that Chromecast Ethernet Adapter would work with it to get a lean setup.

**Comment by maxnet** [comment]
> berryboot-20151229-pi1.zip is a good start. Wished it had Realtek r8152 driver like Raspbian, so that 
> Chromecast Ethernet Adapter would work with it to get a lean setup.

If you type "dmesg" does it mention an error while loading firmware?
If so, which file does it need?

We should have the same drivers as Raspbian (and more), may not have the same firmware blobs in /lib/firmware though.

**Comment by macmpi** [comment]
Sorry, my bad, Realtek r8152 perfectly supported, so Chromecast Ethernet adapter works great !

Can't find a way to return to setup wizard to change some initial settings (and wish to avoid wiping everything and starting fresh).

Thanks so much for this amazing tool!

**Comment by scargill** [comment]
Question:  I've just completed a new script which works on the latest (late November 2015) Jessie from the Pi site.. I need that version as it has Node-Red built in...   If I use Berryboot and install Jessie from the options - is the version I will get the same as that version on the Pi site?

**Comment by scargill** [comment]
Oh, that 2015/09 version of Jessie really needs to go – all sorts of errors when running sudo-apt-get update and upgrade… how can we use the version from December on the Pi site?  That’s an .IMG file

??

Pete.

**Comment by scargill** [comment]
Can you help.  I’ve used the new Berryboot to make a JESSIE installation – and that works a treat… but the main work I’ve done, not easy to copy over- is on a standard (NEW) installation of Jessie on a 16GB microSD.

Is there any way (I’m not a Linux whiz) that I can convert that 16GB card so that the existing code works as is – but the whole thing is running under Berryboot.

The reason for this is obvious – I want to be able to back up the SD to a USB stick without this whole, slow WinDiskManager copy-the-whole-image thing every time.

What would I have to do in order to be able to pop up a new 16gb uSD with Berry boot on it and load my existing uSD in so that next time around I can use Berryboot for a backup to the USB stick?

Pete

**Comment by maxnet** [comment]
> But the main work I’ve done, not easy to copy over- is on a standard (NEW) installation of Jessie on a 16GB microSD.
> Is there any way (I’m not a Linux whiz) that I can convert that 16GB card so that the existing code works as is

http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

**Comment by scargill** [comment]
If I install kpartx and mksquashfx  (they are not on the Pi) can I do that on the Pi and save the result to a stick on the Pi???

(I don’t have a Linux PC) ??

Pete.

**Comment by maxnet** [comment]
> If I install kpartx and mksquashfx  (they are not on the Pi) can I do that on the Pi and save the result to a stick on the Pi???

If you have an USB SD card reader and connect that to the Pi, yes.
Will likely take several hours on a Pi to create a compressed image though.

**Comment by scargill** [comment]
Thank you – I am also downloading Ubuntu in case that fails.  I cannot believe given how easy the pi is to use, that someone hasn’t come up with a one-click backup/convert….   I’m doing this so I can use your easy backup/restore once I get it into Berryboot :)

Pete.

**Comment by macmpi** [comment]
For what is worth, I wrote a small script to convert images to BerryBoot squashFS images. Seems to work but not tested a lot yet. It basically issues the commands referred in here:
http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions
If you have a BerryBoot directory inside your working directory, it compares files from .img FAT partition and list the extra files which you may need to consider to fine-tune your installation (like fore musicbox).
Hope this helps.
Thanks for any feedback

[Pi-BerryBoot-Converter.sh.txt](https://github.com/maxnet/berryboot/files/83833/Pi-BerryBoot-Converter.sh.txt)
(remove .txt extention and chmod 777)

**Comment by scargill** [comment]
Arghh. Well I got the latest Ubuntu working after hours of it taking it’s time to update – loaded your script – loaded my file saved by win32diskmanager….. called everything.img – it created berryboot-everything.img – which I then put on a stick and… Berryboot got half way through loading it before deciding to give it a miss…. Error – no reason.

I give up – I need sleep.

Pete.

**Comment by macmpi** [comment]
Hi @maxnet 
Not sure berryboot-20151229-pi1.zip has the proper setting to let Pi0 run @1GHz (or is it a firmware issue?)
I also read your warnings about overclocking risks, so I'm not sure it is therefore safe to use the following for a Pi0:
arm_freq=1000
gpu_freq=300
core_freq=400
sdram_freq=450
over_voltage=6 
borrowed from here http://openelec.tv/forum/124-raspberry-pi/79023-raspberry-pi-zero?start=15

Any recommendation?
Once set in BerryBoot, will those settings apply to any squashFS image in use, or should parameters be set there too?

Thanks!

**Comment by maxnet** [comment]
Firmware should set the Pi zero to run at 1 ghz by default.

Do not recommend any type of overclocking over the default.
May work short-term, but never had that run stable when doing something CPU intensive for longer periods (like compiling something big overnight).

**Comment by macmpi** [comment]
Thanks for the note maxnet: really appreciated.
Is your zero running at 1GHz with berryboot-20151229-pi1.zip (your comment seemed to imply you had one to test)?

OpenELEC 6.0 squashFS image from GitHub on BerryBoot reports 700MHz for me...
Thought if BerryBoot ran @ 1GHz, any "guest" image would follow same clockrate.
Or is that OpenELEC System info UI reporting inaccurate info?
Interested by your thoughts, and suggested method to figure-it out under BerryBoot console/SSH.

Best

**Comment by macmpi** [comment]
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
700000
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
700000
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
1000000

So I guess it is ok, it's indeed set @1GHz max by default.
OpenELEC reporting was probably accurate, but as it's not much busy in system info menu, then cpu gets to min...

**Comment by maxnet** [comment]
http://sourceforge.net/projects/berryboot/files/berryboot-20160209-pi0-pi1.zip/download supports Pi 0.

**Comment by symbios24** [comment]
macmpi can you update/fix your Pi-BerryBoot-Converter.sh script? its working on ubuntu 12.04 but not on ubuntu 16.04 and Debian jessie 8

Thanks
