### ISSUE TITLE
RTL8188 WifI module does not work

### ISSUE THREAD

**Issue by roses2uk** [maxnet/berryboot#234]
Very disappointed. Just downloaded 'berryboot-20150916-pi2-only' for my R-Pi2 which arrived just in time for Chrimbo.

According to the changelog for 2014-08-26,

"Pi: Enable RTL8188EU driver + IPv6 privacy extensions in kernel config"

there should be support for my Realtek 8188 WiFi dongle - but it is not recognised.

Is there a simple way to add the driver onto the SD card or to load it from the 'Edit' window? If so, where to download it?

I know the dongle works, because:
a) it is easily recognised on other distros on my R-Pi2
b) it works on my Windows laptop
c) it loads successfully on my Banana Pro with the Banana version of BB using exactly the same set up of cables and monitor.

Also, the 'Copy OS from USB stick' function doesn't work in the P-Pi2 version (but again, it does in the B-Pi one) - the stick is simply not recognised, irrespective of which USB socket on the Pi or my USB Hub I use.

So at the moment, I cannot use BB for my R-Pi2 at all.

Please do not give any instructions on how to set up using a wired internet as I do not have such a possibility to connect an RJ45 cable to anywhere. WiFi is all I got!!

Also, any advice using involving using code on a Linux computer to amend the files on the SD card would also be pointless as I don't have such a machine either.

Please BerryBoot developers, why doesn't this work properly Out Of The Box??

**Comment by maxnet** [comment]
What does dmesg say?

**Comment by roses2uk** [comment]
Thanks for quick response.

Wasn't sure at first how to access a terminal in BB, but figured it out eventually.

dmesg gives screens and screens of stuff, but interestingly the last line says:

eth0: linkup, 100 Mbps, full duplex, lpa )xC5E1

and further up it says

usbcore: registered new interface driver r8188eu

but the blue LED of the dongle is not flashing.

I think I also saw a line saying USB Mass Storage Device detected, as well as the manufacturer and name of the USB stick.

So is there possibly a hardware fault with my R-Pi2? If so, why does not it manifest itself in other distros?

(Still working out how to ouput dmesg to a text file onto the SD card so that I can upload it here.....)

**Comment by maxnet** [comment]
> usbcore: registered new interface driver r8188eu

Is that the same driver the distro that does work uses?
Check with lsmod

Also double check dmesg for firmware load errors.

**Comment by roses2uk** [comment]
> > Is that the same driver the distro that does work uses?

Not sure, I assume so - will have a look next time I run another distro.

> > Also double check dmesg for firmware load errors.

Outside my realm of expertise I'm afraid. Sorry to be so dim.

Is it worth downloading a previous version of BB to see if that works OOB? Not really sure if I want to be doing so much technical stuff to sort this out - I just want software that is immediately functional. A bit childish, I know. Soz

**Comment by roses2uk** [comment]
Any chance of a reply from someone within the BB development team please??

**Comment by maxnet** [comment]
My crystal ball does not know why your wifi stick -which I do not have- does not work.

If you expect things to work out-of-the-box you are better of with using the official wifi stick: https://www.raspberrypi.org/products/usb-wifi-dongle/ combined with the official power supply (it consumes a lot)

**Comment by roses2uk** [comment]
Thanks for your advice, but I have no wish to pay 4 times over the odds for an "official WiFi" dongle.

My point is that if the BB changelog says RTL8188 is supported, then it should work OOB (which it does with the Banana Pi version).

Appreciate your input, but I'll wait for someone from the BB team to give me some official feedback.

**Comment by maxnet** [comment]
Hardware support is provided by the Linux kernel.
It did work with the Linux kernel version we were using in 2014, but -judging by your post- apparently not with newer kernel versions.

Allwinner (Banana Pi) uses an older Linux kernel version at the moment. So don't be surprised if it stops working once they catch up.

> Appreciate your input, but I'll wait for someone from the BB team to give me some official feedback.

I am afraid you cannot get a more official reply :-)
Noticed the "owner" label next to my posts?

**Comment by roses2uk** [comment]
My apologies - I did not see the owner label. (Does that mean that you are the owner of the message board, or do you in fact also work for BB?)

But I thought the whole point of Linux was that every successive new kernel ADDED functionality, not removed it. So if I see in the changelog from only a year ago that a particular device is supported, I think it would be fair to assume that that is still the case - or am I badly missing the point here?? It's not as if the 8188 is a rarity - from what I can see it's fairly ubiquitous and widely available.

So if a future version of BB for Banana Pi also removes support for my dongle, I will be very dischuffed.

I'll therefore repeat my previous questions: where can I download a previous version of BB for R-Pi2 (i.e. from around 2014-08-26) that still has the kernel I need? If not, how can I add the driver required from the Edit menu?

**Comment by maxnet** [comment]
You can try some older versions at: http://sourceforge.net/projects/berryboot/files/?source=navbar
Be aware that the Pi 2 was not supported in the 2014 versions though.

**Comment by roses2uk** [comment]
And adding a driver after BB has loaded.........?

**Comment by maxnet** [comment]
Driver = kernel module. They normally come with the kernel. 
But -as said before- check on a distribution where your wifi stick does work properly with lsmod, to see if it is using the same kernel supplied module (r8188eu) or something else.
And again also check dmesg for error messages about firmware, as it is quite possible we do not ship the specific firmware your device wants.

**Comment by roses2uk** [comment]
> Driver = kernel module. They normally come with the kernel.

But when first booting BB, it asks the user to select wired or WiFi, and if the latter it then says 'Loading drivers'. So it must be getting those from somewhere, as the kernel has already loaded, surely?

So why can it not be possible to simply point that part of the program set up to another driver file on the SD card? Again, I thought the whole point of Linux is to give the user total freedom and control and be as transparent as possible.

> it is quite possible we do not ship the specific firmware your device wants.
> Well, I maintain my position that if in a previous changelog it says specifically a certain device is supported, why is it not expressly mentioned in a later changelog that this driver is no longer included in the kernel? Doing that would be very helpful to everyone concerned.

And regarding my R-Pi2, without the USB stick working either, I just cannot use BB at all. I will certainly try some older versions for it, but as I do not have the experience or knowledge to sift through dmesg for error messages, I'm disinclined to spend any more time messing about with it when it is clearly a development fault which hasn't been fully tested and checked with the current crop of Pi 2's.

Furthermore, I have just purchased a SATA drive and a special SATA data & power cable for my Banana Pro with the specific intention of using BB to set up multiple operating systems on it. It will be extremely disappointing if in the future the kernel changes so that my 8188 dongle doesn't work anymore - and it will make all that new hardware redundant & totally unusable.

**Comment by maxnet** [comment]
> But when first booting BB, it asks the user to select wired or WiFi, and if the latter it then says 'Loading 
> drivers'. So it must be getting those from somewhere, as the kernel has already loaded, surely?

The kernel modules are in separate files in the archive shared.tgz
While it is theoretically possible to add your own kernel modules there, that is not for the faint of heart.
If it is just a firmware file you are missing you do could add it there manually.

> And regarding my R-Pi2, without the USB stick working either, I just cannot use BB at all. I will certainly try some older versions for it, but as I do not have the experience or knowledge to sift through dmesg for error  messages

How many lines with the word "firmware" in it do you have in your dmesg output?
Surely not that many that you cannot just type them over in a message here...

**Comment by roses2uk** [comment]
> http://sourceforge.net/projects/berryboot/files/?source=navbar

There appears to be a bug on this web page as I am only able to download the 20150916 version but not any of the other 4 RPi2 versions. In each case it goes to the 'download beginning now' page but nothing actually happens. Clicking on 'direct link' or 'another  mirror' has no effect.

> How many lines with the word "firmware" in it do you have in your dmesg output?

OK, I will try to figure out to output dmesg to a text file and upload it here........but not today. For now, i've had enough of BB.

**Comment by roses2uk** [comment]
> There appears to be a bug on this web page

Correction: downloads of the RPi2 versions are now possible.

Have now tried them all and none of them give WiFi access with the RTL8188 or recognise a well-known brand of USB stick. (The first two versions crashed and caused a screen freeze during setup.)

I regretfully conclude the development and beta testing of this product with the Raspberry Pi 2 was insufficient and that this software is not fit for its intended purpose.

Yes, I know it's free, but I am not a Linux expert and don't really want to start involved in what it says in dmesg outputs. All I want is for it to do what it says on the tin.

**Comment by maxnet** [comment]
> Have now tried them all and none of them give WiFi access with the RTL8188 or recognise a well-known brand of USB stick. (The first two versions crashed and caused a screen freeze during setup.)

You don't have a colourful rainbow icon to the top-right corner of the screen when that happens, right?

**Comment by roses2uk** [comment]
Yes I do as a matter of fact. What does that mean?

**Comment by roses2uk** [comment]
While checking about the rainbow icon thing, I noticed something else.

When booting from a fresh install of 20150916 with the USB stick inserted beforehand, after loading the drivers, the dialogue box gives me the option of formatting either the SD card or the stick. So at this point it can recognise the stick.

And yet if I try to 'Add OS >> Copy OS from USB Stick', it doesn't see it at all This is completely nonsensical as far as I am concerned

**Comment by maxnet** [comment]
> Yes I do as a matter of fact. What does that mean?

That's a low-voltage warning, and means either your power supply or your micro-usb power cable is not up for the job.
Make sure you have at least a 2 amp supply if you want to connect any USB hardware beyond just keyboard/mouse.

**Comment by roses2uk** [comment]
That explains why I've seen it momentarily while booting up other distros (direct image, without BB) but I didn't really put any significance into it - I just thought it was part of the splash screen, or a graphics check or testing the display adapter!!! (Why do the programmers/designers use such a cryptic on-screen icon, instead of just having a simple text message which says 'Warning: low voltage'. That's crazy IMHO.)

I saw it also - bizarrely - during other operations, such as closing a window (I think it was the GUI for raspi-config), while I was running Raspbian Jessie - but not during update/upgrade operations in Terminal, which I would have thought are CPU-intensive and therefore also power hungry.

However, after checking my adapter, it is definitely rated at 5V/2A, although I don't have a multimeter to check any amp readings while it is connected to the RPi. No dosh to even consider buying another one as I'm on a very tight budget - hence eschewing official Raspberry WiFi dongles.

It's the same adapter I use for my BPi Pro while running both Linux and Android, the latter needing a LOT of juice, especially on first boot, and I usually add a second power source via the OTG socket as well in that particular scenario.

And of course, if I run Jessie on the RPi with the power cable plugged into the USB socket of my laptop instead of the adapter, I get the rainbow icon almost constantly....which is to be expected.

But low-voltage while trying to run BB on the RPi would have no bearing on whether the USB stick and Wi-Fi module are recognised and activated, would it??

So is there list somewhere of which dongles (apart from the official one) ARE supported by BerryBoot - maybe I can get one off eBay if they're only a couple of quid.

**Comment by maxnet** [comment]
And to make it even more confusing, it's both splash and a warning icon.

![debug-screen](https://cloud.githubusercontent.com/assets/1123701/12072076/62a22afa-b0cf-11e5-81ba-b857b09c567b.jpg)

If it is full screen, it is splash during boot

![raspi_undervoltage](https://cloud.githubusercontent.com/assets/1123701/12072071/2decb6fe-b0cf-11e5-825b-2882fe15594d.jpg)

Small icon as under voltage

Do not have a list of working wifi sticks.
Wifi support was only added because some Allwinner tablets lack an Ethernet connection.
Would always recommend a wired connection for downloading large files.

**Comment by roses2uk** [comment]
Yeah, thanks for the screenshots, but I did in fact understand the difference between the big splash screen and the small icon. It was just unclear that the latter was giving an important message (which would be better served in words really.)

Seems to me that the BB developers are (either deliberately or unwittingly) alienating a huge swathe of the RPi population by 1) assuming we all have a wired connection and 2) believing we all have pots of money to waste on overpriced official WiFi dongles and 3) expecting we all have the technical know-how and expertise to analyse and decipher system messages like dmesg and to be able to fix things on our own as a result of that understanding. None of these are realistic.

Yes, I know you can't please all the people all of the time, but BerryBoot should and has to work Out-of-the-Box for the majority of users, including noobs.

OK, you've tried your best maxnet, but I'm afraid this message board has no further use for me and I will be suspending or deleting my account in the very near future.

I thought the idea of it was to report bugs and issues. Well, I've done that, but it appears no-one is interested in adding the features and capabilities I and probably many others seek to make this software usable and useful. (It's also very worrying that no other person has chimed in on this thread with either support for my ideas or disagreeing with me.)

From time to time, I will of course keep checking the Source Forge website for a newer version that fulfills my needs and is compatible with my (fairly common, it has to be said) hardware....

...but I won't hold my breath.

**Comment by maxnet** [comment]
> Yeah, thanks for the screenshots, but I did in fact understand the difference between the big splash screen nd the small icon. It was just unclear that the latter was giving an important message (which would be better erved in words really.)

Agreed. But am not in a position to change that, given that it's handled by the Raspberry's firmware, and not BB.

> Seems to me that the BB developers are (either deliberately or unwittingly) alienating a huge swathe of the 
> RPi population by 1) assuming we all have a wired connection and 2) believing we all have pots of money to waste on overpriced official WiFi dongles and 3) expecting we all have the technical know-how and expertise to analyse and decipher system messages like dmesg and to be able to fix things on our own as a result of that understanding. None of these are realistic.

But at the same time you do somehow expect a lone developer to have pots of money to buy dozens of different wifi sticks to test?!

**Comment by macmpi** [comment]
Hi @maxnet,
I'm also trying to get some success with a R8188 based USB Dongle with the Berryboot packaged you kindly provided for RPiZero (Linux raspberrypi 4.1.15-aufs #1 Tue Dec 29 01:16:47 CET 2015 armv6l GNU/Linux).
I'm using Jessy-lite image I made out of [Raspbian Jessie Lite 2015-11-21](https://www.raspberrypi.org/downloads/raspbian/).

I happen to get wifi working, but sometimes I get the association errors in dmesg.

Would it be possible to get some updated drivers from [MrEngman sources](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371) compiled for the 4.1.15-aufs kernel Berryboot uses ([he does not provide Berryboot versions](https://93.93.130.214/forums/viewtopic.php?f=28&t=62371&start=1000))?
Alternatively can you give some detailed explanations on how to build & install them fo computer literate, but not expert ?
Many thanks in advance.

Best

**Comment by maxnet** [comment]
> Would it be possible to get some updated drivers from MrEngman sources

No
If those updated drivers are not acceptable for inclusion in upstream Linux, we do not want them either.
