### ISSUE TITLE
Backups issue

### ISSUE THREAD

**Issue by tjjohnsto** [maxnet/berryboot#235]
In trying to use the backup option in berry or to backup a Kali image. My usb drive I formatted at fat32 is not showing up as a backup option. The only backup location available is /. Am I missing something here. Also it will not backup to any location in /. It just goes back to menu when you try. I'm running the latest berryboot on RPi 2. The new backup drive is seen as  sda1 as berryboot tries to locate files on it at boot. So it is seeing it.

**Comment by maxnet** [comment]
Where did you install Berryboot to?
To another USB stick as opposed to SD card?

**Comment by tjjohnsto** [comment]
Berryboot is on the sd. The OS are in USB.

**Comment by maxnet** [comment]
> The new backup drive is seen as sda1 as berryboot tries to locate files on it at boot.

Are you sure Berryboot is doing that, and it is not just the kernel reading only the partition table, which might blink the led on your usb stick as well?
It should not go searching for its data files on USB drives, if they are on SD card.

Can you mount the partition on your USB drive from within Kali without problems?

**Comment by tjjohnsto** [comment]
The issue was I'm a moron. I don't look in the root/media directory for my actual flash drive. I expected it to show up on the left hand under computer and / in berry boot backups. It's backing up now. Though interestingly enough my existing USB where the OS are becomes sdb and the blank drive becomes sda in berryboot. And the OS are for sure on sub not SD card.  Thanks for the help.
