### ISSUE TITLE
issues compiling driver module

### ISSUE THREAD

**Issue by alec801** [maxnet/berryboot#239]
I need to enable the rtlwifi/rtl8192cu kernel module in my raspbian image. This is included in the Raspbian distribution but it isn't compiled with it.

To make it work i would edit the following files in the standard rapbian source:
- linux/drivers/net/wireless/Kconfig
- linux/drivers/net/wireless/Makefile

and then I would recompile.

I am not quite sure on how to do this with Berryboot, since all OS' share the same kernel. 
I can't find any files that detail the wireless drivers in the Berryboot source code.

If somebody could point me in the right direction, I would appreciate it. Thanks

**Comment by maxnet** [comment]
In theory you can add whatever kernel patches you want to the list at: https://github.com/maxnet/berryboot/blob/berryboot2015/configs/device_pi2#L5

However getting a wifi dongle that doesn't require you to do that -and keep doing that at every Berryboot upgrade- might be less work.
