### ISSUE TITLE
Instructions for migrating guest OS from berryboot

### ISSUE THREAD

**Issue by lepimate** [maxnet/berryboot#24]
Hi,
could you, please, provide instructions for migrating OS from  berryboot to separate SD card. I prepared a backup .img file for my OS (MODIFIED-Debian_Wheezy_Raspbian_2012.12.img192), what to do next?
Thanks.

**Comment by maxnet** [comment]
- Install Berryboot on new SD card.
- In Berryboot menu editor: hold down mouse button over "add OS" -> "from USB stick"

**Comment by lepimate** [comment]
Hi,
I would like to migrate to non-berryboot SD card, how is that possible?

**Comment by maxnet** [comment]
Not something we provide support on.
