### ISSUE TITLE
7" Touchscreen not displaying

### ISSUE THREAD

**Issue by mattyams** [maxnet/berryboot#240]
Trying to get berryboot to load an OS but there is no display with the 7 inch touchscreen.

**Comment by maxnet** [comment]
The official Raspberry Pi touch screen, or a touch screen from a different vendor?
The latter will not work without extra settings.

**Comment by mattyams** [comment]
It is the official screen.

**Comment by maxnet** [comment]
Should work with berryboot-20150916-pi2-only.zip
Are you using an older version or Pi 1?

**Comment by mattyams** [comment]
Nope. Using Pi2 with that version. I redownloaded just to be sure.  I tried it on my regular HDMI monitor and it works. But when trying it on the 7"...nothing.

**Comment by maxnet** [comment]
Tried the touch screen with any other Linux distribution (without Berryboot)?

**Comment by mattyams** [comment]
I just loaded Ubuntu MATE and a Rasbian image with the screen attached.  No issues.

**Comment by maxnet** [comment]
![img_20160114_225011](https://cloud.githubusercontent.com/assets/1123701/12338715/56fbb13e-bb11-11e5-829d-106636beb97c.jpg)

Cannot reproduce your issue.

**Comment by mattyams** [comment]
That doesn't make sense.

**Comment by ManuMod** [comment]
It was the same for me with the berryboot-20150916-pi2-only.zip. No display on my official 7" touch-screen.
I build a new one with the notice in this Git and now it's OK.
For me, the display is upside-down. I have to add "lcd_rotate=2" in the "config.txt".

**Comment by mattyams** [comment]
Can you elaborate more for me?

**Comment by ManuMod** [comment]
If you want to do it, you have to follow the notice at the end of the repositery, for build the "berryboot". It's relatively easy to do.

**Comment by mattyams** [comment]
Thanks!  This worked perfectly!  Now I have an issue after installing Android the "Home" "Recent Apps" and "Back" buttons are not visible. Any ideas?

**Comment by TheSupraLife** [comment]
@ManuMod I have the same problem, the link is broken, is it possible to re-upload the file ?

**Comment by ManuMod** [comment]
@TheSupraLife Why don't you try to compile it by yourself? It's very easy! You just have to follow the notice on the [main page](https://github.com/maxnet/berryboot#build-requirements). I think it's a good exercise to learn a piece of the Raspberry pi philosophy. In case you can't, I (re)uploaded it for you on [this link](http://we.tl/ien6Dxbdlk).

@maxnet Is it possible to update the version on Sourceforge? I don't know why, but it seems that our official 7" Touchscreens were not really the same as the first ones. For information, I received mine the 13/01/2016.

**Comment by maxnet** [comment]
Can you try if the following Berryboot version works better?

http://sourceforge.net/projects/berryboot/files/berryboot-20160209-pi2.zip/download

**Comment by ManuMod** [comment]
I confirm that your new version "berryboot-20160209-pi2.zip" works fine.

**Comment by maxnet** [comment]
Good to hear it is solved now.

**Comment by galien1** [comment]
i get stuck in a reboot loop that has a white screen after the rainbow one.
