### ISSUE TITLE
Adafruit 2.8" TFT Screen not showing the BerryBoot menu

### ISSUE THREAD

**Issue by ultimatef** [maxnet/berryboot#241]
Is there something that I am missing with using the 2.8" TFT screen with BerryBoot?  I have been digging around looking for an option to force the output to the TFT instead of the HDMI, but so far, unable to do so.  I noticed that you had the overlays and everything for the 2.8" TFT and had added the code for the official Raspberry PI Touch Screen, so I was wondering if there was something that I needed to do to get the BerryBoot to work with the TFT.

Thanks

**Comment by maxnet** [comment]
You'll probably need extra settings in config.txt to activate the overlay for your screen.
Asked the vendor?
