### ISSUE TITLE
Adding grsecurity kernel patch

### ISSUE THREAD

**Issue by magarto** [maxnet/berryboot#245]
Hi,

I tried to add one more patch to the kernel before compiling, to add grsecurity policy, editing configs/device_pi2
BR2_LINUX_KERNEL_PATCH="kernel-patches/uinitrd.patch ../configs/grsecurity-3.1-4.3.3-201601192226.patch"

It doesn't work for me. Patch is not applied after uinitrd.patch.
How can I add this patch to the berryboot build process?

Thanks!

**Comment by maxnet** [comment]
Should work.
Make sure you run: `./rebuild-kernel.sh device_pi2` including the device_pi2 part.
Otherwise it will use the last configuration without your changes.

**Comment by magarto** [comment]
Thanks! It works. The patch don't work, but it is related to grsecurity.
One additional question, is berryboot compatible with rpi-4.X.y? Aufs is compatible. Thanks

**Comment by magarto** [comment]
Thanks! It worked, but now I have an error patching the kernel with build-berryboot or rebuild-kernel. Patching kernel directly works perfectly but not with berryboot. Is there any way to let berryboot ignore errors when patching kernel instead of finishing make command?

The error is:

patching file virt/kvm/kvm_main.c
Patch failed!  Please fix grsecurity-3.1-4.3.4-201601231215.patch!
package/pkg-generic.mk:146: recipe for target '/home/pi/kernel/kernel/berryboot/
buildroot-2015.02/output/build/linux-rpi-4.3.y/.stamp_patched' failed
make: **\* [/home/pi/kernel/kernel/berryboot/buildroot-2015.02/output/build/linux
-rpi-4.3.y/.stamp_patched] Error 1

**Comment by magarto** [comment]
kvm_main.c is the last file to be patched with grsecurity.patch. Error dues to other warnings in the patch.

Also package/pkg-generic.mk 146 shows (146 is second one):

$(BUILD_DIR)/%/.stamp_patched:
        @$(call step_start,patch)

**Comment by magarto** [comment]
Up!

**Comment by maxnet** [comment]
Sorry, cannot help with individual patches.

**Comment by magarto** [comment]
Ok, thanks!

**Comment by magarto** [comment]
Ok, thanks. I need only to know if there is a way to ignore errors when patching kernel in berryboot, to let the berryboot script continue.

**Comment by maxnet** [comment]
Fix the errors in the patch instead?

**Comment by magarto** [comment]
I mean, ignore errors in patch like:
patching file virt/kvm/kvm_main.c
Patch failed! Please fix grsecurity-3.1-4.3.4-201601231215.patch!

Avoiding this error:
package/pkg-generic.mk:146: recipe for target '/home/pi/kernel/kernel/berryboot/
buildroot-2015.02/output/build/linux-rpi-4.3.y/.stamp_patched' failed
make: **\* [/home/pi/kernel/kernel/berryboot/buildroot-2015.02/output/build/linux
-rpi-4.3.y/.stamp_patched] Error 1

**Comment by maxnet** [comment]
> I mean, ignore errors in patch like:
> patching file virt/kvm/kvm_main.c
> Patch failed! Please fix grsecurity-3.1-4.3.4-201601231215.patch!

Remove the section that patches virt/kvm/kvm_main.c from the .patch with a normal text editor?

**Comment by magarto** [comment]
No, it is not a problem in kvm_main.c but some "hunk" warnings.
I also tried to make my linux kernel git fork previously patching kernel with grsecurity and modifying berrybot to clone it but I have also an error in .stamp_patched
https://github.com/magarto/linux-rpi-grsecurity

**Comment by maxnet** [comment]
> No, it is not a problem in kvm_main.c but some "hunk" warnings.

Should not fail on warnings.
It did not create a kvm_main.c.rej reject file?

**Comment by magarto** [comment]
I don't understand why but using the method I wrote before (my own patched git repository) it works now but compiling with the PC...
I close this issue. Thanks again for all. If you want me to compile it directly with berry-boot (using standard raspberry linux kernel git) to check .rej files, I can do it.
