### ISSUE TITLE
OpenElec 6.0.1

### ISSUE THREAD

**Issue by mavwolverine** [maxnet/berryboot#249]
Please add openelec 6.0.1 to the list. Thanks.

Also, is there any way to do it as a pull request. I could add it and create a pull request for you and you just simply merge it?

**Comment by maxnet** [comment]
Added

**Comment by psykro** [comment]
Hi,

Just installed it, and cannot boot openelec at all. It is stucked on splash screen right after kodi logo. Any idea ?

Regards,

**Comment by maxnet** [comment]
> Just installed it, and cannot boot openelec at all. It is stucked on splash screen right after kodi logo. Any idea ?

Might be related to what others are reporting here: https://github.com/maxnet/berryboot/issues/255
However haven't been able to reproduce it myself.
