### ISSUE TITLE
RasPlex support?

### ISSUE THREAD

**Issue by DiHydro** [maxnet/berryboot#25]
Can we get RasPlex included as a default OS in the next revision?

http://rasplex.com/

**Comment by maxnet** [comment]
Maybe in the future.
While I am open to adding extra distributions, the problem with RasPlex is that it currently has a new release every other day.

**Comment by rikels** [comment]
is it possible to manually do it? i tried to do it via the way i restored my RaspBian image as described here: http://linux-sunxi.org/Berryboot/Adding_your_own_Linux_distributions . but there's only Lost+found on the second partition and the first partition stores the boot related files (probably also the correct image).

i tried to see how it's done with "the default" OpenElec, but i don't know how the .img is made.
EDIT:
okay, i found out that i need to convert SYSTEM to an img with squashfs filesystem. let's try to manage that.
EDIT2:
I was lazy, so i just tried to renamed SYSTEM to RasPlex.img, and copied it to a usbstick, and added it to the menu. just to see what would happen. AND IT JUST WORKED!

maybe it's possible to let BerryBoot download the RasPlex image file, and extract SYSTEM from the first partition and move it to the image directory and add the img extension to the filename. that's all i did, just extract and "rename" it.

altough I'm not sure it's working correctly... :P

**Comment by maxnet** [comment]
It works because SYSTEM is already in the SquahsFS format Berryboot uses internally. :-)
Might add RasPlex to the standard list in a future release.

**Comment by rikels** [comment]
That's Great to hear! altough there could be some problems with the auto-updater, but I'm not sure about how that all works.

I'd love to help, but as you might have noticed, I'm not that good with all this, but I'm trying to learn!
(Wi-Fi is working! i had to connect to it first, D'OH!)

**Comment by rikels** [comment]
for people that are trying to do the same. you can also download the image from here: https://www.dropbox.com/sh/7aekawzbd4suh8f/VkyuJ1urmP

just put it on a USB-Stick and plug that in to your pi. and from there on you should know what to do =) .

**Comment by maxnet** [comment]
Closing for now

**Comment by 0xdevalias** [comment]
:+1: for rasplex

**Comment by jgstew** [comment]
I'd also like to see RasPlex added to berryboot.

**Comment by andreabisello** [comment]
someone has a tutorial to manually add RasPlex to berryboot?

**Comment by rikels** [comment]
Hi @abioneperhobby , maybe a bit late but... just open the .img you can download from https://github.com/RasPlex/RasPlex/releases (I used RasPlex-1.6.2.123-e23a7eef-RPi2.arm.img.gz) with an archive tool. Open the img file in the archive tool, open "0.fat" also in the archive tool and at last extract SYSTEM. If you want you can rename SYSTEM to something like Rasplex_Berry.img and load it in BerryBoot.

**Comment by andreabisello** [comment]
Thanks a lot !

Il 26 lug 2016 10:06 PM, "rikels" notifications@github.com ha scritto:
