### ISSUE TITLE
Error downloading file from Internet: file corrupt (sha1 does not match)

### ISSUE THREAD

**Issue by AlmightyCrumpet** [maxnet/berryboot#252]
Hey guys,

Whenever I try to add an OS it gives me the error "Error downloading file from Internet: file corrupt (sha1 does not match)". I am not sure what this could be. I thought it could be a problem with my connection but the connection is working fine. It is also a wired connection so it should work grand.

Any ideas?

Thanks,
Jonny

**Comment by maxnet** [comment]
Try again later.

https://twitter.com/sfnet_ops mentions "unplanned maintenance"
