### ISSUE TITLE
Latest berryboot for RPi 1

### ISSUE THREAD

**Issue by jonny789pm** [maxnet/berryboot#253]
The latest berryboot available for rpi1 is berryboot-20140814.zip which is about 1.5 yr old. 

Please upload the latest one for rpi1 with updated firmware and kernel.  
Some latest OS are not working with berryboot-20140814.zip like ArchLinux_2015.09.img

**Comment by maxnet** [comment]
The CPU architecture used by the Pi 1 is too old for some images offered. It does not understand ARMv7 instructions.

A newer Berryboot version is not going to solve that.
