### ISSUE TITLE
Module not compiled

### ISSUE THREAD

**Issue by magarto** [maxnet/berryboot#254]
Hi,

After compiling linux kernel, module bcm2708_wdog is not compiled:

$ sudo modprobe bcm2708_wdog
modprobe: FATAL: Module bcm2708_wdog not found.

So, is there anything to edit? Using your berryboot and standard raspbian installation it was compiled.
Thanks in advance.

**Comment by maxnet** [comment]
Don't compile kernel under Raspbian, but compile kernel as part of Berryboot.

**Comment by magarto** [comment]
No, I compiled it as a part of Berryboot

**Comment by maxnet** [comment]
Make sure you did a fresh Berryboot installation, so the contents of shared.tgz (which contains the kernel modules) was installed, and did not just copy the kernel file.

**Comment by magarto** [comment]
It's weird because /lib/modules/4.1.8v7-aufs/kernel/drivers/watchdog/bcm2708_wdog.ko is present but /lib/modules/4.3.3v7-aufs/kernel/drivers/watchdog/bcm2708_wdog.ko doesn't exist. So it must be a 4.3.3 related problem.
I have some pending question in other issue I created. I'm not sure if you could check it.

Thanks!

**Comment by maxnet** [comment]
>It's weird because /lib/modules/4.1.8v7-aufs/kernel/drivers/watchdog/bcm2708_wdog.ko is present

In shared.tgz?

**Comment by magarto** [comment]
Yes

**Comment by maxnet** [comment]
There is only a CONFIG_BCM2835_WDT=m in the 4.3 configuration.
Use that instead of 2708?

https://github.com/raspberrypi/linux/blob/rpi-4.3.y/arch/arm/configs/bcm2709_defconfig#L634

**Comment by magarto** [comment]
mmm, so it is a problem in the own raspberry 4.3 linux kernel branch... I'll add it as a module in berryboot patch. Thanks!
CONFIG_BCM2708_WDOG=m

**Comment by maxnet** [comment]
Doesn't the bcm2835_wdt module work as well?

**Comment by magarto** [comment]
It is a module for "poweroff" not for "reboot"
https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=100594
http://lists.infradead.org/pipermail/linux-rpi-kernel/2015-June/001886.html

**Comment by maxnet** [comment]
> It is a module for poweroff not for rebooting

Have you tested that?

**Comment by magarto** [comment]
I'm compiling it right now. Will test both "issues"

**Comment by magarto** [comment]
It doesn't compile it :(

**Comment by magarto** [comment]
If someone needs it, I share my berryboot boot image of Linux 4.3.3 with grsecurity and apparmor. cmdline.txt must be modified in order to enable apparmor at boot, adding the following at the end of the only file. Only one (RBAC of grsecurity or APPARMOR) should be enabled.
apparmor=1 security=apparmor

https://mega.nz/#!YQsXBSpK!wY2jFdJTVNerUCG589Z9C-YcpRA7QGJ7sA-Ron8G6uM

**Comment by magarto** [comment]
Fixed: https://github.com/raspberrypi/linux/issues/1285
