### ISSUE TITLE
RetroPie 3.5 image?

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#256]
Hi,
RetroPie 3.5 brings some exciting features over the last 3.1 that is available in BerryBoot repo.
Would be nice it that image can be added.
EDIT: Retropie Project provides is [here](http://blog.petrockblock.com/retropie/retropie-downloads/retropie-image-for-raspberry-pi-1/) for rpi0/1

Updated [Raspian lite image](https://www.raspberrypi.org/downloads/raspbian/) would be nice too.

Many thanks for the help!
Bes

**Comment by maxnet** [comment]
Sorry for the late reply.
Updated RetroPie to 3.6
