### ISSUE TITLE
BerryBoot 2.7: new options?

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#257]
Thanks for the update!
read in release note:
- add berryboot.ini options for secondary repository
  Would you give some more info on how to use this (and few other addtions of that release) ?

Thanks!

**Comment by maxnet** [comment]
Simply add url2=http://somewhere/ to berryboot.ini
See source for what the other options do.

**Comment by macmpi** [comment]
no plan to update the [homepage doc](http://www.berryterminal.com/doku.php/berryboot) with these new options?

**Comment by maxnet** [comment]
Nope.
Not being a native English speaker writing proper documentation takes me an excessive amount of time.
