### ISSUE TITLE
r8712u: Firmware request failed

### ISSUE THREAD

**Issue by lukasvermeer** [maxnet/berryboot#259]
Long story short: dmesg tells me BB doesn't like my wifi dongle.

```
r8712u: Firmware request failed
```

Based on other issues listed here, I gather this is problem with the kernel, not BB itself.

This might explain why the exact same hardware works as expected when I swap SD cards and boot my old OpenElec.

```
Bruce:~ # lsusb
Bus 001 Device 007: ID 0bc2:ab21 Seagate RSS LLC 
Bus 001 Device 005: ID 0bda:8172 Realtek Semiconductor Corp. RTL8191SU 802.11n WLAN Adapter
Bus 001 Device 006: ID 05ac:020c Apple, Inc. Extended Keyboard [Mitsumi]
Bus 001 Device 004: ID 05ac:1003 Apple, Inc. Hub in Pro Keyboard [Mitsumi, A1048]
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bruce:~ # lsmod
Module                  Size  Used by
fuse                   72559  3 
cfg80211              213071  0 
r8712u                150246  0 
bcm2708_rng              801  0 
Bruce:~ # uname -a
Linux Bruce 3.18.10 #1 SMP Tue Mar 31 14:50:33 CEST 2015 armv7l GNU/Linux
```

(Yes, the machine is called "Bruce". Long story. Don't ask.)

Is there any chance this might be fixed in the kernel and trickle down to BB, or is this permanent and should I go and buy a new dongle?

---

Possibly related issue on [http://raspberrypi.stackexchange.com/](http://raspberrypi.stackexchange.com/questions/39867/wifi-dongle-not-working-rtl8712u-firmware-issue).

**Comment by maxnet** [comment]
```
r8712u: Firmware request failed
```

Does it also show which firmware file name it is attempting to load?

**Comment by lukasvermeer** [comment]
Wow. That was a fast response! Kudos! :+1: 

```
r8712u: Loading firmware from "rtlwifi/rtl8712u.bin"
Direct firmware load for rtlwifi/rtl8712u.bin failed with error -2
```

**Comment by maxnet** [comment]
Do not currently ship that file. Might add it to a future release.

**Comment by lukasvermeer** [comment]
Could I compile from source myself? Where would I specify I need the file included?

**Comment by maxnet** [comment]
Add `BR2_PACKAGE_LINUX_FIRMWARE_RTL_87XX=y` to configs/berryboot_defconfig
Then compile as usual.

Or add the file to shared.tgz manually, under /lib/firmware

**Comment by lukasvermeer** [comment]
Awesome! Thanks so much. :+1: 

---

For reference, a grep of dmesg for r8712u on the OpenElec box (where the dongle works).

```
Bruce:~ # dmesg | grep r8712u
[    5.348509] r8712u: module is from the staging directory, the quality is unknown, you have been warned.
[    5.352556] r8712u: Staging version
[    5.352644] r8712u: register rtl8712_netdev_ops to netdev_ops
[    5.352669] usb 1-1.3: r8712u: USB_SPEED_HIGH with 4 endpoints
[    5.353664] usb 1-1.3: r8712u: Boot from EFUSE: Autoload OK
[    5.900240] usb 1-1.3: r8712u: CustomerID = 0x0000
[    5.900269] usb 1-1.3: r8712u: MAC Address from efuse = 00:0b:81:9a:ff:5d
[    5.900281] usb 1-1.3: r8712u: Loading firmware from "rtlwifi/rtl8712u.bin"
[    5.900504] usbcore: registered new interface driver r8712u
[    7.022995] r8712u 1-1.3:1.0 wlan0: 1 RCR=0x153f00e
[    7.023577] r8712u 1-1.3:1.0 wlan0: 2 RCR=0x553f00e
```

I'm guessing the "the quality is unknown, you have been warned" part could be a reason why it's not included in BB by default? (Just trying to understand what's the issue here.)

**Comment by maxnet** [comment]
The main reason we do not include the entire linux-firmware package by default is that it is 125 MB...
And a lot of those chipsets are old or only found on PCI cards not supported by the Pi.

**Comment by lukasvermeer** [comment]
Makes sense. 

I imagine going through the whole list to decide what to include is also not viable, so you just wait for people to report which ones they need, or suggest they compile their own? Reasonable strategy.

FWIW: I got this wifi dongle as part of a package deal together with the Pi. It was being advertised as "pi compatible". Just so you know this is not some dodgy old unit I dug up from a scrap yard. ;-) I was slightly dismayed about the unit when I first got it, as it is almost bigger than the Pi itself, which makes it look super awkward.

![Dongle + Pi](https://lh3.googleusercontent.com/bFZiWQqRQjGskcln1yXOhXtTS5sa2LchK1sY1Bf62rcPqr02Yuy3lfpmvWAA1HMReJeaRz8o4vN42A=w421-h316-no)

**Comment by lukasvermeer** [comment]
> Or add the file to shared.tgz manually, under /lib/firmware

I can confirm this works for me. Simply mount the BB SD from the old Pi install.

```
cd /path/to/sd
tar xzvf shared.tgz
rm shared.tgz
cp /path/to/rtlwifi/rtl8712u.bin /lib/firmware/rtlwifi/.
tar czvf shared.tgz lib
rm -rf lib
```

**Comment by lukasvermeer** [comment]
I also wanted to try the other approach, but that's still compiling while the problem is already solved, so I'll close the issue.

Thanks again for the support. Awesome experience. Keep up the good work! :+1:
