### ISSUE TITLE
chameleon v0.3

### ISSUE THREAD

**Issue by anyf33** [maxnet/berryboot#26]
I try many ways to transfer chameleon v0.3.img to cubieboard. 
http://chameleon.enging.com/chameleon.v03.img.bz2.torrent
But didnot start
the .img has three partitions. What about the third (roms fat32) partitions?
I have also another question Why chameleon v0.2 it is not at the os selection menu? http://sourceforge.net/projects/berryboot/files/os_images/Chameleon_v021.img192/download
Please help.

**Comment by maxnet** [comment]
> I have also another question Why chameleon v0.2 it is not at the os selection menu?

Legal reasons.
I am not sure what the copyright status of some files included with Chameleon is.

**Comment by anyf33** [comment]
ok , what about the conversion to berryboot img?

**Comment by maxnet** [comment]
Well, you mentioned it does not start, but can you be a bit more specific than that?
Blank screen? Big fat error message?

Might need to copy the files on the 3rd partition to /roms on the seconds partition. Other then that I think it should work.

**Comment by anyf33** [comment]
.sh error

2013/3/20 maxnet notifications@github.com

**Comment by anyf33** [comment]
well i am waiting for your new v0.31 to keep testing

2013/3/20 anyf33 anyf33@gmail.com

**Comment by anyf33** [comment]
i fix it. can i upload it to you. (i was thinking that i was writing to
charles) but doesnot matter

2013/3/20 anyf33 anyf33@gmail.com

**Comment by anyf33** [comment]
i try so many times to built chameleon 0.3 and 0.31 img to berryboot but
with no luck.
It is start shows the consoles and computers (you can select what you want)
but no one start!
I know about the roms folder (it is in another partition) but this is not a
problem
i change folder attributes with chmod and i can write to roms folder so i
write a rom for amstrad or another but it dont start after i select it.
Do you have any idea?
I tried in cubieboard but any image even rasbian works perfectly in cubie
so  i dont think that  i need a raspberry to work!
please help antonios from greece

2013/3/20 anyf33 anyf33@gmail.com

**Comment by JonasEnderlein** [comment]
I am failing to create a SquashFS image for berry boot :( It would be very helpful if someone could just upload a working image of chameleon 0.31 that works properly with berryboot...

**Comment by anyf33** [comment]
i have one but it works on menus but none emulator starts (in cubieboard)
but on raspberry may work properly. Do you want to upload it, to test it?
and where?

2013/4/13 JonasEnderlein notifications@github.com

**Comment by JonasEnderlein** [comment]
How did you create it? Can we chat? Skype or sth?

**Comment by anyf33** [comment]
Contact me at skype antonios.33
Óôéò 13 Áðñ 2013 10:15 ÌÌ, ï ÷ñÞóôçò "JonasEnderlein" <
notifications@github.com> Ýãñáøå:

**Comment by kitingChris** [comment]
Thanks for NOT sharing your knowledge! :( 
I have the same issue!

**Comment by anyf33** [comment]
i want to help. i sent you my skype id...

2013/10/25 chris1412 notifications@github.com

**Comment by kitingChris** [comment]
I dont search the internet for skype id's of persons that might be able to help. Please dokument your knowledge here so everyone else who has the same problem and seeks for a solution can find it.
