### ISSUE TITLE
Raspberry PI 3

### ISSUE THREAD

**Issue by smileybob** [maxnet/berryboot#263]
Replaced raspberry pi 2 with pi 3 with same setup, same SD card and USB attached.
Raspberry pi 3 turns on, displays a rainbow colour page and does not go any further.

I think berryboot requires updating to support the new hardware.

Please could this be done soonish? I love using berryboot and cant wait to get my pi 3 up and running.

Many Thanks in advance

Smileybob

**Comment by maxnet** [comment]
Just overwrite your existing files -EXCEPT cmdline.txt- with the newest Berryboot version and it should boot.
Only wifi does not work within Berryboot right now. Will fix that somewhere next week.

**Comment by smileybob** [comment]
I think I have the latest berry boot image.
It's auto updated when I've added an OS, unless there's a newer one than the auto updated one?

**Comment by maxnet** [comment]
Newest is not yet provided as auto-update.
Wanted to see if people run into issues with it first.

**Comment by smileybob** [comment]
Ok, I will try the latest one, is that the 9th Feb berryboot?

Thanks for getting back to me so quickly :)

**Comment by smileybob** [comment]
Ok, I've updated berryboot as you suggested and you were right, it now loads! :)
Now When I choose to load OpenELEC 6.03, a load of text now appears on the left of the screen. One of the messages states:
failed to start load kernel modules
Is this a problem and can I fix it or hide it?

many thanks

smileybob :)

**Comment by smileybob** [comment]
i've worked out what was wrong.
As I use berryboot with a USB pendrive to boot from, the shared lib folder was using the old lib files which didn't work with the newer berryboot.

I did the following to rectify this:
1. download berryboot, extract the files and then copy them accross to the SD card (keeping cmdline.txt (not replacing it)).
2. extract shared.tar.gz to the pc and then copy shared.tar to \IP_address_Of_Pi\berryboot\shared
3. rename lib folder to lib.bak
4. run putty to connect to the pi and locate yourself into the shared directory.
5. type -  tar xvf shared.tar  (this will extract the files into a new lib folder.
6. all done, reboot the pi :)
