### ISSUE TITLE
RPi3 Support?

### ISSUE THREAD

**Issue by RussKay** [maxnet/berryboot#267]
Does the current version 20160209 support/work on an RPi3?

**Comment by oscarmh** [comment]
works great, no prob

**Comment by benburch93** [comment]
I got it to boot, but I have getting "Failed to start load kernel modules" and later "Failed to mount Arbitrary Executable File Formats File System."

I suspect I need a new kernel image for the rpi3?

Is there a nightly build or some such that would have this?

Thanks!

**Comment by maxnet** [comment]
> I got it to boot, but I have getting "Failed to start load kernel modules" and later "Failed to mount Arbitrary Executable File Formats File System."

Using what distribution?

**Comment by kartur** [comment]
I tried the build from today and so far it seems to works fine on my RPi3. :)

**Comment by oscarmh** [comment]
Whhat about wifi ? what drivers does it use ? struggling on that :-(

**Comment by maxnet** [comment]
> What about wifi ? what drivers does it use ? struggling on that :-(

Uses the brcmfmac driver we already supported, as the older official Pi wifi USB stick uses the same.
You do need a recent firmware version that includes`bcm2710-rpi-3-b.dtb`, for it to be detected though.

**Comment by oscarmh** [comment]
MAx thanks a lot, must be fw, I will go throu it
