### ISSUE TITLE
Won't give a signal to TV

### ISSUE THREAD

**Issue by Mirukai** [maxnet/berryboot#268]
I just tried to connect my Raspberry Pi 2 Model B to my TV with a Berryboot-containing MicroSD card, and it came on for three seconds, still a blank screen, and then stopped giving a signal altogether for over thirty seconds, maybe a minute, I wasn't counting.

My TV is a Samsung Smart TV.

Thanks!

**Comment by maxnet** [comment]
Try another HDMI cable.
