### ISSUE TITLE
Time dependent boot? (cron like behavior)

### ISSUE THREAD

**Issue by jcjveraa** [maxnet/berryboot#27]
[Sorry, new here, no clue how to mark this as a 'question']

Hey there Floris,

I was wondering if it is possible (or if not, if you could make it possible :-) to have the default OS dependent on the current system time.

For example I'd like to be able to make a crontab-like file which specifies that between 1:00 AM and 7:00 AM my default boot should be raspberrian, between 8:00 and 10:00 AM OpenElec and at any other time to RaspBMC (just as an example).

I'd then couple this to auto-rebooting behaviors in my installed OS'es, which allows me to automate certain tasks on Raspberrian at night, while still having my system running and ready to go on a 'clean' RaspBMC while I'm personally using the device (the OpenElec added above just as an example). 

I'd be more than happy do do a code suggestion (which would take me some effort as I only speak some higher level languages), but I think/hope this might be quite trivial to implement for you yourself :) 

Cheers,
Jelle

PS It would be quite involved to integrate this in the GUI, but as this is a 'power user feature' I think adding this to the 'special berryboot kernel parameters' would be fine. I'd image this to be something like this, with a time-range specifier coupled to an ID string, to be a bit user friendly while still easy to parse.

BerryBootOSTimeDefaults=0100-0700-Raspberrian,0800-1000-OpenElec,RaspBMC

**Comment by maxnet** [comment]
Sorry, but this is not a common enough feature to include in the main Berryboot distribution.

If you need to add auto reboot functionality within the distributions anyway, you can change the default distribution there as well.
Just mount the data partition, and write the name of the new default to the default file.

**Comment by maxnet** [comment]
Also note that Berryboot does not know the current time.
The Raspberry does not have a hardware clock. Need to boot an os and ask an external server through ntp.
