### ISSUE TITLE
Berryboot with Rasp 2 & 3 support and Xbox 360 wireless remote not detected

### ISSUE THREAD

**Issue by Frucoboti** [maxnet/berryboot#272]
Hello,
Any issue with the detection of the Xbox 360 wireless remote attached to a Rasp 2, with Berryboot for Rasp 2 only. Retropie works fine. It ask for press button if any remote is configured.
Once the configuration wizard ends, continues to Emulastation with no problem. The pad is fully operational.
In order to prepare the SD to use with a new Rasp 3, I have updated the Berryboot files at SD with new ones published a few days ago, maintaining the config.txt and cmdline.txt files.
Retropie 3.5 ask for joystick configuration, and don't detect any activity when push any button from same pad that worked with prior version.
Updated to Retropie 3.6 to check if this was the issue with no luck. Continues without detect anything.
Restored to original files and Retropie 3.5 and 3.6 continues with any issues detecting the remote, and without asking for configuration anytime, because detect original configuration.

Any idea how to solve this?

Thanks

**Comment by maxnet** [comment]
> I have updated the Berryboot files at SD with new ones published a few days ago, maintaining the config.txt and cmdline.txt files.

Need to extract the contents of shared.tgz to /shared on the ext4 partition if you update the files manually.

Can do so from within Berryboot, by going to the menu editor, pressing ">>" and the console button, ctrl+alt+f2 and typing a line like this:

`
gzip -dc /boot/shared.tgz | tar x -C /mnt/shared
`

Press ctrl+alt+f1 to get back to Berryboot.

**Comment by Frucoboti** [comment]
How to type "|" character with a spanish keyboard?
Can I open a ssh session?

**Comment by maxnet** [comment]
Can also try doing it from any installed distribution, if you do have a working keyboard or SSH there.
Assuming you are using SD card as storage, something like this should work:

```
sudo bash
mkdir /tmp/m1 /tmp/m2
mount /dev/mmcblk0p1 /tmp/m1
mount /dev/mmcblk0p2 /tmp/m2
tar xzvf /tmp/m1/shared.tgz -C /tmp/m2/shared
reboot
```

**Comment by Frucoboti** [comment]
No luck:

root@retropie:/home/pi# tar xzvf /tmp/m1/boot/shared.tgz -C /tmp/m2/shared
tar (child): /tmp/m1/boot/shared.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

From a Retropie 3.6 ssh session

**Comment by maxnet** [comment]
Minus the /boot (typo of mine)

```
tar xzvf /tmp/m1/shared.tgz -C /tmp/m2/shared
```

**Comment by Frucoboti** [comment]
Worked! thanks my friend!
