### ISSUE TITLE
OpenElec images gpu ram split (160M minimum)

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#283]
Hi,

It seems Openelec would need [at least 160MB](http://forum.kodi.tv/showthread.php?tid=267806&pid=2303699#pid2303699) to run properly.
I set option to 512 in BerryBoot menu as there is not much granularity possible: it then set the file with img256 as expected.
You may want to adjust file names accordingly for OpenElec images in files repo.

BTW, have you looked at [LibreELEC](https://libreelec.tv/) fork of Openelec?
The image seems a bit complex to adapt to Berryboot: appreciate your thoughts on it.

**Comment by maxnet** [comment]
The stock version runs with 112 MB by default on the original first edition Pi 1.
What issues are you experiencing?

**Comment by macmpi** [comment]
Had some playback failures with some .avi files as described in the thread I referred (some files exited right after start, some crashed the player).
Suggestion came from @popcornmix and this alone solved the issues.

**Comment by maxnet** [comment]
The thread you referred to is about someone who was only using 64 MB GPU memory.
That is not the default Berryboot setting, which is 128 MB and therefore in between what OpenELEC uses by default for first generation Pi 1 (112 MB) and later generation 512 MB Pi 1 (160 MB).

We do not currently have an option to have a dynamic memory split based on Pi model.

**Comment by macmpi** [comment]
That person was me indeed :)
I was using OpenELEC_6.0.3.img128 image and the Kod log sent showed 64MB.
It seems the number in img.xxx is halved.

**Comment by maxnet** [comment]
64 MB does is what Raspbian (.img192) uses by default.
If you run Raspbian first, and then switch to OpenELEC, you do not see it doing an extra reboot (while it changes memory split in config.txt)?

**Comment by macmpi** [comment]
Not sure what you mean about extra reboot.
However I do not recall I was running Raspbian first or not. Actually I had the problem each time I used OpenELEC_6.0.3.img128. This issue disappeared when I named it OpenELEC_6.0.3.img256.
Currently I'm using self-made LibreELEC.img256 with no problem (rpi0).
