### ISSUE TITLE
Add Screenly Image

### ISSUE THREAD

**Issue by vpetersson** [maxnet/berryboot#289]
I have an image ready for [Screenly OSE](https://www.github.com/wireload/screenly-ose/). This is already present in the WD fork. Any chance we could add to the main version? If so, can you point me in the right direction?

**Comment by maxnet** [comment]
Added it to the 'appliances' tab

**Comment by vpetersson** [comment]
Awesome. Is this in the main branch as well? 

Also, I noticed that the mirror is a bit slow. Mind if I point it to our [own mirror](https://releases.screenlyapp.com/2016-04-20-Screenly_OSE_4GB_BerryBoot.img)?

**Comment by maxnet** [comment]
Would be interested to know which speeds (mbit displayed in Berryboot) you get from Screenly in the  'featured' tab, and which speed you get when you download it from the 'appliances' tab.
They currently point to different providers.

**Comment by vpetersson** [comment]
I can try to run some experiments later, but at this point, I cannot seem to install the new Screenly OSE image at all. It just timeouts. 

On a side-note. Yesterday I was able to install the old version of Screenly OSE, but only after it failed from the first mirror and then tried the second mirror.

Also, tried to install Jessie Lite. As you can see below, the speed isn't great :)

<img width="912" alt="screen shot 2016-05-05 at 10 55 35 pm" src="https://cloud.githubusercontent.com/assets/357664/15058996/9e74b098-1317-11e6-879f-99f852728834.png">

**Comment by maxnet** [comment]
That's a bit strange since Raspbian Lite is supposed to be only 256 MB.
Might be a local problem.

This is what I get when downloading that with a fast SD card:

![img_20160506_002501](https://cloud.githubusercontent.com/assets/1123701/15059295/fb0170a8-1321-11e6-87c9-7a2e322c7253.jpg)

And spinning storage:

![img_20160506_003844](https://cloud.githubusercontent.com/assets/1123701/15059595/e26ff148-1323-11e6-8c67-7e629ab067b6.jpg)

(Both with wired Ethernet connection)

**Comment by vpetersson** [comment]
Interesting. The particular setup did however use the [WD Labs SATA board](http://wdlabs.wd.com/products/sata-adapter-board/) and a USB ethernet adaptor. I did however get better performance (up to 10 mbit) for other images and it does appear to be somewhat inconsistent. As such, my best guess is that it's related to the upstream routing or similar. Are you using a CDN for the images?

**Comment by maxnet** [comment]
Suggest you verify speed with a normal Pi, to rule out problems with your USB ethernet adapter as well.

Images in featured tab are currently served by a commercial CDN provider
Images in other tabs by sourceforge.net
Fallback if a download fails by a server at Hetzner.de

If you are experiencing problems with all three, I doubt changing to your own mirror will help much.

**Comment by vpetersson** [comment]
> Suggest you verify speed with a normal Pi, to rule out problems with your USB ethernet adapter as well.

Agreed.

Thanks for the info. Also, great job on BerryBoot. It's a nice piece of software.

**Comment by vpetersson** [comment]
@maxnet Just an update -- i just tested this on a Raspberry Pi 3 (non WDLabs edition) and performance is _very_ difference. Getting ~50mbit from the office. As such, this is definitely a hardware specific issue.
