### ISSUE TITLE
blacklisting modules

### ISSUE THREAD

**Issue by alec801** [maxnet/berryboot#298]
I am using a raspberry pi 3 with berryboot and I want to disable the wifi modules.

I have tried adding a blacklist.conf file to /etc/modprobe.d/ with the lines 

> blacklist brcmfmac
> blacklist brcmutil

but that doesn't seem to work, these modules are stil loaded. 
I have also tried redirecting them  in that same file, so that they are loaded in correctly

> install brcmfmac /bin/false
> install brcmutil /bin/false

Neither of these options seem to work. Does berryboot have a different method that is used to disable modules?

**Comment by maxnet** [comment]
Do not currently support blacklisting modules.
You may have some luck killing wifi through device tree overlays.

https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L851

**Comment by AndreaBorgia-Abo** [comment]
@maxnet This is a bit of a killer issue for me since it won't handle my use-case of unattended reboots. Also, DTO affects all images and cannot be toggled, right? That is, once a device is gone from the tree it won't load, ever, correct?

**Comment by maxnet** [comment]
Sorry, but I do not understand your use case at all.

You do want wifi to be available sometimes, so it is not a legal/certification issue?
Then just rmmod the module in the OSes where you do not want it...

**Comment by AndreaBorgia-Abo** [comment]
@maxnet my use-case is not related to wifi but to blacklisting modules in general (as per bugtitle): all available documentation refers to using blacklist and it can be quite confusing to find it is not working in this specific case. Never mind me, I'll work around it :)

**Comment by maxnet** [comment]
Sorry, my crystal ball cannot guess the use-case.

**Comment by Romeo-Golf** [comment]
One use cases for blacklisting modules is to allow the RTL-SDR code to repurpose a USB TV tuner as a Software Defined Radio, which has applications such as collecting ADS-B data to track aircraft:

https://www.adsbreceiver.net/forums/topic/blacklist-apparently-ignored/

So although Berryboot appears to be a useful means of distributing software, this may be limited if functionality present in Rasperbian such as module blacklisting is not supported.

Is there a reason why this is not supported, or is it just work in progress?

**Comment by maxnet** [comment]
>One use cases for blacklisting modules is to allow the RTL-SDR code to repurpose a USB TV tuner 
>as a Software Defined Radio, which has applications such as collecting ADS-B data to track aircraft:

We will block DVB modules from being loaded automatically by Berryboot in the next version.

https://github.com/maxnet/berryboot/commit/09035b41d266a5e4e78ceae770398929f267d63c

**Comment by Romeo-Golf** [comment]
That is great news, many thanks :)

**Comment by maxnet** [comment]
berryboot-20170208 just released has the dvb-core blacklist.

**Comment by Romeo-Golf** [comment]
Awesome, thanks very much for the swift resolution to our use case.. is there any plans to extend this functionality to allow blacklisting of other modules as would typically be available in Raspbian?

**Comment by maxnet** [comment]
Not sure if there's much demand for that, given most modules can be easily removed again with ``rmmod`` afterwards.
Or can be blacklisted globally (not just in Berryboot) by putting ``modprobe.blacklist=name-of-module`` in cmdline.txt.
