### ISSUE TITLE
libssl-dev required? (and other deps)

### ISSUE THREAD

**Issue by flbuddymooreiv** [maxnet/berryboot#3]
While building, I got this error:

~/berryboot/buildroot-2012.05/output/host/usr/bin/arm-unknown-linux-uclibcgnueabi-g++ -c -pipe -Os -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../host/usr/mkspecs/qws/linux-arm-g++ -I. -I../../host/usr/arm-unknown-linux-uclibcgnueabi/sysroot/usr/include/QtCore -I../../host/usr/arm-unknown-linux-uclibcgnueabi/sysroot/usr/include/QtNetwork -I../../host/usr/arm-unknown-linux-uclibcgnueabi/sysroot/usr/include/QtGui -I../../host/usr/arm-unknown-linux-uclibcgnueabi/sysroot/usr/include -I../../staging/opt/vc/include -I../../staging/opt/vc/include/interface/vcos/pthreads -I/usr/include/openssl  -I. -I. -o adddialog.o adddialog.cpp
adddialog.cpp:54:27: fatal error: openssl/pkcs7.h: No such file or directory

I'm running debian squeeze, so I installed libssl-dev as follows: 

```
apt-get install libssl-dev
```

then I retrieved the berryboot source again and reran rebuild-berryboot.sh. The build still does not work.

Earlier on, through trial and error, I determined I needed to install the following things:

```
sudo apt-get install uboot-mkimage
sudo apt-get install make
sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install bison
sudo apt-get install flex
sudo apt-get install gettext
```

The larger question is: is there/should there be a way to pre-determine if the system has what it needs to build?

**Comment by flbuddymooreiv** [comment]
I did the following

```
cp -r /usr/include/openssl ~/berryboot/berryboot/BerrybootGUI2.0
```

to get to a new error:

~/berryboot/berryboot/buildroot-2012.05/output/host/usr/bin/arm-unknown-linux-uclibcgnueabi-g++ -Wl,-O1 -o BerrybootInstaller main.o mainwindow.o diskdialog.o installer.o adddialog.o logviewer.o editdialog.o clonedialog.o localedialog.o greenborderdialog.o syncthread.o downloaddialog.o networksettingsdialog.o parsedate.o driveformatthread.o copythread.o exportdialog.o iscsidialog.o wifidialog.o confeditdialog.o bootmenudialog.o ceclistener.o logindialog.o berrybootsettingsdialog.o moc_mainwindow.o moc_diskdialog.o moc_installer.o moc_adddialog.o moc_logviewer.o moc_editdialog.o moc_clonedialog.o moc_localedialog.o moc_greenborderdialog.o moc_syncthread.o moc_downloaddialog.o moc_networksettingsdialog.o moc_driveformatthread.o moc_copythread.o moc_exportdialog.o moc_iscsidialog.o moc_wifidialog.o moc_confeditdialog.o moc_bootmenudialog.o moc_ceclistener.o moc_logindialog.o moc_berrybootsettingsdialog.o qrc_icons.o    -L~/berryboot/berryboot/buildroot-2012.05/output/host/usr/arm-unknown-linux-uclibcgnueabi/sysroot/usr/lib -lcrypto -lbcm_host -lvcos -lvchiq_arm -L../../staging/opt/vc/lib -lQtGui -L~/berryboot/berryboot/buildroot-2012.05/output/host/usr/arm-unknown-linux-uclibcgnueabi/sysroot//usr/lib -lQtNetwork -lQtCore -lm -ldl -lrt -lpthread 
~/berryboot/berryboot/buildroot-2012.05/output/host/usr/lib/gcc/arm-unknown-linux-uclibcgnueabi/4.5.3/../../../../arm-unknown-linux-uclibcgnueabi/bin/ld: cannot find -lcrypto
collect2: ld returned 1 exit status
make[1]: **\* [BerrybootInstaller] Error 1
make[1]: Leaving directory `~/berryboot/berryboot/buildroot-2012.05/output/build/berrybootgui2-1.0'
make: **\* [~/berryboot/berryboot/buildroot-2012.05/output/build/berrybootgui2-1.0/.stamp_built] Error 2

**Comment by maxnet** [comment]
Standard compile tools must be installed on the host system (see list at: http://www.buildroot.org/downloads/manual/manual.html#requirement )

However Buildroot should build all libraries for the target system automatically.
It did not create a buildroot-2012.05/output/build/openssl-1.0.0j directory?

If not, try editing buildroot-2012.05/package/berrybootgui/berrybootgui2.mk

Change:

```
BERRYBOOTGUI2_DEPENDENCIES=qt rpi-userland
```

To:

```
BERRYBOOTGUI2_DEPENDENCIES=qt rpi-userland openssl
```

Might be building it in the wrong order.

**Comment by flbuddymooreiv** [comment]
Out of the box, I have:

```
$ ls ~/berryboot/berryboot/buildroot-2012.05/output/build/
berrybootgui2-1.0     host-cmake-2.8.5     host-mpfr-3.1.0
buildroot-config      host-gmp-5.0.4       host-pkg-config-0.25
host-autoconf-2.65    host-libtool-2.2.10  qt-4.8.2
host-automake-1.11.1  host-m4-1.4.16       rpi-userland-next
host-binutils-2.21.1  host-mpc-0.9
```

I will try what you mentioned.

**Comment by flbuddymooreiv** [comment]
I did make it farther.

It fails here now:

```
checking for uuid/uuid.h... no
configure: error: You need the uuid library.
make: *** [~/berryboot/berryboot/buildroot-2012.05/output/build/cryptsetup-1.5.1/.stamp_configured] Error 1
```

I installed 

```
apt-get install uuid-dev
```

but I assume the solution is more along the lines of your original suggestion.

**Comment by maxnet** [comment]
Think the depedency may be "util-linux"

But another ugly workaround is going to the buildroot-2012.05 directory, type "make menuconfig" and search for the package that you have a problem compiling (in this case cryptsetup)
Uncheck it for now, type "make" to let it build everything else first, before trying again with the package enabled.

**Comment by flbuddymooreiv** [comment]
I uninstalled uuid-dev and libssl-dev:

```
apt-get remove uuid-dev
apt-get remove libssl-dev
```

Then, inside "make menuconfig", I disabled -> Package Selection for the target -> BerryBoot -> cryptsetup, saved, ran make, got a successful build, then went back in "make menuconfig", enabled the cryptsetup, saved, ran make again, and got another successful build.

Soon-ish, I will try a from-scratch iteration of this process.

On a side note, can I change kernel options/modules/etc. simply by running "make menuconfig" in buildroot-2012.05/output/build/linux-rpi-... and then going back to the berryboot root and running rebuild-berryroot.sh?

**Comment by maxnet** [comment]
> On a side note, can I change kernel options/modules/etc. simply by running "make menuconfig" in buildroot-
> 2012.05/output/build/linux-rpi-... and then going back to the berryboot root and running rebuild-berryroot.sh?

You can indeed do a "make menuconfig ARCH=arm" there.

Inside the folder are a couple .stamp files:

```
berryboot/buildroot-2012.05/output/build/linux-rpi-3.6.y$ ls .stamp*
.stamp_built  .stamp_configured  .stamp_downloaded  .stamp_extracted  .stamp_images_installed  .stamp_patched  .stamp_target_installed
```

You need to delete .stamp_built .stamp_images_installed and .stamp_target_installed and then do a rebuild-berryboot.sh again to let it build the extra modules you selected.

If you want the kernel to be rebuild from scratch:
Copy the kernel configuration file .config that was edited by menuconfig to buildroot-2012.05/kernel-config
Delete the kernel build folder: rm -rf output/build/linux-*

**Comment by flbuddymooreiv** [comment]
I was able to get berryboot to compile and use it to install Raspbian to my ancient external USB hard drive, but the kernel installed did not have the ums-cypress driver built in, thus not allowing its use as a root device. 

Good news: berryboot got a little bit better in this process
Bad news: my problem still isn't resolved
Good news: berryboot is not the problem in this case

**Comment by maxnet** [comment]
That module shouldn't be necessary to use the drive as storage, only if you want to send it raw ATA commands.

```
CONFIG_USB_STORAGE_CYPRESS_ATACB:                                                                                                               │  
  │                                                                                                                                                 │  
  │ Say Y here if you want to use SAT (ata pass through) on devices based                                                                           │  
  │ on the Cypress USB/ATA bridge supporting ATACB. This will allow you                                                                             │  
  │ to use tools to tune and monitor your drive (like hdparm or smartctl).                                                                          │  
  │                                                                                                                                                 │  
  │ If you say no here your device will still work with the standard usb                                                                            │  
  │ mass storage class.
```

You can enable it in buildroot-2012.05/kernel-config though.

**Comment by maxnet** [comment]
You might also want to try to DISABLE building that module instead.
If it is available as module, the generic driver built into the kernel may not be used.

Berryboot does not load modules automatically (unless you use wifi)

**Comment by flbuddymooreiv** [comment]
As my ultimate goal is to use as much precompiled code as possible, disabling the driver is just as far away from that goal as is building it in. Is there a way I can tell the kernel to blacklist it during the kernel load phase regardless of if it is built in or as a module? I'd like to know both so I can troubleshoot that as a viable option without reimaging first.

**Comment by maxnet** [comment]
Problem is that the kernel blacklists its internal generic driver, if there is a more specific module available. Even if the more specific module is not loaded.
Don't know if there is a way to override that behavior.
