### ISSUE TITLE
RPi hangs when trying to set a static ethernet address when adding a distribution to an iSCSI target

### ISSUE THREAD

**Issue by DanDeufel** [maxnet/berryboot#30]
Version: BerryBoot v2.0 - 20130311

Problem:

When adding an OS to an iSCSI target volume, there is an option to setup the IP information and give the RPi a Static Address. After adding the requested information (IPAddr/NetMask/Gateway), BerryBoot hangs and never closes the network information window (hangs for over an hour). A power reset is necessary and examining the cmdline.txt file after the reboot shows that no changes were made.

Workaround:

Instead of using the popup window to set static information, edit cmdline.txt to add the IP information. E.G. add:

ipv4=192.168.1.30/255.255.255.0/192.168.1.1

(IP Address / NetMask / Gateway Address)

**Comment by maxnet** [comment]
Yes changing network information while connected to iSCSI does not work.

Added a "network configuration" button to the iSCSI configuration window in the newest release. So you can specify it before connecting.
