### ISSUE TITLE
How to get back a previously installed os on exterrnal usb drive ?

### ISSUE THREAD

**Issue by ouaibsky** [maxnet/berryboot#302]
Hi
My setup is RPI2 + WD PiDrive.
I followed installation instruction and all was working fine.

For an unknown cause, my sd card crashed and impossible to repair it.

So I had to reinstall berryboot on another SD, but I didn't find any option to add my raspbian previously installed on my PiDrive (with berry boot of course)

Is there a change to do that ?

Thx
Christophe

**Comment by maxnet** [comment]
Berryboot menu editor: ">>" -> "advanced config" -> cmdline.txt tab
change "datadev=mmcblk0p2" to "datadev=sda1"
reboot

**Comment by ouaibsky** [comment]
Hi
There is no option datadev on my current setup, I'ĺl test by adding sda1

**Comment by maxnet** [comment]
like this:

![berryboot_menu2](https://cloud.githubusercontent.com/assets/1123701/15992967/a9918002-30d9-11e6-8f06-9abe7ace51c9.png)

**Comment by ouaibsky** [comment]
It works like a charm, 
Thx for the help
Christophe
