### ISSUE TITLE
MPG2 and WVC1 decode keys added to OpenELEC config.txt do not work via BerryBoot

### ISSUE THREAD

**Issue by stryker7176** [maxnet/berryboot#303]
When running OpenELEC with berryboot, OpenELEC ignores it's own config.txt. This is normally mounted to /flash, but the folder was empty, so I manually copied all the files over to /flash and it still ignores config.txt.

Because of this I'm unable to use hardware decoding using the MPG2 and WVC1 decode keys.

Raspberry Pi 3
OpenELEC 6.95.3 (tried 6.0.3 that is downloaded in berryboot, and it doesn't work with that version either)

**Comment by maxnet** [comment]
Simply add the key to config.txt in the Berryboot menu editor instead...

">>" button -> "advanced configuration"

**Comment by stryker7176** [comment]
I tried that before and it did not work, however, it's working now. I added them to the bottom of the config.txt above [all] before, where now I have them on the top. Maybe that made the difference?

**Comment by maxnet** [comment]
If you added it a line ABOVE `[all]`, it likely felt under the `[pi1]` section, and only worked if you have a Pi 1.

So add it at the bottom BELOW `[all]`, or at the top above the start of any section.

**Comment by stryker7176** [comment]
That's what it was. It was added in the [pi1] section before. This time I added it at the top above everything.Thanks!
