### ISSUE TITLE
Restart - will no longer boot to img selection / repair options

### ISSUE THREAD

**Issue by flyfishUtah** [maxnet/berryboot#304]
Raspberry Pi2 - 32GB Class 10

I have had a well working Raspberry PI 2 with multiple OS images on it (Debian, Ubuntu, RetroPie, etc) and worked flawlessly.   I left the the Debian image running for a couple weeks to test OpenHAB, and restarted the Pi2, and now it is stuck on the colorful screen.  No network connectivity lights, nothing.

How can I resolve this issue?  How can I backup my images outside of ssh'ing into the Pi which I can't now?

I mounted the SD card on a Ubuntu laptop, and tried to 

`sudo cp * -R BerryBoot/data/ ~/PiData_Backup`

and received tons of errors

Can I fix this without losing all my images?

**Comment by maxnet** [comment]
What errors exactly?

If they are SD card read errors, there may not be much that can be done.
If you have 32 GB disk space to spare, you can try `ddrescue` to take a disk image. And `fsck.ext4` that image.

**Comment by flyfishUtah** [comment]
Tons of errors like -

cp: cannot access 'Ubuntu_Mate_15.04.img192/lib':  Input/output error
cp: cannot access 'Ubuntu_Mate_15.04.img192/bin':  Input/output error
cp: cannot access 'Ubuntu_Mate_15.04.img192/sbin':  Input/output error
cp: cannot access 'Ubuntu_Mate_15.04.img192/media':  Input/output error
etc

Is there a way to back-up images differently?

Is there a way to repair the boot?

**Comment by maxnet** [comment]
Can try `fsck.ext4` to repair file system structures, but that will cause more writes to the SD card, which is not good if the card itself happens to be failing.
Usually better to take a disk image first, but that will require 32 GB of disk space.

**Comment by flyfishUtah** [comment]
How do I go about that , as if I try to execute this on normal auto-mount it says it "the superblock could not not be read does not describe a valid ext2/ext3/ext4 filesystem..."

Auto-mounting the 2 filesystems to /media/(my name)/BerryBoot/ or /media/(my name)/01ES-04C01/

**Comment by maxnet** [comment]
Do not auto-mount the partition.

```
fsck.ext4 -yf /dev/sdX2
fsck.fat -a /dev/sdX1
```

Where sdX is your SD card device.

Will only attempt to make the file system meta data consistent. If the SD card itself is toast it will not help much, and can make things worse.

**Comment by flyfishUtah** [comment]
Thanks for the info - even when I go in and turn off automounting for the ex4 partition, and execute the command on the /mnt/location it is the same error or says "No such file or directory while trying to open  usbKingston....

Sorry for the ongoing questions - would love to resolve this issue without starting over and loose all the images, updates to images, files, etc

Thanks again

**Comment by maxnet** [comment]
Do not use the mount location, but device location.
E.g. /dev/sdX2

See dmesg after plugging in device which sdX device it is.

**Comment by flyfishUtah** [comment]
OK, was able to complete that task -

berryboot: clean, 154100/3866624 files, 5270987/15458048 blocks

**Comment by maxnet** [comment]
Can retry booting Berryboot then.
If it does not boot, copy the files from the Berryboot .zip file to the FAT partition again, **not overwriting cmdline.txt**
(if you did overwrite, add datadev=mmcblk0p2 to cmdline.txt before boot, otherwise it will start new installation procedure).

**Comment by flyfishUtah** [comment]
Copied the zip file over again, and backed-up the cmdline.txt.  That worked!  Back in business.

Thanks you for the terrific support and product!
