### ISSUE TITLE
Non-persistent Berrybooting

### ISSUE THREAD

**Issue by bubaca** [maxnet/berryboot#309]
Hello Max,

Thank you for this great piece of software!
I was wondering if there is a way to eliminate persistence from, say, a lubuntu mate image I converted to SquashFS for Berrybootin'?
I found out that by deleting the `/data` folder, the system refreshes to the original .img state, but I'd like to know if I can automate this procedure upon reboot/shutdown or bootup by adding some commands to cmdline.txt or other config file?
Alternatively, is there a way to create a SquashFS of my custom .img where the folder `/data` isn't created to begin with, hence making the system truly read-only?

Many thanks!

**Comment by muchachagrande** [comment]
There exists an option to do that.
**tzahari** committed on 3 Dec 2015:
**Added support of tmpfs as root:**
Normally the file changes are written to the SD-card. If a file "root_on_tmpfs" exist is in the root of the squashfs image then the changes are stored to a tmpfs (RAM) device. After a reboot all changes
are discarded. Therefore the SD-card is only used by reading and extends there lifetime.

So the only thing you have to do is create an empty file called "root_on_tmpfs" on your compiled SquashFS file.

**Comment by bubaca** [comment]
Awesome, Thank you!
