### ISSUE TITLE
About build BerryBootGui

### ISSUE THREAD

**Issue by ma6174** [maxnet/berryboot#31]
I am learning Qt , and I find your BerryBootGui is writen by Qt ,
I want to write some Qt program to run on my Raspberry Pi ,
I used to compile Qt directly on Raspberry Pi , but it is to slow and must run with xserver runs . 
I want to know how to cross compile Qt on my computer and run on my Raspberry Pi like your BerryBootGui.
Thanks

**Comment by maxnet** [comment]
Easiest is to use a tool like Buildroot to cross-compile Qt.

http://www.buildroot.org/
