### ISSUE TITLE
USB network device and iSCSI

### ISSUE THREAD

**Issue by 59iosl30** [maxnet/berryboot#310]
Hi! I'm using a USB network device on RPi 1 A and this works, when I boot with a fresh new berryboot sdcard and try to download a image on datadev=mmcblkp2. If I do the same with datadev=iscsi the network is searching/waiting.

Is maybe the USB network module in the iSCSI mode missing (after the driver decompression - in my case RTL8150)?

Btw: The iSCSI connect works perfect on a RPi 1 B.

**Comment by maxnet** [comment]
Do indeed not load any modules when performing an iSCSI boot.
You will need to build support statically into the kernel instead of module.

**Comment by 59iosl30** [comment]
Not yet verified but I'm quite shure that your hint fix this issue. Thank you!
