### ISSUE TITLE
Berryboot needs kernel update for compatibility to some new RPi software

### ISSUE THREAD

**Issue by g1t-dlanor** [maxnet/berryboot#311]
Some RPi software is compiled for a newer kernel than that supported by current BerryBoot, which causes various problems. Affected software includes the latest versions of RasPlex (OpenPHT Plex client for RPi1, RPi2, RPi3), which is my main concern. These still boot under BerryBoot, but some features malfunction, apparently due to kernel incompatibility (probably dependencies on newer kernel features). This kind of problem has occurred in the past, and was then solved by a new BerryBoot release using the latest kernel (at that time), so I think a similar update is again needed.

**Comment by muchachagrande** [comment]
Also there are driver updates which solves some problems on new Raspberry Pi 3, for example accessing wifi channels 12 and 13 and bluetooth stability with the built-in adapters

**Comment by maxnet** [comment]
Think enabling channel 12 and 13 does not require a kernel update, but just enabling it in wpa_supplicant.conf.
Don't think it should be the default though given it is illegal to use those channels in some countries (like the US).

**Comment by muchachagrande** [comment]
According to this issue, a kernel update is necessary [https://github.com/raspberrypi/linux/issues/1355](https://github.com/raspberrypi/linux/issues/1355)

**Comment by g1t-dlanor** [comment]
@maxnet:
FYI: Here in Sweden there is no restriction on the WiFi channels, and I always use channel 13 myself.

But regardless of the WiFi issue, there are other and more important kernel features that require a BerryBoot update in order for it to maintain compatibility to softwares based on the latest kernel versions. Here I'm primarily thinking of current RasPlex versions, as mentioned in my original post above, though I'm sure recent releases of other software are also affected.
NB: RasPlex still boots under current BerryBoot, and much of it does work properly, so a quick test might not show the problems.

**Comment by muchachagrande** [comment]
@maxnet I'd really appreciate if you consider recompiling BerryBoot with a kernel and firmware upgraded.
There are some issues with RPI3 that are solved doing firmware upgrade and unfortunately BerryBoot dies when doing this.
Thank you in advance
