### ISSUE TITLE
berryboot deletes existing partitions from hard disk upon installation

### ISSUE THREAD

**Issue by koalabi** [maxnet/berryboot#314]
The concise documentation states clearly that Berryboot formats the target partition (default is sda1) upon installation but what it does not state clearly (if I'm not mistaken) is that it actually erases all partitions on the target device.  At least, I have tried several times and always got the same behavior.

This is not so much annoying with an SD card but it gets well on a hard disk of 314 Gb ;-) or more, the more so if one of the partitions is intended to be a swap partition.

It would be nice if Berryboot only erased the first (or, better yet, only one designated partition on the target drive.  Would this be hard to implement ?

**Comment by maxnet** [comment]
> The concise documentation states clearly that Berryboot formats the target partition

Where do you see the word partition in our [documentation](http://www.berryterminal.com/doku.php/berryboot)?

And there is no mention of partitions on the drive format dialog either:

![bb2](https://cloud.githubusercontent.com/assets/1123701/17271136/5c0fd82c-5674-11e6-902b-48599caa3ea6.png)

Do you want **Warning! All existing data will be erased** to be rephrased "all existing data on all partitions", or something like that?

**Comment by koalabi** [comment]
Well, this is not the problem (formally, you are right ;-) : partition(s) gets mentioned nowhere).  On the other hand, please also note that I haven't classified it as a bug.  Let's say it is an unfortunate feature (is it better so?).

While I can perfectly understand that it makes sense to erase the whole of a (even) 16 Gb microSD card, I find it really annoying that a bootloader erases the whole of a 314 Gb (or even 1 or 2 Tb) HDD to install a few images.  Would it be so hard to only affect one partition and the MBR?

**Comment by maxnet** [comment]
> Would it be so hard to only affect one partition and the MBR?

Yes, it is.

We do not need one partition, but two.
And very few people have two partitions conveniently laying around ready for us to use, so that would require resizing data on existing file systems...

**Comment by koalabi** [comment]
OK.  Too bad!

Thanks for replying.

Kind regards
