### ISSUE TITLE
Booting a Raspberry Pi into an already existing iSCSI root

### ISSUE THREAD

**Issue by DanDeufel** [maxnet/berryboot#32]
Problem:

I have a Raspberry Pi that used BerryBoot v2.0 to install Raspian on an iSCSI target. the RPi also swaps on a second iSCSI target. My SD card started misbehaving and now is unreliable. (A different SD card with BerryBoot, Raspian, and Memtester installed works fine and the failing card doesn't behave in a USB SD Card reader.

Question:

Can you tell me what I have to do to configure a new SD card to point to my iSCSI targets and boot off of them without having the targets erased and a new OS installed? Is it a matter of just restoring the four .txt files to the new SD card after the BerryBoot files have been loaded?

**Comment by maxnet** [comment]
Need to copy the Berryboot files from the .zip, and cmdline.txt and iscsi.sh from the old SD card.

**Comment by DanDeufel** [comment]
Thank you for your reply. I was able to get the *.txt files from the old SD card so I will try it this weekend.

Cheers,
Dan

**Comment by maxnet** [comment]
Closing as issues is >2 months old
