### ISSUE TITLE
2.8 release for P0/P1?

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#320]
Hi,

Just saw BB has been updated for P2/P3: any chance you would release an updated build for P0/P1?

Many thanks in advance!

**Comment by macmpi** [comment]
@maxnet 
If I were to try to build 2.8 for p0, would it build as-is with the following?
`./build-berryboot.sh device_pi1`?
or are some 2.8 changes specific to p2 & p3 and won't work?

Thanks.

**Comment by maxnet** [comment]
Should work.
2.8 runs experimental firmware branch from the next branch though.
And there is not much advantage using that on a Pi 0 or Pi 1.

**Comment by macmpi** [comment]
Some changes made back in March, and never released on P0, may be of interest (OpenElec update). Also thought some newer features in 2.8 may be interesting.
Now, if you intend to do such release soon, then I'll happily hold-off ;)

**Comment by pswiifanwmi** [comment]
Could someone close this issue?
