### ISSUE TITLE
I cant delete BerryBoot

### ISSUE THREAD

**Issue by thevmachine** [maxnet/berryboot#325]
I beg you, dont take my trys(tries?) to delete BerryBoot as an offence. It just crased several days ago and because i came to the conclusion, that i dont need any os besides raspian jessie anymore, i could just easily reinstall raspian alone. Problem: I sat and still sitting at my windows machine trying to delete the partitions on the sd card. I tried to just directly reinstall Raspbian using win32diskimager it gave me a write sucessfull, but after i started the pi up again, there was still the BerryBoot home screen and the dialogue i got with the crash, which was btw. not caused through berryboot but through me who accidentally plugged out the psu while downloading updates to one of the os. This dialogue is "trying to mount partition m(something)" and it didnt changed with the "reinstall" of raspbian. But im also not able to delete/format the around 130 mb, 127mb  for my cause to be exact, fat partition which my mind is telling me need to be the BerryBoot-bootloader or however you want to call it. I tried it with diskpart in an admin-commandline and itchanges nothing.
(tl;dr) :P 
Hope someone can help me. Thx.

**Comment by maxnet** [comment]
Win32diskimager will definitely destroy Berryboot.
If it does not, there may be something wrong with your SD card instead, that effectively turned it read-only.

**Comment by thevmachine** [comment]
can i change it back from read-only?

**Comment by maxnet** [comment]
If it's really broken, I doubt it.
But then you should also have problems writing to it from within Berryboot. E.g. saving files.

**Comment by thevmachine** [comment]
I cant try taht because as said the now existing problem was caused by me and the dialogue isnt removable in any kind while starting up BerryBoot. And the microSD seems to be broken to me by now. Tried several things and nothing worked, so thanks for the help and for everybody ut there: it wasnt The fault of BerryBoot which obstruced my microSD, but it was my own fault.
