### ISSUE TITLE
My IR remote stopped responding

### ISSUE THREAD

**Issue by muchachagrande** [maxnet/berryboot#327]
Hi, I was using LibreELEC with the previous version of Berryboot.
I programed it to respond to an old IR remote control.
But with the last Berryboot update it stopped responding.
May be something related to overlays?
To turn on the pins and receive IR codes I put dtoverlay=lirc-rpi in config.txt

**Comment by nunojusto** [comment]
I can confirm this happens to me also

**Comment by muchachagrande** [comment]
I think I figured out the solution to this.
On previous versions of berryboot the overlays were named xxxx.dtb
Now with the update, the new name is xxxx.dtbo
What I did is to copy lirc-rpi.dtbo to lirc-rpi.dtb and now my IR remote works again.
I've only tested with lirc-rpi but, may be there are other solutions concerning overlays that can be achieved with this workaround.
I think that there has to be another cause to this problem but for now you can try this and tell me if it worked for you.

**Comment by nunojusto** [comment]
No, does not work for me

**Comment by muchachagrande** [comment]
You may try to use xxx_overlay.dtb
That is the old name format.
So the name of the lirc overlay should be lirc-rpi_overlay.dtb
