### ISSUE TITLE
Issue adding custom image to boot menu

### ISSUE THREAD

**Issue by Nullterminator123** [maxnet/berryboot#33]
Trying to add Fedora18 final, I have an issue
Downloaded the final zip from seneca, Unzipping on centos 5.6 , the file did not match checksum. Un zipped on windows, and checksum matched.  ftp'd to centos 5.6 box, and ran commands as in instructions. needed to yum install squashfs-tools reports as version 3.0-patched (2006//08//16)

The original unzipped image is 3.072gb.  The squashed image is around 500mb

When I load the result image and try to boot, I get an error /sbin/init not found, then "emergency recovery shell activated"  and /bin/sh: can't access tty; job control turned off.

ls -l /sbin   shwos many files pointing to ../bin/busybox

I will try to find another sd card and run the fedora img by itself.

Thanks for any suggestions
NullT  (jeb)
### my build history

I had to build in a folder other than /mnt as my mnt is on too small a partition

[root@gazelle raspi]# kpartx -av rpfr-f18-final.img
add map loop0p1 : 0 104448 linear /dev/loop0 2048
add map loop0p2 : 0 6037504 linear /dev/loop0 106496
[root@gazelle raspi]# mount /dev/mapper/loop0p2 /home/jbeasley/raspi/imgbuild
[root@gazelle raspi]# sed -i 's/^\/dev\/mmcblk/#\0/g' imgbuild/etc/fstab
[root@gazelle raspi]# mksquashfs imgbuild 'Fedora-18-Remix.img' -e lib/modules
Creating little endian 3.0 filesystem on Fedora-18-Remix.img, block size 65536.

Little endian filesystem, data block size 65536, compressed data, compressed met
adata, compressed fragments
Filesystem size 499923.08 Kbytes (488.21 Mbytes)
        35.66% of uncompressed filesystem size (1401893.64 Kbytes)
Inode table size 640532 bytes (625.52 Kbytes)
        33.13% of uncompressed inode table size (1933513 bytes)
Directory table size 578397 bytes (564.84 Kbytes)
        43.22% of uncompressed directory table size (1338239 bytes)
Number of duplicate files found 3549
Number of inodes 57215
Number of files 45935
Number of fragments 5806
Number of symbolic links  5766
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 5514
Number of uids 7
        root (0)
        unknown (999)
        unknown (996)
        unknown (994)
        unknown (995)
        smmsp (51)
        uucp (10)
Number of gids 15
        smmsp (51)
        unknown (992)
        root (0)
        slocate (21)
        mail (12)
        nobody (99)
        tty (5)
        dbus (81)
        utmp (22)
        unknown (998)
        utempter (35)
        unknown (995)
        unknown (994)
        unknown (996)
        uucp (14)
[root@gazelle raspi]# umount imgbuild/
[root@gazelle raspi]# kpartx -d rpfr-f18-final.img
loop deleted : /dev/loop0
[root@gazelle raspi]#

**Comment by maxnet** [comment]
Need to move /usr/lib and /usr/sbin to /lib and /sbin and reverse the symlinks.
Search for the post about Archlinux on the Raspberry forum which has the same issue.
