### ISSUE TITLE
berryboot/linaro-alip/hackberry: How to change overscan/screen size?

### ISSUE THREAD

**Issue by joeschmoe40** [maxnet/berryboot#332]
Note: I know how to do this on the Raspberry Pi (and have done so many times), but this question does not have to do with the RPi.  Most of what I've found by Googling is RPi-specific.

(That said)

I am running linaro-alip, booted by Berryboot, on a Hackberry (board made by "Miniand" - who no longer seem to be in business).  It works fine except that the desktop is way too big for the screen.  It is still usable, but basically I cannot see the taskbar (at the bottom of the screen). I know it is there, but I can't see it.  Also, the other menus that popup normally in corners of the screen (such as when you type Ctrl/Escape), pop up half on the screen and half off.  As I said, it is useable, but awkward.

I know that on the RPi, you can edit "config.txt", but I don't know of the equivalent for linaro-alip.  Can anyone help me?

**Comment by ZanderBrown** [comment]
ok so possible a stupid suggestion: have you looked in the preferences? I have never used `linaro-alip` but I would be surprised if it doesn't have a display preferences of some kind?

**Comment by maxnet** [comment]
Maybe in `uEnv.txt` but don't know the exact settings out of the top of my head.

**Comment by joeschmoe40** [comment]
Good news!  I was able to fix this by mucking with the settings on my TV (via the remote).

But, FWIW, it did look like the similar problem on the Pi - which does require hacking the config.txt file.  So it goes...
