### ISSUE TITLE
QUESTION rpi2 to zero

### ISSUE THREAD

**Issue by RubenNL** [maxnet/berryboot#336]
is it possible to use my rpi2(B) sd card in a raspberry pi zero?

EDIT: 
or, is it possible to export a os(openelec) from a rpi2B, and import it on a rpi zero?

**Comment by maxnet** [comment]
Depends on OpenELEC version.
If it is a Pi 2 (armv7) version, it will not run on the Pi zero (armv6)

You will find out soon enough when exporting/importing.

**Comment by RubenNL** [comment]
just an note: i have tried to switch sd-cards, and berryboot just dont start.
so, the only way is exporting the addons of openelec, and import them on another pi.
