### ISSUE TITLE
Bluetooth and 7" touchscreen

### ISSUE THREAD

**Issue by pidelt** [maxnet/berryboot#339]
Hi,

i have created a multiboot system with berryboot V2.0 (Debian Jessie Raspbian 2016.09 and LibreELEC 7.0.1) on my RPi3 B connected with an official touchscreen.

It works fine but there are two issues:

The first (more important for me) on bluetooth; no devices was found by searching mode, in both OS (Debian.., Libre..).

When i'm launching bluetoothctl it replies:

pi@raspberrypi:~ $ bluetoothctl
[NEW] Controller AA:AA:AA:AA:AA:AA raspberrypi [default]
[bluetooth]# agent on
Agent registered
[bluetooth]# scan on
Discovery started
[CHG] Controller AA:AA:AA:AA:AA:AA Discovering: yes
[bluetooth]# 

The second one on the touchscreen, it doesn't work in any OS (Berryboot, Debian, Libre).

Both updates (apt-get update and apt-get upgrade) have been performed.

With only OS Debian.. or Libre.. (without berryboot) everything works properly.

Thanks in advance

P

**Comment by seppforcher** [comment]
I second that issue, I cannot get bluetooth to find any devices on my raspberry pi 3 Model B.
I'm running berryboot-20160930-pi2-pi3 and Jessie Raspbian 2016.09 on top.

**Comment by maxnet** [comment]
Is indeed something wrong with that.

For now you can use the following workaround in Raspbian console:

```
sudo apt-get update
sudo apt-get install --reinstall bluez-firmware
sudo reboot
```
