### ISSUE TITLE
Berryboot inaccessible if screen sizes are too small

### ISSUE THREAD

**Issue by JoshuaFlynn** [maxnet/berryboot#34]
If framebuffer values are set as so in config.txt:
framebuffer_width=340
framebuffer_height=200

On exit and restart, the windows go off-screen and become inaccessible. Berryboot has no way to reset or rectify this problem, and the OS cannot alter the config.txt to reset it. Even if one manages to resize the initial bootscreen to fit within the few seconds prior to booting, clicking the 'Edit' button results in a edit window that is centred such that all parts go off-screen, and thus options cannot be clicked and window cannot be resized in order to access.

The lack of keyboard shortcuts for 'config.txt' mean that there is no way to access config.txt whilst in this state.

Possible solutions:
Force window sizes to fit the screen regardless of height/width parameters (so they never go off-screen).
Implement a short-cut command for accessing config.txt.
Add a windows-esque prompt that asks if the new settings are acceptable (and resets to previous settings if not).
Implement a 'reset config.txt to default' option for the main boot screen (which can be accessed with a keyboard shortcut).

**Comment by maxnet** [comment]
Berryboot was designed to work for SDTV resolutions, but nothing smaller.
What kind of display are you using?

**Comment by maxnet** [comment]
> Perhaps incap the res so it cannot be made any smaller?

Well, config.txt is not read by Berryboot but by the Raspberry Pi firmware.
Not having the source code for that, I cannot modify it to ignore small values.

Also note that it is also possible to modify config.txt in a way that will cause Berryboot to fail to start at all (e.g. by deleting the kernel or initramfs lines)
So while it may have helped against your screen resoltion problem, for many other config.txt edits that went wrong, we are unable to show a "reset config.txt to default" option, as the software wouldn't start at all.

You should be able to edit config.txt by putting the SD card into your normal computer and opening it in a text editor like notepad though.
It's on the FAT partition that should be accessible from any operating system.

**Comment by maxnet** [comment]
> Are there any plans for a keyboard interface for berryboot?

We do have some shortcuts.
E.g. CTRL+A (or red button on TV remote) for "add OS"

Just not for the advanced options.
Might add some in a newer version.

**Comment by maxnet** [comment]
Added the following keyboard short cuts in the lastest release:
- ctrl+E - configuration editor
- ctrl+X - console
