### ISSUE TITLE
berryboot issue with ntfs samba shares

### ISSUE THREAD

**Issue by smileybob** [maxnet/berryboot#35]
Excuse me if I get anything wrong as I'm new to Linux etc.
It seems that openelec 3 installed from the openelec image without berryboot, you can share ntfs directories from openelec accross the network and also write back to the samba share from another pc on the network.
When openelec 3 is installed using the berryboot to install to an external usb hard drive, then you cannot write to the samba ntfs usb share from accross the network. its seems that the ntfs disk is mounted with ro access??
It maybe i'm missing something and blaming berryboot wrongly.
It's a shame as the berryboot system seems really good and would be great to use it.
As i'm new can someone else verify this?

Many Thanks

**Comment by maxnet** [comment]
Can you try if the latest Berryboot update (available under "add os" in the menu editor) fixes this?
Includes a kernel with NTFS write support.

**Comment by smileybob** [comment]
I have tried the latest Berryboot 20130528.
When i view the folders shared from an external drive on Openenelec from accross the network, I am still unable to write to the folders.
When using OpenElec without Berryboot installed, the folders are writable again from accross the network.

**Comment by smileybob** [comment]
I have now managed to fix this issue:
The problem was that openelec in Berryboot  was mounting ntfs drives as read only (Openelec mounted ntfs correctly without Berryboot), what I needed to do was to mount them using ntfs-3g instead (ntfs-3g mounts as rw)
As the drives at boot were automounting (I think using udev or udevil) it was difficult to remount as ntfs-3g automatically upon booting up.
What I did was the following:

I created a file called autostart.sh in the config folder - cd /storage/.config.
*You can use WinSCP from a windows PC to connect and browse to the path.
The file should look like this:

#!/bin/sh
(sleep 30; \
umount /media/The_Drive_to_Unmount \
mount -t ntfs-3g UUID=The_UUID_of_the_drive /var/media/HDD; \
)&

*To find the UUID of the drive type blkid in the command line.

Then reboot the RPI and then via the command prompt(I Use Putty from my windows PC)

I hope this helps people

**Comment by PetteriLah** [comment]
Thanks Works with Rpi 2 and openelec 5.0.3 too.
Line 3 missing ; on your example.

**Comment by smileybob** [comment]
I'm glad it helped, I'm now running on Rpi 2 and Openelec 5.0.1 (I will update Openelec soon)
you said that line 3 missing? could you let me know what that was?
I'm still fumbling my way through Linux, but loving it and the RPi so far ;)

**Comment by PetteriLah** [comment]
End of line 3 missing character semicolon ; 
I good to copy paste code, in coding i'm useless :D
