### ISSUE TITLE
"Encrypt Disk" doesn't work while installation

### ISSUE THREAD

**Issue by sebastianabdu** [maxnet/berryboot#354]
Using berryboot on a raspberry Pi 2 quad core.
When I'm in the installation process of berryboot and in the "Disk Selection" Part, I select the sd-card, give a click to "Encrypt Disk" check box (Filesystem is default set "ext4") an click on format.
It then tells me that "You will be switched to a secure text console shortly, where you need to enter the password you wish to use three times." 
After clicking ok it sends me to the cosole and tells me 
"Warning! this will overwrite data on /dev/XXXX irrevocably. Are you sure? (Type uppercase yes)"
After typing yes it sends me back to "Disk Selection"-Window. 
Error : "Error Formatting data partition (ext4)".
Only way to procede is to untick the "Encrypt Disk" check box.
Happens the same when trying to install on an USB-Stick and on an sd-card in an usb-adaptor.

**Comment by maxnet** [comment]
Make sure it is in uppercase.
YES
Not yes

**Comment by sebastianabdu** [comment]
Ow what a stupid mistake. Thanks, it worked!

**Comment by ghost** [comment]
I am having a similar issue. I get the error after I try to enter my first passphrase. Any idea of what could cause this? I am running BerryBoot on the Raspberry Pi 4.
