### ISSUE TITLE
How can I disable the "Waiting for data partition" at the start?

### ISSUE THREAD

**Issue by Firues** [maxnet/berryboot#357]
Solution: https://www.dropbox.com/s/4tajmfz7meu6q41/BerryBoot_v2.0_bootloader_10sec-to-10min-fix.zip.zip?dl=0
How can I disable the "Waiting for data partition"?
I do not have time to reconnect the hard drive (I have a bad powered usb hub) and all results with an error.
I really need disable it. 

![dpx0cwwfxpy](https://cloud.githubusercontent.com/assets/12688475/21929523/fb8a75a0-d9a1-11e6-88c7-ebb3307c7bda.jpg)

![rngn_tcy4wa](https://cloud.githubusercontent.com/assets/12688475/21929467/b18871fa-d9a1-11e6-8952-aefefda68f64.jpg)
![ug6jrv08nfa](https://cloud.githubusercontent.com/assets/12688475/21929480/c41e3782-d9a1-11e6-9afc-e9b4b65c72fb.jpg)

**Comment by maxnet** [comment]
>How can I disable the "Waiting for data partition"?

For what purpose?
Without your data partition, your data is not there...

If you want to perform clean installation, remove the "datadev=" from cmdline.txt

**Comment by Firues** [comment]
No. I do not want a clean install.
I have a hard disk with the system. Everything works fine. 
But if I want to do a reboot, raspberry pi does not see the hard drive until I switch off and on again usb hub.

I do not have time to do it because of this "Waiting for data partition" falls with an error before I have time to do it.

**Comment by maxnet** [comment]
You have 10 seconds at boot to make sure hard disk is up & running.
Cannot help you if that is not enough.

**Comment by Firues** [comment]
> You have 10 seconds at boot to make sure hard disk is up & running. 

Menu with "Waiting for data partition" appears before it. 
If I have time to press the "Esc", then then I have time to restart USB hub.

**Comment by maxnet** [comment]
"Waiting for data partition" appears for 10 seconds, while it keeps trying and trying to find your drive.
If 10 seconds is not enough, I cannot help you.
Get a better drive.

**Comment by Firues** [comment]
> "Waiting for data partition" appears for 10 seconds, while it keeps trying and trying to find your drive.
If 10 seconds is not enough, I cannot help you.
Get a better drive.

Please look the two small video. I recorded it for you right now.

[**One**](https://youtu.be/f9q0eOOkepM) and [**Two**](https://youtu.be/lci5pcLt1xY)
Please. Maybe it will help explain.

**Comment by maxnet** [comment]
It will only wait for the drive for +/- 10 seconds.
Pressing the "x" only hides the status window, you still need to connect the drive within 10 seconds.
If it takes much longer the drive will not appear even if you connect it.

So what you are asking for is more time than 10 seconds, rather than disabling the status window.

edit: actually it is 20 seconds instead of 10. (searches for 10 seconds for the exact drive it is expecting, and another 10 seconds for any drive)

**Comment by Firues** [comment]
> edit: actually it is 20 seconds instead of 10. (searches for 10 seconds for the exact drive it is expecting, and another 10 seconds for any drive)

Oh no. How can I increase this time?

**Comment by maxnet** [comment]
>Oh no. How can I increase this time?

There is currently not any easy option for that.
If you compile from source, you could make this number higher than 10: https://github.com/maxnet/berryboot/blob/776c383c49ee1fdcfe288fdf7143a89e31c1b89b/BerrybootGUI2.0/bootmenudialog.cpp#L145

Might be easier to get a hard disk that consumes less.
Most do not even need a powered usb hub, but can be connected directly to the Pi.

**Comment by Firues** [comment]
> Might be easier to get a hard disk that consumes less.
Most do not even need a powered usb hub, but can be connected directly to the Pi.

Maybe..... Advise any please?

**Comment by maxnet** [comment]
>Maybe..... Advise any please?

https://www.wdc.com/products/wdlabs/wd-pidrive-foundation-edition.html

But normal WD passport drive should work as well, provided you have a good power supply.

**Comment by Firues** [comment]
>https://www.wdc.com/products/wdlabs/wd-pidrive-foundation-edition.html
But normal WD passport drive should work as well, provided you have a good power supply.

 And there are options with case?

**Comment by maxnet** [comment]
>And there are options with case?

There are cases that can fit both the Raspberry and that drive: https://www.wdc.com/products/wdlabs.html

**Comment by Firues** [comment]
like this:
![120008_2254_draft](https://cloud.githubusercontent.com/assets/12688475/21953985/3fe5dcee-da56-11e6-8f33-d91da841dae5.jpg)

![vneshniy_korpus_dlya_hdd_2 5_orico_2599us3_black_3](https://cloud.githubusercontent.com/assets/12688475/21953983/2974c844-da56-11e6-9048-5a01ceeca06d.jpg)

**Comment by Firues** [comment]
Solution: https://www.dropbox.com/s/4tajmfz7meu6q41/BerryBoot_v2.0_bootloader_10sec-to-10min-fix.zip.zip?dl=0
I compiled (used flag: ./build-berryboot.sh device_pi2). 600 seconds is enough for all. lol.
Working on my Raspberry pi 3.
