### ISSUE TITLE
Berryboot doesn't starts after upgrade

### ISSUE THREAD

**Issue by xumagh** [maxnet/berryboot#36]
Hi¡

Yesterday I tried to Add a new OS and BB suggest to update to a new version.

After did it and close to restart, RPI (B) doesn't starts.

I tried to restore it from an old backup (only FAT fs), and BB starts, but not the OS (openlec or weezy):

Mounting image OpenELEC_2012.12.img128...
Mounting RW data directory on top
Setting CPU governor to performance
Starting operating system OpenELEC_2012.12.img128...
switch_root: can't execute '/sbin/init' Not a directory

Whay can I do? I mainly want to boot again my OSs

Thanks a lot¡

**Comment by maxnet** [comment]
File system of the second ext4 partition is likely corrupt.
Can try the "repair file system" option in the Berryboot menu editor, but cannot guarantee any success with that.
