### ISSUE TITLE
wifi: unable to set regulatory domain

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [maxnet/berryboot#360]
BB is missing "iw" and /etc/default/crda so it is not possible to use it when the network is on a channel outside the driver default domain. Case in point, channel 13 in Italy. Other than that, wifi works since other networks are visibile and RPi has already been tested on channel 13 before installing BB.

**Comment by maxnet** [comment]
Try putting ``country=your-country-code`` in your wpa_supplicant.conf

**Comment by AndreaBorgia-Abo** [comment]
@maxnet already tried before reporting and just retried now to be sure: it does not work.
Also, I see that the wpa_supplicant.conf I can edit via the GUI is different from the one I can access via tty2 console: which one should I edit, then?
