### ISSUE TITLE
[Question] Headless install using ssh?

### ISSUE THREAD

**Issue by snowdd1** [maxnet/berryboot#361]
I tried to figure that out on the homepage and in the issues here on github, but wasn't completely sure:  

Is VNC the only headless mode supported for install?  

No ssh based text headless mode? As far as I could see there are only some choices to be made in those windows seen in the screenshots, aren't they?

Thanks,
Raoul

**Comment by maxnet** [comment]
If you only want a single operating system, and have that automatically installed, you may be better off with NOOBS than with Berryboot.

**Comment by snowdd1** [comment]
Hi thanks for answering so fast!
My intention is to have most of the system on my synology as an iSCSI target, for better backup and extended SD card life.
It is for my [homebridge](https://github.com/nfarina/homebridge) and [knxd](https://github.com/knxd/knxd) servers, which write quite a lot to the logs and other files.

**Comment by maxnet** [comment]
And why is it a problem to connect a display, or use VNC during installation exactly?
It doesn't sound like your Pi is at some remote location, and only reachable by a low bandwidth GRPS modem.

**Comment by snowdd1** [comment]
VNC is a possibility, though I do not use otherwise. Currently I use ssh (puTTy) for server management only.  
From your response I take that pure text based ssh is not possible - I'll try with VNC then.  
Thanks for your help!
