### ISSUE TITLE
USB WIFI dongle 

### ISSUE THREAD

**Issue by Basfet** [maxnet/berryboot#362]
BerryBoot don´t recognize my USB WIFI dongle based at RTL8812au.

**Comment by maxnet** [comment]
We only support models that have mainstream Linux support.

**Comment by Basfet** [comment]
What is that "mainstream Linux support"?
RTL8812au driver is in the Raspbian, OSMC, LibreElec. And it is not in Berryboot. Why can not compile it at Berryboot?
https://github.com/gnab/rtl8812au
