### ISSUE TITLE
berryboot doesn't find data partition directly

### ISSUE THREAD

**Issue by jcmaquet** [maxnet/berryboot#364]
new installation of berry boot on sd with empty hdd disk for last raspian. 
installation without any problem
but at reboot:
-waiting for data partition sda2 =>  10sec
-partition data is not sda2        =>   20sec
-another msg but too quick
then raspbian start normaly without any other problem

working but very slow in berryboot due to this message (+30sec)
I have reinstalled everything, same problem

I have checked the disk, seems ok for me

![20170131_141647](https://cloud.githubusercontent.com/assets/25457319/22466915/c354592e-e7c2-11e6-917d-e01f8cb15f19.jpg)

**Comment by ZanderBrown** [comment]
I must admit berryboot can be very slow to find data for me **Edit** data is on SD

**Comment by maxnet** [comment]
Some hard disks can be very slow to spin up on boot.
First 10 seconds it waits explicitly for the device it is expecting to show up, in this case sda2.
After that it will search all drives that show up. Be it sda2, sdb2, sdc2 or something else.

**Comment by laself** [comment]
hi max
the drive was powered separately (3.5inch)
this occur at each reboot, not only power up.
the last message is something found data on sda2

**Comment by maxnet** [comment]
``dmesg |grep sda`` should give you the number of seconds it took before the drive showed up.

**Comment by laself** [comment]
it seems you are right.
according to dmeg, it take 14s to show up
I don't understand, it is not the spin up time because the drive is already on after a reboot.
?

**Comment by maxnet** [comment]
Not sure why.
Some kind of power saving mode?

**Comment by laself** [comment]
I will try with another drive.
thanks for support and for your time !

I have tried with another HDD and another usb to pata. 
8sec now
work perfectly now
