### ISSUE TITLE
Disable lirc-rpi

### ISSUE THREAD

**Issue by therudy** [maxnet/berryboot#365]
Hello,

i use berryboot with rasplex,

and i need to disable  lirc-rpi

.# dtoverlay=lirc-rpi

for use my dac,

how can i put on it ?
thank

**Comment by maxnet** [comment]
You can edit config.txt/cmdline.txt with the "edit config" button in Berryboot.

I do not think we have any lirc-rpi overlay enabled by default.
If it loads an unwanted module nevertheless you may need to blacklist it in cmdline.txt with ``modprobe.blacklist=nameofmodule``

**Comment by therudy** [comment]
Hello maxnet,

thank for your reply

modprobe.blacklist=lirc-rpi

dont solve my problem, its probably from another, thank you , i go to search :)
