### ISSUE TITLE
Overclock only specific OS

### ISSUE THREAD

**Issue by therudy** [maxnet/berryboot#366]
Hello,

does its possible to overclock from berryboot JUST for 1 OS ?

i actually overclocked berryboot on .txt but its put on all

sorry for my english

thank :)

**Comment by maxnet** [comment]
Not something we provide a GUI for.

You may be able to do some stuff yourself from within the OS.
Play with the settings under /sys/devices/system/cpu/cpu0/cpufreq

**Comment by therudy** [comment]
thank you maxnet :) !
