### ISSUE TITLE
how to configure parameters for iSCSI setting on ubuntu iscsitarget?

### ISSUE THREAD

**Issue by ebasruh** [maxnet/berryboot#37]
I need help to define iscsi parameters. Can anyone send me iscsi.sh file either?
Tanks your help.

**Comment by DanDeufel** [comment]
Here is my copy of iscsi.sh. It will give you the initiator settings for BerryBoot but still requires that your target be set up properly.

root@pi512 /media/RPI1 # cat iscsi.sh
/sbin/iscsistart -i "iqn.2012-08.com.berryboot:pi512" -g 1 -t "iqn.1992-04.com.emc:storage.ix2-dl-7.RPI1" -a "192.168.1.12"
/sbin/iscsistart -i "iqn.2012-08.com.berryboot:pi512" -g 1 -t "iqn.1992-04.com.emc:storage.ix2-dl-7.RPI1-SWAP" -a "192.168.1.12"
root@pi512 /media/RPI1 # 

My RPi is booting off an Iomega ix2-dl NAS box serving two iscsi targets, an 8GB boot partition and a 1GB swap partition. I also have a 256MB RPi booting off a different set of targets on the NAS box.
