### ISSUE TITLE
GUI screenshots

### ISSUE THREAD

**Issue by francesco-vannini** [maxnet/berryboot#372]
I am writing a tutorial that involves BerryBoot. Is there a way to take screenshots of the GUI like you would in Raspbian with scrot?

**Comment by francesco-vannini** [comment]
Could running the OS under QEMU be an easier approach?
I found several articles about how to do this in Raspbian like this one
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=37386
but cannot quite work out how to achieve the same for BerryBoot

**Comment by maxnet** [comment]
Sorry, for the late reply.
The screenshots on the Berryboot website where made by using Berryboot through vnc.

http://www.berryterminal.com/doku.php/berryboot/headless_installation

**Comment by francesco-vannini** [comment]
NW thanks for getting back to me eventually.
