### ISSUE TITLE
No connection with PuTTY

### ISSUE THREAD

**Issue by Fab117** [maxnet/berryboot#379]
Hi,

I just installed BerryBoot on my Raspberry pi 3.

Then, I installed "Debian Jessie Raspian 2016.11" as default OS.
After reboot,it seems OK with the monitor connected to my pi.

However, when I try to connect from my PC with PuTTY, I've the error message:

![putty error](https://cloud.githubusercontent.com/assets/26280294/23724856/9e522e5a-044e-11e7-881e-8d65067dbe9c.jpg)

Do someone know how to solve it?

Thanks.

Fab

**Comment by ZanderBrown** [comment]
Is SSH enabled on the Pi? I believe it is now disabled by default for security purposes

**Comment by Fab117** [comment]
Thank you for your interest.

Don't know (I'm a beginner).
However, I could access when I installed directly Debian on my SD Card (without BerryBoot).

Fab

**Comment by maxnet** [comment]
Not in newer versions.
Can enable SSH in the Raspberry Pi settings tool inside Raspbian.

**Comment by ZanderBrown** [comment]
or `sudo raspi-config`

**Comment by Fab117** [comment]
Hi,
Than you for your help.
You are fully right.
This version of Debian disable SSH by default:
http://hpics.li/8868351


Have a nice week-end.

Fab
