### ISSUE TITLE
How to get a Newbie going ...

### ISSUE THREAD

**Issue by JohnoPolo** [maxnet/berryboot#39]
Hello, yes, I'm the newbie with a problem and despite several hours of effort and searching for relevant information, I am unable to get my new Raspberry Pi model B going (a very unusual experience for me by the way). Because I was unable to get any of several keyboards working (using several different power supplies) I found BerryBoot and realised that if I successfully did a remote install, I wouldn't need a keyboard and my problems would over. Alas, so far, nirvana remains elusive.

The instructions on the BerryBoot site were straightforward. I downloaded and extracted the files to a formatted SDHC 8MB card and edited cmdline.txt by appending vncinstall ipv4=192.168.88.88/255.255.255.0/192.168.88.1. I got some popcorn, fired up the Raspberry and prepared to watch proceedings on the TV I had hooked it up to. The Red, two greens and an orange LED lit up and a line to the effect that "if one wanted to not do a remote install ....." appeared and I prepared to slap my back. Shortly thereafter the TV screen went blank. The LEDs are still lit up and I've tried connecting to 192.168.88.88 (and 192.168.88.1) via the ultraVNC Viewer installed on my PC without success. Pinging the above addresses produces no response either.

The Raspberry is connected to my router via cable and the PC accesses the router via wireless but there's no sign of any new device on the network.  I pulled the plug after an hour ...

So, could someone be kind enough to walk me through the correct procedure? I really would appreciate it.

**Comment by maxnet** [comment]
What is the local IP-address of your own computer? (try running "ipconfig" from the Windows command prompt)

If the first 3 digits of the IP-address differ from the Pi, e.g. if it shows your PC has 192.168.0.10 instead of 192.168.88.10, you need to change the IP-address of your Pi as well to match.
They need to be in the same subnet.

**Comment by JohnoPolo** [comment]
Thank you so much for that response, however I need a little more guidance. Here are the numbers from my PC. Please tell me exactly what numbers to change on the Pi end - I really don't know which address is applicable. Much appreciated :-)

Ethernet adapter Local Area Connection 3:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::7441:e2ce:95ec:5d87%17
   Autoconfiguration IPv4 Address. . : 169.254.93.135
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :

Wireless LAN adapter Wireless Network Connection:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::8006:feff:31f3:aa4f%12
   IPv4 Address. . . . . . . . . . . : 192.168.1.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1

**Comment by maxnet** [comment]
Put in cmdline.txt: "vncinstall ipv4=192.168.1.123/255.255.255.0/192.168.1.1"
And then connect with VNC to 192.168.1.123

**Comment by maxnet** [comment]
Correction gateway should be 192.168.1.1, not 192.168.88.1
Edited my previous comment.

Put in cmdline.txt "vncinstall ipv4=192.168.1.123/255.255.255.0/192.168.1.1"

**Comment by JohnoPolo** [comment]
Thank you so much, it's almost 10:00pm where I am so I'll give it a shot tomorrow. If you ever find yourself in Northern Thailand, I'll buy you a Chang :-)

**Comment by JohnoPolo** [comment]
No luck yet: ultraVNC viewer can't connect on 192.168.1.123. It will however connect to the server installed on my PC - so that seems to be working.

Here is the content of cmdline.txt:
smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=10 vncinstall ipv4=192.168.1.123/255.255.255.0/192.168.1.1

May I again mention that only the one-line statement as previously mentioned appears on the TV. There's no sign of boot activity as there is when trying to get it going via a keyboard.

**Comment by JohnoPolo** [comment]
Oooooooooppps!!!! Ahem ...! 
I omitted to reconnect the LAN cable .... and now I'm In. Thank you so very much for all the assistance :-)

**Comment by JohnoPolo** [comment]
Sadly, I'm back again. Everything went smoothly and the OS installed and there wasn't any other obvious option except to exit - which I did. When I now fire up the Raspberry, I seem to be in pretty much the same situation as I had been previously - and which I was trying to overcome. The Raspberry boots up and displays a list of options that I am unable to deal with because
a) I don't have a keyboard that works
b) VNC doesn't work now that BerryBoot has done its job.
If you have any suggestions I would be most grateful.

**Comment by maxnet** [comment]
Depending on which OS you installed, you may be able to use a SSH client to login.

http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html
Try user: pi pass: raspberry

**Comment by JohnoPolo** [comment]
Again that was a wonderful bit of advice and I'm pleased to tell you that I'm up and running. Again I thank you profusely for all your assistance and let me leave this forum with a suggestion, 

Seeing as other people who may use BerryBoot could well be in a similar position to me, what about adding a few lines of instructions to the BerryBoot procedure - particularly an explanation of the IP addressing. It would also be useful to include a boot.rc file into the BerryBoot installation if the user selected the appropriate OS. Lastly, a little bit about Putty and where to find it would finish it off nicely.
