### ISSUE TITLE
Compiling from cloned source for Raspi3B results in an image that won't do Wifi

### ISSUE THREAD

**Issue by Bilgus** [maxnet/berryboot#392]
Trying to compile Berryboot directly from git source and I can't get wifi to work on the Raspi 3B? am I missing a configuration or setting? 

I tried both a fresh install and even copying my berryboot.img into a known working install and will not find any networks

The eventual goal is to configure autoshutdown and a bootmenu_minimal directive that allows menu to not be shown till a key is pressed otherwise boots directly into default image similar to windows F8 fuctionality or BIOS DEL/F1 key

**Comment by Bilgus** [comment]
Ok I figured out the issue 
Pretty simple actually:
in /BerrybootGUI2.0/wifidialog.cpp 
change
QProcess::execute("/usr/sbin/wpa_supplicant -s -Dnl80211,wext -iwlan0 -c/etc/wpa_supplicant.conf -B");
to 
QProcess::execute("/usr/sbin/wpa_supplicant -Dnl80211,wext -iwlan0 -c/etc/wpa_supplicant.conf -B");

yep just remove -s in two places (lns: 80, 233)

**Comment by Bilgus** [comment]
For anyone interested here is the diff of changes I made
[berryboot_patch.diff.TXT](https://github.com/maxnet/berryboot/files/923688/berryboot_patch.diff.TXT)

Add bootmenu_minimal and the boot menu stays invisible till a key is pressed otherwise boots the default image (absence of a Default shows window on timeout as well) (also hides Waiting for Data Partition dialog!!)


Allows the setting/unsetting of a default image
if no default is set the first image is no longer automatically started

Fixes wifi issue

**Comment by maxnet** [comment]
>yep just remove -s in two places (lns: 80, 233)

Rather than remove logging, I suggest you enable syslog support in your wpa_supplicant build instead.
You are using a custom version?

**Comment by Bilgus** [comment]
This was with the source I pulled directly from your GIT repo, I even tried replacing my bootberry.img in the official one you had released and still had the same issue?
wpa_supplicant -v lists:
wpa_supplicant v2.5

berryboot/buildroot-2015.02/package/wpa_supplicant/wpa_supplicant.mk even lists WPA_SUPPLICANT_VERSION = 2.5

so some kind of configuration issue? can I change it to -f and push it to its own log or should I change the make file for wpa_supplicant?

**Comment by Bilgus** [comment]
Well Duh, I suppose the img contains the condensed OS so it wouldn't do any good to replace the image.

**Comment by Bilgus** [comment]
OK, The root issue was a configuration setting;
 -s sends debug to syslog and is a patch that has to be enabled in the buildroot configuration script.

First 
Delete wpa_supplicant directory -> 'buildroot-2015.02/output/build/wpa_supplicant'
(this makes buildroot rebuild the package)

Second 
open configuration file 'berryboot/configs/berryboot_defconfig'
locate: 
BR2_PACKAGE_WPA_SUPPLICANT=y
BR2_PACKAGE_WPA_SUPPLICANT_CLI=y

add: 'BR2_PACKAGE_WPA_SUPPLICANT_DEBUG_SYSLOG=y'
(this adds the syslog switch patch)

Third 
run 'rebuild-berryboot.sh' with your device as the argument
(wpa_supplicant will be rebuilt with the -s switch and wifi will work)

Two and 1/2
add bash because busybox shells stink. :) 
BR2_PACKAGE_BASH=y
