### ISSUE TITLE
128gb SD card mounting issue

### ISSUE THREAD

**Issue by twr120** [maxnet/berryboot#399]
Hello, I'm a noob with this stuff but i thought i was on the right track.  I have a raspberry pi 3.  I took a 128gb sdxc u3 card and formatted it to FAT32.  Extracted the berryboot zip contents to the card (the latest build from their site).  Inserted it into the pi and everything seemed to load fine.  I'm on screen two, disk selection.  The sd card does not seem to be appearing.  It says mmcblk0: N/A.  Regardless, i would select it and ext4(notrim/discard) and format.  It goes through the partitioning process and completes. Then an error appears, "Error mounting data partition".  After inserting it into my pc, it appears to have created the partitioins.  What could the problem be?

**Comment by maxnet** [comment]
>I'm on screen two, disk selection. The sd card does not seem to be appearing. It says mmcblk0: N/A

If it did not detected the SD card, there would be no mmcblk0 at all.
"N/A" is the model name the card is reporting.

It's not a name a brand name card would use.
Some white label thing from ebay?

**Comment by twr120** [comment]
SanDisk
![20170514_180403](https://cloud.githubusercontent.com/assets/28692603/26038170/15612612-38d0-11e7-8f4c-fb57de5c24d6.jpg)

**Comment by maxnet** [comment]
Not sure whether or not that is a real one.

In the newer series the 128 GB version is all black: https://www.sandisk.com/home/memory-cards/microsd-cards/extremepro-microsd-uhs-ii
But not sure about previous one.

**Comment by twr120** [comment]
![20170514_183652](https://cloud.githubusercontent.com/assets/28692603/26038363/e474dda0-38d4-11e7-888b-792fa55ead24.jpg)
![20170514_183702](https://cloud.githubusercontent.com/assets/28692603/26038364/e9508dd8-38d4-11e7-96ac-da09cc6e2256.jpg)
Seems legit. Maybe I'll get another card. Do you have any other recommendations?

**Comment by maxnet** [comment]
You can try one of the write test programs mentioned here: http://www.happybison.com/reviews/how-to-check-and-spot-fake-micro-sd-card-8/

**Comment by maxnet** [comment]
Actually, your barcode gets mentioned in the linked story...

```
The printed part number SDSDQX-128G-U46A does not even exist.
UPC is 619659097073 which corresponds to 16GB card.
```

Suggest you send card back to where it came from.

**Comment by twr120** [comment]
Haha, just discovered that myself.  Thank you for all your help.
