### ISSUE TITLE
Adding your own custom operating systems to the menu

### ISSUE THREAD

**Issue by ghost** [maxnet/berryboot#4]
Hello!

First of all i would like to thank you for your awesome tool.

I'm  now trying to add Xbian as operating system.
I followed your (mini) Tutorial on http://www.berryterminal.com/doku.php/berryboot#adding_your_own_custom_operating_systems_to_the_menu

But I'm having problems using kpartx.
This is what I enter in my terminal:

[root@alarm xbian]# kpartx -av XBian1.0Alpha4.img

and this is the result error I get:

add map loop0p1 (254:0): 0 69632 linear /dev/loop0 2048
device-mapper: resume ioctl on loop0p2 failed: Invalid argument
create/reload failed on loop0p2
add map loop0p2 (0:0): 0 1331200 linear /dev/loop0 71680

Which isn't the result like on your tutorial. Does this mean XBian is not compatible?

Thanks in advance!

**Comment by maxnet** [comment]
Double check the partition table of your .img is not corrupt (e.g. the partitions do not overlap, or exceed the size of the .img).

**Comment by ghost** [comment]
How can i check this ? i downloaded it freshly from xbian.org

**Comment by maxnet** [comment]
The image they have on their site is corrupt.

```
$ fdisk XBian1.0Alpha4.img

Command (m for help): p

Disk XBian1.0Alpha4.img: 717 MB, 717225984 bytes
255 heads, 63 sectors/track, 87 cylinders, total 1400832 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000f06a6

             Device Boot      Start         End      Blocks   Id  System
XBian1.0Alpha4.img1            2048       71679       34816    c  W95 FAT32 (LBA)
XBian1.0Alpha4.img2           71680     1402879      665600   83  Linux
```

Partition table says partition 2 ends at sector 1402879.
But the image file is only 1400832 sectors big.

**Comment by ghost** [comment]
Hmm.. ok, so nothing i can do yet?

Thank you very much for your time ;)

**Comment by maxnet** [comment]
> Hmm.. ok, so nothing i can do yet?

Other than tell them to fix their image, no.
