### ISSUE TITLE
BerryBoot won't boot. 

### ISSUE THREAD

**Issue by ConvenientlyNoAnswer** [maxnet/berryboot#40]
Alright so I've already solved the issue, but it took me reading through 10+ pages of BerryBoot issues on other sites so I wanted to post the solution here for anyone else in the future. 

Basically I had BerryBoot fully working, but wanted to do a fresh install. I popped my SD card into my PC, and formated it under FAT using EaseUs which is what I used to format for my original install. Unfortunately when I put it back into my Pi it wouldn't boot up. I probably formated it three dozen times just trying different file systems, different version of BerryBoot, different SD cards, and even manually updating the boot files with copies from the RPi sourceforge. Raspbmc worked fine, Raspian worked fine, but I just couldn't get BerryBoot to go. 

Then I read a post about BerryBoot not working if quick format was used. I didn't even consider that EaseUs was doing quick formats instead of complete formats, because it worked perfect the first time. After that I opened up the basic windows formatter, switched off quick format, and tried again... BerryBoot started... It worked.

**Comment by ConvenientlyNoAnswer** [comment]
Sigh... Looks like I still don't have the issue fully figured out. I had another Pi I was trying to put BerryBoot on. Using a brand new SD card I did a complete format under FAT, and moved the BerryBoot files onto it. Plugged the SD card into my pi, and only got red lights. I tried several other SD cards, and had the same issue. I only manage to resolve it this time by running the Raspbmc installer on my SD card, then using the raspbmc installer to restored to default, and then doing a complete format to FAT. The only two things I can think of at this point are that the windows formatter isn't doing it's job properly, or there's a defect with my SD card writer. Next time the issue happens I'll be trying everything on a different computer, and reporting back.

**Comment by maxnet** [comment]
It should not take any special software.
Just delete the existing files on the card (either by deleting them in explorer, or using the Windows format tool), and copy the Berryboot files over.

Do make sure you do not remove the SD card from your computer too soon, and use the "safe to remove hardware" icon in Windows first.
Also make sure that the files end up being copied to the root folder on the SD card, and not to some subfolder under that (some unzip programs create a separate folder by default, that is not what you want)

**Comment by ConvenientlyNoAnswer** [comment]
I always eject before removing the SD card. I'm not sure where the issue is coming from, but for whatever reason I'm having a LOT of problems. 

Step by step. 
1. I downloaded the latest version of BerryBoot from sourceforge. (I've done this multiple times to make sure the download wasn't the problem.)
2. I format my SD card by going to my computer, right clicking on the sd card drive, clicking format, making sure the format type is FAT, and unchecking quick format, and then clicking the format button to complete a full format. 
3. I use winrar to open the BerryBoot download, and extract all of the files directly to my SD card. 
4. I eject the SD card through my computer before removing it from my PC.
5. I gently insert my SD card into my pi until it won't go any further so I know it's connecting properly.
6. I plug my micro usb into my pi. 

After that I only get red lights, and nothing happens on my screen. 

Eventually I'm going to get another new SD card, and test it with that, but I don't believe that's where the problem is coming from. I'm fairly sure it has to do with the formatting after everything I've tried. The times I do get the SD card flashed properly I have no problems afterward. I can restart my pi, and insert/remove it all I want without issues so I don't think it's a microfracture, or anything like that. 

I'm kind of confused at this point, but I'll keep trying things out, and reporting back. 

I should also mention that I have two pis, and the problem happens on each.

**Comment by maxnet** [comment]
Alternatively you can try writing this image (meant for another device, but include Pi files as well) using a tool like win32diskimager:

http://sourceforge.net/projects/berryboot/files/berryboot-cubieboard-beta6.zip/download

Only case where it should give a better result than just reformatting is when the partition table of your SD card is corrupt though.

**Comment by ConvenientlyNoAnswer** [comment]
I may have spoken too soon about it not being an SD card issue. Although I've tried several SD cards, one of them being new I guess it's possible that they're all corrupted. I had gotten it to boot with one of my SD cards, and installed OpenELEC without any issues, but after shutting down my pi, and moving the SD card, and usb drive to my other pi the SD card didn't want to boot again. I formatted it again first using the raspbmc installer to restore to factory defaults, and then using the windows format tool, and now I'm installing OpenELEC again before seeing if the card will keep working in my other Pi. Afterwards I'm going to try using win32 with the image you provided, and I'll report back. 

I might as well though another quick question in here. When I'm first running BerryBoot, and choosing my installation destination there are two options ext4, and ext4 notrim/discard, Does notrim/discard just mean that it'll leave pervious files intact on the device? 

--edit--

Yup, once again after moving it between my two pis the sd card stopped booting. Giving Win32 a shot now.

**Comment by maxnet** [comment]
No, it doesn't save your files.
It indicates whether to use the ATA TRIM command to tell your SD card that it can throw away all the data on the card.
http://en.wikipedia.org/wiki/TRIM

Letting it know that all existing data can be disregarded (as opposed to just overwriting some parts of the disk without telling the intention) can result in higher performance.
However we found out that sending the command can sometimes causes hangs though, so we default to not sending that.
Still all your existing data is going to be deleted.

**Comment by maxnet** [comment]
> Yup, once again after moving it between my two pis the sd card stopped booting.

Double check the SD card for physical damage.
I also have a couple of which the top left corner has a slight crack, and which my Pi no longer reliably accepts.

**Comment by ConvenientlyNoAnswer** [comment]
Thanks for your help I think I have the issue resolved for now. I think that my sd cards might be at different levels of corruption so what was working for one only worked temporarily for another leaving me confused. One of them will only works temporarily if I use Raspbmc to reset it (I'm throwing this one out), and doesn't seem to work with Win32 disk imager. Another one of my cards also doesn't work with windows format tool, but after using Win32 it doesn't seem to be having any other issues. I'll definitely be picking up some higher quality SD cards this time around. 

Once again thank you for your help.

**Comment by maxnet** [comment]
yw
