### ISSUE TITLE
DNS on cmdline.txt?

### ISSUE THREAD

**Issue by coderxx** [maxnet/berryboot#401]
Everything works out of the box so far including a headless install. However, my internet won't work because I'm using a static IP and I can't find any option to pass a nameserver = 8.8.8.8 in the berryboot commandline.txt.

Right now, I have to boot into my pi and issue manually this command everytime:
        echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf

**Comment by maxnet** [comment]
It actually defaults to 8.8.8.8 for static IPs.
At least within Berryboot. What operating systems you install use is outside our control.

**Comment by coderxx** [comment]
@maxnet - As I mentioned, not in my case. I have a startup script doing that in /etc/rc.local on every boot.
My question was, how do I control which nameserver during boot?

**Comment by maxnet** [comment]
Again, Berryboot itself will use 8.8.8.8
Consult the documentation of the operating system you installed to figure out how to change settings there.
