### ISSUE TITLE
Please, update BB to run OS from USB stick

### ISSUE THREAD

**Issue by lucaisi** [maxnet/berryboot#404]
I was able to boot from USB, but I got stucked when I choose my USB device to install OS.

Since the last update (2017-04-10), NOOBS and Raspbian standalone works just fine, but I want to use BerryBoot. Please, fix this...

Raspbian standalone & NOOBS changelog (2017-04-10):
  * Use PARTUUID to support USB boot

**Comment by maxnet** [comment]
>I was able to boot from USB, but I got stucked when I choose my USB device to install OS.

Stuck in what way?

USB boot has been supported for quite a while.
https://github.com/maxnet/berryboot/commit/776c383c49ee1fdcfe288fdf7143a89e31c1b89b

**Comment by lucaisi** [comment]
Sorry I'm a noob... Tomorrow I'll post a screenshot of the error message. In the title of that thared you posted it says Berryboot v2.8, I'm using BB 2.0 from berryterminal website, how can I download this newer version?

**Comment by maxnet** [comment]
Image on the website is fine.

Just make sure you do use a SD card to do the initial installation, and put ``program_usb_boot_mode=1`` in config.txt, even if USB boot was already activated previously.

**Comment by lucaisi** [comment]
It Works!!! I first installed using a SD card and now it works :) Sorry about that...
