### ISSUE TITLE
OS Images from FAT32 IDE USB HDD "not in squashfs format"

### ISSUE THREAD

**Issue by ghost** [maxnet/berryboot#405]
Hello,

I had a problem with berryboot. I´ve downloaded the converted images and drag them onto a 2,5 IDE USB HDD. There a two partitions:

The first one is about 8GB formatted in FAT32 for the images; the second one about 30GB ext4, the installation partition for berryboot.

I was able to select those images but berryboot said "image is not in squashfs format". 

Okay... went to the shop and bought a USB Stick. Formatted in FAT32 and everything worked. 

What is wrong with my partition on the HDD? Is there a conflict cause berryboot will load and install from the same device at the same time?

Would be happy for answers. Please apologize my bad English.

Greetings from Germany

**Comment by maxnet** [comment]
If you happen to be using Linux on your normal desktop, just copy the image file directly to /images on the ext4 partition.

**Comment by ghost** [comment]
Okay,

I will try it out and will let u know ASAP.

**Comment by ghost** [comment]
Hey,

I've copied via ssh on raspbian to the ext partition, that worked for me. Thanks a lot.
