### ISSUE TITLE
gpu_mem memory split by image name: bug?

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#411]
Using a PiZero (512MB) with berryboot (default `config.txt` with `gpu_mem=160`).
I'd like to run one image with 16MB gpu_mem, so I initially named that image by`image.img16`
Once booted I got:
```
$ sudo vcgencmd get_mem gpu
gpu=160M
$ sudo vcgencmd get_mem arm
arm=352M
```
So I went to berryboot UI and selected image info, and with pull-down menu, selected gpu_mem=16.
It renamed my image `image.img240`!
once booted, I had again:
```
$ sudo vcgencmd get_mem gpu
gpu=160M
$ sudo vcgencmd get_mem arm
arm=352M
```
So, it seems whatever the name convention, it runs with `config.txt` setting...

Any advice to run that image with 16MB gpu_mem?
Thanks!

**Comment by maxnet** [comment]
vcgencmd matches with what is in config.txt?
It is supposed to update config.txt

**Comment by macmpi** [comment]
yes `vcgencmd get_mem` does report same value as ones set in original `config.txt` as described; not what is set through image name.
`free` also confirms RAM is not allocated as expected (confirms the arm part of `vcgencmd get_mem`).
Thanks for suggestions/fix, so that split defined as per image name is actually set.

**Comment by macmpi** [comment]
@maxnet can you replicate this issue?
How can I run a specific image with gpu_mem 16MB please?

**Comment by macmpi** [comment]
It seems there's indeed yet-another Pi-detection bug within [`isMemsplitHandlingEnabled()`](https://github.com/maxnet/berryboot/blob/berryboot2015/BerrybootGUI2.0/installer.cpp#L843) routine, consequencial from these `cpuinfo` values changes for Pi models under 4.9.x kernel, like for earlier [CEC](https://github.com/maxnet/berryboot/commit/d8a1a988bf2d34dcb3590d112271a85f462de3e6) issue.

BTW you may want to check/adapt all `cpuinfo` related tests (overscan, etc...)

(while at it, I think I spotted 2 typos referencing [CCM](https://github.com/maxnet/berryboot/search?utf8=%E2%9C%93&q=CCM&type=) rather than CMA I guess)

**Comment by macmpi** [comment]
How about just testing `cpuinfo.contains("BCM2835")` to identify Pi devices in every place now, since all models now report same BCM2835 string?

Other values were in pre 4.8 kernel: I guess it's very unlikely Berryboot will go back to lower kernel than 4.9.x now, right?
