### ISSUE TITLE
improve gpu_mem allocation granularity

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#413]
For some reasons [memsplitParameter](https://github.com/maxnet/berryboot/blob/berryboot2015/BerrybootGUI2.0/bootmenudialog.cpp#L771) seems to be bound to just a few select possible values (240, 224, 128, 256 , other) respectively corresponding to (16, 32, 128, 256, 64)`gpu_mem` values.
(and those former possible value are consistent with current image naming conventions).

While not disrupting compatibility with this "original model", would it be possible to offer an additional (slightly different) image naming convention which would allow to name images directly by actual `gpu_mem` values, and allow whatever number users chooses to name them with?

For instance one could name OpenELEC/LibreELEC image with some form of `160` suffix and obtain `gpu_mem=160` at runtime.
This would be a much more direct method, offering full control to users needing to.

Thanks for consideration.

**Comment by maxnet** [comment]
Memory splits have only been supported on the Pi 1

On later models there is enough memory to always allocate 160 MB.
Problem with the memory split changing all the time is that it often corrupted FAT partition of SD card. So best not to have it at all.

**Comment by macmpi** [comment]
160 value was just an example value here to show we may want/need full granularity!...
They are cases where memory splits are needed still: there is no possible one split fit-them all, and I do not think one can predict them all in cases statements.

Berryboot is really great in allowing to run multiple different images from one single SD (or USB/iSCSI): allowing splits is much needed feature to keep each image within it's optimal memory boundaries. (BTW [fix needed since 4.9](https://github.com/maxnet/berryboot/issues/411#issuecomment-309681365))

Users may not switch images that often, and may just use names without RAM split statement in most cases, so `config.txt` write operations may not happen that much and be that critical for SD lifespan. Still having giving such flexibility for images that require specific split is important.

Your users are probably smart enough to gauge where their principal benefits are, understand eventual trade-offs (thanks for pointing them), and make their educated decision from these: it is probably good to give them options, even if you may have different usage.
I hope Berryboot becomes even more powerful with some open consideration about users needs and feedback (also thinking about custom images updates...): thanks in advance.

**Comment by macmpi** [comment]
@maxnet 
> Problem with the memory split changing all the time is that it often corrupted FAT partition of SD card. So best not to have it at all.

Maybe enabling cma in default `cmdline.txt ` can help, right?
Would it then be meaningful to add `coherent_pool=6M smsc95xx.turbo_mode=N` into it?
(while boundaries setting `cma_`* in `config.txt` is not supported)

**Comment by macmpi** [comment]
well, it looks like CMA is just gone for good from kernel 4.9.57!... https://github.com/raspberrypi/linux/pull/2233
