### ISSUE TITLE
Resize/expand

### ISSUE THREAD

**Issue by symbios24** [maxnet/berryboot#414]
Hello, there i`m jim

i made an image with berryboot on a 8gb card  then i write the image from my computer with win32diskimager to a 16gb card but the extra space is not available only 8gb is available, is there a command i can put/edit in the config.txt or in the cmdline.txt file to autoresize the berryboot image as the first time installation?

Thank you

**Comment by maxnet** [comment]
Use a tool like gparted

**Comment by symbios24** [comment]
i know that but i want to autoresize on first boot like it does on first install is it possible ?

thanks
