### ISSUE TITLE
/lib/lib ?

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#417]
Incidently noted berryboot's `lib` directory is enclosed into finally mounted `/lib`: it may be mounted twice.
`/lib` overlay seems ok, but `/lib/lib` is duplicate.

For instance under provided raspbian lite image:
```
pi@raspberrypi:/lib $ ls
arm-linux-gnueabihf                   libiptc.so.0
cpp                                   libiptc.so.0.0.0
crda                                  libnih-dbus.so.1
dhcpcd                                libnih-dbus.so.1.0.0
firmware                              libnih.so.1
ifupdown                              libnih.so.1.0.0
init                                  libxtables.so.10
klibc-YL2Pal4e_FwRI58JJ6S97Xf241g.so  libxtables.so.10.0.0
ld-linux-armhf.so.3                   lsb
ld-linux.so.3                         modprobe.d
lib                                   modules
libip4tc.so.0                         resolvconf
libip4tc.so.0.1.0                     startpar
libip6tc.so.0                         systemd
libip6tc.so.0.1.0                     terminfo
libipq.so.0                           udev
libipq.so.0.0.0                       xtables
```
(note enclosed `lib `directory)
and moving into it: 
```
pi@raspberrypi:/lib/lib $ ls
firmware  modules
```
Have same with other images...

**Comment by maxnet** [comment]
Unable to reproduce

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.26v7-aufs #1 SMP Tue May 9 20:14:03 CEST 2017 armv7l GNU/Linux
pi@raspberrypi:~ $ ls /lib/lib
ls: cannot access /lib/lib: No such file or directory
```

**Comment by macmpi** [comment]
using berryboot-20170527-pi0-pi1-pi2-pi3 (updated over previous as per https://github.com/maxnet/berryboot/issues/371#issuecomment-305325114), and this image https://sourceforge.net/projects/berryboot/files/os_images/Raspbian_Lite_2016.03.img192/download

Could the update procedure duplicate lib directory then?

**Comment by maxnet** [comment]
Did you perhaps try to manually extract shared.tgz to the ext4 partition, and accidentally extracted it to /shared/lib instead of /shared?

**Comment by macmpi** [comment]
No did not extract manually.
Just copied-over files on SD, preserved my cmdline.txt and config.txt, let BB redo the init selecting "use existing files".

Indeed things got duplicated:
```
# pwd
/mnt/shared/lib
# ls
firmware  lib       modules
```
unsure which one is correct. Maybe both are same between 20170527 and previous 20170509

**Comment by maxnet** [comment]
>unsure which one is correct.

So what do the dates say if you do `ls -l` ?

**Comment by macmpi** [comment]
Compared `firmware` and `modules` folders with `diff`, and they appeared to be the same at the 2 levels.
So I deleted the enclosed one, and all seems fine.

unsure there may be an issue in the install/update procedure?

**Comment by macmpi** [comment]
Closing; will reopen if it shows-up again at next update.
