### ISSUE TITLE
Installing Raspian to USB-stick

### ISSUE THREAD

**Issue by Max11223344** [maxnet/berryboot#422]
Hello,
i like berryboot, but now there is a problem:
I installed Berryboot 20170527 on my sdcard and defined to install all OS to an USB stick.
Ubuntu Mate 16.04 runs perfect
Openelec 8.0.3 runs perfect
Debian Jessie Raspian 2017.06 starts and gives a message
a start job is running for dev-mmcblk0p1.device (this runs for 1 min 30 seconds)
then
Dependency failed for boot
Dependency failed for local file system
Dependency failed for file system check on /dev/mmcblk0p1

 and finally defaults to root..

What can i do?

**Comment by Max11223344** [comment]
In addition to the above:
I always started Berryboot from the USB-Stick - without inserting the SD Card.
So without SD-Card:
Ubuntu Mate and Openelec function, Jessie needs the SD-Card ... 
Can somebody explain why?

**Comment by maxnet** [comment]
Boot with SD card once, comment out the /boot entry in /etc/fstab

**Comment by Max11223344** [comment]
Thanks!
It is working now.
