### ISSUE TITLE
Bump Pi release with kernel 4.9.65

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#426]
Hi,

Would it be possible to release Pi packages with more recent kernel (4.9.41)?
Indeed lots of improvements have occurred since previous release, particularly around i2s DACs.

Longer-term, any chance Pi versions could be built solely on `overlayfs` rather than `aufs` as discussed [here](https://github.com/maxnet/berryboot/issues/201#issuecomment-314040425): this would make such kind of kernel updates really easy for Pi community.
Thanks for consideration.

**Comment by macmpi** [comment]
4.9.51 has been flagged as stable

**Comment by macmpi** [comment]
@maxnet there have been huge lot of [kernel improvements](https://github.com/Hexxeh/rpi-firmware/commits/master) since May, last berryboot build.

Would you mind re-releasing with such fixes (`4.9.65` now fixes important USB-Serial issues for instance)? ...and eventually cram-in `busybox wget` https support in the process :)

Thanks for support

**Comment by alfieoriginal** [comment]
It would be great

**Comment by alfieoriginal** [comment]
Hello, any update on this?
Thanks for support

**Comment by alfieoriginal** [comment]
@macmpi did you get to compile any new Berryboot img for pi2? Just in case

**Comment by macmpi** [comment]
Nope, not yet: had hoped some maintenance update would appear (simultaneously fixing some other issues), but I fear this may take significantly longer to eventually emerge.
Unsure I'll manage to find time to setup a build environment and compile one (for Pi0) unfortunately.

I'm afraid such increasing kernel version gap will cause more & more issues & compatibility problems with many OS distributions (LibreELEC, Volumio2, Raspbian, etc...), making berryboot approach hardly sustainable in next few months.

**Comment by macmpi** [comment]
Closing as today's release moved to 4.14.x
Thanks.
