### ISSUE TITLE
I want to install my own img into berryboot ,how can I make it?

### ISSUE THREAD

**Issue by Vondark** [maxnet/berryboot#427]
I want to install my own img into berryboot, how can I make it ?

The website says:
“Add OS” (or CTRL+A on keyboard, red button on TV remote)
Single click to download additional operating systems from the Internet.
Hold down your mouse button over the “Add OS” button and select “copy OS from USB stick”, to install an operating system saved on USB stick.

Does it mean the system is copied into sd card , or the system is still in the USB stick and I have to use USB stick everytime?

**Comment by maxnet** [comment]
It is copied (as advertised "**copy** OS from USB stick")
