### ISSUE TITLE
Wifi Issues

### ISSUE THREAD

**Issue by HcNguyen111** [maxnet/berryboot#43]
- Wifi works in Berryboot OS downloader no matter what is set in Network Settings.
- Wifi does NOT work for ANY OS when it is set as DHCP in Berry Menu Editor (even vncinstall does not start up a VNC Session) (the dongle does not even start blinking when starting any OS) (Add OS still works).
- When set as static, the dongle starts, can scan and detect networks but cannot connect. (Tried official: RaspBian Wheezy, Puppy, OpenELEC and unofficial: RasPLEX).
- The only OS that does work (when set as static in Berry Network Settings) is BerryWebServer.

Dongle Used: RT8188CUS (widely used Raspberry Pi Dongle, included in linux kernel, etc.)
NOTE: This dongle works on NON-Berryboot SD Cards.

Berryboot Version: berryboot-20130528

**Comment by maxnet** [comment]
What software/commands do you use to configure the wifi inside the operating system?

**Comment by HcNguyen111** [comment]
Exactly the same as on non-berryboot:
- Wheezy: "WIFI Config" app, scan, enter PSK, connect.
- OpenELEC: use Built-in settings plugin, same as above.
- Puppy Linux: "Connect" app, same as above.

**Comment by Shapen** [comment]
I have a number of Wifi dongles.
Berryboot works with most of them but they don't always work with the target OS
E.G.  Openelec won't load with my elephant14 wi-pi but works fine with a micronext MN-WD152B 
Berryboot sees both.

**Comment by Quihico** [comment]
Had issues too, was using wireless-headless install but still could not get succesfull connection on openelec with any of my 3 wifi dongles.
I deleted the headless parts from cmdline.txt and openelec connected straight away.
Still had trouble mounting NFS from XBMC but that was fixable with autostart.sh (google: openelec automount nfs).
Also got succesfull wifi with RbejELEC (both Frodo and Gotham) but only if you start with either 1st may build (gotham) or 11th may build (frodo) and configure wifi before updating and even then settings are not changeable unless you downgrade-change-upgrade.
Also: at first I could not get the gpu-mem over 128 mb. Had to comment out cma_lwm=16, cma_hwm=32 and cma_offline_start=16 before gpu_mem_512 setting would stick, now at 320. 
Made backup, burned it to usb and got it stable at 1050 = 50 % overclock, nice

**Comment by profi248** [comment]
For me WiFi worked for first boot, after that wasn't even in Puppy alpha 4

**Comment by maxnet** [comment]
Closing old wifi issues. Try again with latest version.
