### ISSUE TITLE
berryboot-init: get to know its own environment

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#435]
When `berryboot-init` is invoqued within an image, there does not seem to be a simple way for it to know which image file has been mounted.
It would be very useful in some case (to manage image updates for instance, modify files in relevant `/mnt/data/<image>`, ...)

`/tmp/answer` is wiped too early so that this information is available at that point.
Could you let that file survive post [this](https://github.com/maxnet/berryboot/blob/berryboot2015/buildroot-2015.02/package/berrybootgui2/init#L100), or modify the line to invoke the script as:
`. berryboot-init ${IMAGE}`
(Note: this would obviously be backward compatible with pre-existing `berryboot-init` scripts, as they currently do not read such input parameter).

Thanks for consideration.

**Comment by maxnet** [comment]
Isn't $IMAGE available inside the script?
Thought the . means "inline the contents of the script here" ?

**Comment by macmpi** [comment]
ooops, my bad !
quite smart indeed.

While at it, maybe you have some trick to solve a related problem.
I'd like, through `berryboot-init` find a way to craft a "backdoor" so that my finally booted system can access to `/mnt/data` and `/mnt/images` from a `/berryboot` directory.
I tried to create symlinks, or mount binds, but none seem to survive the aufs overlay recomposing.
Would you have any idea?

Thanks.

**Comment by maxnet** [comment]
Just doing `mount LABEL=berryboot /berryboot` in a startup script inside the OS isn't an option?

**Comment by macmpi** [comment]
That's what I'm doing currently, but I'm not found of this sort of double mount (as `/mnt/data/$IMAGE` is already there and live).
Also there could be issues is another disk on the USB chain has same label (or other "weak" criteria chosen for mount: or we need to explore and then pass UUID...).

So using the existing mounts from `initrd` is quite appealing...if at-all possible: would also be transparent if partition on SD, USB, iSCSI

**Comment by macmpi** [comment]
Mounting inside OS would be particularly difficult if partition is encrypted too...
All this seems to lead to rely on original `bootmenudialog.cpp` `datadev` mount available in `inird`.

So, if one can't find a way to code a redirection method into `berryboot-init`, to allow `/mnt/images` (and eventually `/mnt/data`) access from within `/mnt/data/$IMAGE` mounted into `/` in OS image, could you please consider adding a `/berryboot` `rw` directory with such access(es) in the original aufs overlay composition?

Together with PR https://github.com/maxnet/berryboot/pull/437 (or similar), it would definitely allow to make automated custom images updates out-of `berryboot-init` feature, which would really ease end-user experience with berryboot.

Happy to hear if you think there are other better options.

**Comment by macmpi** [comment]
In case this may help others, mounting the right berryboot folder (the one currently used) in all cases (SD, USB, including for encrypted partition, iSCSI) can be achieved by finding target device partition within `berryboot-init` with:
`df | egrep "/mnt" | awk '{print $1}'` and then mounting it at OS boot.
(putting it in `fstab` entries in OS overlay filesystem will block boot in case of encrypted partitions) 

Still, current `berryboot-init` invocation scheme prevents unmounting image (for updating image, etc). Redirection like in PR #437 would definitely help!

Thanks
