### ISSUE TITLE
Network issues during iSCSI boot

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#436]
I noticed a networking issue during initial setup of devices.

I have a PiZero that gets network connectivity with a USB Ethernet dongle (ASIX AX88772).
While It works very well once berryboot's initial setup is done (can do Add OS, and download images), network will not work at all during the initial setup wizard!...
So it is impossible to add images right away, but all is fine after a reboot (and connection is shown at bottom a screen).

It's generally not so much a big deal (just costs an extra reboot), except if one wants to setup an iSCSI environment: It fails after a sooooo looooooong timeout in iSCSI connection, probably due to missing network...
Interestingly, I tried to trick the setup, and do a normal initial setup (with USB datadev), get things rolling (remotely installed raspbian).
Then I changed to `datadev=iscsi` in `cmdline.txt`, and set the proper `iscsi.sh` command (tested OK previously with the USB datadev and playing with it on rapbian).
At startup, berryboot then uncompresses iscsi drivers and...won't be able to establish network again.

I changed `datadev` back to USB: and all is working fine, including network.

So there seems to be issues to enable some networking drivers @ install or during iscsi operations.

**Comment by maxnet** [comment]
We do not load any drivers for cabled network installations to save time, as normal Raspberry Pi users would use the on-board network card.

You may be able to trick it to load drivers by selecting you want wifi first.

**Comment by macmpi** [comment]
ok, will try, thanks.
However, with the significant number of PiZero out-there (and such ab-normal Pi users :p), could you consider a change in that driver load strategy?
How is there a load-time penalty during install, and not during normal use (which leverage such drivers?
Is that time really unacceptable compromise for install operation that only happens once in a while?

Thanks.

**Comment by maxnet** [comment]
After install the modules are available as individual files on the ext4 file system.
Before install only as a huge tarball that needs to be extracted to memory first, before files can be accessed.

**Comment by macmpi** [comment]
Thanks for the explanation: it's crystal-clear.
Your proposed workaround works great, thanks !!!  It's a good trick to know.
(BTW loading driver on my PiZero just took about 10sec)

**Comment by macmpi** [comment]
In the context of iSCSI, it's not 100% bullet-proof though...
Install works fine with your trick, but follow-up starts get stuck: it seems it uncompresses iscsi drivers, but does not the networking ones: it gets endlessly into "waiting for network to be ready"... (or possibly very loooong time-out)

**Comment by macmpi** [comment]
Note: in environments with encrypted partitions, network drivers are adequately decompressed during normal startup, unlike in the case of iSCSI.
Would be nice to do same in the context of iSCSI, as it is critical for such network-dependent setup.
Thanks.

**Comment by Benoit7413** [comment]
It's because when berryboot starup it doesn't load the drivers for iSCSI boot.
A workaround would be to load driver on the SD card with an EXT4 partition before running on iSCSI.

I'm wondering if I can do something like : 
mount /dev/sda2 /tmp/mount
modprob /tmp/mount/share...
ifup wlo0
/sbin/iscsistart ...

in the iscsi file.

**Comment by Benoit7413** [comment]
Maybe by editing those lines 
`void BootMenuDialog::startISCSI()
{
    loadModule("iscsi_tcp");

    QProgressDialog qpd(tr("Waiting for network to be ready"), QString(), 0, 0, this);
    connect(_i, SIGNAL(networkInterfaceUp()), &qpd, SLOT(close()));
    while (!_i->networkReady())
    {
        _i->startNetworking();
        qpd.exec();
    }

    qpd.setLabelText(tr("Connecting to iSCSI SAN"));
    qpd.show();
    QApplication::processEvents();

    mountSystemPartition();
    if (system("sh /boot/iscsi.sh 2>/dev/null") != 0)`

**Comment by macmpi** [comment]
thanks!
