### ISSUE TITLE
Installing went wrong with 8 Gb USB stick.

### ISSUE THREAD

**Issue by blooper65** [maxnet/berryboot#44]
After booting Rpi with 2GB SD card and 8Gb USB stick I got error message saying formatting USB stick failed. When I connect the USB stick back to a Windows XP machine it said the stick wasn't formatted and needs to format. But this is not possible, because it is write protected now. How can I take away this protection? It seems that Berryboot did this, because it is not possible to disable the write protection under Windows. And I don't have Linux or Linux skills to do it. The USB stick is new and formatted with SDFormatter before I used it with Berryboot. Any suggestions?

**Comment by maxnet** [comment]
Means your USB stick is broken.
Flash storage can only be written to a limited number of times.
