### ISSUE TITLE
runonce does not let networking settle

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#442]
It seems when image startup is fired-up with `runonce` file, that it launches so quick that networking stack may not be fully up.
I confirmed that issue with `wget`-ing sth in a `berryboot-init` file: `wget` fails (no address found) when launching with `runonce`, but works when launching via menu (or `ssh`-ing the commands to `berryboot` while waiting in menu)
Thanks for a fix.

**Comment by maxnet** [comment]
Cannot wait for that.
Can take ages if connected to a managed Ethernet switch that has STP enabled.

**Comment by macmpi** [comment]
Sure, but it seems in case of `runonce`, [initialization phase does exit very early on](https://github.com/maxnet/berryboot/blob/berryboot2015/BerrybootGUI2.0/bootmenudialog.cpp#L198), for instance even before sound modules are loaded, etc...

Could `runonce` feature enjoy the same complete init phase as if UI was brought-up, but just kicks-in without showing the UI (a bit like if timeout timer value was always ignored and set to 0 with `runonce` image)?
For consistency, would be desirable images are always loaded with very same complete initialization phase whatever selection method (direct via menu, `default`, or `runonce`).

**Comment by maxnet** [comment]
There is no way you have a functional network in 0 seconds,
And it can take a very long time.

**Comment by macmpi** [comment]
I understand that. However, it seems the issue is actually more profound than a "waiting" problem on networking, as other stuff (sound,...) do not seem to go though complete initialization, as it is the case when image picker comes-up: so there's more into this than just waiting long-enough.
Is it possible to fix this initialization at startup so that it is the same in all cases (pick-list, default, runonce)?
Then I'll manage the "waiting" bit separately.
Thanks.

**Comment by maxnet** [comment]
Well, you could start udevd manually.
But it should be killed before the main OS starts, as it will conflict with their version...

Same with the dhcp client software.
It must be dead before OS starts. So we should not leave it running.

**Comment by macmpi** [comment]
So it looks like one should not consider`runonce` mode as:
"please launch my image quicker in **usual state**, just avoiding UI picker"
but rather as:
"a quick launch mode with some little (albeit different) initialization"
Right?
From a user standpoint expectation is probably the former, but it seems it is not intended that way.

Such discrepancy makes it hard to know for sure in which state images are run according to launch method. Do I read right that it is not intended to change?
Thanks.

**Comment by maxnet** [comment]
Actually, do not do any initialization was the usual state, until some releases ago.
Thought I could let it load drivers while the user is staring at the boot menu as an optimization.

Problem is that there is no indication when loading has finished.
So what you want would need arbritrary long sleeps.

**Comment by macmpi** [comment]
Yes would definitely be great to have consistency on drivers loading (for instance they are loaded when using encrypted volumes, but not in iSCSI case!).
Wouldn't it be quicker to load if they were in an squash image in boot partition rather than in a .tgz archive?

**Comment by maxnet** [comment]
They are normally available extracted on the ext4 partition.
However it still takes several seconds before USB devices are enumerated, which in turn may ask for extra firmware to be loaded, etc.

And if you want network connectivity it can take 30+ seconds.

**Comment by macmpi** [comment]
> They are normally available extracted on the ext4 partition.

In case of iSCSI that is not the case: would be great if driver load in those cases are better covered, be it when UI is shown at least (drivers decompressed in encrypted partition case, but not iSCSI).

> However it still takes several seconds before USB devices are enumerated, which in turn may ask for extra firmware to be loaded, etc.

Ok. Assuming `berryboot-init` takes care of the waiting part if it really needs a feature then (like network): can we at least ensure drivers files are available to be loaded in all cases (UI, no UI, runonce, whatever partition layout, iSCSI, encrypted)?

**Comment by maxnet** [comment]
>In case of iSCSI that is not the case: would be great if driver load in those cases are better covered, 
>be it when UI is shown at least (drivers decompressed in encrypted partition case, but not iSCSI).

Last time I checked iscsi required use of the iscsi_tcp kernel module...
So yes, they do are extracted in that case.

>Ok. Assuming berryboot-init takes care of the waiting part if it really needs a feature then (like 
>network): can we at least ensure drivers files are available to be loaded in all cases (UI, no UI, 
>runonce, whatever partition layout, iSCSI, encrypted)?

You are welcome to start "udevd" yourself, run "udevadm trigger", let that load the drivers, and wait an unknown time for that to be finished.
Just don't make any assumptions about that being done for you.

**Comment by macmpi** [comment]
> Last time I checked iscsi required use of the iscsi_tcp kernel module...
> So yes, they do are extracted in that case.

In fact, in iSCSI case network drivers are loaded fine during initial install, but are NOT during follow-up starts (for image selection with UI): therefore after fine install you may get totally stuck right at first reboot if using a (install-supported) dongle for instance !...

> Just don't make any assumptions about that being done for you.

Still one key remaining assumption is: driver/firmware files availability in all cases: can this happen?
But got it that `runonce` is not "faster standard boot with image auto-selection" as I assumed, but rather a "barebone startup".

**Comment by maxnet** [comment]
>Still one key remaining assumption is: driver/firmware files availability in all cases: can this happen?

The module files are accessible in all cases, in either ${SHAREDDIR}/lib/modules or ${SHAREDDIR}/usr/lib/modules
Up to you to make sure they are loaded.

**Comment by macmpi** [comment]
sure, as long as you can mount ${SHAREDDIR} !...
This is not the case in iSCSI as we need drivers to mount iSCSI partition containing them!
(in case of luks, which "could" have same issue, drivers are appropriately loaded)
So it seems we have a bug in iSCSI scenario as noted here https://github.com/maxnet/berryboot/issues/436#issuecomment-333664518

Can you please double-check iSCSi case, not using default ethernet HW, but rather something like asix ethernet dongle.
asix driver is part of BB release, and it DOES work for initial iSCSI setup (clicking onto "wireless drivers" to get it loaded), but then after reboot and normal start, it is not loaded anymore!...
(same issue with any other driver most probably)

**Comment by maxnet** [comment]
well, your issue is about berryboot-init
If it can start that, you have access to SHAREDDIR...

**Comment by macmpi** [comment]
nope iSCSI is a specific problem as I do not even reach that point, as nothing gets mounted !
Even without `runonce`, UI gets stuck (with no timeout) with searching for network: that's where missing driver files hits

**Comment by macmpi** [comment]
closing this, but @maxnet can you please avise on the iSCSI problem here https://github.com/maxnet/berryboot/issues/436
