### ISSUE TITLE
Extending USB HID support

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#445]
Could you please enable [few more](https://github.com/maxnet/berryboot/blob/berryboot2015/configs/kernel_config_fragment_berryboot#L22-L54) popular USB HID kernel drivers (extending Logitech coverage, Thrustmaster, Sony & al., eventually some BT ones)? 

This would really improve experience in gaming images such as Retropie, Lakka, & al: [sample definitions here](https://github.com/libretro/Lakka-LibreELEC/blob/Lakka-V2.1-dev/projects/RPi/linux/linux.arm.conf#L2981-L3070)
Thanks.

**Comment by maxnet** [comment]
>eventually some BT ones

We do not have any support for pairing in Berryboot itself...

**Comment by macmpi** [comment]
At least the USB ones, that would be a big +: thanks in advance!

About BT ones, if we assume OS image provides pairing support, I guess we still need the berryboot-compiled drivers, right?
Pairing also needs to be specifically compiled?

**Comment by maxnet** [comment]
We already should have those drivers as modules. So should be available under the OS started.
Modules are not used within Berryboot though.

**Comment by macmpi** [comment]
Yes modules are not of much use within berryboot (though could eventually help for image selection with joypad): we just need them to be readily available for OS use.

Currently my Logitech rumblepad2 does not work in Lakka under berryboot, though it works on native Lakka. So I guess missing `CONFIG_LOGIRUMBLEPAD2_FF=y` in berryboot kernel is the cause...
Probably same for several others.

**Comment by maxnet** [comment]
The fragment file only contains the differences to standard config.
The standard config has some HID modules as module, which mean they wouldn't work in the Berryboot UI itself as at that point modules are not loaded yet. So we differentiate from standard config, and turn them always on.


CONFIG_LOGIRUMBLEPAD2_FF=y is already present in the standard config though (  https://github.com/raspberrypi/linux/blob/rpi-4.9.y/arch/arm/configs/bcm2709_defconfig )
So we should already have that.

**Comment by macmpi** [comment]
Ok, thanks.
Must be sth else at play then... will dig more.
Closing.
