### ISSUE TITLE
Custom repo support

### ISSUE THREAD

**Issue by prae5** [maxnet/berryboot#45]
Hi,

I cam across berryboot a few hours ago and it looks great. I want to use it for allowing users to install testing / nightly builds.

I've looked through the code and it looks like berryboot pulls its image details from http://dl.berryboot.com/distro.zsmime - I'm assuming this is a compress version of http://dl.berryboot.com/distro.smime

Would you be willing to share the script you use for creating the zsmine file so I can point it at my repo? If not a few pointers in what I need to do?

Many thanks

**Comment by maxnet** [comment]
You will need to write your own tool for that.
Compression method is qCompress: http://qt-project.org/doc/qt-5.0/qtcore/qbytearray.html#qCompress

To point to a custom repository.
On the FAT partition of the SD card:
- Create a file called berryboot.ini

```
[repo]
url=http://your-server.com/distro.zsmime
```
- Create a file called berryboot.crt with the public key/certificate used to sign the distribution list.
