### ISSUE TITLE
Exporting an image+Data

### ISSUE THREAD

**Issue by symbios24** [maxnet/berryboot#450]
Hello is it possible to add this feature back when exporting an image with data to have the option to compress it? right now it has only the option uncompressed.

Thank you

**Comment by FarkasJoseph** [comment]
Good post! I agree!

**Comment by symbios24** [comment]
i agree to but i dont see an answer

**Comment by symbios24** [comment]
Anyone???

**Comment by symbios24** [comment]
Can this option be implemented to Berryboot "exporting image+data compressed"??
