### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by blub4747** [maxnet/berryboot#451]
Hi guys,

I am trying add convert Dietpi with mksquashfs so i can add it to my own personal berryboot.
When tyring to convert the image with the following commands 
sudo mksquashfs /mnt converted_image_for_berryboot.img -comp lzo -e lib/modules
which I got from here 
http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions 
on my fresh Debian 9 install I keep walking into the follow error msg.

`mksquashfs` /mnt my_DietPi_v150_RPi-armv6-Jessie.img -comp lzo -e lib/modules
`Parallel mksquashfs: Using 4 processors
`Creating 4.0 filesystem on my_DietPi_v150_RPi-armv6-Jessie.img, block size 131072.
`[========================\                                                                                                                                   `]  1965/12246  16%
`Write failed because No space left on device

`FATAL ERROR:Failed to write to output filesystem
Could someone please tell me how to resolve this problem ?
thx, blub4747

**Comment by symbios24** [comment]
Hello, try debian jessie to convert it debian strech might have some incompatibilities.

**Comment by blub4747** [comment]
Thx guys
