### ISSUE TITLE
Request: Please add DietPi to the official list of Berry Boot projects

### ISSUE THREAD

**Issue by blub4747** [maxnet/berryboot#452]
http://dietpi.com/

Lightweight Justice
DietPi is a extremely lightweight Debian Jessie OS. With images starting at 400MB, thats 3x lighter than 'Raspbian Lite'.

Truly Optimized
DietPi is highly optimized for minimal CPU and RAM resource usage, ensuring your SBC always runs at its maximum potential.

Simple interface
DietPi programs use lightweight Whiptail menu's. You'll spend less time staring at the command line, and more time enjoying DietPi.

DietPi-Software
Quickly and easily install popular software thats "Ready to run" and optimized for your system. Only the software you need is installed.

DietPi-Config
Customise your device's hardware and software, your way. A tweakers wet dream!

DietPi-Backup
Quickly and easily backup or restore your DietPi system.

etc

**Comment by symbios24** [comment]
Here you go.

https://sourceforge.net/projects/berryboot-updated-images/files/Raspberry-Pi/dietpi_v150_all_rpi_2017.05.26_berryboot.img.tar.xz/download

**Comment by blub4747** [comment]
This awesome! Thx guys!
No more sdcard juggling! :)
