### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by Yoshi325** [maxnet/berryboot#453]
Making this Issue to gauge interest. I am willing to do the work and create a Pull Request with the changes needed to support macOS. Is there any interest in this, or do you have anything against it @maxnet ?

**Comment by maxnet** [comment]
There is macOS for Pi?

**Comment by Yoshi325** [comment]
Sorry, I should have been more specific. My thought was to enable `build-berryboot.sh` to be run on macOS, (that way I don't have to keep a linux VM around to run it).

**Comment by maxnet** [comment]
Sorry, but we cannot accept pull requests we cannot test.

**Comment by Yoshi325** [comment]
Fair enough.
