### ISSUE TITLE
Installation freeze "Saving boot files to memory" on rpi A

### ISSUE THREAD

**Issue by mauron85** [maxnet/berryboot#458]
Berryboot looks very promising and congratulate authors for this great project.

However I have difficulties installing it on rpi A (very first model). It boots, I can also select keyboard. But After selecting Destination drive (same card as where berryboot is installed) and fs type ext4. It freezes on ""Saving boot files to memory".

**Comment by maxnet** [comment]
Probably runs out of memory.
Was it one of those models with half the memory of the B?

**Comment by mauron85** [comment]
@maxnet yes exactly that. I've changed gpu_mem to 64 and problem is resolved.
