### ISSUE TITLE
berryboot - install backup image and new image can't be deleted

### ISSUE THREAD

**Issue by vincentkenny01** [maxnet/berryboot#461]
Hi,
Thank you for updating the Berryboot. I have installed the latest version as my pi failed recently and luckily I had a backed up image of previous installation. 
The process I had to follow was like this:
1) When you boot berryboot for the first time there is no way to install backed up image but you have to download a fresh image of same OS and reboot.
2) you have to boot into the new fresh image for berryboot to create appropriate partitions etc. and reboot.
3) Once rebooted, you can then add/copy from USB your backed up image and then reboot.
3) Once rebooted, select your backed up image and your berryboot loads up your old system image.
Now the issue I have faced is:
Once I have copied over the old backed up image and if I try to delete the new fresh OS image and reboot, the Pi fails to load and the error is 'cannot find the partition'. This never used to happen before because i used to delete the fresh image to save space but now I can't. 

1) Is there anyway to load the backed up image without downloading fresh OS image.
2) Can you please add the option to delete the new OS image without losing the partition data so the old image can successfully load again.

Thanks,
V

**Comment by maxnet** [comment]
- I think you should be able to press "cancel" on the "add OS screen" during installation, if you do not want or install anything from the repository.

- Removing an image only deletes some files on the file system, it does not touch the partition structure at all.
That is more typically the result of either a broken SD card, or unplugging the power without shutting down first.

**Comment by vincentkenny01** [comment]
Hi Maxtor,
Thanks for getting back to me.
I think if I recall correctly if you press cancel it just reboots and then nothing loads. Could you check this for me? I will try doing it on a separate sd card this weekend to check if by pressing cancel I can then select backed up image to be copied and loaded. 
I will also check if I can delete the new fresh OS image. I tried this yesterday like 3 times after my backed up image was loaded. But pi failed to boot up with the error I mentioned in the above post. 

I will give both a go but if you can test it that will be great.

V

**Comment by vincentkenny01** [comment]
Hi just tested it and it worked.  Not sure what was happening yesterday but it seems to have worked today. Closing this thread. Thanks for your response though.
