### ISSUE TITLE
Arch Linux on BerryBoot, How to make it work?

### ISSUE THREAD

**Issue by XxAcielxX** [maxnet/berryboot#462]
Hello there,

I have seen the Arch Linux images being updated with the 2018 ver, but I want to ask that does it work with Berryboot?

I added the image in BB and booted it, but I am unable to install anything in it. There are always error, exists in filesystem, dependencies and much more.

I have followed multiple guides and searched the Google a lot, still with dozen of tries I have failed every time.

Please help me out with this.

**Comment by maxnet** [comment]
We do not support Linux distributions that require non-standard file systems. (Arch uses XATTR)
