### ISSUE TITLE
BerryBoot 2.0 - Image boot issue

### ISSUE THREAD

**Issue by HansiEdis** [maxnet/berryboot#464]
Hello,

There is an issue booting images in BerryBoot.
"Debian Stretch Raspbian 2016.09" does not work
"NOC-PS Lite (Limited to 25 servers)" does work
"OpenELEC 8.0.3/6.0.3" does not work
"Raspian Lite 2016.11" does not work

Kind Regards
Hans
![img_20180122_115901](https://user-images.githubusercontent.com/35661529/35217479-beba362e-ff6b-11e7-9564-ad4682abcf35.jpg)
![img_20180122_115725](https://user-images.githubusercontent.com/35661529/35217480-bee71720-ff6b-11e7-97f9-c32253316ffb.jpg)
![img_20180122_115650](https://user-images.githubusercontent.com/35661529/35217481-bf16ce70-ff6b-11e7-8f63-ba4bd7d34477.jpg)
![img_20180122_115516](https://user-images.githubusercontent.com/35661529/35217483-bf3da428-ff6b-11e7-91d1-ecb3ad9b307d.jpg)

**Comment by maxnet** [comment]
Sounds more like your storage is corrupt.

**Comment by HansiEdis** [comment]
It is installed on iSCSI Target btrfs

**Comment by maxnet** [comment]
We cannot provide support on iSCSI targets we do not have.
Works fine with Synology.

**Comment by HansiEdis** [comment]
I'am use LaCie 5big Pro.
Thanks for Feedback with Synology.

**Comment by HansiEdis** [comment]
I'am have tested a complete new installation.
BerryBoot with USB Stick 8GB Ext4 and OpenELEC will boot complete.
There really an issue with my iSCSI SAN and btrfs. btrfs was only worked and not Ext4.

What is the issue on my iSCSI ?
