### ISSUE TITLE
Full Disk Encryption Support

### ISSUE THREAD

**Issue by Muntoyl** [maxnet/berryboot#47]
Hi  I read the change-log and it says that there is disk encryption support, does that mean there is an option or check box in the gui to set this up easily? or how is this set up? I have been looking everywhere for an answer to this without success. Its crucial for me to have FDE in there before I buy a cubieboard, so I'm asking to make sure that what I want to do is possible before I pull the trigger.

TIA

**Comment by maxnet** [comment]
Yes.

During installation, in the "disk selection" window where you can choose if you want to install Berryboot to SD card or on another drive, simply check the box at the bottom that says "encrypt disk"
You will then be prompted for a password.
