### ISSUE TITLE
Custom OS will not boot whatsoever

### ISSUE THREAD

**Issue by joshikoff** [maxnet/berryboot#470]
I performed all steps as outlined in building custom os, no errors. Os is copied by berryboot and ready for startup. When starting the os the panic mode is always activated.
Pls see the resulting log portion:
[boot.log](https://github.com/maxnet/berryboot/files/1677167/boot.log)

**Comment by maxnet** [comment]
Comment out the entries that in /etc/fstab that refer to PARTUID

**Comment by joshikoff** [comment]
Thank you very much - all works fine now.

Your solution forced me to read and learn about SED and fstab.

**Comment by FarkasJoseph** [comment]
Will you close this?

**Comment by joshikoff** [comment]
as far as I am concerned / this subject has been resolved.
