### ISSUE TITLE
Get no IP address

### ISSUE THREAD

**Issue by Quester1** [maxnet/berryboot#473]
I have a Raspbery PI 3 model B.
When i copy the Berryboot to my MicroSD Card the Raspberry boots, but gets no IP address. If i boot the raspberry with raspbian jessie, the device gets an IP address. The Berryboot System boots (I see the GUI), but gets no Network conection. The device is connected via LAN.

**Comment by FarkasJoseph** [comment]
That is very strange. Did you make sure to select LAN at setup, or if not,
go into the berryboot menu, click the network bar at the bottom, and then
select LAN. Does this work?

**Comment by FarkasJoseph** [comment]
Did this solve your issue? Is it fixed?
