### ISSUE TITLE
Berryboot+volumio2+Allo DigiOne= Error. Failed to open "Alsa"

### ISSUE THREAD

**Issue by pongoxxx** [maxnet/berryboot#475]
**Hello
I have Berryboot with Volumio installed. As a DAC I have an Allo DigiOne. I Setting Volumio I2SDAC to ON, and Model DAC = To DigiOne; if I press PLAY to listen an audio file, I have a error message: Error. Failed to open "Alsa" [Alsa]; Failed to open ALSA device "hw:1,0": No such file or directory.
I tried the solutions proposed on the net but without success. PLEASE HELP ME !!

**Comment by macmpi** [comment]
Current Berryboot kernel does not support this DAC (but does support others from the same brand).
Allo did build support for DigiOne from 4.9.31 Foundation's stock kernel: so you would need @maxnet to release Berryboot with a more recent kernel base to get built-in support (last 4.9.x seems to be 4.9.80, or then 4.14.17 or more).

**Comment by macmpi** [comment]
@pongoxxx you may want to try new berryboot version just released today: it's likely it now supports Allo DigiOne.
Thought new kernel (4.14.18) is now more advanced than Volumio's, it seems Volumio accommodates it just fine (more tests needed).
Feel free to confirm if it works.

**Comment by pongoxxx** [comment]
@macmpi Thank you !!! Now it works perfectly. Great !!! I just had to add in the file cmdline.txt  -->  bootdev=mmcblk0p1 and everything is ok !
