### ISSUE TITLE
When OS-Download crashes, the OS does not show up in list

### ISSUE THREAD

**Issue by cubuzz** [maxnet/berryboot#477]
I mean, I can't delete the OS without a different PC. Can't we just have it show up as "corrupt" so we can delete it?

**Comment by maxnet** [comment]
If it doesn't show up, the file system is likely corrupt.
There do is a "repair file system" button.

**Comment by cubuzz** [comment]
Going to close this since I didn't keep track of this. I'll reopen if I can reproduce this.
