### ISSUE TITLE
Ability to Compress Image+Data

### ISSUE THREAD

**Issue by symbios24** [maxnet/berryboot#478]
Hi

Can this option implemented to Berryboot "exporting image+data compressed" ??

It was years before in an old version but its removed due to slow compression
RaspberryPi 2/3 will do this process a lot faster so its good to add it again.

**Comment by symbios24** [comment]
well i assume the creators dont like to hear this kind of questions you could just answer me that you dont want to add this feauture anyway thanks

**Comment by maxnet** [comment]
Pull requests welcome

**Comment by symbios24** [comment]
no clue how to do that otherwise i will already have done

**Comment by symbios24** [comment]
If i knew how to do that i wouldn't ask you,i will just do it,for months i`m asking for this feature to be added to berryboot,and nobody cares.i`m helping people there by answering to what i know,i have using berryboot for years and know some things,this feature will be great in general and save a lot of time.anyway thanks

**Comment by symbios24** [comment]
anyway leave it dont get tired so much you have time for help for ridiculous issues but not for this

**Comment by symbios24** [comment]
anyway leave it you have time to help solve ridiculous issues but apparently not time for this

**Comment by maxnet** [comment]
Not much to do with time, but lack of USB sticks I haven't broken yet.
