### ISSUE TITLE
BerryBoot v2.0 Error downloading distribution list from Internet 

### ISSUE THREAD

**Issue by HelloMick** [maxnet/berryboot#48]
I can't download anything.
I always get "BerryBoot v2.0 Error downloading distribution list from Internet".
I install RASPBMC before and that works well.

**Comment by maxnet** [comment]
Do you have network connectivity inside of RaspBMC?
E.g. can you use it to watch Youtube without problems?

**Comment by HelloMick** [comment]
Yes, inside of RaspBMC I can watch Youtube, hear radio over Shoutcast 2, connect to my NAS, ...
No problems.

But if I try to install BerryBoot I didn't get a connection. "BerryBoot v2.0 Error downloading distribution list from Internet"

Same in OpenELEC.

Link: Connected
MAC Address: left this out for convenience
IP Address: 169.254.xxx.xxx
Subnet Mask: 255.255.0.0
Gateway: [blank]
Primary DNS: 127.0.0.1
Secondary DNS: [blank]
Internet: Not connected. Check Network Settings

My Modem/Router: AVM FritzBox 7390 (IP Adress: 192.168.xxx.xxx)

**Comment by maxnet** [comment]
At http://fritz.box/ does it show the Pi under active connections?
If so, double check that there is not another device in the network using the IP meant for the Pi.

**Comment by maxnet** [comment]
Closing as inactive for 7 days
