### ISSUE TITLE
Not detecting exFAT drive

### ISSUE THREAD

**Issue by AidanWelch** [maxnet/berryboot#480]
I am trying to install two .img files that are too large for FAT32 does anyone know a work around?  If not, a solution would be appreciated

**Comment by agoldcheidt** [comment]
Hey @AidanWelch, you can use EXT4 partition format.

**Comment by AidanWelch** [comment]
I know, but I was looking for a better solution for windows users

**Comment by Nilpo** [comment]
@AidanWelch What do you mean by better? You have to use a file system supported by the Pi that allows large files. EXT4. Windows users can add support for EXT4 easily. Take a look at [Ext2Fsd](http://www.ext2fsd.com/).

**Comment by kmpm** [comment]
RPI will get exFAT in kernel 5.9 from how it looks. 
* https://github.com/raspberrypi/linux/issues/3901
* https://github.com/raspberrypi/linux/commit/fc4e05f2797c8e2744e7c0e037e3d7e051996049

**Comment by AidanWelch** [comment]
Ah, then this should be closed.
