### ISSUE TITLE
Can't download any OS

### ISSUE THREAD

**Issue by Zumzod** [maxnet/berryboot#481]
Hello,

Recently bought a new rasp pi and installed berryboot on a SD-card but when I boot it up and go to Add OS (from internet) I get the error:
"Error downloading file from Internet: file corrupt (sha1 does not match)"

Read somewhere that it ment that the hosting-site for the Rasbian OS was down but its been like this for 20hours now.

So is that the problem or did they change the source file so the hash doesn't match anymore or am I doing something wrong?

Cheers

EDIT:
I have now installed it manually via USB but I'm still wondering if its a problem on my part or a other source.

**Comment by maxnet** [comment]
https://twitter.com/sfnet_ops/status/969743281922936832
