### ISSUE TITLE
Customizing

### ISSUE THREAD

**Issue by radimkohout** [maxnet/berryboot#483]
Hello,
I have a three questions:
1)How can i change the rainbow background, when i plug Raspberry Pi to adapter?
2)How can i change default location for downloading OS image?
3)How can i change the Raspberries, when the OS select screen is viewed?
Thanks
rktech

**Comment by maxnet** [comment]
1) recall you cannot change it, but do can disable it with some `config.txt` option ( disable_splash=1 ?)
The rainbow screen isn't drawn by Berryboot but by the Raspberry Pi firmware. So ask in their forum if the option does not work.

2) put a `berryboot.ini` on the SD card

```
[repo]
url=http://your-server/distro.smime
```

And your public key in `berryboot.crt`

3) the 4 Raspberries on boot? That's a Linux kernel logo.
Google: custom linux kernel logo

**Comment by radimkohout** [comment]
And where is on internet default(when i install berryboot) OS download page??

**Comment by maxnet** [comment]
They look like this: http://dl.berryboot.com/distro.smime
(Berryboot downloads the compressed verison .zsmime by default though)

**Comment by symbios24** [comment]
instead of adding this ridiculous features why not focusing on adding something real

**Comment by radimkohout** [comment]
And how can i compile berryboot with my own kernel?

**Comment by maxnet** [comment]
Read the buildroot manual

**Comment by radimkohout** [comment]
where to find it??

**Comment by maxnet** [comment]
First result in Google

**Comment by radimkohout** [comment]
but how to use compiled rpi2 kernel??

**Comment by maxnet** [comment]
Just rename it from zImage to the kernel.img you are replacing...
