### ISSUE TITLE
I2C and LCD HD44780

### ISSUE THREAD

**Issue by Lucky0005** [maxnet/berryboot#485]
Hi

I have some trouble with I2C and LCD HD44780, maybe you could help me.

When I did clean installation of Libreelec (on SD card was only this system) LCD working fine via i2c bus.
Besides other setting in Libreelce is necessary enable i2c in config.txt with these two commands:
dtparam=i2c1=on
dtparam=i2c_arm=on

But when I used latest version of berryboot (berryboot-20180314-pi0-pi1-pi2-pi3) and libreelec and added commands from above to config.txt under berryboot editor. LCD via I2C didn´t work, from my point of view it looks to I2C bus wasn´t enabled.

Did you anybody meet this issue or is there any know issue?

thank you in advance for your answer.

**Comment by maxnet** [comment]
Cannot help with LCD displays I do not have.

**Comment by Petr325** [comment]
Hi
I have the same problem. The display HD44780 I2C is reliable for a clean installation LibreELEC. Berryboot (edit config.txt) does not pass I2C activation to LibreELEC :-(  
Any idea how to enable I2C bus ?

Thanks

**Comment by maxnet** [comment]
You do have /dev/i2c* in Raspbian?

**Comment by Petr325** [comment]
Editing config.txt:
dtparam=i2c1=on
dtparam=i2c_arm=on

Clear instalation LibreELEC - i had the device / dev / i2c-1
LibreELEC Berryboot  - does not contain /dev/i2c-1

**Comment by Lucky0005** [comment]
@maxnet for test maybe you don´t need whole LCD,  I2C adapter (module) will be enough 
[https://www.ebay.com/itm/2PCS-5V-IIC-I2C-SPI-TWI-Series-Adapter-for-2004-20X4-1602-LCD-Display-Arduino/201042782490?epid=1545631970&hash=item2ecf15691a:g:O2AAAOSwMmBVgi3F](url)
or another I2C device

**Comment by maxnet** [comment]
Can you test if it works better with berryboot-20180322 (just released)?

**Comment by Petr325** [comment]
Tested, but the same problem :-(
LibreELEC Berryboot - does not contain /dev/i2c-1

RPi 3B+  berryboot-20180322 + LibreELEC 8.2.4 (flash driver)

**Comment by maxnet** [comment]
Do have the device under OpenELEC:

```
OpenELEC:~ # uname -a
Linux OpenELEC 4.14.29v7-aufs #1 SMP Thu Mar 22 19:24:41 CET 2018 armv7l GNU/Linux
OpenELEC:~ # ls -l /dev/i2c*
crw-------    1 root     root       89,   1 Apr 29  2017 /dev/i2c-1
```

Make sure you put in `config.txt` in the Berryboot config editor:

```
dtparam=i2c=on
```

**Comment by Petr325** [comment]
I do not know what you're doing otherwise. Is there anything else to change? Thanks

config.txt:
`dtparam=i2c=on`


Putty:
`OpenELEC (official) Version: 8.0.4`
`OpenELEC:~ # uname -a`
`Linux OpenELEC 4.14.29v7-aufs #1 SMP Thu Mar 22 19:24:41 CET 2018 armv7l GNU/Linux`
`OpenELEC:~ # ls -l /dev/i2c*`
`ls: /dev/i2c*: No such file or directory`

**Comment by maxnet** [comment]
Seems you put it in the [pi1] section that is only executed if you boot on a Pi 1.
Better put the line at the bottom (below [all]) or at the top of the file, if you want things to work on other Pi models like Pi 3...

**Comment by Petr325** [comment]
He's already working perfectly
I'm sorry, i forgot part of the file in config.txt [pi1].... 
Thank you very much for your work and patience.

**Comment by maxnet** [comment]
Good to hear its solved.
