### ISSUE TITLE
update berryboot

### ISSUE THREAD

**Issue by neoskyriper** [maxnet/berryboot#489]
hello can you update berryboot as a "os" in the console berryboot with "sudo apt-get update" (it does not work) because easier to reinstall all thank you for your answer

**Comment by maxnet** [comment]
Extract the new Berryboot files to the FAT partition of the SD card. Select "use existing files" during installation.

**Comment by neoskyriper** [comment]
yes I know it may be well to add an updated mode in berryboot

Le 28 mars 2018 6:50 PM, maxnet <notifications@github.com> a écrit :

Extract the new Berryboot files to the FAT partition of the SD card. Select "use existing files" during installation.

**Comment by maxnet** [comment]
There's actually update functionality within Berryboot.
Just haven't used it for the last couple releases, as some users are currently better off with the old version.

**Comment by neoskyriper** [comment]
can you tell me the functions because it interests me strongly I have the version of February 16, 2018 and I wanted to put the last without having to do again thank you

Le 28 mars 2018 19:16, maxnet <notifications@github.com> a écrit :

There's actually update functionality within Berryboot.
Just haven't used it for the last couple releases, as some users are currently better off with the old version.

**Comment by maxnet** [comment]
When you press "add OS" in the Berryboot GUI it will give you a pop-up if a newer version is made available.
But like I said, I did not make the latest versions available through that way.

Unless you have a 3+ there is no need to update.
The new kernel has more issues than the old one. So most users should NOT upgrade.

**Comment by vincentkenny01** [comment]
Could you also add stretch lite on the list of downloadable os's please?

**Comment by neoskyriper** [comment]
maxnet
yet you have released a new version of berryboot 6 days ago

vincentkenny01 
stretch Lite
https://berryboot.alexgoldcheidt.com/search-downloads/?dl_cat=0&dl_search=stretch+Lite

**Comment by maxnet** [comment]
Added todays update to the update mechanism available under "add OS"

**Comment by maxnet** [comment]
>Could you also add stretch lite on the list of downloadable os's please?

It's under the tab "Others"
