### ISSUE TITLE
Rotate screen

### ISSUE THREAD

**Issue by OxygenGS** [maxnet/berryboot#491]
When i use berryboot all work fine and easy.
However, i got a 7inch touchscreen. In Raspbian for example i can use LCD_rotate=2 to get it good again. However, how to do this in berryboot?

**Comment by maxnet** [comment]
The same way.
Just put that setting in config.txt

Easiest to do so is using the built-in config editor in the Berryboot menu editor.

**Comment by OxygenGS** [comment]
Weird is not i run Raspbian via Berryboot, however, there is no conifg.txt when i try to do: sudo nano boot/config.txt. Now what?

**Comment by OxygenGS** [comment]
Even if u go into sudo raspi-config and i go to boot, i cannot add the command no where.
But, how to rotate the screen now in berryboot to begin with?

**Comment by maxnet** [comment]
Use the built-in config editor...
This one: https://www.berryterminal.com/lib/exe/detail.php/berryboot_menu2.png?id=berryboot

**Comment by OxygenGS** [comment]
Ok, so and in wich txt file and what command line do i put in? lcd_rotate=2?

**Comment by maxnet** [comment]
Whatever line works for you with Raspbian.

Closing as this is not Berryboot specific.

**Comment by OxygenGS** [comment]
Thgis is specific wth?
