### ISSUE TITLE
/lib/modules/4.14.32v7-aufs/modules.dep.bin (problem with iptables)

### ISSUE THREAD

**Issue by rwaaren** [maxnet/berryboot#497]
after a reboot my iptables command no longer work on my PI-3 with debian stretch>

errormessage:

iptables -L
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.14.32v7-aufs/modules.dep.bin'
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.14.32v7-aufs
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

tried to solve this with an rpi-update but that one is telling me that the kernel will notbe updated.
Is this something that can be solved with a new version of Berryboot ?

My Berryboot is berryboot-20180405-pi0-pi1-pi2-pi3

**Comment by maxnet** [comment]
Does `ls -l /lib/modules` show you actually have a 4.14.32v7-aufs directory, or some different version?

**Comment by rwaaren** [comment]
on my PI"

s -l /lib/modules
total 0
drwxr-xr-x 1 root root 346 Mar 29 03:39 4.14.30+
drwxr-xr-x 1 root root 346 Mar 29 03:40 4.14.30-v7+
drwxrwxr-x 1 pi   pi   346 Jan  1  1970 4.9.26v7-aufs

**Comment by maxnet** [comment]
You tried to upgrade to 20180405 from an older version manually?

Extract shared.tgz to /shared on the ext4 partition.
E.g. from within the Berryboot menu editor -> "console"

```
/bin/gzip -dc /boot/shared.tgz | /bin/tar x -C /mnt/shared
```

**Comment by rwaaren** [comment]
Could well be. I had some problems with my card so I copied from another card and replaced the iscsi,sh and  cmdline.txt. to get it booting again.
I extracted the shared.tgz to the  /lib dir on my NAS (btrfs) and everything worked. And still does after a reboot. Many thanks for your help !
