### ISSUE TITLE
format not working on a 16GB SDHC class10 card

### ISSUE THREAD

**Issue by ironbodri** [maxnet/berryboot#5]
Thx this very nice tool. All working on my default 4GB card. On a 16GB car after a short peiod of time it say cant format device. I have tried all of two format opcion. Then I can install any os becouse say not enought space on device. (i think becouse format wnt wrong) Any idea ?

**Comment by maxnet** [comment]
The Pi is known to have problems getting along with some SD cards.
That isn't capacity related. I do have a working 16 GB card.

**Comment by ironbodri** [comment]
Hmm, I see yet. :( I get the wrong type. Do you mean its a hw or sw related bug ? Newer kernel version will it support ?

**Comment by maxnet** [comment]
Don't know if it is in the hardware or kernel module.
But if your card is not be supported now, I wouldn't count on it ever working properly.

Better get a different one.
Or a USB stick.
