### ISSUE TITLE
Delete warning message "Copy OS"

### ISSUE THREAD

**Issue by Petr325** [maxnet/berryboot#501]
Please delete the warning windows - item _Copy OS from usb stick_ 

_No media found_

_Insert a USB stick or other external medium first, and try again_

Image files are stored on the same disk as the operating system. I do not use other USB media.

Thanks.

**Comment by maxnet** [comment]
That's not a supported scenario.

Just copy the images files to /images on the ext4 partition directly.

**Comment by Petr325** [comment]
Super info 
I did not know about this possibility. Thanks
