### ISSUE TITLE
ISCSI fails against ubuntu tgt iscsi server

### ISSUE THREAD

**Issue by betchern0t** [maxnet/berryboot#509]
I get "error zeroing MBR/GPT SD card may be broken or advertising wrong capacity". The card is a PI3 and the connection is ethernet - try the easy way before wifi. Duplicate results from ubuntu 18.04 and 16.04. 

targets.conf:

default-driver iscsi

\<target iqn.2018-05.au.org.singlespoon:lun01\>
       backing-store /luns/lun01.img
       initiator-address ALL
\</target\>

loading it from another linux box seems to work fine. It is managing to partition the volume and format the two partitions.

Berryboot is the latest stable version.
tia

Paul

**Comment by symbios24** [comment]
oti na nai

**Comment by symbios24** [comment]
you understand that you talk nonsence?

**Comment by betchern0t** [comment]
No I don't. That is what I am seeing. If you want more information or different information, I am happy to gather it but would need some pointers as to what. Your response to date is not helpful.

**Comment by symbios24** [comment]
can you say in simple words what exactly you want to do?

**Comment by betchern0t** [comment]
Thank you symbios24. I have unzipped Berry boot on an sd card. I boot the pi off the card which brings up the initialization dialogs. I click through and choose iscsi as the storage to use and supply the iqn and ip address. The boot loader loads the iscsi drivers, then partitions and formats the volume. After that it reports the given error message and gives up.

**Comment by symbios24** [comment]
look here

https://www.reddit.com/r/raspberry_pi/comments/3tsvar/berryboot_iscsi_to_local_storage/

https://www.reddit.com/r/raspberry_pi/comments/49l25b/iscsi_booting_your_raspberry_pi/

**Comment by maxnet** [comment]
The file size of `/luns/lun01.img` does is dividable by 512 ?

**Comment by lulol** [comment]
@betchern0t See #282 replace berryboot.img with [that which has an scsi delay](https://github.com/maxnet/berryboot/issues/282#issuecomment-413059342).

**Comment by maxnet** [comment]
Should be fixed in 20180904
