### ISSUE TITLE
Cubieboard debian wheezy raspbian  no net connection

### ISSUE THREAD

**Issue by df0021** [maxnet/berryboot#51]
hello

I can't get any net connection to my cubieboard with debian.
If I write ping 192.168.178.1 comes the answer: network unreachable.
ifconfig shows no ip address.
I did try to write the ip address to /etc/network/interfaces, but I can't because I am only the user pi without any rights to write and the root's passwort do I not know.

Any recommandations?

regards 
df0021

**Comment by maxnet** [comment]
You did have network connectivity inside Berryboot?

> because I am only the user pi without any rights to write and the root's passwort do I not know.

Try: sudo bash

**Comment by maxnet** [comment]
Closing as no response
