### ISSUE TITLE
VNC IP address

### ISSUE THREAD

**Issue by sv-kov** [maxnet/berryboot#511]
When included in the cmdline.txt vnc, after downloading the raspberry P3 network card stores and uses the IP address of the vnc. Openmediavault does not have Internet access until you remove vncinstall from the cmdline.txt. Please specify, so it should be or it can be corrected. It is desirable that with the start of the download the device is fully unloaded vnc and did not use the IP address specified and vncinstall.

**Comment by sv-kov** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP ql                                                                                                                                                              en 1000
    link/ether b8:27:eb:52:63:7c brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.180/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.0.121/24 brd 192.168.0.255 scope global eth0
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DO                                                                                                                                                              WN qlen 1000
    link/ether b8:27:eb:07:36:29 brd ff:ff:ff:ff:ff:ff

**Comment by sv-kov** [comment]
192.168.1.180 - IP address  vnc
you can connect to the device at 192.168.0.121, but the Internet does not work

**Comment by maxnet** [comment]
As soon as Berryboot exits, the VNC port is closed.
Any static IP configuration you configured remains active though, it does not bring down the network interface.
Doing so can provide problems with some other configurations (e.g. iSCSI).

**Comment by carry0987** [comment]
Hello, how can I know which IP and gateway can I use? I want to use VNC to control my berryboot, but I don't know what can I write here:
vncinstall ipv4=IP/Mask/Gateway /wlan0

**Comment by sv-kov** [comment]
Thanks. The problem was solved by putting in 
 rc.local network restart after boot.
