### ISSUE TITLE
Pi Zero W won't boot

### ISSUE THREAD

**Issue by llamafilm** [maxnet/berryboot#512]
I downloaded the contents of berryboot-20180405-pi0-pi1-pi2-pi3.zip to an SD card, formatted MBR and FAT32.  My Pi Zero W does not boot.  No HDMI output and no green LED.  I tried copying all the files from https://github.com/raspberrypi/firmware/tree/master/boot.  I also tried commenting out all the `kernel=` lines in config.txt.
I know the hardware is good because it boots fine in a different OS.

**Comment by symbios24** [comment]
clean you card contacts with some paper just to take the fingerprints, if it does not work format your card with SDFormatter tool and set the the format size adjustment to on from the options,and try another card also.

**Comment by symbios24** [comment]
Hi, Clean you card contact pins with some paper just to take the fingerprints, if it does not work format your card with SDFormatter tool and set the the format size adjustment to on from the options,and try another card also.

**Comment by symbios24** [comment]
Hi, you need to extract the archive to the card and not copy the zip file like this,Clean you card contact pins with some paper just to take the fingerprints, if it does not work format your card with SDFormatter tool and set the the format size adjustment to on from the options,and try another card also.

**Comment by symbios24** [comment]
Hi, you need to extract the archive to the card and not copy the zip file like this,if you did extracted the archive and it does this then clean you card contact pins with some paper just to take the fingerprints, if it does not work format your card with SDFormatter tool and set the the format size adjustment to on from the options,and try another card also.

**Comment by llamafilm** [comment]
Can you explain what you mean by extract the archive?  It's not an IMG file, it's a zip.  So I thought it just needs a single FAT32 partition.

**Comment by symbios24** [comment]
open the zip file with an archive manager like winrar or 7zip and extract/copy the contents in the root of the memory card
