### ISSUE TITLE
support non-linux OS's?

### ISSUE THREAD

**Issue by raingloom** [maxnet/berryboot#513]
I'd really like to dual boot into some non-Linux things like BSD and 9front, is that possible? And if not, could it be made possible?

**Comment by maxnet** [comment]
No
Under Berryboot all Linux distributions installed share a single partition and file system. And that does not work well with other operating systems.

**Comment by raingloom** [comment]
Ah well. Is there some other way this could be accomplished? I just want Plan 9 and Raspbian on the same microsd, but all the dual boot docs are for Linux. Maybe I could have two FAT partitions and reorder them from a different machine...

**Comment by maxnet** [comment]
Not with Berryboot.
Try NOOBS or PINN.
