### ISSUE TITLE
Berryboot 2.0 and SCSI on synology

### ISSUE THREAD

**Issue by joshikoff** [maxnet/berryboot#516]
following exactly the instructions on setting up both on Pi and NAS. The Target SCSI gets formatted, an OS can be picked and installed. After message "writing to disc" process comes to and end and says, please reboot now. After rebooting, the SCSI connection can not be found and Bootberry terminates with panic shell.

**Comment by maxnet** [comment]
You do are connected by wired Ethernet?
We do not support wifi for iSCSI.

**Comment by joshikoff** [comment]
It does not work with wifi.

But i still have troubles, maybe it comes from the fact that the ethernet connection i use is based on a Powerline Extender. I had similar troubles with TV-Tuner via Ethernet.

**Comment by joshikoff** [comment]
I still have troubles uploading berryboot images to SCSI. The images are storred on FAT32 USB stick. They have been tested thru uploading on different RPi system with USB-disc.

However, when trying to upload on SCSI, the loading process is endless and error messages are written to monitor.  (I try to upload PressPI OS)
![img_3166 1](https://user-images.githubusercontent.com/28642440/43061792-3f3e6946-8e5f-11e8-8776-f32b7bea9e4c.jpg)
