### ISSUE TITLE
RPi 3 has several issues after switch to Linux kernel 4.14.x

### ISSUE THREAD

**Issue by Forusim** [maxnet/berryboot#519]
Hello,
I used **berryboot-20170527-pi2-pi3.zip** on my Raspberry Pi 3 Model B for a while, which worked fine either over LAN or WiFi.

Now have overwritten the boot partition with the latest **berryboot-20180715-pi2-pi3.zip**, which have following issues:

- Onboard WiFi is not recognized anymore
- Accessing my NAS repo gives me "error mounting network share"

The smb.cfg on my Unraid NAS should not be the issue, because my smart TV is using NT1 protocol without a problem.

After some research I found, that the issues started with **berryboot-20180216-pi2-pi3.zip**, which had that switch to Linux kernel 4.14.x.

Do I have to do some special initialization?

**Comment by maxnet** [comment]
>Now have overwritten the boot partition with the latest berryboot-20180715-pi2-pi3.zip

Have you overwritten everything including cmdline.txt, and selected "use existing files" during installation?

If not, you may need to manually extract shared.tgz -containing the kernel modules- to the /shared on the ext4 partition.

**Comment by Forusim** [comment]
You are right, I have kept the configs.
After replacing all the files, the new firmware flashed properly.
Thank you the for fast help!

**Comment by maxnet** [comment]
Good to hear that solved it.
