### ISSUE TITLE
A20 soc (cubieboard2) support

### ISSUE THREAD

**Issue by disconnect928** [maxnet/berryboot#52]
I've just tried berryboot on cubieboard2 with A20 soc, but it isn't works, nor the app for android (it writes the android is not rooted while it is), nor the berryboot image written to SD card.

**Comment by maxnet** [comment]
Cubieboard A20 is indeed not supported yet.
Do have one laying on my desk, but haven't had time to look into it yet. Probably requires another kernel.

**Comment by h6w** [comment]
+1 for this.  (I wish github issues had a "me too!" button like launchpad.)

**Comment by kingneutron** [comment]
Hi - I've just got my Cubietruck with the A20 processor + gig ethernet, etc; can you please add support for it to your Berryboot (which is an EXCELLENT tool - I used it on my Cubie v1!) ?

**Comment by HLFH** [comment]
Hi - It would be great to have a CubieTruck support.

**Comment by allenelson** [comment]
If anyone would like to test on their cubieboard2, download below. I've posted an issue because a script in berryboot is not loading the OS. I don't have time to dig through the berry stuff. I'm hoping someone else does which is why I put the image up.

download for sdcard image
ftp://ciscoeng.pro/berryboot_a20_50M_sdcard.img.xz

**\* pastebin of openelec failing to load ***
http://pastebin.com/rs9baESv

install to your sdcard and load the same way.
unxz berryboot_a20_50M_sdcard.img.xz
dd if=berryboot_a20_50M_sdcard.img of=/dev/sdX bs=1M count=50
(replace sdX with actual device)

**Comment by hsh-ru** [comment]
I have Cubieboard 3 Cubietruck with the A20 processor. 
Please add support for it to Berryboot project.
Link ftp://ciscoeng.pro/berryboot_a20_50M_sdcard.img.xz is broken.

**Comment by allenelson** [comment]
apologies for the link, i didn't realize i had FTP filtered on the
firewall. please ignore the image though. i ended up recompiling the aufs
support and will need to replace that image with the new one for you.

**Comment by hsh-ru** [comment]
allenelson, thank you very much for your reply. Would be grateful for a working bootloader.

**Comment by allenelson** [comment]
give this one a try
ftp://ciscoeng.pro/berryboot_a20_50M_sdcard.img.bz2
i deleted my source files but that was the working image. i had the /data
mount on an external usb drive.

**Comment by hsh-ru** [comment]
Link is not opens. You have no way to put a file on an external resource?

**Comment by vanschroeder** [comment]
Ran into the same issue as everyone else above on a new CB2, willing to give the last link a go if you can put it on publicly accessable download link

**Comment by allenelson** [comment]
I don't know what the issue is. FTP is wide open and I can login with an FTP client. I did notice the link in a remote web browser doesn't work.

I moved it to the html directory. Download here:

http://ciscoeng.pro/berryboot_a20_50M_sdcard.img.bz2

**Comment by maxnet** [comment]
For Cubieboard 2 support there is now an "official" image at: http://sourceforge.net/projects/berryboot/files/berryboot-cubieboard2-20140627.zip/download
