### ISSUE TITLE
HDMI LCD screen driver don't works if Raspbian is installed with berryboot

### ISSUE THREAD

**Issue by Inky1003** [maxnet/berryboot#521]
I have an LCD screen that have these drivers, and when I try to do sudo ./LCD7B-show in Raspbian, the pi shuts down and don't turn on anymore. And this only happens with berryboot, when I install Raspbian without berryboot, the driver works fine, but when I install Raspbian with berryboot, here is the problem.

Can anyone tell me what do I do?

[LCD-show-160701.tar.gz](https://github.com/maxnet/berryboot/files/2228158/LCD-show-160701.tar.gz)
[How to install the LCD driver (En).pdf](https://github.com/maxnet/berryboot/files/2228159/How.to.install.the.LCD.driver.En.pdf)

**Comment by maxnet** [comment]
Does it work better if you mount /boot before executing that command?

```
sudo mount /dev/mmcblk0p1 /boot
```

**Comment by pauromateusu** [comment]
It says this:
![237bacbd-a029-4351-bc63-80f53411352b](https://user-images.githubusercontent.com/13457223/43214527-e85d7204-900f-11e8-98ad-4e4005120741.jpg)
and then I get the same problem, It shuts down and don't boot anymore

**Comment by maxnet** [comment]
Seems the script replaces cmdline.txt and config.txt with their version.
Which will indeed brick any non-standard system.

Try doing the modifications manually.
E.g. use the stock Berryboot config.txt and try adding to the bottom:

```
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt 800 480 60 6 0 0 0
dtoverlay=ads7846,cs=1,penirq=25,penirq_pull=2,speed=50000,keep_vref_on=0,swapxy=0,pmax=255,xohms=150,xmin=200,xmax=3900,ymin=200,ymax=3900
```

**Comment by pauromateusu** [comment]
Thanks! It worked!
