### ISSUE TITLE
Issue on trying to use the RetroPie Menu

### ISSUE THREAD

**Issue by Inky1003** [maxnet/berryboot#522]
When I select any options of this screen:
![jpeg_20180725_161359](https://user-images.githubusercontent.com/13457223/43223130-7ce6e366-9028-11e8-8972-bd3256368dd9.jpg)

This happens:
![20180725_161259](https://user-images.githubusercontent.com/13457223/43223184-a827dcb0-9028-11e8-8463-90e38b57c6cc.jpg)

Where do I need to set this variable?

**Comment by pauromateusu** [comment]
I'll try in the RetroPie help
