### ISSUE TITLE
How do images boot from iSCSI?

### ISSUE THREAD

**Issue by findcoop** [maxnet/berryboot#524]
Have set up iSCSI successfully, installed LibreElec into iSCSI target. I can see the image and data folder are created successfully. However, the LibreElec OS will not boot, I suspect because each installed image within BerryBoot also needs to be iSCSI aware? Is there an easy way to do this with cmdline.txt? Guidance appreciated.

**Comment by maxnet** [comment]
Does work fine with OpenELEC.

At least running it.
Shutting down does hang because it tries to disable network interface then, and wants to execute scripts after that, while iSCSI is no longer available without network...

**Comment by macmpi** [comment]
@findcoop  Did you use latest Berryboot 20180729 image?
You may want to try to install LibreELEC with [this method](https://github.com/macmpi/berryboot-scripts/tree/master/LibreELEC): let me know if you get a better chance.
(for any question specific to this install method, post an issue on that repo).

**Comment by findcoop** [comment]
@macmpi thank you, I am using 0729 build and will give your suggestion a try. Cheers
