### ISSUE TITLE
Error message during first time installation

### ISSUE THREAD

**Issue by edegraaff** [maxnet/berryboot#527]
Hi , i have an error during the fist time installation.
Error zeroing .... 

i use the solution underneath but maybe it could be fixed in a next release? i use this fix and then everything is working fine

On a Synology NAS with DSM 4.2 I first got the 'Error zeroing MBR/GPT message' mentioned 
I could repair this fault by placing the SD card in my windows computer card reader and in files cmdline.txt and uEnv.txt replaced datadev=SDA1 by datadev=iscsi
Then placed SD card back in RPI and powerup the system.

**Comment by maxnet** [comment]
Should be fixed in 20180904

**Comment by edegraaff** [comment]
thnx
