### ISSUE TITLE
brcm firmware files reference changed

### ISSUE THREAD

**Issue by macmpi** [maxnet/berryboot#529]
Incidentally noted that few built-in rpi-wifi firmware files are different in [newer build](https://github.com/maxnet/berryboot/blob/berryboot2018/buildroot-2018.08/package/linux-firmware/linux-firmware.mk).
Some do not match [those of RPi-Disto](https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm) ( `brcmfmac43430-sdio.txt` in particular)
```
 	brcmfmac43430-sdio.bin 	Update brcmfmac43430-sdio.bin 	6 months ago
	brcmfmac43430-sdio.txt 	Improved brcmfmac BT coexistence parameters 	20 days ago
	brcmfmac43455-sdio.bin 	Add brcmfmac43455-sdio 	6 months ago
	brcmfmac43455-sdio.clm_blob 	Add brcmfmac43455-sdio 	6 months ago
	brcmfmac43455-sdio.txt 	Improved brcmfmac BT coexistence parameters 	20 days ago
```
You might want to to take references from RPi-Disto ones as in the past.

**Comment by maxnet** [comment]
Think upstream buildroot changed to LibreELEC because the bluetooth files are hard to find on rpi-distro.

**Comment by macmpi** [comment]
LibreELEC? not sure I understand, as buildroot seems to uses files from kernel.org actually.

Isn't it possible to add a later recipe in the build to use Foundation's files on top (through [github repo](https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm) probably, as [packages names & location](https://github.com/RPi-Distro/firmware-nonfree/blob/master/debian/changelog#L1) are more [tricky to guess](https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/)), since they seem to be more proactive to get fixes in?

**Comment by maxnet** [comment]
>LibreELEC? not sure I understand, as buildroot seems to uses files from kernel.org actually.

Nope

https://git.busybox.net/buildroot/tree/package/rpi-wifi-firmware/rpi-wifi-firmware.mk
https://git.busybox.net/buildroot/tree/package/rpi-bt-firmware/rpi-bt-firmware.mk

**Comment by macmpi** [comment]
ok, thanks for the pointers.
~~Then these may not get executed or fail: looking at resulting files in `shared.tgz`, you'll see [brcmfmac43430-sdio.txt](https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi/blob/master/firmware/brcm/brcmfmac43430-sdio.txt) and [brcmfmac43455-sdio.txt](https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi/blob/master/firmware/brcm/brcmfmac43455-sdio.txt) do not match those of LibreELEC repo (which happen to match those of Pi Foundation). They just match those of upstream kernel.org~~

EDIT: actually [`rpi-wifi-firmware.mk`](https://github.com/maxnet/berryboot/blob/berryboot2018/buildroot-2018.08/package/rpi-wifi-firmware/rpi-wifi-firmware.mk#L7) / [`rpi-bt-firmware.mk`](https://github.com/maxnet/berryboot/blob/berryboot2018/buildroot-2018.08/package/rpi-bt-firmware/rpi-bt-firmware.mk#L7) & assorted hashes may just need to use current LibreELEC master, or commit [8c1e2bff1da9850f68efcfff3da5d939ec27a2ee](https://github.com/LibreELEC/brcmfmac_sdio-firmware-rpi/commits/master)

**Comment by macmpi** [comment]
Thanks
