### ISSUE TITLE
Memory split displays wrong numbers on 512MB Pis

### ISSUE THREAD

**Issue by lurch** [maxnet/berryboot#53]
The "edit memory split" dropdown seems to be hardcoded to assuming that the Pi has 256MB of memory, i.e. even though I'm running berryboot on a 512MB Pi it still displays

```
no preference
128 MB (gpu_mem=128)
192 MB (gpu_mem=64)
224 MB (gpu_mem=32)
240 MB (gpu_mem=16)
```

instead of

```
no preference
384 MB (gpu_mem=128)
448 MB (gpu_mem=64)
480 MB (gpu_mem=32)
496 MB (gpu_mem=16)
```

Of course, on a 512MB Pi the gpu_mem can go all the way up to 448 ( http://elinux.org/RPi_config.txt#Memory ) so you _might_ want to choose a different range of available splits than those listed above.

**Comment by maxnet** [comment]
Note that berryboot defaults to cma nowadays, so not sure if its worth keeping the memsplit selection.
It is kinda legacy.

**Comment by maniqui** [comment]
I'm seeing the same thing in the dropdown for OpenELEC, even when gpu_mem is set to 256.

Background: I'm a bit new to RPi and OpenELEC, and I'm having an issue with a particular video that, when played, it only plays the audio (not the video). It's a video on YouTube (playable using the YouTube add-on) and I've even downloaded it (using the same add-on) but it's the same: no video, just audio. On my desktop computer, it plays fine. Also, the video is a low-quality video (240p), and I've no problem playing high-quality videos on my RPi. But then, I've read on some thread at OpenELEC forum that other user had this issue and solved it raising gpu_mem to 256. In my config.txt is set to that value, but the dropdown still shows values up to 128.

Edit: this may be a codec issue, but so far, I've had no problems playing many, many other videos on YouTube.

**Comment by lurch** [comment]
To help people diagnose this problem, could you provide a link to the actual YouTube video that's causing you problems? ;-)

**Comment by maniqui** [comment]
Yes, sorry.
Here it is:
http://www.youtube.com/watch?v=z-3YZsSdQNQ

I wonder if this issue may be related to codecs. I know (but really, not in detail) that the RPi doesn't play some filetypes without buying/installing some proprietary codecs.
