### ISSUE TITLE
[Request] Prevent boot once

### ISSUE THREAD

**Issue by andriy2** [maxnet/berryboot#533]
Set `nobootmenutimeout` once from file `/berryboot/data/preventboot` which will disable boot menu timeout and won't boot.

Why?
I use instant boot default OS with `bootmenutimeout=0` and using `/berryboot/data/runonce` to boot another OS, but sometimes I need to go to boot menu (install new OS, etc) and the only way is edit `/boot/cmdline.txt` before istalling and revert it after.

**Comment by maxnet** [comment]
Sorry, but I don't see any advantage above editing cmdline.txt which is easy to automate with sed as well.
