### ISSUE TITLE
9.29 release broke cifs mounting

### ISSUE THREAD

**Issue by randomgitname** [maxnet/berryboot#536]
mounting from console: no device error regardless of settings used.
Rolled back to 9.9 release, cifs resumed working.

ps. it would be super cool if we could pass iscsi and cifs mount commands from cmdline.txt when booting from pxe. Alternatively make sure when pxe booting to pull the rest of the files from the tftp server.

thanks for this cool project, soon we will not need a flash card again.

**Comment by maxnet** [comment]
Recall newer kernel versions use a different cifs version by default.
May need to pass whatever version you would like to use as parameter when mounting.

**Comment by randomgitname** [comment]
Yeah, i was already doing that.
mount -t cifs -o username=guest,vers=1.0 //IP/share/path /mnt/cifs
this works on 9.9, fails on 9.29. I've tried many variations of the mount command none seem to work on .29. 
cifs is working for you?

**Comment by maxnet** [comment]
Yes, works for me.

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.72v7-aufs #1 SMP Sat Sep 29 19:45:02 CEST 2018 armv7l GNU/Linux
pi@raspberrypi:~ $ sudo mount -o user=admin //192.168.178.123/surveillance /mnt
Password for admin@//192.168.178.123/surveillance:  **************
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
pi@raspberrypi:~ $ sudo mount -o user=admin,vers=1.0 //192.168.178.123/surveillance /mnt
Password for admin@//192.168.178.123/surveillance:  **************
pi@raspberrypi:~ $
```

I get "Operation not supported" if not downgrading to lower CIFS version, though.
If you get a different error message, there may be another issue.
Kernel modules do load correctly, e.g. `lsmod` is not empty?

**Comment by randomgitname** [comment]
Loaded .29 berryboot, Edit menu, enable console and switch to command line. 
login as root.
uname -a: berryboot 4.14.72v7-aufs
lsmod is EMPTY.
Mount command fails with"No Such Device" doesn't matter what version of cifs is called.
If I intentionally put in a incorrect filesystem path it errors with no file/directory.

.9 berryboot same steps.
uname berryboot 4.14.67v7-aufs
lsmod is not empty, 13 modules loaded.
mount works as expected.

**Comment by maxnet** [comment]
>lsmod is EMPTY.

Make sure you extracted everything in the berryboot .zip to the FAT partition, including cmdline.txt

**Comment by macmpi** [comment]
@randomgitname how did you upgrade your install?
If you did it manually, you need to extract new `shared.tgz` after first boot under console as [per this](https://github.com/maxnet/berryboot/issues/371#issuecomment-305324386)?.
If not, your upgrade will not have matching module folder...

**Comment by randomgitname** [comment]
Mac nailed it. User error.
