### ISSUE TITLE
Support for big disks using GPT?

### ISSUE THREAD

**Issue by diegoherranz** [maxnet/berryboot#538]
Hi,

I wanted to boot a Raspberry Pi from a big (4TB) hard drive which, given the size, needs to use a GPT partition table.

As far as I'm aware, the built-in ROM code on the Raspberry Pi 3/3+, only supports MBR and not GPT.
So, I was planning to use Berryboot to boot from the SD first and then continue from the HDD.

Does berryboot support GPT partition tables and big disks (e.g. 4TB)?

Many thanks!

**Comment by maxnet** [comment]
No.
I do not have USB drives that big.

**Comment by diegoherranz** [comment]
Thanks for your reply.

I'll stick with 2TB, then.
Any plans to support GPT in the future?

Thanks again!

**Comment by maxnet** [comment]
No plans in the short term.
Don't like to release stuff, I cannot test.


If you are adventorous you can try changing the source yourself though.
Probably requires adding `--label gpt` to the sfdisk options here: https://github.com/maxnet/berryboot/blob/berryboot2018/BerrybootGUI2.0/driveformatthread.cpp#L306
and perhaps changing the partition type of the FAT partition (currently 0E) to whatever GPT GUID it needs to be instead.

**Comment by diegoherranz** [comment]
> Don't like to release stuff, I cannot test.

Sounds like a good strategy :)
However, you don't need a big disk to test GPT. It can be used in "small" (<2TB) disks too.

> If you are adventorous you can try changing the source yourself though.

Thanks for the information of what to change. I may give it a try and if so, I'll let you know.
I've also seen I could perhaps try a hybrid MBR/GPT (without berryboot).

Thanks again!

**Comment by symbios24** [comment]
it will be good to add real support for NTFS

**Comment by diegoherranz** [comment]
Please note that NTFS and GPT/GBR are completely independent/unrelated things as far as I'm aware.

**Comment by maxnet** [comment]
Berryboot 2018-11-28 should support GPT (not extensively tested)
