### ISSUE TITLE
BerryBoot v2.0 Error downloading distribution list from Internet behind proxy and web filtering

### ISSUE THREAD

**Issue by mariohi** [maxnet/berryboot#54]
Hi, I noticed previous ticket was closed, but my situation is little different: I'm getting this error in school where I work  We are behind proxy, and we have filtered traffic, but if I know what addresses / ports are required to download images I can get it unblocked. From other Pi's on Wheezy I can install with no problems.

**Comment by maxnet** [comment]
List of mirrors is dynamic and subject to change.
You will need uncensored Internet access, or copy the image files to USB stick if you wish to use Berryboot.
