### ISSUE TITLE
Move (or at least create) an OS to a partition of an USB-attached external HDD

### ISSUE THREAD

**Issue by FlipeGarcia** [maxnet/berryboot#55]
I have a HDD with one free partition waiting to have the OSs for the Raspberry stored on it. However, I don't see the manner to select the partition and instead it appears that I can only select the whole HDD in Berryboot with the threat that the whole HDD will be formatted, which I most certainly don't want to happen. Is there any manner to select a partition within the HDD to host the OSs?

**Comment by maxnet** [comment]
Nope.
We only support using an entire disk.

Resizing existing partitions and the file systems on them is problematic.
