### ISSUE TITLE
No Soundcard found

### ISSUE THREAD

**Issue by Quester1** [maxnet/berryboot#550]
Hello,

i had an running System with an old Berryboot Version. Today I updated the files on the SD Card to get the new Berryboot.

Now i have the Problem, that the internal soundcard of the Raspberry is not recognized.
 Operating System: Raspbian GNU/Linux 9 (stretch)
 Kernel: Linux 4.14.83v7-aufs

aplay -l
aplay: device_list:270: keine Soundkarten gefunden ...

In the config.txt is the line
dtparam=audio=on

I have no idea how to get the soundcard working.

**Comment by maxnet** [comment]
>Today I updated the files on the SD Card to get the new Berryboot.

Make sure you also overwrote cmdline.txt, and select "use existing files" during installation.

**Comment by Quester1** [comment]
Perfekt support. I copied three old files. cmdline.txt, config.txt and uEnv.txt
That was the Problem. Now i overwrote all files and did as you said. But after that I had the Problem that there was a failure that says, that there are no files on sda2. Then I modified the comandline.txt to datadev=iscsi
And now it works.
Thank you very much.
