### ISSUE TITLE
BerryWebserver cannot use Wifi on Rpi Zero W

### ISSUE THREAD

**Issue by fantasydr** [maxnet/berryboot#553]
I've installed BerryBoot for my Rpi Zero WH (same as W, just added GPIO headers).
It works fine in BerryBoot menu, I could connect to Wifi and download OS from internet.
The Raspbian lite works, I could setup the wifi by editing /etc/network/interfaces .
(uname showing Linux raspberrypi 4.14.83-aufs #1 Wed Nov 28 23:06:53 CET 2018 armv6l GNU/Linux)

But BerryWebserver could not connect to Wifi. Logs showing "sending discover" 3 times then "no lease, failing".

The wlan0 device could be manually bring up by 'ifup wlan0', ifconfig also showing the info, but it won't connect to my router, and won't get IP by DHCP. If i tried to use static IP, the IP shown but it still won't connect. 

The ifconfig output, there is no RX/TX packet and no RUNNING flag.
```
wlan0   Link encap: Ethernet HWaddr <MAC of my Zero W, which is correct>
        UP BROADCAST MULTICAST MTU:1500 Metric:1
        RX packets:0 errors:0  dropped:0  overruns:0  frame:0
        TX packets:0 errors:0  dropped:0 overruns:0  carrier:0  collisions:0 txqueuelen:1000
        RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
```

The /etc/network/interfaces content is:
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto wlan0
iface wlan0 inet dhcp
wpa-ssid myssid
wpa-psk mypw
```

I also tried static ip, or using something like
```
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```
All of these methods won't work. There is no error from ifup/ifdown/ifconfig, seems udhcpc cannot get IP, but i guess it didn't connect to router at all.

lsmod showing
```
snd_bcm2835            23106  0
brcmfmac              273911  0
brcmutil                9464  1 brcmfmac
snd_pcm                89619  1 snd_bcm2835
snd_timer              22424  1 snd_pcm
snd                    60383  3 snd_timer,snd_bcm2835,snd_pcm
cfg80211              542121  1 brcmfmac
rfkill                 21483  6 bluetooth,cfg80211
uio_pdrv_genirq         3686  0
uio                    10089  1 uio_pdrv_genirq
fixed                   3001  0
```

It seems the brcmfmac module is there. 
Did I miss anything or does the BerryWebserver not support Zero W?

Thanks for your reading and thank you for providing the awesome BerryBoot.

**Comment by symbios24** [comment]
Hi,The berrywebserver is very old and needs updating probably that is the reason its not working.
try with the apt-get update/upgrade commands

**Comment by fantasydr** [comment]
> Hi,The berrywebserver is very old and needs updating probably that is the reason its not working.
> try with the apt-get update/upgrade commands

Hi, since the BerryWebserver is a customized Linux which didn't have  any package manager, there is no way to run apt-get or upgrade.

And I've checked the version by uname -a in the console, the BerryWebserver is build on top of Linux 4.14, which is almost the latest build.
```
Linux berrywebserver 4.14.83-aufs #1 2018/11/28 armv61
```

I guess there must be somthing missing or it didn't support Zero W in the first place?

**Comment by maxnet** [comment]
berrywebserver is indeed not maintained.

Kernel used belongs to Berryboot, so will always be recent regardless of distribution booted.

**Comment by symbios24** [comment]
install apt-get and try to update

**Comment by maxnet** [comment]
symbios24: apt-get is a Debian thing.
There is no apt-get on custom buildroot images.

**Comment by symbios24** [comment]
apt-get exist in almost all linux distributions eg debian/ubuntu/xubuntu/lubuntu

**Comment by fantasydr** [comment]
Thank you maxnet! Now I knows I misunderstood the way BerryBoot working.
I'll try to build a small webserver by BootBuild later. Issue closed :)

BTW, @symbios24 thank you anyway but you might not know the issue properly. Ubuntu is based on Debian, apt-get is for deb package which is a Debian thing that BerryWebserver do not have. There is no point to add more stuffs for BerryWebserver since its aim is a slim Linux build.
