### ISSUE TITLE
Edit kernel module

### ISSUE THREAD

**Issue by taravasya** [maxnet/berryboot#556]
Hi! I need to edit file from linux kernel sources (/sound/usb/quirks.c), to fix the problem with my USB-DAC.

I successfully did it on a single-boot operating system. To do this, I downloaded the source code of my system’s kernel, re-compiled this library, and then replaced the snd-usb-audio.ko file in the file system of my operating system.

Now I want to do the same on a multi-boot system using the berryboot.

I understand correctly that guest operating systems in any way use the berryboot kernel?
Does this mean that the berryboot kernel modules are also used by them?

If all this is true, from which kernel sources repo do I need to download sources, in order to compile this module(snd-usb-audio.ko), compatible with the latest version of berryboot?

Thank you!!!

**Comment by maxnet** [comment]
Berryboot uses the rpi-4.14 branch from https://github.com/raspberrypi/linux

If you you have an unified diff .patch file with your changes to /sound/usb/quirks.c : 
- open configs/device_pi2 in a text editor
- add the path to your patch file to BR2_LINUX_KERNEL_PATCH
- ./rebuild-kernel.sh device_pi2

**Comment by taravasya** [comment]
You mean clone your git and build berryboot from scratch, right?
I cant to rebuild only:
`make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules SUBDIRS=sound/usb`
from:
https://github.com/raspberrypi/linux
and replace this module in shared.tgz?
(sorry I will can to check this only tomorrow)) )

**Comment by maxnet** [comment]
Might work as well.
But letting Berryboot rebuild the entire kernel ensures you have the exact same version as the rest of the kernel, and not some different git commit.

**Comment by taravasya** [comment]
Thanks a lot! A did it. Work like a charm ))
