### ISSUE TITLE
[question] openvpn and bluetooth

### ISSUE THREAD

**Issue by DarthRaver** [maxnet/berryboot#566]
I can not get openvpn and bluetooth to work in raspbian with berryboot, while it is working fine on an normal raspbian image.
Are there extra steps necessary to get it working, is it a bug, or just not supported?

**Comment by maxnet** [comment]
As long as you do not have configured special network settings such as a static IP in Berryboot, the configuration used should be the same as plain Raspbian. So things like openvpn should also work the same.

Not sure why it does not.
Can you be a little bit more specific than that it does not work?

**Comment by DarthRaver** [comment]
I didn't know that i was supposed to run this command after updating berryboot:

`gzip -dc /boot/shared.tgz | tar x -C /mnt/shared`

So now Bluetooth seems to be working, and i guess (haven't tried yet) openvpn will also.
