### ISSUE TITLE
ssh enable option for OS

### ISSUE THREAD

**Issue by poudenes** [maxnet/berryboot#574]
Hi All,

Maybe a good idea to have a option to enable SSH when you install a linux distribution?
Only thing that has be done is:

touch ssh on the boot partition.

When berryboot is done with the install it will put this file on the /boot/ of the os, when you startup then you directly have access using SSH

**Comment by maxnet** [comment]
Sorry, but Berryboot is for GUI users.

**Comment by poudenes** [comment]
Ok... So fully headless configuration is not possible then... Thanks
