### ISSUE TITLE
Berryboot available for Raspberry PI 4 ?

### ISSUE THREAD

**Issue by rwaaren** [maxnet/berryboot#577]
I would very much welcome to be able to connect my RPI-4 to my synology storage and make full use of the Gb ethernet. What needs te be done to achieve this ?

**Comment by symbios24** [comment]
Hi, You have to wait until a berryboot version is available to support Rpi4

**Comment by rwaaren** [comment]
In understand that part but in the readme there is a subject titled

> To add support for a new ARM device


Thing is that the level of my Linux skills is not high enough to use that as a cookbook to actually do the job myself. Maybe one of the other visitors of this github can give me some guidance on the steps to be taken.

**Comment by symbios24** [comment]
its very complicated you need expert skills to do this not even i can do it,better to wait for a new version

**Comment by maxnet** [comment]
Not sure if I'll add support for Pi 4 soonish.
May wait for a 64-bit kernel to materialize, instead of the LPE stop gap.

**Comment by macmpi** [comment]
hum...seems like 64-bit kernel is [still a long shot](https://github.com/raspberrypi/linux/issues/3024#issuecomment-506257948) according to Phil.
Not sure what LPE stop gap refers to?

**Comment by symbios24** [comment]
You can release for now a 32bit version with Raspberry Pi 4 support the latest kernel is 4.19.56

thanks

**Comment by maxnet** [comment]
>Not sure what LPE stop gap refers to?

Pi 4 has memory mapped peripherals that are located above 4 gb in memory.
They are currently using techniques similair to what is PAE on x86 to make that work.

So Pi 4 uses different kernel than Pi 2-3.


Rather go for upstream 64-bit kernel when that becomes usable.

**Comment by symbios24** [comment]
so whoever has RPi 4 cannot use it for a long time with berryboot, also when he will be able to use it
it will work only with 64bit os am i correct?
my opinion is that 64bit architecture has a lot of bugs/problems,even in modern os like windows 10

**Comment by maxnet** [comment]
OS can be both 32-bit or 64-bit under 64-bit kernel.

And long time is relative.
The timeline the Raspbian guys want to switch over to 64-bit userspace is not the same when there will be a usable kernel.

**Comment by symbios24** [comment]
yes but the 32 bit kernel will perform faster and more stable.
also the max memory 32bit can see is 4gb so i dont see any problem here nor will be any speed improvement only the os will perform slower due to heavier 64 bit architecture
have you tried the latest kernel with Rpi4 with a beta berryboot version you created ?
also there is not any significant number of 64bit os`es for raspberry since the Rpi3 release and i dont think there will be

**Comment by macmpi** [comment]
> So Pi 4 uses different kernel than Pi 2-3.

I see, that's the 7l derivative.

Some of key big P4 benefits are around PCI Express bus & direct Ethernet interfaces: no more dreadful USB sharing and USB problems that affected previous models...(but might be others).
Should greatly help for lots USB peripherals (DACs, disks,...), streaming,...
Definitely interesting for demanding distributions such as LibreELEC and al. under berryboot.

**Comment by symbios24** [comment]
before you can release a 64 bit version a 32 bit version can be handy so people can start using their Pi 4 for now

thanks

**Comment by hellyberry** [comment]
If there is a (dedicated/experimental) built image, I could test it on Pi 4 (4 GB).

Raspbian-kernel since June 24 supports Pi4.

**Comment by symbios24** [comment]
more memory does not do any great different except in browsers like chrome

I hope soon a new berryboot version will be released, its only a firmware update does not need any other special things, to get finally Rpi 4 usable

**Comment by maxnet** [comment]
>its only a firmware update does not need any other special things

Need different kernel.
- LPAE stop gap. better wait for proper arm64

Any old OS images that do anything graphically accelerated (e.g. Kodi) will not work.
- Need to switch over to the fkms OpenGL stuff.
Which is another stop gap in between using the full KMS driver. May also be better to wait for that.

**Comment by symbios24** [comment]
but there is already a new kodi version that support the Rpi4 who is going to use an old kodi on a new RPi 4 a new raspbian with Rpi4 support etc
Opengl was not working with berryboot in raspbian anyway

Just try a 32 bit version with a firmware update and i will test it with as many images possible

**Comment by maxnet** [comment]
>but there is already a new kodi version that support the Rpi4 who is going to use an old kodi on a new RPi 4 

Existing users?

**Comment by symbios24** [comment]
the new kodi is out for all Rpi boards old and new
if someone wants to use an ancient os and is not working there is always the previous bb version
netherless Rpi4 is not supporting any older operating systems
also you can release a version only for 4 if you think its going to be a problem for old os`es or boards
as i said i can test it and report back

**Comment by h4de5** [comment]
as far as i understood, the kodi/libreelec team has worked together with the rpi foundation for over 6 months to get that version ready on day one .. so I am not sure if you are aware of what you are asking here? You could at least give the owner another 6 months starting from the launch to produce a bearly working alpha version, too...

anyways - just posting here to keep me updated on that issue. if there are images to test, let me know.

**Comment by symbios24** [comment]
Im asking for a 32bit bb version to support Rpi4 and i can test it to make sure it works 100% in 6 months Rpi5 could be released...

**Comment by SargonofAssyria** [comment]
I got "Buster" running on a RPi 3B(+) booting from an iSCSI LUN, so a RPi 4 should run too.
Unfortunately I still have to use a SD-card because I cannot get PXE in my Synology running, it won't fetch the bootbin. The SD-card does not need to be mounted once the Pi is up, only needed to get the LUN mounted.

**Comment by actraiser30** [comment]
any progress for the raspberry pi 4 version??

**Comment by IRawXI** [comment]
Just as an update, it looks like they are testing a 64bit kernel, but it seems still experimental: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=250730

And a dumb question: When BB is running on a 64bit kernel, is it still possible to have one version for all Raspberry Pis? (As in, have 32- and 64bit-kernel versions and load whichever is appropriate?)

**Comment by maxnet** [comment]
>And a dumb question: When BB is running on a 64bit kernel, is it still possible to have one version for 
>all Raspberry Pis? (As in, have both versions and lod whichever is appropriate?)

64-bit kernel should also run on Pi 3.
Not sure if it is worth continuing supporting older Pi.

**Comment by macmpi** [comment]
> Not sure if it is worth continuing supporting older Pi.

Yes it is definitely worth!...
Hope support of PiZero, Pi2 and al will continue: thanks for consideration!

**Comment by codekoch** [comment]
We are using many Pis in school in combination with berryboot and a tuned version of raspbian (-> https://github.com/codekoch/mediakit_RaspberryPi).  Now we are going to change the old 3b+ Pis to the new version 4 also because of the better performance. Therefore we also looking forward to a new berryboot build. Or is there any way to build a berryboot version on our own?

**Comment by actraiser30** [comment]
better stay with the Pi`s 3 its almost 4 months that the pi4 is out and still no berryboot update,and i dont think anytime soon will be any.

**Comment by maxnet** [comment]
Added a 64-bit Pi 4 edition to the download page.
It is good enough for Raspbian (32-bit) and OpenSuse (64-bit)
Not in an usable state for Kodi yet.

**Comment by rwaaren** [comment]
Thank you very much !
Installation worked right out of the box. (Using iSCSI connection to Synology IQN with BTRFS)
Do you want to keep this issue open or is it OK to close ?

**Comment by Crayyy** [comment]
I got BerryBoot running on a Raspberry Pi4 with 4gb ram and have Debian Buster Raspbian FULL 2019.10 and BerryWebserver installed on it now running good BUT I would REALLY love to get Kali Linux  loaded on it also, They now have a Pi4 compatible version available :) Here is the link to their download page for all of their ARM images :) https://www.offensive-security.com/kali-linux-arm-images/#1493408272250-e17e9049-9ce8
