### ISSUE TITLE
Wi-Fi doesn't activate.

### ISSUE THREAD

**Issue by zackp30** [maxnet/berryboot#58]
I am trying to get Wi-Fi to activate with the Realtek Semiconductor Corp. RTL8188SU 802.11n WLAN Adapter but it doesn't seem to even turn on (I can see that the LED on the adapter is not turning on). EDIT: This is confirmed to work on a seperate Raspbian install and seperate OpenELEC install.

**Comment by maxnet** [comment]
The new Berryboot release has a newer kernel version, try again with that. If still does not work, reopen issue.
