### ISSUE TITLE
Cloning

### ISSUE THREAD

**Issue by radimkohout** [maxnet/berryboot#580]
Hi,
I want to clone bb to create booting system for only my own OS's. My question is, what the license requirments are? I don't understand it.
Thanks 
radimkohout

**Comment by maxnet** [comment]
See: https://github.com/maxnet/berryboot/blob/berryboot2018/LICENSE.berryboot

Other than the requirement to include the license terms somewhere, there aren't much restrictions.
Change the Berryboot code to your liking.

**Comment by radimkohout** [comment]
Thanks. This "somewhere" is just as it is, or I have to change something?

**Comment by maxnet** [comment]
As-is as far as I am concerned.
But do double check the license terms of other software you may be using.

**Comment by radimkohout** [comment]
Thanks.
