### ISSUE TITLE
Could you please include the most recent image of Raspbian (2013.07)?

### ISSUE THREAD

**Issue by MrLinDowsMac** [maxnet/berryboot#59]
I read somewhere that you have a file pointing to a some kind of repository http://dl.berryboot.com/distro.smime, 

I figured out that you don't have the most recent of raspbian (2013.07), you just have a earlier one (2013.05). 

Could you add it please?  Some stuff (like symlinks or something) gets broken if you just upgrade from (2013.05)

This update will be highly appreciated.

**Comment by learntofly83** [comment]
Hi,

I am not affiliated with the author of BerryBoot or the project. 

I have just discovered this project and after noticing some of the images were a little out of date, I created my own BerryBoot images, Raspbian's July release and OpenELEC's 3.2.0 release (released just 2 hours ago!) are available on my Dropbox. 

Drop them into the /images/ folder on the ext4 partition or follow the "official" route of instaling them from a USB stick

To the best of my knowledge these images are fully working (they are on my pi) however I give no guarantees :)

https://www.dropbox.com/l/zWs1IvUiOFCnjzSXZOxPob

**Comment by mrKrzysztoff** [comment]
Thank you @learntofly83 ! I was trying to make images that work with berryboot, but im lost. I'm newbie to linux, sa i try do this with tutorial http://www.howtogeek.com/141325/how-to-multi-boot-your-raspberry-pi-with-berryboot/ but i failed. Anyway thank you to do this images!

**Comment by maxnet** [comment]
Upgraded Raspbian
