### ISSUE TITLE
Berryboot not working after Raspberry Pi 4 firmware update

### ISSUE THREAD

**Issue by gordonfreemanhr** [maxnet/berryboot#597]
So, I tried to use Berryboot to get a Ubuntu 19.10 Server/Lakka dual boot setup on my Raspberry Pi 4. I read that it’s advisable to update the Pi’s firmware first. I booted Raspbian and performed:

sudo apt updata
sudo apt full-upgrade

which worked fine. Reboot failed, returning „can’t find boot partition” error.

Since then, the SD card is unusable, no matter how many times I format it.

**Comment by maxnet** [comment]
You probably just formatted the FAT partition.

Unzip the berryboot .zip file on the SD card again.
Select "use existing files" during installation, and you should have your files back.

**Comment by gordonfreemanhr** [comment]
I made it work again by deleting all existing partitions and creating a new, FAT one. Then I copied the Berryboot files over again and it works well. Case closed.

Thanks for the help!

**Comment by maxnet** [comment]
Next time: it should also work if you do not format anything, but just copy the Berryboot files over again.
No need to reformat anything.
