### ISSUE TITLE
PI-4 does not find boot after apt update / upgrade

### ISSUE THREAD

**Issue by rwaaren** [maxnet/berryboot#598]
I installed beryboot for Raspberry PI-4 and it worked out of the box, using my Synology NAS to store OS and data.
After a standard sudo apt update / sudo apt upgrade, Berryboot could no longer find some necessary files on my SD needed to continue the boot process. During the sudo apt upgrade I noticed that many files in /boot were touched and probably something essential was overwritten causing Berryboot to fail.

The work-around I used:

- Restore OS / data on my NAS using a snapshot from before apt upgrade.
- Restore /boot on SD card from copy of Berryboot SD without iscsi.sh and cmdline.txt
- Booted Raspberry PI-4 // Now ok again
- sudo apt-mark hold raspberrypi-kernel
- sudo apt-mark hold raspberrypi-bootloader
- sudo apt-mark hold firmware*

- sudo apt update / sudo apt upgrade
- Booted Raspberry PI-4 // Still OK
 

My two questions:
- Is the the preferred method.
- What kind of problems to expect if I never update kernel / bootlader / firmware 

Many thanks for your work so far !!

**Comment by maxnet** [comment]
>During the sudo apt upgrade I noticed that many files in /boot were touched and probably something 
>essential was overwritten causing Berryboot to fail.

Yeah. The "upgrades" are actually OLDER then what ships with Berryboot, and that is a problem.

>What kind of problems to expect if I never update kernel / bootlader / firmware

None
If you update Berryboot once in a while, you also get newer files through that.

**Comment by rwaaren** [comment]
OK. Thx !
