### ISSUE TITLE
Use partitions instead of squashfs images

### ISSUE THREAD

**Issue by Poulpatine** [maxnet/berryboot#60]
Hi,

would it be possible to have an option which would permit us to use Berryboot as a simple bootloader in order to use systems installed on other partitions of SD card instead of have systems on squash fs images ?

Thanks.

**Comment by maxnet** [comment]
You can use NOOBS instead if you prefer booting partitions instead of squashfs images.

Berryboot prefers squashfs images as they are easier to work with than partitions. Especially if you want to add and delete OSes later on.
