### ISSUE TITLE
iSCSI target does not have any partitions

### ISSUE THREAD

**Issue by bramstroker** [maxnet/berryboot#605]
I am trying to setup Berryboot on a Raspberry PI 4 with a iSCSI LUN on my Synology NAS.
Followed the instructions as described [here](https://www.berryterminal.com/doku.php/storing_your_files_on_a_synology_nas_using_iscsi) but cannot get it to work smoothly.

When berryboot is starting the following error message is thrown:
![Desktop screenshot](https://user-images.githubusercontent.com/2345875/71691392-958c2700-2da7-11ea-9d49-30a57f08f355.png)

After I click "OK" berryboot will resume and actually find the image OS on the iSCSI target and boot succesfully. Also in Synology iSCSI manager the raspberry PI is listed as a connected client to the target.

I need to run the PI headless, so it's not feasible I need to manually dismiss the error dialog to get the PI to boot. 
I have no clue what causes this issue or how I need to debug this.

Also tried setting it up on a Raspberry PI 2 with a newly created LUN, but get exactly the same error.

**Comment by h07d0q** [comment]
Did you solve the problem? I have the same problem with almost every raspberry reboot. If I notice that the server is not running, I have to connect via VNC and klick "OK" to proceed. Is there any setting to skip this message after some time or not raise this error?

**Comment by heuvep** [comment]
Is there a solution for this problem because i have the same problem?
