### ISSUE TITLE
WIndows, FAT32 no booting

### ISSUE THREAD

**Issue by slrslr** [maxnet/berryboot#607]
I used microSD formated as FAT32 using WIndows's "diskpart" tool (quick format):
diskpart
select disk x
clean (to remove partition scheme i quess)
create partition primary
format quick
quit

I also used different new microSD drive formated in the factory to FAT32.

Using 7zip i extracted content of the berryboot-20191005-pi4.zip into both microSD drives.
I tried both in RPi4, but none boots. no signal. But when i put different OS sd card, it boots OK... can you please give me an advice for MS Windows?

**Comment by dolbi13** [comment]
i think that windows only runs on ntfs that's why u are facing that issue

**Comment by actraiser30** [comment]
Hi,if you have a 4gb RPi4 its not booting like that,there is a fix in here in another thread

**Comment by slrslr** [comment]
OP here, **i think that the problem was with the bad connectivity of the HDMI cable**, i am sorry.
What worked is to quick format the drive on Windows as a FAT32 and then copy over the files. (i have not extracted these directly to SD, but first to HDD then to SD card). I tried https://www.sdcard.org/downloads/formatter/index.html too and may also work.
