### ISSUE TITLE
Shared partition between different OS?

### ISSUE THREAD

**Issue by rajesh-s** [maxnet/berryboot#609]
Please pardon me if this has already been addressed. I checked under issues & documentation and could not find any information on this.

Can a partition created on the "/" space be shared between different OS? I have two OS installed on a RPi3 and when I use "df -kh", I see there's a lot of space with filesystem as ```None``` probably because of no partitions created. Are there any guidelines on handling different partitions with BerryBoot?

**Comment by maxnet** [comment]
All operating systems already share the same partition.

**Comment by rajesh-s** [comment]
Okay thanks. 

So I can create a single partition with the entire space that shows up and it can be accessed from both the OS?

**Comment by maxnet** [comment]
Raspberry Pi needs two partitions to be able to boot.
But all operating system files are already in one giant partition.
Nothing you need to do.

**Comment by rajesh-s** [comment]
Thank you for your time.
Just to clarify, I'm talking about the data partitions here (and not where the OS are installed). For eg. Can I have a single ext4 partition to house all my files and share them between OS? Because I don't see a partition other than for the OS installs.

**Comment by maxnet** [comment]
Can mount the main partition somewhere.

sudo mount LABEL=berryboot /mnt

**Comment by rajesh-s** [comment]
I believe in my case berryboot is already mounted. Here's the output of df -kh for reference

https://imgur.com/a/FOIEN5m

The highlighted space is what I'm trying to access across operating systems

**Comment by rajesh-s** [comment]
Got it! Thanks. I mounted the partition like you mentioned and created a new directory underneath for shared files with updated permissions.
