### ISSUE TITLE
[Docs] Berryboot As Bootloader 

### ISSUE THREAD

**Issue by arky** [maxnet/berryboot#61]
Is it possible use berryboot to boot OS images from microSD card ie. Cynogenmod custom builds, Linux ARM yocto builds. If yes, Is there any berryboot custom boot entries documentation. 

PS: Using Berryboot as bootloader on MK802(A10 SOC chip) HDMI stick.

**Comment by maxnet** [comment]
http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

**Comment by arky** [comment]
@maxnet Thank you!
