### ISSUE TITLE
Add arkOS

### ISSUE THREAD

**Issue by peakwinter** [maxnet/berryboot#62]
Hi there,

My name is Jake and I'm the main developer behind [arkOS](https://arkos.io), a new distro designed to help people easily self-host their data from a Raspberry Pi. A user [contacted me](https://bbs.arkos.io/t/add-arkos-to-the-berryboot-project/89/2) to see if it would be possible to add arkOS as an install option to BerryBoot. It sounds like a cool idea to me, should be easy to make it compatible as it is Arch-based and very similar to ALARM, and I would be able to produce alternate images should they need to be changed in any way to be compatible.

Feel free to contact me if this sounds good to you.

Thanks,
-J

**Comment by shaula** [comment]
would love to see progress on this :-)

**Comment by maxnet** [comment]
Anything Arch based is a no-go.
Their /lib -> /usr/lib symlink hackery interferes with us sharing the kernel modules located at /lib/modules between all distributions installed.
