### ISSUE TITLE
Kodi "hang" for 3:45 on reboot

### ISSUE THREAD

**Issue by owl770** [maxnet/berryboot#620]
I'm not sure if this is a Berryboot issue or not but gotta start somewhere...
I am running Berryboot (from berryboot-20190612-pi0-pi1-pi2-pi3) on a RPi3 using iscsi on a Synology DS414. Raspbian buster works fine (including reboots).
I have tried a number of Kodi variants (LibreElec v9.2.1 stable, LibreELEC Dev (Milhouse) 2020.03.15). During normal operation, everything works fine.
When you click on the reboot option of the Kodi shutdown menu, the screen freezes for a second or two (as you expect) and then the screen goes blank. It stays this way for 3 minutes and 45 seconds and then reboots. It does this 100% of the time. I can't see anything in the Kodi debug log that may indicate the cause.
Does Berryboot log anything anywhere?
Has anyone else seen this issue?
Anyone got any suggestions on how to investigate further?
Thanks.

**Comment by maxnet** [comment]
Suspect the shut down sequence releases the DHCP lease and shutsdown the Ethernet interface, which it should not do if it still needs to access file on iSCSI afterwards.
Not all operating systems are iSCSI aware.

**Comment by owl770** [comment]
Thanks for the hint - from looking at my DHCP server, it appears that is exactly what is happening.
This may be a little heavy-handed but it works...referring to...

> https://forum.libreelec.tv/thread/1567-pxe-boot-stuck-on-reboot-shutdown/?postID=128387&highlight=ISCSI#post128387

Following these instructions...

`Copy the file "/usr/lib/systemd/system/connman.service" to "YOUR_STORAGE_PATH/.config/system.d"`
`Edit "YOUR_STORAGE_PATH/.config/system.d/connman.service" and add the following line to the [Service] section`
`ExecStop=/usr/bin/killall -9 connmand`
`I then ran "systemctl daemon-reload" and "systemctl enable connman" to get the proper symlink created under "YOUR_STORAGE_PATH/.config/system.d...".`
`Check that "systemctl status connman" displays the new service-file path in the second line.`

The LibreELEC system then shuts down and reboots in the normal time. Problem "solved".
