### ISSUE TITLE
Unable to produce a clean build for Pi4

### ISSUE THREAD

**Issue by benton** [maxnet/berryboot#622]
Hello.

I am enjoying this software quite a bit, but need to make a couple of tweaks, and am currently unable to perform a clean build for Pi4, as per [the instructions][1], using a host running the latest Ubuntu 18.04 Long-term Support release. 

Procedure:
---
1. Boot an Ubuntu 18.04 LTS Instance in AWS, from the Canonical source (account ID `099720109477`).
2. Login as `ubuntu`, and fully update the host:

       # Update system (and reboot for new kernel?)
       sudo apt update && sudo apt -y upgrade && sudo shutdown -r now

3. after reboot, login again, and install the [BuildRoot dependencies][2]...

       sudo apt -y install git build-essential python wget binutils \
           gcc "g++" patch bzip2 cpio unzip rsync file bc locales-all

4. and finally, perform a clean checkout and build for Pi4...
     
       # EC2 instances have more storage at /mnt
       sudo chown ubuntu:ubuntu /mnt
       git clone https://github.com/maxnet/berryboot.git /mnt/berryboot
       cd /mnt/berryboot
   
       export LANG=en_US.UTF-8
       export LANGUAGE=en_US.UTF-8
       export LC_ALL=en_US.UTF-8
       time ./build-berryboot.sh device_pi64

Expected Result:
---
Some files in `output`, beyond `cmdline.txt` and `config.txt`?

Actual Result:
---
     ...
     Hunk #8 succeeded at 881 (offset -4 lines).
     Hunk #9 succeeded at 941 (offset -4 lines).
     cp -r /mnt/berryboot/buildroot-2018.08/output/build/aufs-aufs4.19.17+/fs/aufs/ /mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y/fs/
     cp /mnt/berryboot/buildroot-2018.08/output/build/aufs-aufs4.19.17+/include/uapi/linux/aufs_type.h /mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y/include/uapi/linux/
     if [ -f /mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y/tools/perf/Documentation/Makefile ]; then printf "%%:\n\t@:\n" >/mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y/tools/perf/Documentation/GNUmakefile; fi
     for p in  ; do if test -d $p ; then PATH=/mnt/berryboot/buildroot-2018.08/output/host/bin:$PATH support/scripts/apply-patches.sh  /mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y $p \*.patch || exit 1 ; else PATH=/mnt/berryboot/buildroot-2018.08/output/host/bin:$PATH support/scripts/apply-patches.sh  /mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y `dirname $p` `basename $p` || exit 1; fi done
     /bin/sh: 1: aarch64-linux-gnu-gcc: not found
       HOSTCC  scripts/basic/fixdep
     /bin/sh: 1: aarch64-linux-gnu-gcc: not found
       HOSTCC  scripts/kconfig/conf.o
       YACC    scripts/kconfig/zconf.tab.c
       LEX     scripts/kconfig/zconf.lex.c
       HOSTCC  scripts/kconfig/zconf.tab.o
       HOSTLD  scripts/kconfig/conf
     ./scripts/gcc-version.sh: 26: ./scripts/gcc-version.sh: aarch64-linux-gnu-gcc: not found
     ./scripts/gcc-version.sh: 27: ./scripts/gcc-version.sh: aarch64-linux-gnu-gcc: not found
     ./scripts/gcc-version.sh: 29: ./scripts/gcc-version.sh: aarch64-linux-gnu-gcc: not found
     ./scripts/gcc-version.sh: 26: ./scripts/gcc-version.sh: aarch64-linux-gnu-gcc: not found
     ./scripts/gcc-version.sh: 27: ./scripts/gcc-version.sh: aarch64-linux-gnu-gcc: not found
     ./scripts/gcc-version.sh: 29: ./scripts/gcc-version.sh: aarch64-linux-gnu-gcc: not found
     init/Kconfig:17: syntax error
     init/Kconfig:16: invalid option
     ./scripts/clang-version.sh: 15: ./scripts/clang-version.sh: aarch64-linux-gnu-gcc: not found
     ./scripts/gcc-plugin.sh: 11: ./scripts/gcc-plugin.sh: aarch64-linux-gnu-gcc: not found
     scripts/kconfig/Makefile:104: recipe for target 'bcm2711_defconfig' failed
     make[3]: *** [bcm2711_defconfig] Error 1
     Makefile:534: recipe for target 'bcm2711_defconfig' failed
     make[2]: *** [bcm2711_defconfig] Error 2
     linux/linux.mk:553: recipe for target '/mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y/.config' failed
     make[1]: *** [/mnt/berryboot/buildroot-2018.08/output/build/linux-rpi-4.19.y/.config] Error 2
     Makefile:79: recipe for target '_all' failed
     make: *** [_all] Error 2

     real	77m3.936s
     user	149m46.696s
     sys	17m21.197s

  Full build log _(watch out, it's big!)_: [berryboot-screenlog.txt.gz](https://github.com/maxnet/berryboot/files/4416837/berryboot-screenlog.txt.gz)

---

For the record, I'm attempting to build from the current `HEAD` of the default branch:

    ubuntu@ip-10-0-0-114:/mnt/berryboot$ git log -1

    commit 9e129fd97e582db48b8a3af7aca56af21a4596f7 (HEAD -> berryboot2018, origin/berryboot2018, origin/HEAD)
    Author: Floris Bos <bos@je-eigen-domein.nl>
    Date:   Sat Oct 5 22:43:24 2019 +0200

       Basic Pi 4 support
       
       - Add 64-bit kernel for Pi 4
       - Add support for using different compiler for kernel than rootfs
       - Default to using overlayfs instead of aufs
       - Allow sourceforge mirror selection (for cases the default one
         is very slow)
       - Use squashfs shared.img for drivers instead of shared.tgz
       - Prevent udisks from auto-mounting berryboot partition by
         udev rule.

I guess running so-called "continuous integration" on a project like this is not really feasible, given that the above build took 77 minutes on an `m3.xlarge` Spot Instance! So there's probably no official build server for this repo, whose setup I could copy.

Given that unfortunate fact, if anyone has had recent success building this software, can you please respond with some similarly detailed description of your process?

Thanks in advance!

[1]:https://github.com/maxnet/berryboot#build-requirements
[2]:http://www.buildroot.org/downloads/manual/manual.html#requirement

**Comment by maxnet** [comment]
Need to install gcc-aarch64-linux-gnu package to build 64-bit kernel for Pi 4.
Userspace Berryboot is still 32-bit for compatibility with other models.
And buildroot only supports building single toolchain. So just using system compiler for building kernel.

**Comment by benton** [comment]
Thanks, that fixed it. 

There was one more missing utility on Ubuntu 18: `lzop`.

So, the current build process for 64-bit Pi 4 on Ubuntu 18.04 is:

1. on first boot

       # Update system (and reboot for new kernel?)
       sudo apt update && sudo apt -y upgrade && sudo shutdown -r now

2. after update and reboot

       sudo apt -y install git build-essential python wget binutils \
         gcc "g++" patch bzip2 cpio unzip rsync file bc locales-all \
         gcc-aarch64-linux-gnu lzop

       # EC2 instances have more storage at /mnt
       sudo chown ubuntu:ubuntu /mnt
       git clone https://github.com/maxnet/berryboot.git /mnt/berryboot
       cd /mnt/berryboot

       export LANG=en_US.UTF-8
       export LANGUAGE=en_US.UTF-8
       export LC_ALL=en_US.UTF-8
       time ./build-berryboot.sh device_pi64

Whole thing took about 77 minutes again, this time on a `c4.xlarge`. So, no real gain from more CPU. I'll probably be building quite a few times, so I'll try adding some more I/O instead.

I'm going to be running containers over a cluster of Pis, so my first tweak is to build the kernel with `CONFIG_CFS_BANDWIDTH=y` _(I've encountered the last of the issues listed [here][1] by another Pi cluster admin)_. So, do I just need to append that to `configs/kernel_config_fragment_pi64` and then `./rebuild-kernel.sh`?

Once more, thanks for your work on this!

- benton

[1]:https://github.com/jpeach/rpi#issues-and-workarounds

**Comment by benton** [comment]
Also, Amazon can boot ARM64 Instances now (though it's still new enough I couldn't manage a Spot Instance). Do you know if BuildRoot will skip the whole cross-compiler thing if it's not really required? That would _certainly_ speed up the build!

**Comment by maxnet** [comment]
Buildroot builds a 32-bit toolchain.
ARM64 cannot build ARM 32-bit executable natively.

**Comment by benton** [comment]
OK, thanks.
