### ISSUE TITLE
Need option to disable console

### ISSUE THREAD

**Issue by DJMatus23** [maxnet/berryboot#63]
Hi,

I have been using Berryboot for about a week and it has been great - while fiddling around, I enabled the console, which was set up on another TTY, which I couldn't test as I don't have a keyboard for my rPi (I know, why did I enable the console?) - anyway, now when I boot up, the display shown via HDMI is the console, and the only way to get to the graphical menu is via VNC.  Is there a config.txt or cmdline.txt setting I can change to disable the console, or to have the graphical menu show up on my TV?

Best regards
DJM23

**Comment by maxnet** [comment]
Remove "vncinstall" from cmdline.txt
