### ISSUE TITLE
Berryboot not Supporting Dual Monitors on Raspberry Pi

### ISSUE THREAD

**Issue by rmervine** [maxnet/berryboot#633]
I have noticed that when using berryboot, it doesn't appear that it passes on support for dual monitors. I tested this by using the exact same version of Debian Buster. If I boot with berryboot, the second monitor will have the rainbow image. But if I use another card and boot into Debian Buster, then I get both monitors. This is in despite of me not having to edit config.txt on getting it to work without Berry Boot. And when I compared both the config.txt with Berry Boot and with Debian Buster, I can't see any differences on why that second monitor doesn't generate.

Now there is something interesting I noticed here. Apparently tvservice can see the other monitor. In fact, I can shutdown the port using tvservice and the monitors turns off. It just seems that with berryboot there is a limitation of loading that second monitor at berryboot's load screen. And because of that, it never can display that second monitor correctly. Just to add, both monitors are the exact same model.

Is this by any chance a known issue? I searched the issues here and not seeing anything.

**Comment by theonetruemorty85** [comment]
I have the exact same problem using the Raspberry Pi 4 8gb model. Tried with multiple OSs and editing the config.txt file, but didn't get it to work. I can't find anything that mentions HDMI:0 and HDMI:1 AND Berryboot; maybe it doesn't have support for it since the rpi4 is newer; although there was a recent update to it that allows support for the 8gb model.

**Comment by StewartBeel** [comment]
I'm having the same issue.  Raspberry Pi 4 8Gb.  My dual screens work perfectly fine with Raspberry Pi OS if I boot directly to it, but as soon as I try using Berryboot, only HDMI 0 works.

I really would like to use multi-boot but without dual screen support I cannot use it.  A fix for this would be really appreciated.

**Comment by w4taw** [comment]
Add me to the list of those having this problem.  Stewart's comment's describes my problem exactly.

**Comment by hadadil** [comment]
+1

**Comment by gezeni** [comment]
Anyone heard of a fix/work around for this?

**Comment by carterme** [comment]
Exactly the same problem here, perhaps the developer could assign someone to fix this, as it is a major limitation.

Fixing this would be really appreciated.

**Comment by devonhg** [comment]
Same here.

**Comment by Schbatzafresser** [comment]
I'm in 2

**Comment by nesslinger-it** [comment]
We are using BerryBoot with Ubuntu 20.10 and encrypted SD-Card. We have the same problem. Using a second monitor would be a huge benefit, because we are using the Raspberry as VPN and RDP client.

**Comment by Neon-Ice** [comment]
Same here on pi4 8gb, 
but when I change the driver in config.txt to dtoverlay=vc4-kms-v3d-pi4 I do see 2 screens working, only problem is I now can not boot up any OS because after loading all the lines in console on 2 screens, all screens go black instead of showing logon-screen and need to unplug my pi4 from the power to restart,..

**Comment by shpegel** [comment]
I too am having this issue, Would love to use Berryboot but need dual monitors more.

**Comment by Geektoolkit** [comment]
Hitting this now, was about to do a video on how awesome berryboot was with a ras pad 3 but this really nerfs it. Any updates or workarounds?

**Comment by muddauber** [comment]
Same problem using Argon, Deskpi Pro and Berry Boot, one screen works the other is a rainbow screen.
Problem with Raspberry Pi (32 bit and 64 bit), Ubuntu, Manjaro.

**Comment by rmervine** [comment]
I'm going to end up just closing this issue. It's been well over 2 years since I reported the issue and no code has been updated for 2 years.

**Comment by muddauber** [comment]
Extremely aggravating that they don't fix this. BerryBoot would otherwise be a great service. I guess there is another option with WowWo or something like that.
