### ISSUE TITLE
berryboot does not boot on Raspberry Pi 4 - 8GB ram

### ISSUE THREAD

**Issue by aeslami** [maxnet/berryboot#637]
Hi,

I formatted my SD Card using Raspberry Pi Imager to FAT32. Downloaded berryboot for Raspberry Pi 4. Copied the berryboot files to SD Card but my pi won't boot.

Please ask me any questions you have for troubleshooting.
I am using macOS and Raspberry Pi 4 - 8GB Ram

Thanks in advance

**Comment by MariusQuabeck** [comment]
Hi,

what kind of error message do you see?
If it is about start4.elf file being invalid you can download all .elf and .dat files from this specific version https://github.com/raspberrypi/firmware/tree/a6c9b6b48ce86ef2527586a50760d52f1b33f642

This fixed it for me, although no mouse/keyboard, so I'm stuck as well :)

**Comment by aeslami** [comment]
@MariusQuabeck 
I got a error message saying start4x.elf is not compatible 0x0.
So I downloaded start4x.elf from the source you mentioned. I was able to boot but no mouse/keyboard control as you mentioned :(

**Comment by MariusQuabeck** [comment]
thank you for confirming this, I already opened a separate issue for this.
Feel free to merge or remove #638

I managed to usb boot Raspberry Pi OS on the 8 GB version but I'd prefer ubuntu and there is a berryboot image for it :) Let's hope this will get fixed soon.

**Comment by aeslami** [comment]
@MariusQuabeck 
I enabled VNC in berryboot config and used berryboot via VNC. I added an ISCSI target and installed Ubuntu 64bit successfully. I later used SSH to login to Ubuntu and the rest is history. However I can not use any USB on my pi :(

**Comment by aeslami** [comment]
This bug was also mentioned on YouTube: https://www.youtube.com/watch?v=6EQFpvLGE9Q

**Comment by Pierreau-fr** [comment]
Exactly the same error, and the patch for .elf and .dat files also freezes my keyboard and mouse. Can't install anything else than Raspian 32 bit on SD card :( Really too bad!

**Comment by maxnet** [comment]
Fixed in 20200612

**Comment by Jtenore** [comment]
can't find 20200612 can someone link it to me?
