### ISSUE TITLE
Berryboot does not boot on Raspberry Pi 4 8GB

### ISSUE THREAD

**Issue by MariusQuabeck** [maxnet/berryboot#638]
Hi,

berryboot doesnt boot on the 8GB model without me replacing the .elf and .dat files from this specific commit https://github.com/raspberrypi/firmware/tree/a6c9b6b48ce86ef2527586a50760d52f1b33f642

also there is no keyboard/mouse support on the 8GB model. I just inserted the sd card into my pi4 4GB model and keyboard/mouse works just fine there.

**Comment by maxnet** [comment]
Fixed in 20200612
