### ISSUE TITLE
Additional OS

### ISSUE THREAD

**Issue by Sennsay** [maxnet/berryboot#64]
I am trying to add MineCraft and Kali to my SD card, but I do not see the option listed in the walk through to "add from USB stick"  I have both on separate SD cards now. and they both run on the Pi.  Can you give more details on how to transfer them?

**Comment by maxnet** [comment]
http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

Requires a regular Linux computer in addition to your Pi.
