### ISSUE TITLE
Berryboot not working on Pi 4 4GB and 8gb model.

### ISSUE THREAD

**Issue by pmauer456** [maxnet/berryboot#644]
Hi all, I'm new to all this Raspberry Pi stuff.  I'm trying to berryboot my Pi 4 8GB model.  I've followed the instructions from the website and many tutorials and I keep hitting a roadblock.  I copy the files to an sd card and insert the card.  Turn the Pi on and wait.  And wait .  And wait.  I waited over an hour just to be sure.  The only thing that happens is I hear the fan spin for maybe 5-10 seconds then that stops and nothing.  I put the same SD card in a different Pi (4GB model) and the same thing happens.  I've re-formated and reloaded the Sd card three times and tried other SD cards.  Nothing works.  I put other OS's on sd cards in both pi's and they boot.  Any advice would be appreciated.

Thanks

**Comment by gotouchgo** [comment]
did you format as fat32? How big is the SD card? If too big, maybe can't be formatted as fat32. Try create a smaller fat32 partition and put berryboot files on it?

Well, I actually hit a SD card issue. After I installed the OS using my berryboot usb drive, the date of cmdline.txt and wpa_supplicant.conf are set to 1980/01/01, (1979/12/31 when look at in Windows), Then I reboot the OS, SD card still plugged in, but it can't boot at all. I have to reformat the SD card on Windows, and copy over all berryboot files from the zip, then it can boot, but I have to install OS again.

So I backup the files, reformat the SD card on Windows, copy over all berryboot files from the zip, open the cmdline.txt and wpa_supplicant.conf with notepad and save with current time. Then copy these two files to the newly formatted SD card. Now finally it boots up correctly. It is so weird.

I see a small partition of 127MB is created on my USB SSD drive with a copy of berryboot files there. My USB SSD is bootable, but nt sure if possible to use those files to boot.

**Comment by pmauer456** [comment]
Thanks for the info.  Turns out that I was formatting as a Logical partition and it needed to be a Primary partition.
