### ISSUE TITLE
Just a little addition to the doc

### ISSUE THREAD

**Issue by Koopzington** [maxnet/berryboot#65]
I just want to say that i'd add a note on the "How to install custom images" doc that the usb drive needs to have a FAT32 filesystem in order to get detected by Berryboot.

**Comment by maxnet** [comment]
Doesn't need to be. E.g. fat16 or ext4 is fine as well.

Might not work with NTFS though.

**Comment by Koopzington** [comment]
In that case I'd inform the users that NTFS doesn't
Am 25.10.2013 15:41 schrieb "maxnet" notifications@github.com:
