### ISSUE TITLE
Creating Custom Repository

### ISSUE THREAD

**Issue by greavette** [maxnet/berryboot#66]
Hello Max,

Thanks very much for this amazing system you've created for us!

I wanted to follow up on an issue you helped someone else with regarding using a custom repository to download images from.  I'm using berryboot in our small office for a custom thin client image based upon Raspbian.  I know I can, from Raspbian, connect to the berryboot filesystem and copy a new image.  But I'm very interested in being able to download a new image from my own repo.  

In Issue #45 - https://github.com/maxnet/berryboot/issues/45 you mentioned two things that I'd like to clarify.  

Firstly you mentioned that the person would need to write his own tool for compression and secondly to create two files called berryboot.ini and berryboot.crt for public keys.

For my situation where I have a squashed image already of my thin client O/S, do I still need to write my own tool?  Or can I simply create the berryboot.ini and public key file and point to my own url which has my squashed image?  Or does my thin client image need to be in a different format from what I currently have in order to use my own repo?

Forgive my ignorance please, but I don't understand what the url is that I would be pointing too?  Is it just a file repository where my thin client image resides waiting to be downloaded?  How does berryboot know to download the new image?  Does berryboot have a program that I can use simply by updating the berryboot.ini with the name of my image or is this what you mean when you said we'll need to write our own program to download our custom images?

Any help you can provide would be greatly appreciated.

Thank you,

**Comment by maxnet** [comment]
> Forgive my ignorance please, but I don't understand what the url is that I would be pointing too? Is it just a file 
> repository where my thin client image resides waiting to be downloaded? How does berryboot know to download the 
> new image?

You need to point the URL to a S/MIME signed message containing the list of available images:

It looks like this (uncompressed): http://dl.berryboot.com/distro.smime
The file then needs to be compressed with qCompress() and uploaded.

You can create the file in a text editor, S/MIME sign it with the openssl command line tools, and write something to do the compression. 
I do not provide any ready made utilities to do that.

**Comment by greavette** [comment]
Thanks very much Max.

**Comment by oxbown** [comment]
Hi Max, I´ve a problem when i try to make my own custom repo. 
I use this commands to create the certificate and to sign the dristro.txt file:

openssl genrsa -des3 -out berryboot.key 1024
openssl req -new -key berryboot.key -out berryboot.csr
openssl x509 -req -days 30000 -in berryboot.csr -signkey berryboot.key -out berryboot.crt
openssl smime -sign -in distro.txt -text -out distro.smime -signer berryboot.crt -inkey berryboot.key

I compress the distro.smime file with a tool that I made in Qt Creator , and i think that all is ok. The problem appears when berryboot try to download the distribution list from the internet. An error appears "error downloading distribution list, certificates doesn´t much"  or something like that. I copied the berryboot.crt and the berryboot.ini in the SD root folder like you said in the previous post.

Could you help me? What i´m doing wrong?
Thanks
