### ISSUE TITLE
Cannot open access to console, the root account is locked.

### ISSUE THREAD

**Issue by rameshputrevu** [maxnet/berryboot#660]
Hello

I have Raspberry Pi 4 and so far with the help of Berryboot, I was able to install couple of different images. One of the two images I successfully converted using mksquashfs tool.

Now I wanted to get my existing Raspberry 32 bit OS (with all my apps) onto Berryboot. So I made an .img file of my entire OS and used mksquashfs to convert into berryboot format/image. Now when I tried to boot into that new image, I get this message..

-----------------------------------------------------------------------------
_You are in emergency mode. After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or "exit"
to boot into default mode.

Cannot open access to console, the root account is locked,
See sulogin(8) man page for more details.

Press Enter to continue._
--------------------------------------------------------------------------------

I appreciate any pointers to resolve this.

Thank you

**Comment by maxnet** [comment]
You did comment out the lines in /etc/fstab ?
(Either manually or using sed like described here: https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions )

**Comment by rameshputrevu** [comment]
oh no.. I missed it.. let me rerun mksquashfs again.. 

thank you!! for the quick reply

**Comment by rameshputrevu** [comment]
Thank you! I reran mksquashfs again and it worked fine.
