### ISSUE TITLE
firmware update RPI4 does not work with berryboot ?

### ISSUE THREAD

**Issue by kiai72** [maxnet/berryboot#663]
Hello, i took the latest pi os for all PIs, did
sudo apt-get update
sudo apt-get upgrade

but the firmware is still the old one.
"rpi-eeprom-update -a" says it will update with next reboot - but after reboot the same ... it just does not do any update during reboot.
Is this because of berryboot ?

pi@raspberrypi:~ $ sudo rpi-eeprom-update -a
BCM2711 detected
Dedicated VL805 EEPROM detected
*** INSTALLING EEPROM UPDATES ***
BOOTLOADER: update available
CURRENT: Mon 15 Jul 12:59:55 UTC 2019 (1563195595)
 LATEST: Thu  3 Sep 12:11:43 UTC 2020 (1599135103)
 FW DIR: /lib/firmware/raspberrypi/bootloader/critical
VL805: update available
CURRENT: 000137ad
 LATEST: 000138a1
BOOTFS /boot
**EEPROM updates pending. Please reboot to apply the update.**

**Comment by maxnet** [comment]
May need to mount /dev/mmcblk0p1 on /boot first.

**Comment by kiai72** [comment]
> May need to mount /dev/mmcblk0p1 on /boot first.

so i should mount it - and try "rpi-eeprom-update -a" again ? Does this help ?

**Comment by maxnet** [comment]
It should

**Comment by kiai72** [comment]
hmmm, so do i have to modify fstab ?

pi@raspberrypi:~ $ ls /dev/mm*
/dev/mmcblk0  /dev/mmcblk0p1  /dev/mmcblk0p2
pi@raspberrypi:~ $ mount /dev/mmcblk0p1
mount: /dev/mmcblk0p1: can't find in /etc/fstab.
pi@raspberrypi:~ $

**Comment by maxnet** [comment]
Just specify the mount point.

sudo mount /dev/mmcblk0p1 /boot

**Comment by kiai72** [comment]
seems to work:

pi@raspberrypi:~ $ sudo mount /dev/mmcblk0p1 /boot
pi@raspberrypi:~ $ sudo rpi-eeprom-update -a
BCM2711 detected
Dedicated VL805 EEPROM detected
*** INSTALLING EEPROM UPDATES ***
BOOTLOADER: update available
CURRENT: Mon 15 Jul 12:59:55 UTC 2019 (1563195595)
 LATEST: Thu  3 Sep 12:11:43 UTC 2020 (1599135103)
 FW DIR: /lib/firmware/raspberrypi/bootloader/critical
VL805: update available
CURRENT: 000137ad
 LATEST: 000138a1
BOOTFS /boot
EEPROM updates pending. Please reboot to apply the update.
pi@raspberrypi:~ $ sudo reboot now

*** AFTER reboot:

pi@raspberrypi:~ $ sudo rpi-eeprom-update
BCM2711 detected
Dedicated VL805 EEPROM detected
BOOTLOADER: up-to-date
CURRENT: Thu  3 Sep 12:11:43 UTC 2020 (1599135103)
 LATEST: Thu  3 Sep 12:11:43 UTC 2020 (1599135103)
 FW DIR: /lib/firmware/raspberrypi/bootloader/critical
VL805: up-to-date
CURRENT: 000138a1
 LATEST: 000138a1
