### ISSUE TITLE
Raspberry Pi 3B+ headless installation, no connection.

### ISSUE THREAD

**Issue by mcmellow** [maxnet/berryboot#665]
Downloaded BerryBoot version berryboot-20201103-pi4.zip
Installed it on a SD-card and add lines and changes for a headless installation.  It is for a RPi 3B+

At power up only red led is solid on.  No green led at all.  nothing happens and can not ping the IP address

What can I do next? Please help.

**Comment by mcmellow** [comment]
Dear Maxnet,

Still struggling to get Berryboot running on a SD-Card. I have tried 2 versions 20201103-pi4 and 20200612-pi4.
Used two different 64GB SD-cards formatter with SD-formatter and also with the Raspberry Pi Imager.  Almost 10 different tries now. 
The Berry boot versions are unzipped to the root of the SD-card, add a ssh file and a wpa_supplicant.conf. And changed cmdline.txt  for the use of VNC because I only have a headless RPi 3B+  Nothing else connected to it except a 5V - 2A PSU

When I boot the the rpi with the SD-card,  the red led solid on and the green led flashing for 1-2 secs. Then only the red led is on solid. After 10-15 min I remove the power and look at the SD-card on a running RPi.  There seems to be nothing changed at all on the sd-card. It is still one partition.

```
Disk /dev/sdb: 59.5 GiB, 63864569856 bytes, 124735488 sectors
Disk model: MicroSD/M2
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xa553a923

Device     Boot Start       End   Sectors  Size Id Type
/dev/sdb1        2048 124735487 124733440 59.5G  c W95 FAT32 (LBA)
```
No are there some other tricks I can do?  Or am I doing something wrong?

**Comment by maxnet** [comment]
Sorry, but I don't provide support on anything headless.
Connect a monitor...

**Comment by mcmellow** [comment]
> Sorry, but I don't provide support on anything headless.
> Connect a monitor...

Thanks for your reply. 
It's a pity that I only hear this after 8 days of my first question. And 2 days of trial and error as described in my second question.
And even a bit odd when you have this page on the website.
https://www.berryterminal.com/doku.php/berryboot/headless_installation

Unfortunately I don't own a separate monitor, only a laptop and RPi. Using a headless RPi is just one of the biggest pro's for me. You only need a RPi and a 5V PSU.

**Comment by maxnet** [comment]
No support, as in no technical support.
Great if you can get it to work headless, but if not for any debugging a monitor is not optional.
