### ISSUE TITLE
Only one OS found NOC-PS

### ISSUE THREAD

**Issue by javaarchive** [maxnet/berryboot#668]
I recently started using a pi that had a 1 to 3 year old berryboot version. When adding oses I saw only noc-ps. When prompted to upgrade berryboot, I let it upgrade. Afterwards the only os available was still NOC-PCS. I then did some digging around and manually downloaded the repo data. I noticed that for each os I couldn't download, device=aarch64 was on a line.
I'm not sure if I got the distro list from the right place but I got them from http://dl.berryboot.com/distro.smime
I noticed in the source code, it references "http://dl.berryboot.com/distro.zsmime" so that may be different

**Comment by maxnet** [comment]
Only support 64-bit OSes nowadays. Which requires at least Pi 3.

**Comment by javaarchive** [comment]
My board says "Raspberry Pi 2015" below "Raspberry Pi 3 Model B V. 2" though

**Comment by grey-co** [comment]
I have the same issue as OP.
I have a Raspberry Pi 3B+, though. I am connected to the internet and thought maybe I need to add/ update the repo.
The only OS I can add is the NOC-PCS... anyone have any thoughts, or suggestions?
Thanks.

**Comment by daveneeley** [comment]
> Only support 64-bit OSes nowadays.

Is there a 64bit download of BerryBoot for Pi3? The download entry for `berryboot` in the `distro.smime` file is from 2018.

```
[berryboot]
version=v2.907
description=New Berryboot version
url=http://downloads.sourceforge.net/project/berryboot/updates/update-20180729.tgz
sha1=b95a020cf90f94036c56556cdf63ef71f636d2a2
size=57318371
```

**Comment by maxnet** [comment]
>Is there a 64bit download of BerryBoot for Pi3?

The Pi 4 download SHOULD work on the Pi 3 as well.
Has not been tested by me though, so is therefore not advertised as such.

**Comment by Camposmansi** [comment]
The same thing happens to me in pi zero

**Comment by daveneeley** [comment]
I tried out Pi 3 with the latest pi 4 download. It starts out just fine, but doesn't seem to survive reboots very well.

**Alternatives**
This developer has been maintaining all sorts of BerryBoot friendly images:
https://berryboot.alexgoldcheidt.com/

You can load these into berry boot via USB stick (described near the bottom)
https://www.howtogeek.com/141325/how-to-multi-boot-your-raspberry-pi-with-berryboot/

**Comment by VerbTheNoun95** [comment]
Noticing the same thing on a pi 4 with 64 bit.

**Comment by javaarchive** [comment]
Update: my pi won't boot now with the major berryboot update I did, unfortunately I've decided to reformat my SD card so this issue can be closed.

**Comment by edegraaff** [comment]
> I have the same issue as OP.

I have the same problem how do i manipulate to get the noc-ps replaced by berryboot images?

**Comment by array-in-a-matrix** [comment]
I am also getting this issue on my raspberry pi zero w after a clean install. downloaded berryboot from [here](https://cfhcable.dl.sourceforge.net/project/berryboot/berryboot-20181211-pi0-pi1-pi2-pi3.zip).

**Comment by dolphin-cat** [comment]
same on raspberry pi 1 with berryboot-20190612-pi0-pi1-pi2-pi3.zip

**Comment by azndoodle** [comment]
> https://berryboot.alexgoldcheidt.com/

How can I point berryboot to this list of images? I'd like to be able to install directly over wifi.
