### ISSUE TITLE
Issues with Mouse and Keyboard not responding

### ISSUE THREAD

**Issue by greavette** [maxnet/berryboot#68]
Hello,

Are there any known issues with mouse and keyboard not responding when using berryboot?  It's not a common problem that happens everytime, but sometimes on a reboot I have no mouse or keyboard and I need to hard reboot the raspberry pi.  

Any ideas what could cause this problem?  Or would this be more attributable to overclocking or not enough power to power the pi.

Thank you.

**Comment by maxnet** [comment]
The new release includes a more recent kernel, check if it works better with that. If not, reopen.
