### ISSUE TITLE
How to self update berryboot from version 20160130-r2 to latest version?

### ISSUE THREAD

**Issue by PeSalomon** [maxnet/berryboot#680]
Hi,
I'm running my Raspberry Pi3 with Berryboot 20160130 version including linux kernel release 4.14 and would like to upgrade to a newer version without reinstalling my existing OS installations including the running applications.

I tried to follow the procedure described in "https://github.com/maxnet/berryboot/issues/371" with no success.

I downloaded berryboot version 20190612-pi0-pi1-pi2-pi3 and copied the included files to my SD card overwriting existing files.
When booting from the sd-card and select "use existing files" during installation, berryboot does not find any os installation on my WD-Drive.
When skipping cmdline.txt boot works fine but my Raspberry is not detecting wlan0 device. Even changing wlan-country in Raspberry config is not possible since device is not detected.

A "gzip -dc /boot/shared.tgz | tar x -C /mnt/shared" after boot resulted in errors:
tar: C-: not found in archive
tar: /mnt/shared: not found in archive
tar: stopped because of error
May bee those error messages are somehow different in English since I'm running my systems in German but the meaning should be correct.
Any help to solve the upgrade to kernel 4.19 o 5.x is really appreciated.

Best regards
Peter

**Comment by PeSalomon** [comment]
I just detected a tipo in one of the error messages above:
tar: -C: not found in archive
is correct.

Peter

**Comment by maxnet** [comment]
With newer Berryboot editions you need to use unsquashfs to extract shared.img to /shared

**Comment by PeSalomon** [comment]
Hi  @maxnet,
thank you for your fast reply. I must admit, I probably missunderstand your advice.  
I'm not able to locate shared.img on my SD-Card nor on my WD-drive.
Directory /boot is still containing a file shared.tgz. There is no shared.img.
Also a full search for *shared.img did not show any result on my system.

I than looked in "berryboot-20190612-pi0-pi1-pi2-pi3.zip" and only found a shared.tgz there.
I found a file shared.img in "berryboot-20201103-pi4.zip". Is your advice to use this latest version of berryboot?
Also my current directory /mnt is empty. Do I need to extract shared.img into that?
Would that command be correct:     unsquashfs /boot/shared.img 'mnt/shared'

Sorry for asking such beginners questions. But I'm more a user than a system admin.
Your help is really appreciated.

Best regards and
many thanks in advance

Peter

**Comment by PeSalomon** [comment]
Hi @maxnet,
I think I solved my issue. On my system the correct directory to extract the content of the archive /boot/shared.tgz is /lib.
Respective sub-directories are /lib/firmware and /lib/modules.
My system is now running "berryboot-20190612-pi0-pi1-pi2-pi3.zip" with Rasbian VERSION="10 (buster") with kernel 4.19.49v6v7 :-)

Best regards and thanks again

Peter
