### ISSUE TITLE
After choosing my OS, my OS wont boot

### ISSUE THREAD

**Issue by Damokless** [maxnet/berryboot#686]
Hello everyone and thank you for reading this post,
I have installed two custom OS, when I choose one it doesn't boot. Anyone have an idea?
(To convert my images I used [berryconverter](https://github.com/Kingo71/BerryConverter) )

SCREEN 1
```bash
Mounting Image recalbox-bb.img ...
Error: unable to locate or excute /sbin/init /usr/lib/systemd/systemd /init inside recalbox-bb.img
```
SCREEN 2
```bash
Emergency recovery shell activated
/bin/sh : can't access tty : job control turned off
/squashfs # _
```

**Comment by owl770** [comment]
Sorry to state the obvious but what that error means is that in the image `recalbox-bb.img` there was no file called `/sbin/init`, `/usr/lib/systemd/systemd` or `/init`. Berryboot looks for these files to be able to boot the image.
If you mount the squashfs image (or use the prompt on SCREEN 2), you should be able to see that these files don't exist.
Maybe `recalbox` uses some other method to startup. If that is the case, it means `recalbox` is not compatible with Berryboot.

**Comment by Damokless** [comment]
> Sorry to state the obvious but what that error means is that in the image `recalbox-bb.img` there was no file called `/sbin/init`, `/usr/lib/systemd/systemd` or `/init`. Berryboot looks for these files to be able to boot the image.
> If you mount the squashfs image (or use the prompt on SCREEN 2), you should be able to see that these files don't exist.
> Maybe `recalbox` uses some other method to startup. If that is the case, it means `recalbox` is not compatible with Berryboot.

Thanks for the answer, sorry I may have asked a beginner's question, but this is the first time I use berryboot :/
