### ISSUE TITLE
Raspberry Pi Zero W install link

### ISSUE THREAD

**Issue by Jeremy-coderer** [maxnet/berryboot#698]
I want to get berryboot for my raspberry pi zero W to get started with learning linux, however, there is only one link which is for the raspberry pi 3, 4, and 400. Will this link work for the raspberry pi zero W?

**Comment by maxnet** [comment]
Pi zero is no longer supported.
Does not support 64-bit OS images.

**Comment by Jeremy-coderer** [comment]
Do you know if I can use the raspberry pi zero w at all to run linux?

**Comment by maxnet** [comment]
Sure, as long as you do not want to do webbrowsing (will run out of memory too fast)

Just write RPI OS to card using RPI Imager, and use that.

**Comment by Jeremy-coderer** [comment]
I just want to use it to do some simple hacking. I just want to learn how linux works and how it can be used to hack. Is that fine for the raspberry pi zero w? sorry for the questions, I am very new to all of this.
