### ISSUE TITLE
Unable to install 2012-12-16-wheezy-raspbian on a model B RPi

### ISSUE THREAD

**Issue by D1reW0lf** [maxnet/berryboot#7]
Hi there.

I'm trying to use BerryBoot to create a multi-boot SD Card.
By now I was able to install every option on the "Add OS" menu, except for the "official one", Raspbian “wheezy”.
When it starts downloading it after just a few second it freezes / crash.
I tried to let it on for a couple of hours but still no luck.

I even tried to copy it thru a usb pen but without any luck.
After using the info on the end of your page and have BootBerry properly copied it to the SC card when I try to restart it always crash with an "error 8" code.

When, using the same card, I create the system using the image downloaded from the RPi site  it works just fine.

If there's any help regarding this that anyone could give me I would really appreciate it.

Thank you!
Pedro Fardilha

**Comment by maxnet** [comment]
> when I try to restart it always crash with an "error 8" code.

Have a photo of the full error?

**Comment by D1reW0lf** [comment]
Hi there!
Thank you for such a quick replay.

> Have a photo of the full error?
> 
> Sure here it goes a photo.
> This is from when I add the modified img manually thru the USB pen.
> When it freezes during the download, it just stays there, so there's no error that I can show.

Once again, thank you!!
Pedro Fardilha

A 2013/01/18, às 19:42, maxnet notifications@github.com escreveu:

**Comment by maxnet** [comment]
Github removes attachments from e-mails.
So you will have to upload it somewhere, like on http://www.postimage.org/

Does it work if you download this image on your normal computer?
http://178.63.95.79/dl/Debian_Wheezy_Raspbian_2012.12.img192

**Comment by D1reW0lf** [comment]
Ops, I wasn't aware of that.
Here it goes:
http://ficheiros.fardilha.net/IMG_1311.JPG

Thanks!

A 2013/01/18, às 20:46, maxnet notifications@github.com escreveu:

**Comment by maxnet** [comment]
Remove or comment out the entries for / and /boot in /etc/fstab inside the image.

**Comment by D1reW0lf** [comment]
Thanks,
I'll try that.

A 2013/01/18, às 20:50, maxnet notifications@github.com escreveu:

**Comment by maxnet** [comment]
Reopen if issue persists.
