### ISSUE TITLE
BerryBoot Image Collection

### ISSUE THREAD

**Issue by pierew** [maxnet/berryboot#70]
I've made a WordPress site where I add Images for BerryBoot, these Images are the originals but converted, like KaliLinux or RetroPie.

You can register there to Comment and Add your own Converted Images, The ScreenMediaCast Network DON'T host images ourself, YOU must upload them on your own Storage and include the Downloadlink into the integrated Downloadsection. BUT it must be an directfile Link, not a Ad Supportet link or a normal Share Link!

If the Berryboot Developer wish to integrate this into their Website they can, Ask me and I give you da currently existing Database and you can Use This.

http://berrybootimages.pierewoehl.de

**Comment by nonameolsson** [comment]
Nice! Would really like to see an image for the latest OpenElec. The one in Berryboot list is really old. I've been googling for two days, but I can't find a way to manually install the latest one.

**Comment by maxnet** [comment]
Closing issue, as site shows "This user has elected to delete their account and the content is no longer available."
