### ISSUE TITLE
Only images that run wizard on installation works

### ISSUE THREAD

**Issue by mizifih** [maxnet/berryboot#702]
I don't know why, bot apparently only images that, on the first boot, run some sort of wizard, like Manjaro and Ubuntu, are the ones that I can install. Can it be the storage size being a problem? I never considered the fact that it's a M.2 SATA card adapted to USB. Tried PiOS from the repository, used cifs to load TwisterOS and RetroPi from my home server, it didn't work either, they're listed, added to the Pi, but don't work. I get that "_A start job is running for /dev/disk/by-label/boot_", "_Dependency failed for /boot_", "_Dependency failed for Local File Systems_", bla bla bla, "_You are in emergency mode_ bla bla bla, "_Cannot open access to console, the root account is locked_", bla bla bla, "_Press enter to continue_".

Tried google, no joy. What could it be?

Pi4 8GB
Argon One M.2
1TB M.2 SATA (_don't judge me, I want options_)
64GB SD Card (_overkill, but it's what I have_)

**Comment by maxnet** [comment]
Should work better in 2021-07-01
