### ISSUE TITLE
Pi 4 w/Berryboot, and missing Ethernet

### ISSUE THREAD

**Issue by krackers101** [maxnet/berryboot#704]
Hey all,
I'm having an issue with Berryboot 2.0 and my Pi 4.  I installed BB on a 32gb microsd from scratch and installed a couple OSs through ethernet.  I updated/upgraded them and generally did some new install house cleaning (new user, backgrounds, web browsing, file copies with flash drives, etc).  At some point, maybe a day or two later, when I boot up, BB can't find the ethernet connection, and the OSs I installed can't either.  When this is occurring, the Wifi connection will work fine, but no ethernet.  If I wipe the card, and start over installing everything, it will work fine for a while and then the same happens.  I can flash a card with any PI compatible OS (using imager), and the ethernet never goes missing.  Works great.
I've googled this issue and found others that have the same issue, and some that have similar ones, but nothing has worked yet, other than starting over..  I'm good with PCs & tech, but a noob where Linux is concerned.  Any ideas on getting berryboot to re-detect and use the ethernet when it happens?
Thanks
Paul

**Comment by krackers101** [comment]
Additional info:  in berryboot and the glitching operating systems both, if I use a console, ifconfig shows only the loopback..  eth0 isn't shown.  I'll post specific command results if you need them.  Thanks again!
EDIT: I did a fresh install of Berryboot and RPI OS Lite.  Both were able to use eth0.  I logged in and did "sudo apt update" & "sudo apt full-upgrade".  Rebooted and eth0 was gone.

**Comment by danijell2** [comment]
I also have this problem, but noticed it with earlier version. Recently I've tried the latest berryboot 20210701 and immediately run apt-get upgrade. Restart and eth0 is still there. Now, I don't know for how long is this going to last, or perhaps it was fixed in the latest version?

**Comment by danijell2** [comment]
Just an update. The problem didn't appear again to me, so it seems the issue has been resolved with the latest berryboot.

**Comment by krackers101** [comment]
Good to hear and thank you for updating us on the issue!
Paul
