### ISSUE TITLE
Time out waiting for device /dev/disk/by-label/boot

### ISSUE THREAD

**Issue by dev-mansonthomas** [maxnet/berryboot#707]
I'm setting up a Raspberry 4B 8G with a NVMe on USB3 (Samsung 970 Evo plus, 500GB).
I've downloaded the latest version of BerryBoot, checked the sha256 signature, unzipped, copied content to SD Card.

- I boot the Raspberry Pi
- format /dev/sda with ext4
- I get "error unmounting system partition" but I've seen this on another guy video, so I assume it's ok (https://youtu.be/Q1btyPoL0GI?t=254)
- I install RPI Os Lite
- Reboot
- The debian starts but fails with the following error "Time out waiting for device /dev/disk/by-label/boot"
https://photos.app.goo.gl/N8Lzd7fJvZu7avt67

I don't see what I could have done wrong.
How can I debug /fix this ?

**Comment by dev-mansonthomas** [comment]
Thanks for the hints of @spammassive
I solve the issue by building a custom image for berryboot from the default RaspberryPi Os

See the description here to **build** the image
https://docs.google.com/document/d/1o6LavsAASWddieJ8YjO_qAQt5c5hvLD3D2yD338QTio/edit#heading=h.tqisi346sf2d

See the description here to **use** the image : 
https://docs.google.com/document/d/1o6LavsAASWddieJ8YjO_qAQt5c5hvLD3D2yD338QTio/edit#heading=h.lwa6x0asle32
(in short : on the OS selection, click cancel to reboot, then long left click "Add OS" button, and select the image that you have copied on to an USB Key)

If you want to reuse the image I've just built, download it here : 
https://drive.google.com/drive/folders/1Hqg-f3J_TyLw-vMZus0iLY0OG27aEmTe


I copy paste the part of the doc that is relevant in case the doc is no longer available : 


With the currently available RaspberryPi Os image, you’ll get an error message at boot time
See https://github.com/maxnet/berryboot/issues/707

To workaround that, I’ll create a custom distribution from the official RaspberryPiOs image following the instructions here :
https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

It can’t be done on MacOSX, kpartx is missing even via brew.
So I’ve installed an Ubuntu system on VMWare to do it.
Download Raspberry Pi latest image
Lite version for K8s cluster

Image link taken from : https://www.raspberrypi.org/software/operating-systems/
Raspberry Pi OS Lite

wget https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip

thomasmanson@ubuntu:/tmp$ sha256sum 2021-05-07-raspios-buster-armhf-lite.zip 2021-05-07-raspios-buster-armhf-lite.zip 
c5dad159a2775c687e9281b1a0e586f7471690ae28f2f2282c90e7d59f64273c  2021-05-07-raspios-buster-armhf-lite.zip
c5dad159a2775c687e9281b1a0e586f7471690ae28f2f2282c90e7d59f64273c  2021-05-07-raspios-buster-armhf-lite.zip
thomasmanson@ubuntu:/tmp$ 
Compare with the checksum value on the website




**Convert the official image to BerryBoot format**

unzip 2021-05-07-raspios-buster-armhf-lite.zip
sudo apt-get install kpartx
thomasmanson@ubuntu:/tmp$ sudo kpartx -av 2021-05-07-raspios-buster-armhf-lite.img
add map loop5p1 (253:0): 0 524288 linear 7:5 8192
add map loop5p2 (253:1): 0 3129344 linear 7:5 532480
thomasmanson@ubuntu:/tmp$ 

sudo mount /dev/mapper/loop5p2 /mnt

sudo sed -i 's/^\/dev\/mmcblk/#\0/g' /mnt/etc/fstab
sudo sed -i 's/^PARTUUID/#\0/g' /mnt/etc/fstab
sudo rm -f /mnt/etc/console-setup/cached_UTF-8_del.kmap.gz
sudo rm -f /mnt/etc/systemd/system/multi-user.target.wants/apply_noobs_os_config.service
sudo rm -f /mnt/etc/systemd/system/multi-user.target.wants/raspberrypi-net-mods.service
sudo rm -f /mnt/etc/rc3.d/S01resize2fs_once

thomasmanson@ubuntu:/tmp$ sudo mksquashfs /mnt 2021-05-07-raspios-buster-armhf-lite.berryboot.img -comp lzo -e lib/modules
Parallel mksquashfs: Using 2 processors
Creating 4.0 filesystem on 2021-05-07-raspios-buster-armhf-lite.berryboot.img, block size 131072.
[=====================================================================================================================================================|] 31699/31699 100%

Exportable Squashfs 4.0 filesystem, lzo compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 359689.06 Kbytes (351.26 Mbytes)
	45.95% of uncompressed filesystem size (782811.07 Kbytes)
Inode table size 472114 bytes (461.05 Kbytes)
	37.67% of uncompressed inode table size (1253201 bytes)
Directory table size 398020 bytes (388.69 Kbytes)
	49.57% of uncompressed directory table size (802978 bytes)
Number of duplicate files found 1218
Number of inodes 36909
Number of files 27861
Number of fragments 2141
Number of symbolic links  5920
Number of device nodes 8
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 3120
Number of ids (unique uids + gids) 18
Number of uids 5
	root (0)
	thomasmanson (1000)
	messagebus (103)
	man (6)
	tss (106)
Number of gids 15
	root (0)
	render (109)
	shadow (42)
	thomasmanson (1000)
	users (100)
	utmp (43)
	tty (5)
	kvm (108)
	tss (111)
	syslog (110)
	staff (50)
	man (12)
	nogroup (65534)
	adm (4)
	mail (8)
thomasmanson@ubuntu:~/tmp$ 

sudo umount /mnt
sudo kpartx -d 2021-05-07-raspios-buster-armhf-lite.berryboot.img

Package and upload to Google Drive

bzip2 -9 2021-05-07-raspios-buster-armhf-lite.berryboot.img
sha256sum 2021-05-07-raspios-buster-armhf-lite.berryboot.img.bz2 > 2021-05-07-raspios-buster-armhf-lite.berryboot.img.bz2.sha256.txt

Upload to Google Drive

**Comment by jejones3141** [comment]
Could someone replace the image that causes the problem with a corrected one? Seems better than making everyone build a corrected image.

**Comment by dev-mansonthomas** [comment]
I've shared my images for reuse in the post above

**Comment by jejones3141** [comment]
Thank you, sir!
