### ISSUE TITLE
OS cannot find "boot" partition

### ISSUE THREAD

**Issue by CorruptName** [maxnet/berryboot#712]
I have converted a couple images to SquashFS and am having issues getting them to boot properly. It seems they are unable to find the "boot" partition.
The Images which I am using are:
https://github.com/OpenHD/Open.HD/releases
and
https://cosmostreamer.com/products/djifpvgoggles/

both were converted using this guide:
https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

I suspect the issue is that both of these distributions use non-standard config files placed on the "boot" partition.

Sorry if this has been covered somewhere else but if it was I couldn't find it.

**Comment by maxnet** [comment]
Should work better in 2021-07-01

**Comment by CorruptName** [comment]
Same issue, I get:
`mount: /boot: mount point not mounted or bad option`
when trying to boot either image.

Both of these images use user config files located on the boot partition and therefor must be able to load those config files on boot.
