### ISSUE TITLE
cant create berryboot image from bullseye image (04.04.22)

### ISSUE THREAD

**Issue by chrome511** [maxnet/berryboot#736]
since the newest bullseye image from 04.04.2022 it is not possible to convert it.
if i want to convert the image, it only shows the following error message:
```
Can't find a SQUASHFS superblock on 2022-04-04-raspios-bullseye-armhf-lite.img
Wrong filesystem or filesystem is corrupted!
Failed to read existing filesystem - will not overwrite - ABORTING!
To force Mksquashfs to write to this block device or file use -noappend
```

**Comment by symbios24** [comment]
Try this method and let me know if it worked

https://github.com/agoldcheidt/Universal-Image-Generator-for-Berryboot

**Comment by chrome511** [comment]
I already tried this method. The links in the Script are dead. So I checken the Script an copied the commands from that. The result is the same. With the image from 28.01.2022 it works.

**Comment by symbios24** [comment]
I suggest use the 28.01.2022 image for now until someone comes with a solution

Have you tried the latest buster image aka raspberry pi os legacy?

If the latest legacy works means bullseye has the "problem" only

**Comment by maxnet** [comment]
>if i want to convert the image, it only shows the following error message:

Please provide the entire command line you are entering.
From the error it sounds like you are telling mksquashfs to create a new Squashfs/Berryboot image file with the same file name as the original unconverted image, which isn't going to work....

**Comment by maxnet** [comment]
>So I checken the Script an copied the commands from that.

Suggest you read the offical documentation instead of copying random commands from other scripts: https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

**Comment by chrome511** [comment]
I already Reader the official documentation

**Comment by maxnet** [comment]
>I already Reader the official documentation

The docs will tell you to create a converted_image_for_berryboot.img, not a file with the same file name as your source image.

**Comment by symbios24** [comment]
The official method is outdated and not working for some time now at least for buster images,i doubt it will work for bullseye also
