### ISSUE TITLE
Berryboot not recognizing USB device

### ISSUE THREAD

**Issue by JERasmussen** [maxnet/berryboot#74]
1)Berry Boot on a Raspberry PI model B with old Raspbian OS installed on 32G SD card.

2)Device in question is a 16G mini-SD card in a USB dongle, partitioned via Win32DiskImager.  

Mini-SD does not register as an install target from the main Berry Boot menu, nor as a mount point from the Berry Boot console.  Raspbian does see the mini-SD card, listing it as a removable HDD.  Mini-SD is also seen from an ASUS laptop running Windows 7, via both the dongle and directly, when placed in an external card reader.

**Comment by maxnet** [comment]
Try again with the latest version, has kernel upgraded to 3.12 branch
