### ISSUE TITLE
cmdline.txt UUID

### ISSUE THREAD

**Issue by fhychoi** [maxnet/berryboot#75]
since data device is moved to USB stick, does the cmdline.txt support UUID instead of assigned device ID to avoid?

current cmdline.txt:
smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=10 datadev=sda2

thank you.

**Comment by maxnet** [comment]
We do not support UUIDs, but do take the LABEL into account.

On boot it waits for datadev to become available and analyzes that first, but it searches all other devices for a filesystem with LABEL berryboot if the file system is not at datadev.
