### ISSUE TITLE
I can't get Berryboot to boot

### ISSUE THREAD

**Issue by xKNIGHTMAREx** [maxnet/berryboot#753]
I downloaded the latest version of Berryboot, unzipped it, copied it to a microSD formatted in Fat32 and inserted it into a Rpi4 and it does nothing, the green reading LED does not turn on, it does not load anything and no menu appears, I have also tried it on a Rpi3b+ and it does the same. Any idea what could be happening to me? Thanks.

**Comment by actraiser30** [comment]
Try another memory card and check the HDMI cable, or clean the card contacts with some isopropyl alcohol,if pi4 is revision 1.5 it might not work,also if pi3b+ is the last revision 1.4 it might not work also.

Try also this berryboot it's 3 months newer than the latest in here

https://berrybeta.alexgoldcheidt.com/berryboot/dimitris-unofficial-berryboot-update/latest-berryboot-20210930-kernel-5.10.63-pi4.zip

**Comment by xKNIGHTMAREx** [comment]
I'll try it and comment here, thanks.

Because is there any option to have two systems on a microSD and be able to boot from a Rpi3b or Rpi4 and have a menu appear to choose from?

**Comment by actraiser30** [comment]
> I'll try it and comment here, thanks.
> 
> Because is there any option to have two systems on a microSD and be able to boot from a Rpi3b or Rpi4 and have a menu appear to choose from?

Yes you can use the same card in both pi3/pi4

Try the berryboot  I gave you and let me know if it worked in both 3/4

**Comment by xKNIGHTMAREx** [comment]
The image you gave me works on the Rpi3b+, I need to try it on the RPi4. In this image there is hardly anything to download, Retropie and Recalbox do not appear. The image I want to put tells me that it is in mksquashfs, I suppose I will have to convert it to SquashFS.

**Comment by actraiser30** [comment]
> The image you gave me works on the Rpi3b+, I need to try it on the RPi4. In this image there is hardly anything to download, Retropie and Recalbox do not appear. The image I want to put tells me that it is in mksquashfs, I suppose I will have to convert it to SquashFS.

Try it also on pi4,the downloads are from the official berryboot servers that haven't updated for many years.yes you have to convert it in squashfs

You can find updated converted images here:

https://berryboot.alexgoldcheidt.com/

**Comment by xKNIGHTMAREx** [comment]
It also worked for me on the RPi4 Rev 1.5, now I just need to convert the image to ScuashFS, let's see if I can do it.

**Comment by actraiser30** [comment]
> It also worked for me on the RPi4 Rev 1.5, now I just need to convert the image to ScuashFS, let's see if I can do it.

What image it is? Maybe there is in the site I gave you 

Also check my site for custom projects based on berryboot images

https://singleboard.alexgoldcheidt.com/projects/dimitris/

**Comment by xKNIGHTMAREx** [comment]
It's a standalone image of an MSX system running on Rpi3b+. I don't think it's there.
It is the image that puts RC-741.
https://msxvr.com/resources/
Do you think I can convert her?

**Comment by actraiser30** [comment]
Follow the instructions here to do it

https://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

**Comment by xKNIGHTMAREx** [comment]
I'm trying to get it to boot on a CM4 and it won't boot. Would I need to do anything to get it to boot? Is it supposed to work like the RPi4? I want to try it on a Retroflag GPI Case 2 with cm4.

**Comment by actraiser30** [comment]
You mean the os is not booting or berryboot?

**Comment by xKNIGHTMAREx** [comment]
Does not start in CM4

**Comment by actraiser30** [comment]
The max does not start??? Or berryboot does not start?

**Comment by xKNIGHTMAREx** [comment]
It doesn't start and the installation menu doesn't appear or anything. I would like to be able to use Dual boot on the Retroflag and be able to put two systems on it.

**Comment by actraiser30** [comment]
Cm4 should work is supported,cannot help you more,probably bb needs an update and that won't come since floris abandoned it.

**Comment by xKNIGHTMAREx** [comment]
I'll try with another SD and see, thanks.

**Comment by actraiser30** [comment]
If it does not work means that cm4 is newer revision,just use pi4

**Comment by xKNIGHTMAREx** [comment]
Let's see if I'm lucky, I really wanted to use dual boot so I could have two systems on the Retroflag GPI Case 2 which has a CM4.

**Comment by actraiser30** [comment]
It's not going to work on GPI probably not supporting the screen

**Comment by xKNIGHTMAREx** [comment]
That's what's happening, is there any way to set the boot resolution to 640*480?

**Comment by actraiser30** [comment]
You need to edit the config.txt 

http://wiki.sunfounder.cc/index.php?title=Adjust_Resolution_for_Raspberry_Pi

Or run the raspi-config and set the resolution from there

**Comment by xKNIGHTMAREx** [comment]
I'll try to see if I can do it later, thanks 😊
