### ISSUE TITLE
BerryTerminal Login

### ISSUE THREAD

**Issue by djmckenzie77** [maxnet/berryboot#76]
Trying to install berryboot for the first time.  It is asking me to login to the berryterminal.  I read that there is no password and the username is "root."  Every time I type that in, it just freezes and I have to reboot.  Just wondering if I am doing something wrong?  Thanks!

**Comment by maxnet** [comment]
Do you get a fancy GUI asking for a password, or a text screen?

In the first case enter your Edubuntu username and password.

**Comment by djmckenzie77** [comment]
Thanks for the swift reply! I just got it resolved. My SD card was missing a few files that prevented it from booting. Once they were in place it worked great! I am up and running.

Sent from my iPhone

On Jan 20, 2014, at 9:16 AM, "maxnet" <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you get a fancy GUI asking for a password, or a text screen?

In the first case enter your Edubuntu username and password.

**Comment by maxnet** [comment]
Good to hear it is solved
