### ISSUE TITLE
Old version of OpenELEC

### ISSUE THREAD

**Issue by nonameolsson** [maxnet/berryboot#77]
I love Berryboot, solved a lot of problem for me! But there is one thing though. I can't figure out how to install the latest version of OpenELEC.
How com the version in the list in Berryboot is so old? Would it be possible to update to latest build?

**Comment by ghost** [comment]
You can do a manual update, just extract the openelec files to the update folder. Take a look on Openelec Website.
http://wiki.openelec.tv/index.php/Raspberry_Pi_FAQ#A_new_build_has_come_out._How_can_I_update.3F

Anyway, I agree with you. It's time to update the default image.

**Comment by maxnet** [comment]
Upgraded OpenELEC

**Comment by ians325** [comment]
How can i upgrade openelec to the Latest test builds cause would normal drag and drop in update folder but that does not work with berry 4.0.6
