### ISSUE TITLE
BerryBoot don´t recognize my USB WIFI dongle

### ISSUE THREAD

**Issue by oxbown** [maxnet/berryboot#78]
Is there any solution to my problem? can i install the wifi drivers via berryboot terminal?

**Comment by maxnet** [comment]
Do you know what brand/model/chipset wifi dongle do you have?

**Comment by oxbown** [comment]
Mi wifi dongle is: TL-WN725N and the chipset is Realtek  RTL8188
Thaks

**Comment by maxnet** [comment]
Not sure what is wrong with that.
We do have a kernel module for RTL8188CU, so should work in theory.

Had you had any success on using the wifi dongle on the Pi with something other than Berryboot?

**Comment by oxbown** [comment]
I used it in Raspbmc and Raspbian and it worked.

**Comment by maxnet** [comment]
The new Berryboot release includes a more recent kernel, check if it works better with that. If not, reopen.
