### ISSUE TITLE
berryboot compiled for a20 cubieboard2

### ISSUE THREAD

**Issue by allenelson** [maxnet/berryboot#79]
I've patched kernel 3.4.61 for aufs and have successfully compiled, installed and am running berryboot on the a20. Loading an OS fails with the attached message below. It seems there is something wrong with the berryboot-init script but I'm unsure what. I can successfully make/mount the directories and mount the image manually. But once it comes time to load the script, it claims /aufs does not exist but it does.. I've tried this with multiple OS's. Could someone test the cb2 image by any chance?

Also the installer was buggy when the shared.tgz folder was about 200mb. I've taken this image down to about 35M total, so the file shouldn't fail to extract. But if it does fail, open the console and extract it manually in the /mnt/shared folder via:

gunzip shared.tgz
tar xvf shared.tar

All common drivers should work (nand,mmc,usb,hdmi,sound), plus RTL8192 and RTL8188 wireless, sunxi-emac, HID-Logitech-DJ keyboard/mouse etc etc.

**_download for sdcard image**_
ftp://ciscoeng.pro/berryboot_a20_50M_sdcard.img.xz

**\* pastebin of openelec failing to load ***
http://pastebin.com/rs9baESv

**Comment by patrickhwood** [comment]
Is there an initrd (ramdisk) involved?  Could the /aufs be missing on that?

**Comment by allenelson** [comment]
My thoughts too, I added aufs manually to the ramdisk and have also added
it to the buildroot environment now. I've also checked the inital bootup
mounts proc, dev, etc properly.

drwxr-xr-x  2 root root 4096 Jan 30 11:14 aufs
drwxr-xr-x  2 root root 4096 Jan 30 11:14 bin
drwxr-xr-x  5 root root 4096 Jan 30 11:14 dev
drwxr-xr-x  6 root root 4096 Jan 30 11:14 etc
drwxr-xr-x  4 root root 4096 Jan 30 11:14 home
-rwxr-xr-x  1 root root 2076 Jan 30 11:14 init
drwxr-xr-x  2 root root 4096 Jan 30 11:14 lib
lrwxrwxrwx  1 root root   11 Jan 30 11:14 linuxrc -> bin/busybox
drwxr-xr-x  2 root root 4096 Jan 30 11:14 media
drwxr-xr-x  2 root root 4096 Jan 30 11:14 mnt
drwxr-xr-x  2 root root 4096 Jan 30 11:14 opt
drwxr-xr-x  2 root root 4096 Jan 30 11:14 proc
drwxr-xr-x  2 root root 4096 Jan 30 11:14 root
drwxr-xr-x  2 root root 4096 Jan 30 11:14 rootfs
lrwxrwxrwx  1 root root    3 Jan 30 11:14 run -> tmp
drwxr-xr-x  2 root root 4096 Jan 30 11:14 rw
drwxr-xr-x  2 root root 4096 Jan 30 11:14 sbin
drwxr-xr-x  2 root root 4096 Jan 30 11:14 sys
drwxrwxrwt  3 root root 4096 Jan 30 11:14 tmp
drwxr-xr-x  6 root root 4096 Jan 30 11:14 usr
drwxr-xr-x  3 root root 4096 Jan 30 11:14 var

**Comment by allenelson** [comment]
In the init script, the comment claims BerrybootGUI writes the chosen OS to /tmp/answer. I think that's the issue, it's not actually doing it. I'll confirm some time after removing the following rm statement to see if the file exists. The fact I can mount the loop image tells me the script should in fact work.

While confirming I did indeed add /aufs to the ramdisk I noticed the usr/sbin/chroot_image script. I didn't see this before because it was late and assuming I couldn't edit BerrybootGUI I was going to leave it up to someone else if they wanted to.. I'll have a look though when I've got free time.

If anyone's wondering, my ultimate goal is to setup berryboot on the A20 which can download a modified OpenELEC that'll use xbmc + external player.. I'll tackle that if I can get the OS to load. Trying to make things simple for end users with a CB2. The CB2 is such a disappointment to me, I thought for sure it would be a better option for an HTPC over the raspberry pi I purchased. So now I'm on a mission to make it somewhat useful for that purpose, and simple process.

# Show GUI, it will write the OS choosen to /tmp/answer

/usr/bin/BerrybootGUI -qws 2>/tmp/debug 

# Clear screen

clear

IMAGE=`cat /tmp/answer`
DATADIR="/mnt/data/$IMAGE"
rm /tmp/answer

if [ "$IMAGE" != "" ]; then
        mkdir -p /squashfs /aufs $DATADIR
        clear
        echo Mounting image ${IMAGE}...
        mount -o loop "/mnt/images/$IMAGE" /squashfs

**Comment by maxnet** [comment]
> I've patched kernel 3.4.61 for aufs

Make sure you enabled aufs in the kernel configuration, build into the kernel (and not as module)

**Comment by allenelson** [comment]
Ive tried both even compiling aufs3-linux and utils. This might be a module
version ill have to check. But regardless parts of the error say /aufs no
such directory.. Its even in the ramdisk It exists.

**Comment by maxnet** [comment]
> But regardless parts of the error say /aufs no such directory..

/aufs is always created by the startup script here: https://github.com/maxnet/berryboot/blob/berryboot2.0/buildroot-2012.05/package/berrybootgui2/init#L44

So think the error message may be misleading.

Double check that your kernel config has CONFIG_AUFS_FS=y

**Comment by allenelson** [comment]
The script failing is what led me to creating it manually. Mkdir shouldn't
be aufs related. Ill recheck though and ensure the fs is not a module.

**Comment by maxnet** [comment]
> The script failing is what led me to creating it manually.

Your pastebin says "no such device" (as opposed to "No such file or directory")
Think the error relates to what is being mounted, rather than the mount point not existing.

Again tipple check your kernel is both patched and AUFS support is built-into the kernel in the kernel config.

**Comment by allenelson** [comment]
You were absolutely right. I suppose have 5 folders named linux-allwinner-aufs34.x got the better of me. OpenELEC is loading now that aufs is built in instead of a module. Drives me nuts knowing i tried both and wasted so much time with a folder naming error.

Looks like from the console it might be crashing, but at least its loading. Gonna set this up on the TV and see what it's doing now. Thanks for the help guys.

http://pastebin.com/u3gUVYtq

**Comment by maxnet** [comment]
For Cubieboard 2 support there is now an image at: http://sourceforge.net/projects/berryboot/files/berryboot-cubieboard2-20140627.zip/download

Be aware that OpenELEC is not going to work though, as it uses code specific to the Pi's Videocore GPU.
