### ISSUE TITLE
Switch the system Wirelessly.

### ISSUE THREAD

**Issue by rickdgit** [maxnet/berryboot#80]
Hello!
I'm using Pi as a small server(operate via ssh) however sometimes i need use it as XBMC.
I check most of webpage but can not figure it out.
I just wondering is that possible to choose the system via command(no mouse or keyboard or TV controller available)

Appreciate for any suggestions.
Rick

**Comment by maxnet** [comment]
As root:

```
    mount LABEL=berryboot /mnt
    echo -n "name-of-image-to-reboot-to.img" > /mnt/data/runonce
    umount /mnt
    reboot
```

After mount, do "ls -l /mnt/images" if you are not sure what the filename of the image you want to boot is.
