### ISSUE TITLE
Add OS to menu

### ISSUE THREAD

**Issue by michaelkrtikos** [maxnet/berryboot#81]
Hello, I know that this has been asked many times and it gets tiring but i am completely new to linux.

I would like to add to berryboot a nightly built of openelec Gotham. I have the image file of OpenELEC and i try to follow the steps from here:
http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

However, when i copy-paste or type the following command:
sudo sed -i 's/^\/dev\/mmcblk/#\0/g' /mnt/etc/fstab
I get that /mnt/etc/fstab no such file or directory.

I am going into /mnt where i only find a lost&found folder. When i try to mount again the loop0p2 it prompts that is already mounted.

Could anyone instruct me with the steps from the beginning please?

Thank you very much

**Comment by michaelkrtikos** [comment]
I cannot make it work... First of all i have found out why the sed command does not work. In OpenELEC there is no fstab. So i exclude this command.

Another question that came to me is weather i use the image file downloaded from the openelec.tv or do i have to install it - resize it and create an image with Disk32imager?

In case i need to install it, i will have an image with the size of 15GB since this is the capacity of my SD card. I check the size of the already squashfsed images you provide and they are not over 100MB.

Could anyone help me please?

**Comment by maxnet** [comment]
OpenELEC uses the same Squashfs image format as Berryboot.
Just rename SYSTEM to OpenELEC.img128

Not sure if the nightly builds do not use a newer Linux kernel than we ship with Berryboot though.
If that is the case it might not work.

**Comment by michaelkrtikos** [comment]
Thank you very much for your reply.

I have found this in the Raspberry Pi forum. When i tried, i got an error on boot:

Error: sbin/init not found in xxxx.img

I found that i need to play with the sbin and lib and reverse the symplinks. I do not know exactly how to do it but i will figure it out i suppose. If you can be so kind to write down the commands it would be great.

Now you brought up another problem. In the nightly built OpenELEC uses kernel 3.13. I might give it a try and if it doesn't work i will just let it go...

**Comment by tristan-k** [comment]
Same here. Can someone please write a tutorial for openelec berryboot images. With the newly released OpenElec 4 I dont want to wait anymore longer.

**Comment by maxnet** [comment]
> Error: sbin/init not found in xxxx.img

Yeah, OpenELEC no longer uses /sbin/init but now has /usr/lib/systemd/systemd
Fixed in f9c9fd1c6d66378f57dbd1f40e714c185b629c27
