### ISSUE TITLE
camera for raspberry pi not working

### ISSUE THREAD

**Issue by freddii** [maxnet/berryboot#82]
camera is not working on berryboot
when i try to enable it with raspi-config it says: "your firmware appears to be out of date(no start_x.elf). Please update"

**Comment by maxnet** [comment]
In the Berryboot GUI, press the ">>" -> "Advanced configuration" -> tab config.txt
Add:

```
start_file=start_x.elf
fixup_file=fixup_x.elf
```

**Comment by stackmasm** [comment]
I have exactly the same problem do we have a solution?
The second line should be
fixup_file=fixup_x.dat

**Comment by dmshimself** [comment]
is there an alternative way to get the camera to work?  I've tried changing the config.txt file to have both these lines at the bottom and no joy.  I've used it with a fresh install today with the 2018.3 stretch with the fixup_file=fixup_x.dat and fixup_x.elf and I still get the

Your firmware appears to be out of date (no
start_x.elf) Please update

message

**Comment by maxnet** [comment]
start_x is the enabled by default nowadays on Berryboot.
If your camera is not working, there is a different issue.

**Comment by dmshimself** [comment]
Any advice appreciated. This is a fresh install from the latest version of berryboot I did today.  It uses an iscsi boot and full stretch install from berryboot. Nothing fancy but i get that error when trying to enable the camera in raspi-config. The same machine when booted ‘tegularly’ lets me enable the camera. I don’t think its a hardware camera issue, I’m not sure at this point how to do any further analysis.

**Comment by maxnet** [comment]
Camera is already enabled by default.
So just skip raspi-config and start using it.

**Comment by dmshimself** [comment]
So it does :-)  I had not picked up on that previously and did what I always did with a pi to enable the camera.  I really appreciate the steer.

**Comment by pointsplitter** [comment]
I am having the same issue as many others. I have a raspberry pi hq camera and keep getting the message about "Your firmwave appears to be out of date (no start_x.elf). Please update" when I try to enable it in the usual config window. I have manually edited the config.txt file to add in the various things such as "start_x=1" but that didn't work. When I try the straightforward raspistill -o test.jpg as some suggest, I get the error that ends with "Camera is not enabled with this build. Try running "sudo raspi-config" and ensure that the "camera" has been enabled." I have gotten myself into an infinite loop. Any help is appreciated.

**Comment by maxnet** [comment]
start_x=1 is there by default, so that is not the problem.

Could be that the software you are using is unable to run under a 64-bit kernel, though.
Would argue that the software would need to be fixed then, instead of ours.
Think raspistill is no longer supported though, and being replaced by the new libcamera stuff in Bullseye.
