### ISSUE TITLE
Update to latest kernel / aufs

### ISSUE THREAD

**Issue by Treebro** [maxnet/berryboot#83]
The kernel version is simply out of date.

Less than an issue, but what I've been playing with:
In specific, referring to https://github.com/raspberrypi/linux/issues/415

I want to incorporate this update to the kernel into the image I'm creating.  I've been having many issues with SD card corruption recently (30+/100+) and looking to this as a solution.

This is far from my area of expertise, but updating the firmware would be just changing the kernel sources in the .config of buildroot correct? (Using the menuconfig under buildroot program to do this.)

Update to 3.10.x, only a hunch on how to do it.
1. Change custom repository version under Linux Kernel to rpi-3.10.y
2. Download compatible aufs patches, looking at http://sourceforge.net/p/aufs/aufs3-standalone/ci/aufs3.10.x/tree/
3. Point the Custom kernel patches string to the aufs files.

Edit: Attempted and didn't work.  Pi stuck on splash screen, led shows status of "7 flashes: kernel.img not found."

**Comment by maxnet** [comment]
Make sure you also update kernel-config for 3.10

We may update to rpi-3.10 eventually.
But want to try to get Android working under 3.6 first.

**Comment by maxnet** [comment]
Upgraded to the rpi-31.12.y branch
