### ISSUE TITLE
Can not install FBTFT module to berryboot 

### ISSUE THREAD

**Issue by sshaar08** [maxnet/berryboot#84]
https://github.com/notro/fbtft/issues/97

I would like advice on how to install the FBTFT module into berryboots shared modules?

Thanks in advance!

**Comment by maxnet** [comment]
- Make a diff between a vanilla raspberry pi kernel tree and one that has the FBFT stuff added
- Add the diff file to the list here: https://github.com/maxnet/berryboot/blob/berryboot2.0/buildroot-2012.05/.config#L1131
- run rebuild-berryboot.sh
