### ISSUE TITLE
How does berryboot interact/use my Pi distribution's config.txt and cmdline.txt parms

### ISSUE THREAD

**Issue by greavette** [maxnet/berryboot#88]
Hello Max,

I'm using my Raspberry Pi as a type of thin client.  The O/S I use is from rptc.blogspot.ca.  That distribution has made some tuning changes to /boot/config.txt and /boot/cmdline.txt.

What happens when I create an image of this O/S and put it on berryboot?  Does the parameters my rpitc have in config.txt and cmdline.txt get ignored?

Just want to understand how Berryboot interacts with each O/S?

Thank you.

**Comment by maxnet** [comment]
It will simply share the cmdline.txt and config.txt with ALL distributions installed.

So the other distribributions will see the cmdline.txt settings for your OS as well.
(and probably ignore them if they don't know what the extra parameters mean)

Generally it should not be necessary to have a custom config.txt
Note that Berryboot defaults to using CMA, so no need to mess with memsplit settings.

**Comment by greavette** [comment]
Thanks for the information Max.  Very informative.  

I'll use the /boot files from the rpitc distribution I'm adding to berryboot and see how it goes.

Thanks again.
