### ISSUE TITLE
List of OS versions

### ISSUE THREAD

**Issue by eyp** [maxnet/berryboot#89]
Hi, it'd be fine to have a file (readme or so) where a list of OS names & versions. If it already exists, a link in the README file would be useful.

Also, if there is already a repository for currently working OS images (SquashFs), or a place where people could contribute with new ones, that would be useful too. For example someone that has converted a RetroPie image to SquashFs could add it's image there... well that's only an idea :)

**Comment by sal666** [comment]
Here you will find all currently available official images:
http://sourceforge.net/projects/berryboot/files/os_images/

**Comment by eyp** [comment]
Thank you!
