### ISSUE TITLE
problem with wifi when installing berryboot-20140626

### ISSUE THREAD

**Issue by MrEngman** [maxnet/berryboot#90]
I re-built the berryboot image adding a wifi driver to the 20140626 image. When installing berryboot I can select the wifi module and set the wifi but when it comes to reformatting the SD card berryboot issues an error. 

```
Error saving bootfiles to memory. SD card may be damaged.
```

I tried reformatting and re-installing berryboot several times, and tried several different SD cards, but it gave the same error each time.

To check it wasn't an issue with my build I changed the wifi module to one that's included in the image and I then attempted to install the official berryboot-20140626.zip image and the same error happened. I then re-installed the SD card and installed berryboot using a wired network connection and all was OK.

I then re-installed my original build and installed berryboot using a wired internet connection. All went OK and I installed raspbian. I then configured the wifi in raspbian and it works without problems as it has done for months before I tried berryboot.

To see if it was an issue with berryboot 20140626 I tried an older image from January and it worked fine when I tried installing using the wifi.

Looks like there may be an issue with installing berryboot20140626 using a wifi connection.

**Comment by maxnet** [comment]
> Error saving bootfiles to memory. SD card may be damaged.

That means "cp -a /boot /tmp" returned an error.

When that happens, try going to tty2 (ctrl+alt+f2), login as root without password, enter that command manually and see what error you get.
Also check if "dmesg" shows anything out of ordinary.

Also make sure the (uncompressed) size of shared.tgz is not too large, as it has to uncompress that to memory when loading the wifi drivers. It doesn't have to uncompress that file when using LAN, as the Ethernet driver is built-in the kernel instead of as module.

**Comment by MrEngman** [comment]
Apologies for the delay in responding. I don't know what happened here I left a comment, or I thought I did, over 24hrs ago, unless I didn't commit it. As I don't see it lets try again.

Changing to tty2 and cp -a /boot /tmp returns an error 

```
cp: write error: No space left on device
```

df command shows

```
Filesystem      size    Used    Available   Used%   Mounted on
dev             51.4M   0       51.4M       0%      /dev
/dev/mmcblk0p1  14.8G   34.3M   14.8G       0%      /boot
```

I am using an old Pi Mk 1 256MB, usually running 24/7 with raspbian. Maybe there is insufficient ram on the Mk 1 for the latest berryboot. I am using 16GB SD cards and have tried several different ones which have previously been working and do with berryboot if I install using a wired connection.

There are no error messages in dmesg and in fact it shows the wifi connecting OK. However /var/log/debug shows several errors.

```
CecListener thread started 
CecListener done initializing 
Changing keymap to: ":/qmap/ad" 
Changing keymap to: ":/qmap/us" 
Changing keymap to: ":/qmap/gb" 
tar: write error: No space left on device
modprobe: module usb:v1D6Bp0002d0312dc09dsc00dp01ic09isc00ip00in00 not found in modules.dep
modprobe: module usb:v0424pEC00d0200dcFFdsc00dp01icFFisc00ipFFin00 not found in modules.dep
modprobe: module usb:v04F3p0103d0107dc00dsc00dp00ic03isc01ip01in00 not found in modules.dep
modprobe: module usb:v04F3p0103d0107dc00dsc00dp00ic03isc00ip00in01 not found in modules.dep
modprobe: module usb:v15D9p0A4Cd0100dc00dsc00dp00ic03isc01ip02in00 not found in modules.dep
modprobe: module usb:v050Dp0224d0100dc09dsc00dp01ic09isc00ip00in00 not found in modules.dep
modprobe: module usb:v0424p9512d0200dc09dsc00dp02ic09isc00ip02in00 not found in modules.dep
ioctl[SIOCSIWAP]: Operation not permitted
ioctl[SIOCSIWAP]: Operation not permitted
route: SIOCDELRT: No such process
sh: write error: No space left on device
sh: write error: No space left on device
QProcess: Destroyed while process is still running.
Initializing QFontEngineQPF failed for /usr/lib/fonts/DejaVuSans-Bold.ttf
curl ret 6 
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
```

This are from installing my own build but I would like to stress that I appear to get similar behaviour when trying to install using berryboot-20140626.zip from your web site. For your own install file, berryboot-20140626.zip /var/log/debug shows

```
CecListener thread started 
CecListener done initializing 
Changing keymap to: ":/qmap/ad" 
Changing keymap to: ":/qmap/us" 
Changing keymap to: ":/qmap/gb" 
tar: write error: No space left on device
modprobe: module usb:v1D6Bp0002d0312dc09dsc00dp01ic09isc00ip00in00 not found in modules.dep
modprobe: module usb:v0424pEC00d0200dcFFdsc00dp01icFFisc00ipFFin00 not found in modules.dep
modprobe: module usb:v04F3p0103d0107dc00dsc00dp00ic03isc01ip01in00 not found in modules.dep
modprobe: module usb:v04F3p0103d0107dc00dsc00dp00ic03isc00ip00in01 not found in modules.dep
modprobe: module usb:v15D9p0A4Cd0100dc00dsc00dp00ic03isc01ip02in00 not found in modules.dep
modprobe: module usb:v050Dp0224d0100dc09dsc00dp01ic09isc00ip00in00 not found in modules.dep
modprobe: module usb:v0424p9512d0200dc09dsc00dp02ic09isc00ip02in00 not found in modules.dep
ioctl[SIOCSIWAP]: Operation not permitted
ioctl[SIOCSIWAP]: Operation not permitted
route: SIOCDELRT: No such process
sh: write error: No space left on device
sh: write error: No space left on device
Initializing QFontEngineQPF failed for /usr/lib/fonts/DejaVuSans-Bold.ttf
curl ret 6 
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
cp: write error: No space left on device
```

Installing using ethernet and then loading the raspbian OS is OK and I can then load the wifi without problems.

To run through what I see I install then boot berryboot and get the initial "Welcome" screen. I select wifi, set locale to Europe/London and kb to gb, and testing kb is OK. Selecting OK then shows dialog "Loading drivers" then "Starting wpa_supplicant". Then the "Wifi settings" screen opens and I see a list of my local networks. I select the network I want and then enter the password. Selecting OK I get "Connecting to access point" dialog. After a short time I then get the "Disk selection" window which shows "mmcblk0 SD16G" and "Networked Storage (iSCSI SAN)". With mmcblko selected I select the Format button and then I get the error "Error saving bootfiles to memory ....".

**Comment by maxnet** [comment]
Ok, will fix that in the next version.

Kernel is supposed to create ramdisks (tmpfs file system) with a quota of half the amount of usable memory by default.
But I suspect it excludes the CMA region in the calculation in kernel version 3.12.x
It should have created a tmpfs of around 100 MB instead of the 51 MB that shows on your df on a 256 MB Pi.

Already runs out of tmpfs space when it is extracting shared.tgz for the wifi drivers:

```
tar: write error: No space left on device
```

**Comment by MrEngman** [comment]
Thanks for that. Can you suggest a change I could try on my own  build to fix the issue?

**Comment by maxnet** [comment]
Try entering `mount -o remount,size=110M /` in tty2 prior to selecting wifi.
If it does work with that, add that line somewhere at the top in 
`buildroot-2012.05/package/berrybootgui2/init` and run rebuild-berryboot.sh to make it permanent.

**Comment by MrEngman** [comment]
Thanks, I'll give it a try.

**Comment by MrEngman** [comment]
Hi

Brilliant!! That appears to have sorted the problem, with both my own and your images. I rebuild my image with the mount instruction included after several other mount commands at the beginning of  'buildroot-2012.05/package/berrybootgui2/init' and it now runs and installs the OSes OK.

Just a couple of things I found a little strange. First, the errors in /var/log/debug regarding modprobe still appear in the working version, both my own and your images. And second, my DHCP server, on my domain controller as i have my own domain, shows a blank hostname for the Pi while berryboot is initialising and installing the OSes. However, once the OS is installed and running then a valid hostname is shown.

Thanks very much for your time.

**Comment by maxnet** [comment]
> First, the errors in /var/log/debug regarding modprobe still appear in the working version

Berryboot has very simple module loading code, that simply takes the list of all USB devices connected to the system, and executes "modprobe usb:ID" for each of them.
It is not clever enough to only do that for devices for which a module actually exist, something more advanced module loading software -such as udev/systemd- does do. 

That no module exists for those USB IDs, doesn't necessarily mean the hardware is not supported by the way.
The errors you are seeing are probably for the USB controller, Ethernet (that is also connected to the USB bus on the Pi), USB hub, and your mouse and keyboard, for which there is no separate module as support for those is linked-in statically into the kernel.

> And second, my DHCP server, on my domain controller as i have my own domain, 
> shows a blank hostname for the Pi while berryboot is initialising and installing the OSes.

Believe `udhcpc` defaults to using the MAC-address as client ID when talking to the DHCP server, unless you explicitly pass a hostname as a parameter.

**Comment by MrEngman** [comment]
Well they don't cause any problems so I will forget about them for now.

Just have to say Thanks very much for the time you've put into this issue with the wifi.

Best Regards
MrEngman

**Comment by maxnet** [comment]
yw
