### ISSUE TITLE
TP-Link TL-WN725N V2 wifi module driver.

### ISSUE THREAD

**Issue by MrEngman** [maxnet/berryboot#93]
Re https://github.com/maxnet/berryboot/issues/78

The build I created that you helped me get running was to include the driver for the WN725N wifi module. It uses the rtl8188eus chipset and requires a seperate driver loading as it will not run with any of the Realtek drivers included in the linux source.

Out of curiosity just to see what happens I have now checked it out with your most recent image berryboot-20140626.zip and it seems to work with that version as well. I was qute surprised, but it is compiled using the same linux source version, so I suppose I shouldn't be that surprised.

The compiled driver is available at https://dl.dropboxusercontent.com/u/80256631/berryboot-8188eu-20140626.tar.gz

Useful for the guys who've been trying to get the WN725N running with Berryboot but it needs installing directly into any installed OS. 

If it can be included directly into your image somehow so it can be used to install berryboot feel free to use it.

Regards
MrEngman

**Comment by maxnet** [comment]
Rather see the code added somewhere upstream.

**Comment by maxnet** [comment]
> It uses the rtl8188eus chipset and requires a seperate driver loading as it will not run with any of the 
> Realtek drivers included in the linux source.

https://github.com/raspberrypi/linux/issues/640 suggests the TL-WN725N V2 does work with the R8188EU driver that is included with the Linux source, if you enable it in the kernel config.
Have you tested that one, before going for the out-of-tree driver?

**Comment by maxnet** [comment]
Added CONFIG_R8188EU=m to the Berryboot kernel config in 20140806 (untested)
