### ISSUE TITLE
"There was an error running option 5 Enable Camera"

### ISSUE THREAD

**Issue by bigdawgte** [maxnet/berryboot#94]
Several people are reporting problems using raspi-config to enable camera when running D-Wheezy under Berryboot - me too!  Is there any workaround for this?  If not, how can I clone my D-Wheezy installation to the SD card that I now need to get?

**Comment by maxnet** [comment]
Just use the Berryboot config editor and add the option you need there.
Think you need start_x=1 in config.txt for camera.

http://www.berryterminal.com/lib/exe/detail.php/berryboot_menu2.png?id=berryboot

**Comment by bigdawgte** [comment]
Apologies, but you are not clear here.  How would I know what options are available?  What option should I add?  Is the config,txt for the camera separate from the BB config editor?  If not, where is it?  Is ther any documentation anywhere that clarifies this?

**Comment by maxnet** [comment]
Note that config.txt is not specific to Berryboot.

> How would I know what options are available?

http://elinux.org/RPiconfig
But it is incomplete

> What option should I add?

Try:

start_x=1

**Comment by bigdawgte** [comment]
Thanks, I got It working.  Also reserved memory to gpu (128M).

**Comment by mzaforas** [comment]
I still have this issue. @bigdawgte Do you only add to berryboot config.txt gpu_mem=128 and start_x=1? Could you give me another clue to fix the issue?

I obtain an error related with memory when I try init camera from python shell: "mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)"

Thanks in advance!
