### ISSUE TITLE
Berryboot VNC not working

### ISSUE THREAD

**Issue by pgpg123** [maxnet/berryboot#95]
It tells me to connect but it just shows a recovery shell when i connect

see http://raspberrypi.stackexchange.com/questions/22048/my-pi-with-berryboot-with-vnc-enabled-wont-work for more details

**Comment by oncleben31** [comment]
Same problem for me. 
When trying to use the native mac VNC client, the client is frozen after asking me a password. And if I use Real VNC I've the message on the Raspberry screen "emergency recovery shell activated"

**Comment by oncleben31** [comment]
I've avoid the "emergency recovery shell activated message" by correcting a bug in my gateway ip adress in cmdline.txt file. But I've still a dark screen in my VNC client.

**Comment by maxnet** [comment]
Make sure your VNC client is requesting 24 bit color, and not 256 colors pellete mode.
If using RealVNC, set FullColour to true: http://s7.postimg.org/3karg4bq3/realvnc_settings.png
