### ISSUE TITLE
Add image from network location

### ISSUE THREAD

**Issue by ruisebastiao** [maxnet/berryboot#96]
Hello,
first of all thanks for the great job that you are doing.

Is it possible in future releases have an option to add an image from network location?

Thanks,
Rui

**Comment by greavette** [comment]
I think this is a great idea!  I vote for this as well.

**Comment by maxnet** [comment]
Can you be a bit more specific.
Are you looking for an option to download an image from a custom HTTP URL?
Or do you want to store images on a local Windows networking/NFS share?

**Comment by ruisebastiao** [comment]
Hello,

the image is stored on a local Windows networking/NFS share.

**Comment by maxnet** [comment]
Added basic support for installing images from a local CIFS (Windows networking) share.

To use it, in the "Add image" window press the "Network settings" button -> tab "Repository" and enter the address of your CIFS server there.
Or add to berryboot.ini on the FAT partition of the SD card:

```
[repo]
url=cifs://1.2.3.4/name-of-network-share
```

Where 1.2.3.4 is the IP-address of your server.
Defaults to logging in as guest.

**Comment by ruisebastiao** [comment]
Thanks,
I will test it soon

**Comment by ruisebastiao** [comment]
Hello,

i'm testing the local repository and i'm always getting "Error mounting network share", i test to mount the windows share in ubuntu and everything was ok, is there any way to get more details about the error while mounting

**Comment by maxnet** [comment]
Try going to the console and see what error you get when you enter manually:

```
mkdir /share
mount -t cifs -o username=guest //1.2.3.4/name-of-share /share
```

Change the username, and add -o password=password if you need a password.

**Comment by ruisebastiao** [comment]
i got some initial errors because of missing modules 
after i load the needed modules i got  the following error: 
CIFS VFS: Send error in SessSetup =-13
Permission Denied

**Comment by maxnet** [comment]
What are you connecting to? Windows? What version? A NAS device?

Try if you have better luck when you specify an authentication method with "-o sec=<authentication method>", available values:

```
       sec=
           Security mode. Allowed values are:

           ·   none - attempt to connection as a null user (no name)

           ·   krb5 - Use Kerberos version 5 authentication

           ·   krb5i - Use Kerberos authentication and forcibly enable packet signing

           ·   ntlm - Use NTLM password hashing

           ·   ntlmi - Use NTLM password hashing and force packet signing

           ·   ntlmv2 - Use NTLMv2 password hashing

           ·   ntlmv2i - Use NTLMv2 password hashing and force packet signing

           ·   ntlmssp - Use NTLMv2 password hashing encapsulated in Raw NTLMSSP message

           ·   ntlmsspi - Use NTLMv2 password hashing encapsulated in Raw NTLMSSP message, and force packet signing
```

Also try playing with "-o vers=<version>"

```
       vers=
           SMB protocol version. Allowed values are:

           ·   1.0 - The classic CIFS/SMBv1 protocol. This is the default.

           ·   2.0 - The SMBv2.002 protocol. This was initially introduced in Windows Vista Service Pack 1, and Windows Server 2008. Note that the
               initial release version of Windows Vista spoke a slightly different dialect (2.000) that is not supported.

           ·   2.1 - The SMBv2.1 protocol that was introduced in Microsoft Windows 7 and Windows Server 2008R2.

           ·   3.0 - The SMBv3.0 protocol that was introduced in Microsoft Windows 8 and Windows Server 2012.

           Note too that while this option governs the protocol version used, not all features of each version are available.
```

Only tested the functionality with a Synology NAS myself, don't have Windows.

**Comment by ruisebastiao** [comment]
I'm using a windows share, no luck for options none and ntlm

**Comment by ruisebastiao** [comment]
Ok, it's solved, sorry was my problem, the account was locked

**Comment by D4ZzyD** [comment]
'' maxnet commented on Aug 4, 2014
Can you be a bit more specific.
Are you looking for an option to download an image from a custom HTTP URL?''




Maxnet, broz can you make it so we can add berry servers [alexgolds] site to the downloadable menu? so we can get all the distoz possible straight from berry boot, i talk to him on gmail and I'm going to be sharing all my kali linux distroz and anonymous 1.0 I'm working on. i just want to download them straight from the booty list man. can you help me? the list will be filled! dude would be sooo awesome man lola hahahaha  here the url   http://berryboot.alexgoldcheidt.com/images/ he's pretty kool dude i can ask permission for you. but I'm sure you too have spoken lol

**Comment by ZanderBrown** [comment]
Not sure i understand what your saying there but i believe you are requesting the same feature as @GitHubMad in #344 

@D4ZzyD for future reference all comments made on GitHub are public and should preferably be made in clear, concise, semi-formal language

**Comment by C-Fu** [comment]
It's been over a year now, and it's not clear if adding alexgoldcheidt's sourceforge link (via .ini file or something) is available now. 

If we can do it now, mind somebody explaining to me the way?

**Comment by maxnet** [comment]
Problem with the files on the other sourceforge site is that the images are compressed and need to be unzipped first.
We do not support doing that automatically.
